'use client';
import {useEffect,useMemo,useState,type ReactNode} from 'react';
import {loadDay069PracticeSessionV2,sealDay069V2,startDay069PracticeSessionV2} from '@hnk/supabase-client';
import type {Day069ControlScores,Day069PostScores,Day069PreScores,Day069SafetyReason,Day069Symptoms} from '@hnk/practice-contract';
import {createWebVaultTextPort} from '../_runtime/WebVaultTextPort';
import {useWebHnkRuntime} from '../_runtime/WebHnkRuntime';
type Session=NonNullable<Awaited<ReturnType<typeof loadDay069PracticeSessionV2>>>;
type Draft={activeSeconds:number;controlSeconds:number;reps:number;pre:Day069PreScores;post:Day069PostScores;control:Day069ControlScores;symptoms:Day069Symptoms;activeDone:boolean;seated:boolean;naturalHead:boolean;moderate:boolean;slow:boolean;pause:boolean;belowFatigue:boolean;noForced:boolean;noExtreme:boolean;thirtyOptional:boolean;guidance:boolean;controlDone:boolean;separate:boolean;central:boolean;sameDuration:boolean;comparison:boolean;afterBoth:boolean;observableOnly:boolean;noBrainwave:boolean;noHemisphere:boolean;noTherapy:boolean;nullValid:boolean;reduceIfDiscomfort:boolean;noCompetition:boolean;psalm:boolean;formula:boolean;eyesRested:boolean;traditionalSeparated:boolean;thanks:boolean;headNormal:boolean;noDizziness:boolean;limitation:boolean;abandonIfNeeded:boolean;returned:boolean;vaultRef:string|null;privacy:boolean;voluntary:boolean;finalSafety:boolean;safetyStop:boolean;safetyReason:Day069SafetyReason};
const symptoms:Day069Symptoms={pain:false,blurredVision:false,nausea:false,vertigo:false,uncomfortableNystagmus:false,headache:false,growingDiscomfort:false};
const empty:Draft={activeSeconds:0,controlSeconds:0,reps:1,pre:{ocularComfort:5,dizziness:0,headache:0,focus:5},post:{focus:5,ocularTension:0,calm:5,dizziness:0},control:{focus:5,calm:5,ocularTension:0,dizziness:0},symptoms:{...symptoms},activeDone:false,seated:false,naturalHead:false,moderate:false,slow:false,pause:false,belowFatigue:false,noForced:false,noExtreme:false,thirtyOptional:false,guidance:false,controlDone:false,separate:false,central:false,sameDuration:false,comparison:false,afterBoth:false,observableOnly:false,noBrainwave:false,noHemisphere:false,noTherapy:false,nullValid:false,reduceIfDiscomfort:false,noCompetition:false,psalm:false,formula:false,eyesRested:false,traditionalSeparated:false,thanks:false,headNormal:false,noDizziness:false,limitation:false,abandonIfNeeded:false,returned:false,vaultRef:null,privacy:false,voluntary:false,finalSafety:false,safetyStop:false,safetyReason:'NONE'};
const card={background:'#121217',border:'1px solid #34313f',borderRadius:18,padding:18,margin:'14px 0'} as const,button={background:'#d9b86c',color:'#17120a',border:0,borderRadius:10,padding:'10px 13px',fontWeight:800,cursor:'pointer'} as const;
function dk(u:string){return`hnk:day069:${u}:draft:v2`}function sk(u:string){return`hnk:day069:${u}:session:v2`}function parse<T>(v:string|null):T|null{try{return v?JSON.parse(v) as T:null}catch{return null}}function cid(u:string){return`hnk-web-d069-v2-${u}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`}function clamp(v:number){return Number.isFinite(v)?Math.max(0,Math.min(10,Math.trunc(v))):0}
export function Day069GoldenV2Web(){const auth=useWebHnkRuntime(),vault=useMemo(()=>auth.userId?createWebVaultTextPort(auth.client??null):null,[auth.client,auth.userId]);const[session,setSession]=useState<Session|null>(null),[d,setD]=useState<Draft>(empty),[loaded,setLoaded]=useState(false),[activeStart,setActiveStart]=useState<number|null>(null),[controlStart,setControlStart]=useState<number|null>(null),[privateText,setPrivateText]=useState(''),[error,setError]=useState<string|null>(null),[busy,setBusy]=useState(false),[complete,setComplete]=useState(false);const live=Boolean(auth.configured&&auth.phase==='signed-in'&&auth.client&&auth.userId);
useEffect(()=>{if(!auth.userId)return;setD(parse<Draft>(localStorage.getItem(dk(auth.userId)))??empty);setLoaded(true);const id=localStorage.getItem(sk(auth.userId));if(id&&auth.client)void loadDay069PracticeSessionV2(auth.client,id).then(x=>x?setSession(x):localStorage.removeItem(sk(auth.userId!))).catch(()=>undefined)},[auth.client,auth.userId]);
useEffect(()=>{if(auth.userId&&loaded&&!complete)localStorage.setItem(dk(auth.userId),JSON.stringify(d))},[auth.userId,d,loaded,complete]);
useEffect(()=>{const h=()=>{if(document.visibilityState==='visible')return;setPrivateText('');if(activeStart!==null||controlStart!==null){setActiveStart(null);setControlStart(null);setError('medicao_corrente_descartada__retorne_ao_foreground')}};document.addEventListener('visibilitychange',h);return()=>document.removeEventListener('visibilitychange',h)},[activeStart,controlStart]);
function patch(p:Partial<Draft>){setD(x=>({...x,...p}))}function end(which:'active'|'control'){const st=which==='active'?activeStart:controlStart;if(st===null)return;const add=Math.max(1,Math.floor((Date.now()-st)/1000));if(which==='active'){patch({activeSeconds:d.activeSeconds+add});setActiveStart(null)}else{patch({controlSeconds:d.controlSeconds+add});setControlStart(null)}}
async function ensureSession(){if(session)return session;if(!live||!auth.client||!auth.userId)throw new Error('online_session_required_before_day069_practice');const x=await startDay069PracticeSessionV2(auth.client,{clientSessionId:cid(auth.userId),appVersion:'0.1.0-web-day069-v2'});setSession(x);localStorage.setItem(sk(auth.userId),x.id);return x}
async function saveVault(){if(!privateText.trim())throw new Error('private_reflection_empty');if(!vault||!auth.userId)throw new Error('vault_unavailable');await ensureSession();const e=await vault.saveText({userId:auth.userId,day:69,kind:'journal',plaintext:JSON.stringify({schema:'hnk-day069-reflection-v2',text:privateText.trim()})});patch({vaultRef:e.entryId});setPrivateText('')}
async function resolvedVault(){if(!d.vaultRef)return undefined;if(!vault||!auth.userId)throw new Error('vault_unavailable');await vault.flushPending(auth.userId);const x=await vault.resolveEntryId(auth.userId,d.vaultRef);if(!x)throw new Error('vault_sync_required');return x}
function stop(){if(d.safetyReason==='NONE'){setError('day069_safety_reason_required');return}setPrivateText('');setActiveStart(null);setControlStart(null);patch({safetyStop:true,finalSafety:false});setError('safety_stop_registered__do_not_complete')}
async function seal(){if(!auth.client||!auth.userId)return;setBusy(true);setError(null);try{const s=await ensureSession(),ref=await resolvedVault();const r=await sealDay069V2(auth.client,{evidence:{sessionId:s.id,active:{durationSeconds:d.activeSeconds,repetitionsCompleted:d.reps,completedConfirmed:d.activeDone,seatedSupportedConfirmed:d.seated,headStableOnlyWhileNaturalConfirmed:d.naturalHead,moderateAmplitudeConfirmed:d.moderate,slowPaceConfirmed:d.slow,pauseAndComfortCheckConfirmed:d.pause,personalLimitBelowFatigueConfirmed:d.belowFatigue,noForcedRepetitionConfirmed:d.noForced,noExtremeSpeedConfirmed:d.noExtreme,thirtyRepetitionsNotRequiredConfirmed:d.thirtyOptional,relevantConditionGuidanceRespectedConfirmed:d.guidance,preScores:d.pre,postScores:d.post,symptoms:d.symptoms},control:{durationSeconds:d.controlSeconds,completedConfirmed:d.controlDone,separateSessionConfirmed:d.separate,centralStableGazeConfirmed:d.central,approximatelySameDurationConfirmed:d.sameDuration,scores:d.control},comparison:{completedConfirmed:d.comparison,afterBothConditionsConfirmed:d.afterBoth,selfReportAndObservableExecutionOnlyConfirmed:d.observableOnly,brainwaveClaimNotMadeConfirmed:d.noBrainwave,hemisphericIntegrationClaimNotMadeConfirmed:d.noHemisphere,therapySubstituteNotClaimedConfirmed:d.noTherapy,nullOrControlBetterResultValidConfirmed:d.nullValid,lateralDiscomfortTriggersReduceOrDiscardConfirmed:d.reduceIfDiscomfort,noCompetitionOrExtremeSpeedConfirmed:d.noCompetition},middle:{psalm99Confirmed:d.psalm,memBetHeConfirmed:d.formula,eyesRestedConfirmed:d.eyesRested,movementsNamedCount:1,comfortNamedCount:1,focusNamedCount:1,symptomsNamedCount:1,traditionalHypothesisSeparatedConfirmed:d.traditionalSeparated,thanksToGodConfirmed:d.thanks,objectsAtDifferentDistancesCount:3,headMovedNormallyConfirmed:d.headNormal,noDizzinessBeforeEndConfirmed:d.noDizziness,limitationRegisteredConfirmed:d.limitation,acceptAbandonIfNeededConfirmed:d.abandonIfNeeded,returnConfirmed:d.returned},...(ref?{privateVaultEntryRef:ref,privateVaultE2eeConfirmed:true}:{}),practiceRecordNoPrivateProseConfirmed:d.privacy,voluntaryCompletionConfirmed:d.voluntary,finalSafetyClearConfirmed:d.finalSafety,safetyStopOccurred:d.safetyStop,safetyStopReason:d.safetyReason}});if(!r.ok)throw new Error(r.code);setComplete(true);localStorage.removeItem(dk(auth.userId));localStorage.removeItem(sk(auth.userId))}catch(e){setError(e instanceof Error?e.message:'day069_completion_failed')}finally{setBusy(false)}}
if(!auth.userId)return <main style={{padding:32,color:'#eee'}}>ENTRE NO ÁTRIO PARA INICIAR O DAY 069.</main>;if(complete)return <main style={{padding:32,color:'#eee'}}><h1>Day 069 concluído</h1><p>Mebahel III registrado. Próximo: Day 070.</p></main>;
const noSymptoms=!Object.values(d.symptoms).some(Boolean),checks=[d.activeDone,d.seated,d.naturalHead,d.moderate,d.slow,d.pause,d.belowFatigue,d.noForced,d.noExtreme,d.thirtyOptional,d.guidance,d.controlDone,d.separate,d.central,d.sameDuration,d.comparison,d.afterBoth,d.observableOnly,d.noBrainwave,d.noHemisphere,d.noTherapy,d.nullValid,d.reduceIfDiscomfort,d.noCompetition,d.psalm,d.formula,d.eyesRested,d.traditionalSeparated,d.thanks,d.headNormal,d.noDizziness,d.limitation,d.abandonIfNeeded,d.returned,d.privacy,d.voluntary,d.finalSafety].every(Boolean),ready=checks&&noSymptoms&&d.activeSeconds>=1&&d.controlSeconds>=1&&d.reps>=1&&!d.safetyStop&&activeStart===null&&controlStart===null;
return <main style={{maxWidth:980,margin:'0 auto',padding:'28px 18px 72px',fontFamily:'Inter,system-ui,sans-serif',color:'#eee'}}><p style={{letterSpacing:2,opacity:.7}}>CHOKMAH · MEBAHEL III · DAY 069</p><h1>Integração de Hemisférios Cerebrais</h1><p>O título é tradicional. O protocolo mede movimento ocular, conforto, foco e sintomas — não ondas cerebrais nem integração hemisférica.</p>{error&&<p role="alert" style={{color:'#ff9da8'}}>{error}</p>}
<Card title="Jachin · movimento lateral"><Timer seconds={d.activeSeconds} running={activeStart!==null} start={()=>setActiveStart(Date.now())} end={()=>end('active')}/><Num label="Repetições confortáveis" value={d.reps} set={v=>patch({reps:v})}/><p>30 repetições NÃO são obrigatórias. Pare antes de fadiga.</p>{[['Sessão ativa concluída','activeDone'],['Sentado/com apoio','seated'],['Cabeça estável só enquanto natural','naturalHead'],['Amplitude moderada','moderate'],['Ritmo lento','slow'],['Pausa + checagem de conforto','pause'],['Limite abaixo de fadiga','belowFatigue'],['Sem repetição forçada','noForced'],['Sem velocidade extrema','noExtreme'],['30 não é requisito','thirtyOptional'],['Orientação relevante respeitada','guidance']].map(([l,k])=><Check key={k} l={l} v={Boolean(d[k as keyof Draft])} set={v=>patch({[k]:v} as Partial<Draft>)}/>) }<Scores title="Antes" value={d.pre} set={v=>patch({pre:v as Day069PreScores})}/><Scores title="Depois" value={d.post} set={v=>patch({post:v as Day069PostScores})}/></Card>
<Card title="Sintomas de parada imediata">{([['Dor','pain'],['Visão turva','blurredVision'],['Náusea','nausea'],['Vertigem','vertigo'],['Nistagmo desconfortável','uncomfortableNystagmus'],['Cefaleia','headache'],['Desconforto crescente','growingDiscomfort']] as const).map(([l,k])=><Check key={k} l={l} v={d.symptoms[k]} set={v=>patch({symptoms:{...d.symptoms,[k]:v}})}/>)}{!noSymptoms&&<p style={{color:'#ff9da8'}}>PARE A PRÁTICA. Não conclua enquanto houver sintoma de alerta.</p>}</Card>
<Card title="Boaz · olhar central"><Timer seconds={d.controlSeconds} running={controlStart!==null} start={()=>setControlStart(Date.now())} end={()=>end('control')}/>{[['Controle concluído','controlDone'],['Sessão separada','separate'],['Olhar central estável','central'],['Duração aproximada semelhante','sameDuration']].map(([l,k])=><Check key={k} l={l} v={Boolean(d[k as keyof Draft])} set={v=>patch({[k]:v} as Partial<Draft>)}/>)}<Scores title="Controle" value={d.control} set={v=>patch({control:v as Day069ControlScores})}/></Card>
<Card title="Comparação">{[['Comparação concluída','comparison'],['Após ambas condições','afterBoth'],['Somente autorrelato + execução observável','observableOnly'],['Sem alegar ondas cerebrais','noBrainwave'],['Sem alegar integração hemisférica','noHemisphere'],['Não substitui terapia','noTherapy'],['Resultado nulo/controle melhor é válido','nullValid'],['Desconforto lateral reduz/descarta técnica','reduceIfDiscomfort'],['Sem competição/velocidade extrema','noCompetition']].map(([l,k])=><Check key={k} l={l} v={Boolean(d[k as keyof Draft])} set={v=>patch({[k]:v} as Partial<Draft>)}/>)}</Card>
<Card title="Pilar do Meio">{[['Salmo 9:9','psalm'],['MEM-BET-HE','formula'],['Descansei os olhos','eyesRested'],['Separei hipótese tradicional do observado','traditionalSeparated'],['Agradeci a Deus','thanks'],['Movi a cabeça normalmente','headNormal'],['Sem tontura antes de encerrar','noDizziness'],['Registrei limitação','limitation'],['Aceito abandonar a técnica se necessário','abandonIfNeeded'],['Retorno confirmado','returned'],['Practice Record sem prosa privada','privacy'],['Conclusão voluntária','voluntary'],['Estado final seguro','finalSafety']].map(([l,k])=><Check key={k} l={l} v={Boolean(d[k as keyof Draft])} set={v=>patch({[k]:v} as Partial<Draft>)}/>) }<p>Confirme visualmente 3 objetos em distâncias diferentes antes de encerrar.</p></Card>
<Card title="Vault E2EE opcional"><textarea value={privateText} onChange={e=>setPrivateText(e.target.value)} style={{width:'100%',minHeight:90}}/><button style={button} disabled={Boolean(d.vaultRef)||!privateText.trim()} onClick={()=>void saveVault().catch(e=>setError(e instanceof Error?e.message:String(e)))}>Selar reflexão</button></Card>
<Card title="Safety stop"><select value={d.safetyReason} onChange={e=>patch({safetyReason:e.target.value as Day069SafetyReason})}>{(['NONE','PAIN','BLURRED_VISION','NAUSEA','VERTIGO','HEADACHE','GROWING_DISCOMFORT','OTHER'] as const).map(x=><option key={x}>{x}</option>)}</select><button style={{...button,marginLeft:8}} onClick={stop}>Registrar stop</button></Card><button style={button} disabled={!ready||busy} onClick={()=>void seal()}>{busy?'Selando…':'Concluir Day 069'}</button></main>}
function Card({title,children}:{title:string;children:ReactNode}){return <section style={card}><h2>{title}</h2>{children}</section>}
function Check({l,v,set}:{l:string;v:boolean;set:(v:boolean)=>void}){return <label style={{display:'block',margin:'8px 0'}}><input type="checkbox" checked={v} onChange={e=>set(e.target.checked)}/> {l}</label>}
function Num({label,value,set}:{label:string;value:number;set:(v:number)=>void}){return <label style={{display:'block',margin:'8px 0'}}>{label}: <input type="number" min={0} value={value} onChange={e=>set(Math.max(0,Math.trunc(Number(e.target.value)||0)))}/></label>}
function Timer({seconds,running,start,end}:{seconds:number;running:boolean;start:()=>void;end:()=>void}){return <p>{seconds}s <button style={button} disabled={running} onClick={start}>Iniciar</button> <button style={button} disabled={!running} onClick={end}>Finalizar</button></p>}
function Scores({title,value,set}:{title:string;value:Record<string,number>;set:(v:Record<string,number>)=>void}){return <div><h3>{title}</h3>{Object.entries(value).map(([k,v])=><label key={k} style={{display:'inline-block',margin:'5px 8px'}}>{k}: <input type="number" min={0} max={10} value={v} onChange={e=>set({...value,[k]:clamp(Number(e.target.value))})}/></label>)}</div>}
