import type {QuestDefinition,QuestDefinitionLoader} from '@hnk/quest-engine';
import day036QuestJson from '../../../docs/experience/kether/day-036/day-036.quest.json';
import day036CanonJson from '../../../docs/experience/kether/day-036/day-036.canon-blocks.json';
import day036PackJson from '../../../docs/experience/kether/day-036/day-036.quest-pack.json';
import day037QuestJson from '../../../docs/experience/chokmah/day-037/day-037.quest.json';import day037CanonJson from '../../../docs/experience/chokmah/day-037/day-037.canon-blocks.json';import day037PackJson from '../../../docs/experience/chokmah/day-037/day-037.quest-pack.json';
import day038QuestJson from '../../../docs/experience/chokmah/day-038/day-038.quest.json';import day038CanonJson from '../../../docs/experience/chokmah/day-038/day-038.canon-blocks.json';import day038PackJson from '../../../docs/experience/chokmah/day-038/day-038.quest-pack.json';
import day039QuestJson from '../../../docs/experience/chokmah/day-039/day-039.quest.json';import day039CanonJson from '../../../docs/experience/chokmah/day-039/day-039.canon-blocks.json';import day039PackJson from '../../../docs/experience/chokmah/day-039/day-039.quest-pack.json';
import day040QuestJson from '../../../docs/experience/chokmah/day-040/day-040.quest.json';import day040CanonJson from '../../../docs/experience/chokmah/day-040/day-040.canon-blocks.json';import day040PackJson from '../../../docs/experience/chokmah/day-040/day-040.quest-pack.json';
import day041QuestJson from '../../../docs/experience/chokmah/day-041/day-041.quest.json';import day041CanonJson from '../../../docs/experience/chokmah/day-041/day-041.canon-blocks.json';import day041PackJson from '../../../docs/experience/chokmah/day-041/day-041.quest-pack.json';
import day042QuestJson from '../../../docs/experience/chokmah/day-042/day-042.quest.json';import day042CanonJson from '../../../docs/experience/chokmah/day-042/day-042.canon-blocks.json';import day042PackJson from '../../../docs/experience/chokmah/day-042/day-042.quest-pack.json';
import day043QuestJson from '../../../docs/experience/chokmah/day-043/day-043.quest.json';import day043CanonJson from '../../../docs/experience/chokmah/day-043/day-043.canon-blocks.json';import day043PackJson from '../../../docs/experience/chokmah/day-043/day-043.quest-pack.json';
import day044QuestJson from '../../../docs/experience/chokmah/day-044/day-044.quest.json';import day044CanonJson from '../../../docs/experience/chokmah/day-044/day-044.canon-blocks.json';import day044PackJson from '../../../docs/experience/chokmah/day-044/day-044.quest-pack.json';
import day045QuestJson from '../../../docs/experience/chokmah/day-045/day-045.quest.json';import day045CanonJson from '../../../docs/experience/chokmah/day-045/day-045.canon-blocks.json';import day045PackJson from '../../../docs/experience/chokmah/day-045/day-045.quest-pack.json';
import day046QuestJson from '../../../docs/experience/chokmah/day-046/day-046.quest.json';import day046CanonJson from '../../../docs/experience/chokmah/day-046/day-046.canon-blocks.json';import day046PackJson from '../../../docs/experience/chokmah/day-046/day-046.quest-pack.json';
import day047QuestJson from '../../../docs/experience/chokmah/day-047/day-047.quest.json';import day047CanonJson from '../../../docs/experience/chokmah/day-047/day-047.canon-blocks.json';import day047PackJson from '../../../docs/experience/chokmah/day-047/day-047.quest-pack.json';
import day048QuestJson from '../../../docs/experience/chokmah/day-048/day-048.quest.json';import day048CanonJson from '../../../docs/experience/chokmah/day-048/day-048.canon-blocks.json';import day048PackJson from '../../../docs/experience/chokmah/day-048/day-048.quest-pack.json';
import {BundledQuestLibrary as Day001To035Library} from './library.js';import type {RuntimeCanonManifest,RuntimeQuestBundle,RuntimeQuestBundleLoader} from './types.js';
function bundle(day:36|37|38|39|40|41|42|43|44|45|46|47|48):RuntimeQuestBundle{const map:Record<number,[unknown,unknown,unknown]>={36:[day036QuestJson,day036CanonJson,day036PackJson],37:[day037QuestJson,day037CanonJson,day037PackJson],38:[day038QuestJson,day038CanonJson,day038PackJson],39:[day039QuestJson,day039CanonJson,day039PackJson],40:[day040QuestJson,day040CanonJson,day040PackJson],41:[day041QuestJson,day041CanonJson,day041PackJson],42:[day042QuestJson,day042CanonJson,day042PackJson],43:[day043QuestJson,day043CanonJson,day043PackJson],44:[day044QuestJson,day044CanonJson,day044PackJson],45:[day045QuestJson,day045CanonJson,day045PackJson],46:[day046QuestJson,day046CanonJson,day046PackJson],47:[day047QuestJson,day047CanonJson,day047PackJson],48:[day048QuestJson,day048CanonJson,day048PackJson]};const[q,c,p]=map[day];return{day,quest:q as QuestDefinition,canon:c as RuntimeCanonManifest,pack:p as Record<string,unknown>}}
function validate(value:RuntimeQuestBundle){if(value.quest.day!==value.day||value.canon.source.day!==value.day)throw new Error(`quest_library_day_mismatch:${value.day}`);if(value.quest.canonical.source_sha!==value.canon.source.blob_sha)throw new Error(`quest_library_source_sha_mismatch:${value.day}`);return value}
export class PortalAwareQuestLibrary implements RuntimeQuestBundleLoader,QuestDefinitionLoader{private readonly base=new Day001To035Library();async loadBundle(day:number):Promise<RuntimeQuestBundle|null>{if(day>=36&&day<=48)return validate(bundle(day as 36|37|38|39|40|41|42|43|44|45|46|47|48));return this.base.loadBundle(day)}async loadDay(day:number):Promise<QuestDefinition|null>{return(await this.loadBundle(day))?.quest??null}listAvailableDays():number[]{return[...new Set([...this.base.listAvailableDays(),...Array.from({length:13},(_,i)=>i+36)])].sort((a,b)=>a-b)}}
export function createBundledQuestLibrary():PortalAwareQuestLibrary{return new PortalAwareQuestLibrary()}
