'use client';
import {useEffect,useMemo,useState,type ReactNode} from 'react';
import {loadDay068PracticeSessionV2,sealDay068V2,startDay068PracticeSessionV2} from '@hnk/supabase-client';
import type {Day068ControlScores,Day068EarlyExitReason,Day068FastScores,Day068SafetyReason} from '@hnk/practice-contract';
import {createWebVaultTextPort} from '../_runtime/WebVaultTextPort';
import {useWebHnkRuntime} from '../_runtime/WebHnkRuntime';
type Session=NonNullable<Awaited<ReturnType<typeof loadDay068PracticeSessionV2>>>;
type Draft={fastSeconds:number;controlSeconds:number;fastScores:Day068FastScores;controlScores:Day068ControlScores;impulsiveChecks:number;unlocks:number;feedMinutes:number;fastDone:boolean;exceptions:boolean;critical:boolean;responsibilities:boolean;earlyAllowed:boolean;earlyExit:boolean;earlyReason:Day068EarlyExitReason;noPurity:boolean;noAutoBlock:boolean;controlDone:boolean;otherDay:boolean;normalUse:boolean;comparison:boolean;afterBoth:boolean;noWinner:boolean;nullValid:boolean;egregoreMetaphor:boolean;noSingleCause:boolean;confounds:boolean;adjustRule:boolean;infoPreserved:boolean;sustainable:boolean;reviewDays:number;psalm:boolean;formula:boolean;limitCount:number;keepCount:number;responsibilityCount:number;thanks:boolean;reconnect:boolean;sevenDayRule:boolean;returned:boolean;vaultRef:string|null;privacy:boolean;voluntary:boolean;finalSafety:boolean;safetyStop:boolean;safetyReason:Day068SafetyReason};
const empty:Draft={fastSeconds:0,controlSeconds:0,fastScores:{anxietyBefore:5,checkingUrgeBefore:5,focusAfter:5,moodAfter:5},controlScores:{anxiety:5,focus:5,decisionQuality:5},impulsiveChecks:0,unlocks:0,feedMinutes:0,fastDone:false,exceptions:false,critical:false,responsibilities:false,earlyAllowed:false,earlyExit:false,earlyReason:'NONE',noPurity:false,noAutoBlock:false,controlDone:false,otherDay:false,normalUse:false,comparison:false,afterBoth:false,noWinner:false,nullValid:false,egregoreMetaphor:false,noSingleCause:false,confounds:false,adjustRule:false,infoPreserved:false,sustainable:false,reviewDays:7,psalm:false,formula:false,limitCount:1,keepCount:1,responsibilityCount:1,thanks:false,reconnect:false,sevenDayRule:false,returned:false,vaultRef:null,privacy:false,voluntary:false,finalSafety:false,safetyStop:false,safetyReason:'NONE'};
const card={background:'#121217',border:'1px solid #34313f',borderRadius:18,padding:18,margin:'14px 0'} as const,button={background:'#d9b86c',color:'#17120a',border:0,borderRadius:10,padding:'10px 13px',fontWeight:800,cursor:'pointer'} as const;
function dk(u:string){return`hnk:day068:${u}:draft:v2`}function sk(u:string){return`hnk:day068:${u}:session:v2`}function parse<T>(v:string|null):T|null{try{return v?JSON.parse(v) as T:null}catch{return null}}function cid(u:string){return`hnk-web-d068-v2-${u}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`}function clamp(v:number){return Number.isFinite(v)?Math.max(0,Math.min(10,Math.trunc(v))):0}
export function Day068GoldenV2Web(){const auth=useWebHnkRuntime(),vault=useMemo(()=>auth.userId?createWebVaultTextPort(auth.client??null):null,[auth.client,auth.userId]);const[session,setSession]=useState<Session|null>(null),[d,setD]=useState<Draft>(empty),[loaded,setLoaded]=useState(false),[fastStart,setFastStart]=useState<number|null>(null),[controlStart,setControlStart]=useState<number|null>(null),[sourceNames,setSourceNames]=useState<[string,string,string]>(['','','']),[privateText,setPrivateText]=useState(''),[error,setError]=useState<string|null>(null),[busy,setBusy]=useState(false),[complete,setComplete]=useState(false);const live=Boolean(auth.configured&&auth.phase==='signed-in'&&auth.client&&auth.userId);
useEffect(()=>{if(!auth.userId)return;setD(parse<Draft>(localStorage.getItem(dk(auth.userId)))??empty);setLoaded(true);const id=localStorage.getItem(sk(auth.userId));if(id&&auth.client)void loadDay068PracticeSessionV2(auth.client,id).then(x=>x?setSession(x):localStorage.removeItem(sk(auth.userId!))).catch(()=>undefined)},[auth.client,auth.userId]);
useEffect(()=>{if(auth.userId&&loaded&&!complete)localStorage.setItem(dk(auth.userId),JSON.stringify(d))},[auth.userId,d,loaded,complete]);
useEffect(()=>{const h=()=>{if(document.visibilityState==='visible')return;setSourceNames(['','','']);setPrivateText('');if(fastStart!==null||controlStart!==null){setFastStart(null);setControlStart(null);setError('medicao_corrente_descartada__retorne_ao_foreground')}};document.addEventListener('visibilitychange',h);return()=>document.removeEventListener('visibilitychange',h)},[fastStart,controlStart]);
function patch(p:Partial<Draft>){setD(x=>({...x,...p}))}function end(which:'fast'|'control'){const st=which==='fast'?fastStart:controlStart;if(st===null)return;const add=Math.max(1,Math.floor((Date.now()-st)/1000));if(which==='fast'){patch({fastSeconds:d.fastSeconds+add});setFastStart(null)}else{patch({controlSeconds:d.controlSeconds+add});setControlStart(null)}}
async function ensureSession(){if(session)return session;if(!live||!auth.client||!auth.userId)throw new Error('online_session_required_before_day068_practice');const x=await startDay068PracticeSessionV2(auth.client,{clientSessionId:cid(auth.userId),appVersion:'0.1.0-web-day068-v2'});setSession(x);localStorage.setItem(sk(auth.userId),x.id);return x}
async function saveVault(){const names=sourceNames.map(x=>x.trim()).filter(Boolean);if(names.length!==3&&!privateText.trim())throw new Error('private_content_empty');if(!vault||!auth.userId)throw new Error('vault_unavailable');await ensureSession();const e=await vault.saveText({userId:auth.userId,day:68,kind:'journal',plaintext:JSON.stringify({schema:'hnk-day068-private-v2',sources:names,text:privateText.trim()})});patch({vaultRef:e.entryId});setSourceNames(['','','']);setPrivateText('')}
async function resolvedVault(){if(!d.vaultRef)return undefined;if(!vault||!auth.userId)throw new Error('vault_unavailable');await vault.flushPending(auth.userId);const x=await vault.resolveEntryId(auth.userId,d.vaultRef);if(!x)throw new Error('vault_sync_required');return x}
function stop(){if(d.safetyReason==='NONE'){setError('day068_safety_reason_required');return}setSourceNames(['','','']);setPrivateText('');setFastStart(null);setControlStart(null);patch({safetyStop:true,finalSafety:false});setError('safety_stop_registered__do_not_complete')}
async function seal(){if(!auth.client||!auth.userId)return;setBusy(true);setError(null);try{const s=await ensureSession(),ref=await resolvedVault();const r=await sealDay068V2(auth.client,{evidence:{sessionId:s.id,fast:{durationSeconds:d.fastSeconds,sourcesCount:3,completedConfirmed:d.fastDone,essentialExceptionsDefinedConfirmed:d.exceptions,criticalAlertsPreservedConfirmed:d.critical,responsibilitiesPreservedConfirmed:d.responsibilities,earlyExitAllowedConfirmed:d.earlyAllowed,earlyExitOccurred:d.earlyExit,earlyExitReason:d.earlyReason,noMoralPurityClaimConfirmed:d.noPurity,noAutomaticCriticalBlockingConfirmed:d.noAutoBlock,scores:d.fastScores,impulsiveChecks:d.impulsiveChecks},control:{durationSeconds:d.controlSeconds,completedConfirmed:d.controlDone,comparableOtherDayConfirmed:d.otherDay,normalUseNoBehaviorImprovementConfirmed:d.normalUse,scores:d.controlScores,unlocks:d.unlocks,feedMinutes:d.feedMinutes},comparison:{completedConfirmed:d.comparison,afterBothWindowsConfirmed:d.afterBoth,noWinnerDeclaredConfirmed:d.noWinner,nullOrControlBetterResultValidConfirmed:d.nullValid,egregoreMetaphorNotLiteralizedConfirmed:d.egregoreMetaphor,noSingleCauseClaimConfirmed:d.noSingleCause,routineSleepWorkConfoundsConsideredConfirmed:d.confounds,communicationHarmTriggersRuleAdjustmentConfirmed:d.adjustRule,informationAndResponsibilityPreservedConfirmed:d.infoPreserved,sustainableRuleDefinedConfirmed:d.sustainable,reviewDays:d.reviewDays},middle:{psalm99Confirmed:d.psalm,memBetHeConfirmed:d.formula,sourceToLimitNamedCount:d.limitCount,sourceToKeepNamedCount:d.keepCount,responsibilityNotSilencedNamedCount:d.responsibilityCount,thanksToGodConfirmed:d.thanks,deliberateReconnectionConfirmed:d.reconnect,sevenDayRuleConfirmed:d.sevenDayRule,returnConfirmed:d.returned},...(ref?{privateVaultEntryRef:ref,privateVaultE2eeConfirmed:true}:{}),practiceRecordNoSourceNamesOrPrivateProseConfirmed:d.privacy,voluntaryCompletionConfirmed:d.voluntary,finalSafetyClearConfirmed:d.finalSafety,safetyStopOccurred:d.safetyStop,safetyStopReason:d.safetyReason}});if(!r.ok)throw new Error(r.code);setComplete(true);localStorage.removeItem(dk(auth.userId));localStorage.removeItem(sk(auth.userId))}catch(e){setError(e instanceof Error?e.message:'day068_completion_failed')}finally{setBusy(false)}}
if(!auth.userId)return <main style={{padding:32,color:'#eee'}}>ENTRE NO ÁTRIO PARA INICIAR O DAY 068.</main>;if(complete)return <main style={{padding:32,color:'#eee'}}><h1>Day 068 concluído</h1><p>Mebahel II registrado. Próximo: Day 069.</p></main>;
const sourcesReady=sourceNames.every(x=>x.trim().length>0)||Boolean(d.vaultRef);const checks=[d.fastDone,d.exceptions,d.critical,d.responsibilities,d.earlyAllowed,d.noPurity,d.noAutoBlock,d.controlDone,d.otherDay,d.normalUse,d.comparison,d.afterBoth,d.noWinner,d.nullValid,d.egregoreMetaphor,d.noSingleCause,d.confounds,d.adjustRule,d.infoPreserved,d.sustainable,d.psalm,d.formula,d.thanks,d.reconnect,d.sevenDayRule,d.returned,d.privacy,d.voluntary,d.finalSafety].every(Boolean);const ready=sourcesReady&&checks&&d.fastSeconds>=1&&d.fastSeconds<=43200&&d.controlSeconds>=1&&d.controlSeconds<=43200&&d.reviewDays===7&&(!d.earlyExit||d.earlyReason!=='NONE')&&(d.earlyExit||d.earlyReason==='NONE')&&!d.safetyStop&&fastStart===null&&controlStart===null;
return <main style={{maxWidth:980,margin:'0 auto',padding:'28px 18px 72px',fontFamily:'Inter,system-ui,sans-serif',color:'#eee'}}><p style={{letterSpacing:2,opacity:.7}}>CHOKMAH · MEBAHEL II · DAY 068</p><h1>Quebra de Megagregores de Ruído</h1><p>“Megagregor” é linguagem tradicional/metafórica para padrões coletivos de influência; o protocolo não afirma entidade externa mensurada.</p>{error&&<p role="alert" style={{color:'#ff9da8'}}>{error}</p>}
<Card title="Três fontes · memória local apenas">{sourceNames.map((v,i)=><input key={i} value={v} onChange={e=>setSourceNames(x=>{const n:[string,string,string]=[...x];n[i]=e.target.value;return n})} placeholder={`Fonte ${i+1}`} style={{display:'block',width:'100%',margin:'8px 0',padding:10}}/>)}<p>Esses nomes não entram no draft nem no evidence. Opcionalmente, sele no Vault.</p></Card>
<Card title="Jachin · jejum eletrônico"><Timer seconds={d.fastSeconds} running={fastStart!==null} start={()=>setFastStart(Date.now())} end={()=>end('fast')}/><p>Teto canônico: 12h. Encerrar antes por responsabilidade real é válido.</p>{[['Jejum concluído/encerrado conscientemente','fastDone'],['Exceções essenciais definidas','exceptions'],['Alertas críticos preservados','critical'],['Responsabilidades preservadas','responsibilities'],['Saída antecipada permitida','earlyAllowed'],['Sem moralizar pureza digital','noPurity'],['App não bloqueou serviço crítico automaticamente','noAutoBlock']].map(([l,k])=><Check key={k} l={l} v={Boolean(d[k as keyof Draft])} set={v=>patch({[k]:v} as Partial<Draft>)}/>)}<Check l="Houve saída antecipada" v={d.earlyExit} set={v=>patch({earlyExit:v,earlyReason:v?d.earlyReason:'NONE'})}/><label>Motivo: <select value={d.earlyReason} onChange={e=>patch({earlyReason:e.target.value as Day068EarlyExitReason})}>{(['NONE','ESSENTIAL_COMMUNICATION','WORK','FAMILY','SECURITY_AUTH','OTHER'] as const).map(x=><option key={x}>{x}</option>)}</select></label><Metric label="Ansiedade antes" value={d.fastScores.anxietyBefore} set={v=>patch({fastScores:{...d.fastScores,anxietyBefore:v}})}/><Metric label="Impulso de checagem antes" value={d.fastScores.checkingUrgeBefore} set={v=>patch({fastScores:{...d.fastScores,checkingUrgeBefore:v}})}/><Metric label="Foco depois" value={d.fastScores.focusAfter} set={v=>patch({fastScores:{...d.fastScores,focusAfter:v}})}/><Metric label="Humor depois" value={d.fastScores.moodAfter} set={v=>patch({fastScores:{...d.fastScores,moodAfter:v}})}/><NumberField label="Checagens impulsivas" value={d.impulsiveChecks} set={v=>patch({impulsiveChecks:v})}/></Card>
<Card title="Boaz · janela habitual controle"><Timer seconds={d.controlSeconds} running={controlStart!==null} start={()=>setControlStart(Date.now())} end={()=>end('control')}/>{[['Controle concluído','controlDone'],['Outro dia comparável','otherDay'],['Uso normal sem tentar melhorar comportamento','normalUse']].map(([l,k])=><Check key={k} l={l} v={Boolean(d[k as keyof Draft])} set={v=>patch({[k]:v} as Partial<Draft>)}/>)}<NumberField label="Desbloqueios" value={d.unlocks} set={v=>patch({unlocks:v})}/><NumberField label="Minutos de feed" value={d.feedMinutes} set={v=>patch({feedMinutes:v})}/><Metric label="Ansiedade" value={d.controlScores.anxiety} set={v=>patch({controlScores:{...d.controlScores,anxiety:v}})}/><Metric label="Foco" value={d.controlScores.focus} set={v=>patch({controlScores:{...d.controlScores,focus:v}})}/><Metric label="Qualidade de decisão" value={d.controlScores.decisionQuality} set={v=>patch({controlScores:{...d.controlScores,decisionQuality:v}})}/></Card>
<Card title="Comparação">{[['Comparação concluída','comparison'],['Após ambas as janelas','afterBoth'],['Sem vencedor','noWinner'],['Resultado nulo/controle melhor é válido','nullValid'],['“Egregor” mantido como metáfora, não entidade literal','egregoreMetaphor'],['Sem atribuir tudo a uma causa única','noSingleCause'],['Considerei rotina, sono e trabalho','confounds'],['Se houve prejuízo de comunicação, ajustei a regra','adjustRule'],['Informação e responsabilidade preservadas','infoPreserved'],['Regra sustentável definida','sustainable']].map(([l,k])=><Check key={k} l={l} v={Boolean(d[k as keyof Draft])} set={v=>patch({[k]:v} as Partial<Draft>)}/>)}<p>Revisão: 7 dias.</p></Card>
<Card title="Pilar do Meio">{[['Salmo 9:9','psalm'],['MEM-BET-HE','formula'],['Agradeci a Deus','thanks'],['Retornei deliberadamente à conectividade','reconnect'],['Regra definida para revisão em 7 dias','sevenDayRule'],['Retorno confirmado','returned'],['Practice Record sem nomes/prosa privada','privacy'],['Conclusão voluntária','voluntary'],['Estado final seguro','finalSafety']].map(([l,k])=><Check key={k} l={l} v={Boolean(d[k as keyof Draft])} set={v=>patch({[k]:v} as Partial<Draft>)}/>) }<p>Nomeie localmente: 1 fonte a limitar, 1 a manter e 1 responsabilidade que não pode ser silenciada.</p></Card>
<Card title="Vault E2EE opcional"><textarea value={privateText} onChange={e=>setPrivateText(e.target.value)} style={{width:'100%',minHeight:90}} placeholder="Reflexão privada"/><button style={button} disabled={Boolean(d.vaultRef)||(!privateText.trim()&&!sourceNames.some(Boolean))} onClick={()=>void saveVault().catch(e=>setError(e instanceof Error?e.message:String(e)))}>Selar conteúdo privado</button></Card>
<Card title="Safety stop"><select value={d.safetyReason} onChange={e=>patch({safetyReason:e.target.value as Day068SafetyReason})}>{(['NONE','DISTRESS','ESSENTIAL_RESPONSIBILITY_RISK','SECURITY_OR_AUTH_RISK','OTHER'] as const).map(x=><option key={x}>{x}</option>)}</select><button style={{...button,marginLeft:8}} onClick={stop}>Registrar stop</button></Card><button style={button} disabled={!ready||busy} onClick={()=>void seal()}>{busy?'Selando…':'Concluir Day 068'}</button></main>}
function Card({title,children}:{title:string;children:ReactNode}){return <section style={card}><h2>{title}</h2>{children}</section>}
function Check({l,v,set}:{l:string;v:boolean;set:(v:boolean)=>void}){return <label style={{display:'block',margin:'7px 0'}}><input type="checkbox" checked={v} onChange={e=>set(e.target.checked)}/> {l}</label>}
function Timer({seconds,running,start,end}:{seconds:number;running:boolean;start:()=>void;end:()=>void}){return <div><strong>{seconds}s</strong> <button style={button} disabled={running} onClick={start}>Iniciar</button><button style={{...button,marginLeft:8}} disabled={!running} onClick={end}>Finalizar</button></div>}
function Metric({label,value,set}:{label:string;value:number;set:(v:number)=>void}){return <label style={{display:'block',margin:'8px 0'}}>{label}: <input type="number" min={0} max={10} value={value} onChange={e=>set(clamp(Number(e.target.value)))}/></label>}
function NumberField({label,value,set}:{label:string;value:number;set:(v:number)=>void}){return <label style={{display:'block',margin:'8px 0'}}>{label}: <input type="number" min={0} value={value} onChange={e=>set(Math.max(0,Math.trunc(Number(e.target.value)||0)))}/></label>}
