'use client';
import {useEffect,useMemo,useState,type ReactNode} from 'react';
import {loadDay071PracticeSessionV2,sealDay071V2,startDay071PracticeSessionV2} from '@hnk/supabase-client';
import type {Day071ActiveScores,Day071ControlScores,Day071SafetyReason} from '@hnk/practice-contract';
import {createWebVaultTextPort} from '../_runtime/WebVaultTextPort';
import {useWebHnkRuntime} from '../_runtime/WebHnkRuntime';
type Session=NonNullable<Awaited<ReturnType<typeof loadDay071PracticeSessionV2>>>;
type Draft={activeSeconds:number;controlSeconds:number;activeDone:boolean;safeSpace:boolean;noRealFlame:boolean;imaginaryOnly:boolean;circleSymbolic:boolean;patternNoEntity:boolean;environmentAware:boolean;freeToStop:boolean;visualizationClosed:boolean;activeEffect:boolean;controlDone:boolean;separateMoment:boolean;sameGesture:boolean;noFormula:boolean;noImaginaryFlame:boolean;noExpulsion:boolean;similarDuration:boolean;controlEffect:boolean;comparison:boolean;afterBoth:boolean;noWinner:boolean;nullValid:boolean;noEntityDiagnosis:boolean;noThirdPartyAccusation:boolean;antiCompulsion:boolean;noRepeatFear:boolean;supportPriority:boolean;realSafety:boolean;carePreserved:boolean;noInvulnerability:boolean;noExternalEnemy:boolean;psalm:boolean;formula:boolean;finalOnce:boolean;thanks:boolean;exerciseClosed:boolean;flamesReleased:boolean;handsOpened:boolean;environmentObserved:boolean;practicalBoundary:boolean;openHypothesis:boolean;noMonitoring:boolean;noReconfirmation:boolean;dailyAction:boolean;returned:boolean;activeScores:Day071ActiveScores;controlScores:Day071ControlScores;vaultRef:string|null;privacy:boolean;voluntary:boolean;finalSafety:boolean;safetyStop:boolean;safetyReason:Day071SafetyReason};
const a0:Day071ActiveScores={tensionBefore:5,tensionAfter:5,clarityBefore:5,clarityAfter:5,ruminationBefore:5,ruminationAfter:5,expectation:0};const c0:Day071ControlScores={tension:5,clarity:5,rumination:5,expectation:0};
const empty:Draft={activeSeconds:0,controlSeconds:0,activeDone:false,safeSpace:false,noRealFlame:false,imaginaryOnly:false,circleSymbolic:false,patternNoEntity:false,environmentAware:false,freeToStop:false,visualizationClosed:false,activeEffect:false,controlDone:false,separateMoment:false,sameGesture:false,noFormula:false,noImaginaryFlame:false,noExpulsion:false,similarDuration:false,controlEffect:false,comparison:false,afterBoth:false,noWinner:false,nullValid:false,noEntityDiagnosis:false,noThirdPartyAccusation:false,antiCompulsion:false,noRepeatFear:false,supportPriority:false,realSafety:false,carePreserved:false,noInvulnerability:false,noExternalEnemy:false,psalm:false,formula:false,finalOnce:false,thanks:false,exerciseClosed:false,flamesReleased:false,handsOpened:false,environmentObserved:false,practicalBoundary:false,openHypothesis:false,noMonitoring:false,noReconfirmation:false,dailyAction:false,returned:false,activeScores:{...a0},controlScores:{...c0},vaultRef:null,privacy:false,voluntary:false,finalSafety:false,safetyStop:false,safetyReason:'NONE'};
const card={background:'#121217',border:'1px solid #34313f',borderRadius:18,padding:18,margin:'14px 0'} as const,button={background:'#d8c07a',color:'#16120a',border:0,borderRadius:10,padding:'10px 14px',fontWeight:800,cursor:'pointer'} as const;
function dk(u:string){return`hnk:day071:${u}:draft:v2`}function sk(u:string){return`hnk:day071:${u}:session:v2`}function parse<T>(v:string|null):T|null{try{return v?JSON.parse(v) as T:null}catch{return null}}function cid(u:string){return`hnk-web-d071-v2-${u}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`}function clamp(v:number){return Number.isFinite(v)?Math.max(0,Math.min(10,Math.trunc(v))):0}
export function Day071GoldenV2Web(){const auth=useWebHnkRuntime(),vault=useMemo(()=>auth.userId?createWebVaultTextPort(auth.client??null):null,[auth.client,auth.userId]);const[session,setSession]=useState<Session|null>(null),[d,setD]=useState<Draft>(empty),[loaded,setLoaded]=useState(false),[activeStart,setActiveStart]=useState<number|null>(null),[controlStart,setControlStart]=useState<number|null>(null),[privateText,setPrivateText]=useState(''),[error,setError]=useState<string|null>(null),[busy,setBusy]=useState(false),[complete,setComplete]=useState(false);const live=Boolean(auth.configured&&auth.phase==='signed-in'&&auth.client&&auth.userId);
useEffect(()=>{if(!auth.userId)return;setD(parse<Draft>(localStorage.getItem(dk(auth.userId)))??empty);setLoaded(true);const id=localStorage.getItem(sk(auth.userId));if(id&&auth.client)void loadDay071PracticeSessionV2(auth.client,id).then(x=>x?setSession(x):localStorage.removeItem(sk(auth.userId!))).catch(()=>undefined)},[auth.client,auth.userId]);
useEffect(()=>{if(auth.userId&&loaded&&!complete)localStorage.setItem(dk(auth.userId),JSON.stringify(d))},[auth.userId,d,loaded,complete]);
useEffect(()=>{const h=()=>{if(document.visibilityState==='visible')return;setPrivateText('');if(activeStart!==null||controlStart!==null){setActiveStart(null);setControlStart(null);setError('medicao_corrente_descartada__retorne_ao_foreground')}};document.addEventListener('visibilitychange',h);return()=>document.removeEventListener('visibilitychange',h)},[activeStart,controlStart]);
function patch(p:Partial<Draft>){setD(x=>({...x,...p}))}function end(w:'active'|'control'){const st=w==='active'?activeStart:controlStart;if(st===null)return;const add=Math.max(1,Math.floor((Date.now()-st)/1000));if(w==='active'){patch({activeSeconds:d.activeSeconds+add});setActiveStart(null)}else{patch({controlSeconds:d.controlSeconds+add});setControlStart(null)}}
async function ensureSession(){if(session)return session;if(!live||!auth.client||!auth.userId)throw new Error('online_session_required_before_day071_practice');const x=await startDay071PracticeSessionV2(auth.client,{clientSessionId:cid(auth.userId),appVersion:'0.2.0-web-day071-v2'});setSession(x);localStorage.setItem(sk(auth.userId),x.id);return x}
async function saveVault(){if(!privateText.trim())throw new Error('named_pattern_required');if(!vault||!auth.userId)throw new Error('vault_unavailable');await ensureSession();const e=await vault.saveText({userId:auth.userId,day:71,kind:'journal',plaintext:JSON.stringify({schema:'hnk-day071-pattern-v2',pattern:privateText.trim()})});patch({vaultRef:e.entryId});setPrivateText('')}
async function resolvedVault(){if(!d.vaultRef)throw new Error('day071_vault_required');if(!vault||!auth.userId)throw new Error('vault_unavailable');await vault.flushPending(auth.userId);const x=await vault.resolveEntryId(auth.userId,d.vaultRef);if(!x)throw new Error('vault_sync_required');return x}
function stop(){if(d.safetyReason==='NONE'){setError('day071_safety_reason_required');return}setPrivateText('');setActiveStart(null);setControlStart(null);patch({safetyStop:true,finalSafety:false});setError('safety_stop_registered__do_not_complete')}
async function seal(){if(!auth.client||!auth.userId)return;setBusy(true);setError(null);try{const s=await ensureSession(),ref=await resolvedVault();const r=await sealDay071V2(auth.client,{evidence:{sessionId:s.id,active:{durationSeconds:d.activeSeconds,completedConfirmed:d.activeDone,safeSpaceConfirmed:d.safeSpace,realFlameNotUsedConfirmed:d.noRealFlame,imaginaryFlameOnlyConfirmed:d.imaginaryOnly,circleSymbolicConfirmed:d.circleSymbolic,patternNamedWithoutEntityClaimConfirmed:d.patternNoEntity,environmentAwarenessPreservedConfirmed:d.environmentAware,freedomToStopConfirmed:d.freeToStop,visualizationClosedConfirmed:d.visualizationClosed,activeEffectPresent:d.activeEffect,scores:d.activeScores},control:{durationSeconds:d.controlSeconds,completedConfirmed:d.controlDone,separateMomentConfirmed:d.separateMoment,sameGestureAndBreathingConfirmed:d.sameGesture,noFormulaConfirmed:d.noFormula,noImaginaryFlameConfirmed:d.noImaginaryFlame,noExpulsionLanguageConfirmed:d.noExpulsion,similarDurationConfirmed:d.similarDuration,controlEffectPresent:d.controlEffect,scores:d.controlScores},comparison:{completedConfirmed:d.comparison,afterBothConditionsConfirmed:d.afterBoth,noWinnerDeclaredConfirmed:d.noWinner,nullOrControlBetterResultValidConfirmed:d.nullValid,entityDiagnosisNotClaimedConfirmed:d.noEntityDiagnosis,thirdPartyEntityAccusationForbiddenConfirmed:d.noThirdPartyAccusation,antiCompulsionRuleConfirmed:d.antiCompulsion,noRepeatToNeutralizeFearConfirmed:d.noRepeatFear,persistentFearSupportPriorityConfirmed:d.supportPriority,realSafetyPreservedConfirmed:d.realSafety,appropriateCarePreservedConfirmed:d.carePreserved,invulnerabilityNotClaimedConfirmed:d.noInvulnerability,externalEnemyNotConfirmed:d.noExternalEnemy},middle:{psalm99Confirmed:d.psalm,memBetHeConfirmed:d.formula,finalGestureOnceConfirmed:d.finalOnce,thanksToGodConfirmed:d.thanks,exerciseDeclaredClosedConfirmed:d.exerciseClosed,imaginaryFlamesReleasedConfirmed:d.flamesReleased,handsOpenedConfirmed:d.handsOpened,environmentObservedConfirmed:d.environmentObserved,practicalBoundaryNamedCount:d.practicalBoundary?1:0,openHypothesisNamedCount:d.openHypothesis?1:0,noContaminationMonitoringConfirmed:d.noMonitoring,noRitualReconfirmationConfirmed:d.noReconfirmation,dailyActionNamedCount:d.dailyAction?1:0,returnConfirmed:d.returned},privateVaultEntryRef:ref,privateVaultE2eeConfirmed:true,practiceRecordNoPrivateProseConfirmed:d.privacy,voluntaryCompletionConfirmed:d.voluntary,finalSafetyClearConfirmed:d.finalSafety,safetyStopOccurred:d.safetyStop,safetyStopReason:d.safetyReason}});if(!r.ok)throw new Error(r.code);setComplete(true);localStorage.removeItem(dk(auth.userId));localStorage.removeItem(sk(auth.userId))}catch(e){setError(e instanceof Error?e.message:'day071_completion_failed')}finally{setBusy(false)}}
if(!auth.userId)return <main style={{padding:32,color:'#eee'}}>ENTRE NO ÁTRIO PARA INICIAR O DAY 071.</main>;if(complete)return <main style={{padding:32,color:'#eee'}}><h1>Day 071 concluído</h1><p>Mebahel V registrado. Próximo: Day 072.</p></main>;
const flags=[d.activeDone,d.safeSpace,d.noRealFlame,d.imaginaryOnly,d.circleSymbolic,d.patternNoEntity,d.environmentAware,d.freeToStop,d.visualizationClosed,d.controlDone,d.separateMoment,d.sameGesture,d.noFormula,d.noImaginaryFlame,d.noExpulsion,d.similarDuration,d.comparison,d.afterBoth,d.noWinner,d.nullValid,d.noEntityDiagnosis,d.noThirdPartyAccusation,d.antiCompulsion,d.noRepeatFear,d.supportPriority,d.realSafety,d.carePreserved,d.noInvulnerability,d.noExternalEnemy,d.psalm,d.formula,d.finalOnce,d.thanks,d.exerciseClosed,d.flamesReleased,d.handsOpened,d.environmentObserved,d.practicalBoundary,d.openHypothesis,d.noMonitoring,d.noReconfirmation,d.dailyAction,d.returned,d.privacy,d.voluntary,d.finalSafety].every(Boolean);const ready=flags&&Boolean(d.vaultRef)&&d.activeSeconds>=1&&d.controlSeconds>=1&&!d.safetyStop&&activeStart===null&&controlStart===null;
return <main style={{maxWidth:980,margin:'0 auto',padding:'28px 18px 72px',fontFamily:'Inter,system-ui,sans-serif',color:'#eee'}}><p style={{letterSpacing:2,opacity:.7}}>CHOKMAH · MEBAHEL V · DAY 071</p><h1>O Ritual de Banimento de Mebahel</h1><p>“Larva etérica mental” é vocabulário tradicional/metafórico para padrões, ruminação ou peso percebido; não é diagnóstico de entidade. O rito é simbólico e não substitui segurança real ou cuidado apropriado.</p>{error&&<p role="alert" style={{color:'#ff9da8'}}>{error}</p>}
<Card title="Jachin · rito ativo"><Timer seconds={d.activeSeconds} running={activeStart!==null} start={()=>setActiveStart(Date.now())} end={()=>end('active')}/>{[['Sessão ativa concluída','activeDone'],['Espaço seguro','safeSpace'],['Sem chama real','noRealFlame'],['Chamas apenas imaginárias','imaginaryOnly'],['Círculo entendido como símbolo','circleSymbolic'],['Padrão nomeado sem alegar entidade','patternNoEntity'],['Consciência do ambiente preservada','environmentAware'],['Liberdade para parar','freeToStop'],['Visualização encerrada','visualizationClosed']].map(([l,k])=><Check key={k} label={l} value={Boolean(d[k as keyof Draft])} set={v=>patch({[k]:v} as Partial<Draft>)}/>) }<Check label="Percebi algum efeito subjetivo" value={d.activeEffect} set={v=>patch({activeEffect:v})}/><ActiveScores value={d.activeScores} set={v=>patch({activeScores:v})}/></Card>
<Card title="Boaz · controle neutro"><Timer seconds={d.controlSeconds} running={controlStart!==null} start={()=>setControlStart(Date.now())} end={()=>end('control')}/>{[['Controle concluído','controlDone'],['Outro momento','separateMoment'],['Mesmo gesto + respiração','sameGesture'],['Sem fórmula','noFormula'],['Sem chamas imaginárias','noImaginaryFlame'],['Sem linguagem de expulsão','noExpulsion'],['Duração semelhante','similarDuration']].map(([l,k])=><Check key={k} label={l} value={Boolean(d[k as keyof Draft])} set={v=>patch({[k]:v} as Partial<Draft>)}/>)}<Check label="Percebi algum efeito subjetivo" value={d.controlEffect} set={v=>patch({controlEffect:v})}/><ControlScores value={d.controlScores} set={v=>patch({controlScores:v})}/></Card>
<Card title="Comparação e anti-compulsão">{[['Comparação concluída','comparison'],['Após ambas as condições','afterBoth'],['Sem vencedor','noWinner'],['Nulo/controle melhor é válido','nullValid'],['Sem diagnóstico de entidade','noEntityDiagnosis'],['Nunca acusar terceiros de entidade/influência','noThirdPartyAccusation'],['Regra anti-compulsão confirmada','antiCompulsion'],['Não repetir para neutralizar medo','noRepeatFear'],['Medo persistente → grounding/apoio primeiro','supportPriority'],['Segurança real preservada','realSafety'],['Cuidado apropriado preservado','carePreserved'],['Sem invulnerabilidade','noInvulnerability'],['Sem inimigo externo confirmado','noExternalEnemy']].map(([l,k])=><Check key={k} label={l} value={Boolean(d[k as keyof Draft])} set={v=>patch({[k]:v} as Partial<Draft>)}/>)}</Card>
<Card title="Pilar do Meio · encerrar de verdade">{[['Salmo 9:9','psalm'],['MEM-BET-HE','formula'],['Gesto final uma única vez','finalOnce'],['Agradeci a Deus','thanks'],['Declare o exercício encerrado','exerciseClosed'],['Deixei as chamas imaginárias desaparecerem','flamesReleased'],['Abri as mãos','handsOpened'],['Observei o ambiente','environmentObserved'],['Nomeei 1 limite prático','practicalBoundary'],['Nomeei 1 hipótese aberta','openHypothesis'],['Não monitorarei sinais de contaminação','noMonitoring'],['Não buscarei reconfirmação ritual','noReconfirmation'],['Nomeei 1 ação cotidiana','dailyAction'],['Retorno confirmado','returned'],['Practice Record sem prosa privada','privacy'],['Conclusão voluntária','voluntary'],['Estado final seguro','finalSafety']].map(([l,k])=><Check key={k} label={l} value={Boolean(d[k as keyof Draft])} set={v=>patch({[k]:v} as Partial<Draft>)}/>)}</Card>
<Card title="Vault E2EE obrigatório"><p>Digite apenas o padrão/ruminação que deseja encerrar. Não descreva terceiros como entidades.</p><textarea value={privateText} onChange={e=>setPrivateText(e.target.value)} style={{width:'100%',minHeight:90}}/><button style={button} disabled={Boolean(d.vaultRef)||!privateText.trim()} onClick={()=>void saveVault().catch(e=>setError(e instanceof Error?e.message:String(e)))}>{d.vaultRef?'Padrão selado':'Selar padrão no Vault'}</button></Card>
<Card title="Safety stop"><select value={d.safetyReason} onChange={e=>patch({safetyReason:e.target.value as Day071SafetyReason})}>{(['NONE','COMPULSIVE_REPEAT_URGE','PERSISTENT_FEAR','PERSECUTION_DISTRESS','DISORIENTATION','FUNCTIONAL_IMPAIRMENT','OTHER'] as const).map(x=><option key={x}>{x}</option>)}</select><button style={{...button,marginLeft:8}} onClick={stop}>Registrar stop</button></Card><button style={button} disabled={!ready||busy} onClick={()=>void seal()}>{busy?'Selando…':'Concluir Day 071'}</button></main>}
function Card({title,children}:{title:string;children:ReactNode}){return <section style={card}><h2>{title}</h2>{children}</section>}
function Check({label,value,set}:{label:string;value:boolean;set:(v:boolean)=>void}){return <label style={{display:'flex',gap:10,alignItems:'center',margin:'8px 0'}}><input type="checkbox" checked={value} onChange={e=>set(e.target.checked)}/><span>{label}</span></label>}
function Timer({seconds,running,start,end}:{seconds:number;running:boolean;start:()=>void;end:()=>void}){return <div style={{display:'flex',gap:10,alignItems:'center',marginBottom:12}}><strong>{seconds}s</strong><button style={button} disabled={running} onClick={start}>Iniciar</button><button style={button} disabled={!running} onClick={end}>Finalizar</button></div>}
function N({label,value,set}:{label:string;value:number;set:(v:number)=>void}){return <label style={{display:'grid',gridTemplateColumns:'1fr 90px',gap:10,margin:'6px 0'}}><span>{label}</span><input type="number" min={0} max={10} value={value} onChange={e=>set(clamp(Number(e.target.value)))}/></label>}
function ActiveScores({value,set}:{value:Day071ActiveScores;set:(v:Day071ActiveScores)=>void}){return <div><N label="Tensão antes" value={value.tensionBefore} set={v=>set({...value,tensionBefore:v})}/><N label="Tensão depois" value={value.tensionAfter} set={v=>set({...value,tensionAfter:v})}/><N label="Clareza antes" value={value.clarityBefore} set={v=>set({...value,clarityBefore:v})}/><N label="Clareza depois" value={value.clarityAfter} set={v=>set({...value,clarityAfter:v})}/><N label="Ruminação antes" value={value.ruminationBefore} set={v=>set({...value,ruminationBefore:v})}/><N label="Ruminação depois" value={value.ruminationAfter} set={v=>set({...value,ruminationAfter:v})}/><N label="Expectativa" value={value.expectation} set={v=>set({...value,expectation:v})}/></div>}
function ControlScores({value,set}:{value:Day071ControlScores;set:(v:Day071ControlScores)=>void}){return <div><N label="Tensão" value={value.tension} set={v=>set({...value,tension:v})}/><N label="Clareza" value={value.clarity} set={v=>set({...value,clarity:v})}/><N label="Ruminação" value={value.rumination} set={v=>set({...value,rumination:v})}/><N label="Expectativa" value={value.expectation} set={v=>set({...value,expectation:v})}/></div>}
