import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from 'react-native';
import { useHnkAuth } from '../auth/AuthContext';
import { HarielDays074to076Experience } from './HarielDays074to076Experience';
import { HarielDay077CommunicationExperience } from './HarielDay077CommunicationExperience';
import { HarielDay078SilentVeilExperience } from './HarielDay078SilentVeilExperience';

const DAYS=[74,75,76,77,78] as const; type Day=(typeof DAYS)[number];
export function BinahCycle01Hariel(){
 const auth=useHnkAuth(); const [currentDay,setCurrentDay]=useState(74); const [xp,setXp]=useState(0); const [title,setTitle]=useState('Teurgo'); const [display,setDisplay]=useState<Day>(74); const [loading,setLoading]=useState(true);
 const refresh=useCallback(async()=>{if(!auth.client||auth.phase!=='signed-in'){setLoading(false);return;}const {data,error}=await auth.client.from('user_progress').select('current_day,xp_total,initiatory_title').maybeSingle();if(!error&&data){setCurrentDay(data.current_day);setXp(data.xp_total);setTitle(data.initiatory_title);if(data.current_day>=74&&data.current_day<=78)setDisplay(data.current_day as Day);if(data.current_day>78)setDisplay(78);}setLoading(false);},[auth.client,auth.phase]);
 useEffect(()=>{void refresh();},[refresh]); useEffect(()=>{if(!auth.client||auth.phase!=='signed-in')return;const id=setInterval(()=>void refresh(),4000);return()=>clearInterval(id);},[auth.client,auth.phase,refresh]);
 if(loading&&auth.phase==='signed-in')return <View style={s.loading}><ActivityIndicator color="#d9b8e8"/><Text style={s.loadingText}>ABRINDO O CICLO DE HARIEL</Text></View>;
 const completed=Math.max(0,Math.min(5,currentDay-74));
 return <View style={s.screen}><View style={s.rail}><View style={s.railLine}/>{DAYS.map((day,index)=>{const done=index<completed,available=day<=currentDay,active=display===day;return <Pressable key={day} disabled={!available} onPress={()=>setDisplay(day)} style={s.nodeWrap}><View style={[s.node,done&&s.nodeDone,active&&s.nodeActive,!available&&s.nodeLocked]}><Text style={[s.nodeText,(done||active)&&s.nodeTextActive]}>{done?'✓':day}</Text></View><Text style={[s.nodeLabel,active&&s.nodeLabelActive]}>{day===74?'ORIGEM':day===75?'VERBOS':day===76?'COMPARAR':day===77?'DIÁLOGO':'SILÊNCIO'}</Text></Pressable>;})}</View>
 <View style={s.header}><View><Text style={s.eyebrow}>BINAH · CICLO I · PRECISÃO E DISCERNIMENTO DE HARIEL</Text><Text style={s.heading}>DIA {String(display).padStart(3,'0')}</Text></View><View style={s.stats}><Text style={s.stat}>{title.toUpperCase()}</Text><Text style={s.stat}>{xp} XP</Text><Text style={s.stat}>LEVEL 3</Text></View></View>
 {display>=74&&display<=76?<HarielDays074to076Experience day={display}/>:null}{display===77?<HarielDay077CommunicationExperience/>:null}{display===78?<HarielDay078SilentVeilExperience/>:null}</View>;
}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:'#08050b'},loading:{flex:1,alignItems:'center',justifyContent:'center',gap:16,backgroundColor:'#08050b'},loadingText:{color:'#9277a0',fontSize:9,letterSpacing:1.5},rail:{flexDirection:'row',justifyContent:'space-between',paddingHorizontal:18,paddingTop:18,paddingBottom:10,backgroundColor:'#0b0710',position:'relative'},railLine:{position:'absolute',left:44,right:44,top:33,height:1,backgroundColor:'#392542'},nodeWrap:{flex:1,alignItems:'center',gap:7},node:{width:30,height:30,borderRadius:15,borderWidth:1,borderColor:'#573b64',backgroundColor:'#130c18',alignItems:'center',justifyContent:'center'},nodeDone:{borderColor:'#9168a5',backgroundColor:'#28152f'},nodeActive:{borderColor:'#d7b5e7',backgroundColor:'#44254e'},nodeLocked:{opacity:.3},nodeText:{color:'#8d7798',fontSize:8,fontWeight:'700'},nodeTextActive:{color:'#f5e8fa'},nodeLabel:{color:'#715b7a',fontSize:6,letterSpacing:.7},nodeLabelActive:{color:'#c3a2d2'},header:{flexDirection:'row',justifyContent:'space-between',gap:16,paddingHorizontal:24,paddingVertical:14,borderBottomWidth:1,borderBottomColor:'#302038'},eyebrow:{color:'#9a78ad',fontSize:8,letterSpacing:1.5},heading:{color:'#f2e9f6',fontSize:14,letterSpacing:2.1,marginTop:5},stats:{alignItems:'flex-end',gap:3},stat:{color:'#8f7998',fontSize:8,letterSpacing:1}});
