import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from 'react-native';
import { useHnkAuth } from '../auth/AuthContext';
import { LauviahDay084MirrorExperience } from './LauviahDay084MirrorExperience';
import { LauviahDays085to087Experience } from './LauviahDays085to087Experience';
import { LauviahDay088FireTransmutationExperience } from './LauviahDay088FireTransmutationExperience';

const DAYS=[84,85,86,87,88] as const; type Day=(typeof DAYS)[number];
export function BinahCycle03Lauviah(){
 const auth=useHnkAuth(); const [currentDay,setCurrentDay]=useState(84); const [xp,setXp]=useState(0); const [title,setTitle]=useState('Teurgo'); const [display,setDisplay]=useState<Day>(84); const [loading,setLoading]=useState(true);
 const refresh=useCallback(async()=>{if(!auth.client||auth.phase!=='signed-in'){setLoading(false);return;}const {data,error}=await auth.client.from('user_progress').select('current_day,xp_total,initiatory_title').maybeSingle();if(!error&&data){setCurrentDay(data.current_day);setXp(data.xp_total);setTitle(data.initiatory_title);if(data.current_day>=84&&data.current_day<=88)setDisplay(data.current_day as Day);if(data.current_day>88)setDisplay(88);}setLoading(false);},[auth.client,auth.phase]);
 useEffect(()=>{void refresh();},[refresh]); useEffect(()=>{if(!auth.client||auth.phase!=='signed-in')return;const id=setInterval(()=>void refresh(),4000);return()=>clearInterval(id);},[auth.client,auth.phase,refresh]);
 if(loading&&auth.phase==='signed-in')return <View style={s.loading}><ActivityIndicator color="#e3a67f"/><Text style={s.loadingText}>ABRINDO O CICLO DE LAUVIAH</Text></View>;
 const completed=Math.max(0,Math.min(5,currentDay-84));
 return <View style={s.screen}><View style={s.rail}><View style={s.railLine}/>{DAYS.map((day,index)=>{const done=index<completed,available=day<=currentDay,active=display===day;return <Pressable key={day} disabled={!available} onPress={()=>setDisplay(day)} style={s.nodeWrap}><View style={[s.node,done&&s.nodeDone,active&&s.nodeActive,!available&&s.nodeLocked]}><Text style={[s.nodeText,(done||active)&&s.nodeTextActive]}>{done?'✓':day}</Text></View><Text style={[s.nodeLabel,active&&s.nodeLabelActive]}>{day===84?'ESPELHO':day===85?'NEGRO':day===86?'BRANCO':day===87?'MENTE':'FOGO'}</Text></Pressable>;})}</View>
 <View style={s.header}><View><Text style={s.eyebrow}>BINAH · CICLO III · ESPELHO E FOGO DE LAUVIAH</Text><Text style={s.heading}>DIA {String(display).padStart(3,'0')}</Text></View><View style={s.stats}><Text style={s.stat}>{title.toUpperCase()}</Text><Text style={s.stat}>{xp} XP</Text><Text style={s.stat}>LEVEL 3</Text></View></View>
 {display===84?<LauviahDay084MirrorExperience/>:null}{display>=85&&display<=87?<LauviahDays085to087Experience day={display}/>:null}{display===88?<LauviahDay088FireTransmutationExperience/>:null}</View>;
}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:'#08050b'},loading:{flex:1,alignItems:'center',justifyContent:'center',gap:16,backgroundColor:'#08050b'},loadingText:{color:'#9c7563',fontSize:9,letterSpacing:1.5},rail:{flexDirection:'row',justifyContent:'space-between',paddingHorizontal:18,paddingTop:18,paddingBottom:10,backgroundColor:'#100906',position:'relative'},railLine:{position:'absolute',left:44,right:44,top:33,height:1,backgroundColor:'#4d3023'},nodeWrap:{flex:1,alignItems:'center',gap:7},node:{width:30,height:30,borderRadius:15,borderWidth:1,borderColor:'#654432',backgroundColor:'#1a0f0a',alignItems:'center',justifyContent:'center'},nodeDone:{borderColor:'#a87657',backgroundColor:'#352016'},nodeActive:{borderColor:'#e8b28e',backgroundColor:'#543223'},nodeLocked:{opacity:.3},nodeText:{color:'#987d6e',fontSize:8,fontWeight:'700'},nodeTextActive:{color:'#fff0e6'},nodeLabel:{color:'#785f52',fontSize:6,letterSpacing:.7},nodeLabelActive:{color:'#d5aa91'},header:{flexDirection:'row',justifyContent:'space-between',gap:16,paddingHorizontal:24,paddingVertical:14,borderBottomWidth:1,borderBottomColor:'#3d2a20'},eyebrow:{color:'#b0785e',fontSize:8,letterSpacing:1.5},heading:{color:'#f8ece5',fontSize:14,letterSpacing:2.1,marginTop:5},stats:{alignItems:'flex-end',gap:3},stat:{color:'#9a7e70',fontSize:8,letterSpacing:1}});
