import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from 'react-native';
import { useHnkAuth } from '../auth/AuthContext';
import { CalielDay089SilenceExperience } from './CalielDay089SilenceExperience';
import { CalielDays090to092Experience } from './CalielDays090to092Experience';
import { CalielDay093BreathExperience } from './CalielDay093BreathExperience';

const DAYS=[89,90,91,92,93] as const; type Day=(typeof DAYS)[number];
export function BinahCycle04Caliel(){
 const auth=useHnkAuth(); const [currentDay,setCurrentDay]=useState(89); const [xp,setXp]=useState(0); const [title,setTitle]=useState('Teurgo'); const [display,setDisplay]=useState<Day>(89); const [loading,setLoading]=useState(true);
 const refresh=useCallback(async()=>{if(!auth.client||auth.phase!=='signed-in'){setLoading(false);return;}const {data,error}=await auth.client.from('user_progress').select('current_day,xp_total,initiatory_title').maybeSingle();if(!error&&data){setCurrentDay(data.current_day);setXp(data.xp_total);setTitle(data.initiatory_title);if(data.current_day>=89&&data.current_day<=93)setDisplay(data.current_day as Day);if(data.current_day>93)setDisplay(93);}setLoading(false);},[auth.client,auth.phase]);
 useEffect(()=>{void refresh();},[refresh]); useEffect(()=>{if(!auth.client||auth.phase!=='signed-in')return;const id=setInterval(()=>void refresh(),4000);return()=>clearInterval(id);},[auth.client,auth.phase,refresh]);
 if(loading&&auth.phase==='signed-in')return <View style={s.loading}><ActivityIndicator color="#9ac8e3"/><Text style={s.loadingText}>ABRINDO O CICLO DE CALIEL</Text></View>;
 const completed=Math.max(0,Math.min(5,currentDay-89));
 return <View style={s.screen}><View style={s.rail}><View style={s.railLine}/>{DAYS.map((day,index)=>{const done=index<completed,available=day<=currentDay,active=display===day;return <Pressable key={day} disabled={!available} onPress={()=>setDisplay(day)} style={s.nodeWrap}><View style={[s.node,done&&s.nodeDone,active&&s.nodeActive,!available&&s.nodeLocked]}><Text style={[s.nodeText,(done||active)&&s.nodeTextActive]}>{done?'✓':day}</Text></View><Text style={[s.nodeLabel,active&&s.nodeLabelActive]}>{day===89?'SILÊNCIO':day===90?'NEGRO':day===91?'BRANCO':day===92?'CAUSA':'SOPRO'}</Text></Pressable>;})}</View>
 <View style={s.header}><View><Text style={s.eyebrow}>BINAH · CICLO IV · PALAVRA E AR DE CALIEL</Text><Text style={s.heading}>DIA {String(display).padStart(3,'0')}</Text></View><View style={s.stats}><Text style={s.stat}>{title.toUpperCase()}</Text><Text style={s.stat}>{xp} XP</Text><Text style={s.stat}>LEVEL 3</Text></View></View>
 {display===89?<CalielDay089SilenceExperience/>:null}{display>=90&&display<=92?<CalielDays090to092Experience day={display}/>:null}{display===93?<CalielDay093BreathExperience/>:null}</View>;
}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:'#06080b'},loading:{flex:1,alignItems:'center',justifyContent:'center',gap:16,backgroundColor:'#06080b'},loadingText:{color:'#7998aa',fontSize:9,letterSpacing:1.5},rail:{flexDirection:'row',justifyContent:'space-between',paddingHorizontal:18,paddingTop:18,paddingBottom:10,backgroundColor:'#071018',position:'relative'},railLine:{position:'absolute',left:44,right:44,top:33,height:1,backgroundColor:'#274759'},nodeWrap:{flex:1,alignItems:'center',gap:7},node:{width:30,height:30,borderRadius:15,borderWidth:1,borderColor:'#355b70',backgroundColor:'#0a1720',alignItems:'center',justifyContent:'center'},nodeDone:{borderColor:'#5b8ca8',backgroundColor:'#123044'},nodeActive:{borderColor:'#9ac8e3',backgroundColor:'#1b4862'},nodeLocked:{opacity:.3},nodeText:{color:'#7795a6',fontSize:8,fontWeight:'700'},nodeTextActive:{color:'#ecf8ff'},nodeLabel:{color:'#5f7f91',fontSize:6,letterSpacing:.7},nodeLabelActive:{color:'#acd4e9'},header:{flexDirection:'row',justifyContent:'space-between',gap:16,paddingHorizontal:24,paddingVertical:14,borderBottomWidth:1,borderBottomColor:'#213d4d'},eyebrow:{color:'#78a9c4',fontSize:8,letterSpacing:1.5},heading:{color:'#eef8fd',fontSize:14,letterSpacing:2.1,marginTop:5},stats:{alignItems:'flex-end',gap:3},stat:{color:'#7895a5',fontSize:8,letterSpacing:1}});
