import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from 'react-native';
import { useHnkAuth } from '../auth/AuthContext';
import { PahaliahDay099AssiahBodyExperience } from './PahaliahDay099AssiahBodyExperience';
import { PahaliahDays100to101Experience } from './PahaliahDays100to101Experience';
import { PahaliahDay102FatigueExperience } from './PahaliahDay102FatigueExperience';
import { PahaliahDay103AltarExperience } from './PahaliahDay103AltarExperience';
const DAYS=[99,100,101,102,103] as const; type Day=(typeof DAYS)[number];
export function BinahCycle06Pahaliah(){
 const auth=useHnkAuth(); const [currentDay,setCurrentDay]=useState(99); const [xp,setXp]=useState(0); const [title,setTitle]=useState('Teurgo'); const [display,setDisplay]=useState<Day>(99); const [loading,setLoading]=useState(true);
 const refresh=useCallback(async()=>{if(!auth.client||auth.phase!=='signed-in'){setLoading(false);return;}const {data,error}=await auth.client.from('user_progress').select('current_day,xp_total,initiatory_title').maybeSingle();if(!error&&data){setCurrentDay(data.current_day);setXp(data.xp_total);setTitle(data.initiatory_title);if(data.current_day>=99&&data.current_day<=103)setDisplay(data.current_day as Day);if(data.current_day>103)setDisplay(103);}setLoading(false);},[auth.client,auth.phase]);
 useEffect(()=>{void refresh();},[refresh]); useEffect(()=>{if(!auth.client||auth.phase!=='signed-in')return;const id=setInterval(()=>void refresh(),4000);return()=>clearInterval(id);},[auth.client,auth.phase,refresh]);
 if(loading&&auth.phase==='signed-in')return <View style={s.loading}><ActivityIndicator color="#d0b171"/><Text style={s.loadingText}>ABRINDO O CICLO DE PAHALIAH</Text></View>; const completed=Math.max(0,Math.min(5,currentDay-99));
 return <View style={s.screen}><View style={s.rail}><View style={s.railLine}/>{DAYS.map((day,index)=>{const done=index<completed,available=day<=currentDay,active=display===day;return <Pressable key={day} disabled={!available} onPress={()=>setDisplay(day)} style={s.nodeWrap}><View style={[s.node,done&&s.nodeDone,active&&s.nodeActive,!available&&s.nodeLocked]}><Text style={[s.nodeText,(done||active)&&s.nodeTextActive]}>{done?'✓':day}</Text></View><Text style={[s.nodeLabel,active&&s.nodeLabelActive]}>{day===99?'CORPO':day===100?'NEGRA':day===101?'BRANCA':day===102?'CANSAÇO':'ALTAR'}</Text></Pressable>;})}</View><View style={s.header}><View><Text style={s.eyebrow}>BINAH · CICLO VI · TERRA E CONSTÂNCIA DE PAHALIAH</Text><Text style={s.heading}>DIA {String(display).padStart(3,'0')}</Text></View><View style={s.stats}><Text style={s.stat}>{title.toUpperCase()}</Text><Text style={s.stat}>{xp} XP</Text><Text style={s.stat}>LEVEL 3</Text></View></View>{display===99?<PahaliahDay099AssiahBodyExperience/>:null}{display>=100&&display<=101?<PahaliahDays100to101Experience day={display}/>:null}{display===102?<PahaliahDay102FatigueExperience/>:null}{display===103?<PahaliahDay103AltarExperience/>:null}</View>;
}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:'#0d0b07'},loading:{flex:1,alignItems:'center',justifyContent:'center',gap:16,backgroundColor:'#0d0b07'},loadingText:{color:'#98845d',fontSize:9,letterSpacing:1.5},rail:{flexDirection:'row',justifyContent:'space-between',paddingHorizontal:18,paddingTop:18,paddingBottom:10,backgroundColor:'#121006',position:'relative'},railLine:{position:'absolute',left:44,right:44,top:33,height:1,backgroundColor:'#524628'},nodeWrap:{flex:1,alignItems:'center',gap:7},node:{width:30,height:30,borderRadius:15,borderWidth:1,borderColor:'#695b35',backgroundColor:'#1b170a',alignItems:'center',justifyContent:'center'},nodeDone:{borderColor:'#a99156',backgroundColor:'#372e13'},nodeActive:{borderColor:'#e0c274',backgroundColor:'#574821'},nodeLocked:{opacity:.3},nodeText:{color:'#9a885e',fontSize:8,fontWeight:'700'},nodeTextActive:{color:'#fff5d8'},nodeLabel:{color:'#776a4c',fontSize:6,letterSpacing:.7},nodeLabelActive:{color:'#ddc68d'},header:{flexDirection:'row',justifyContent:'space-between',gap:16,paddingHorizontal:24,paddingVertical:14,borderBottomWidth:1,borderBottomColor:'#41371f'},eyebrow:{color:'#b0985f',fontSize:8,letterSpacing:1.5},heading:{color:'#f9f2df',fontSize:14,letterSpacing:2.1,marginTop:5},stats:{alignItems:'flex-end',gap:3},stat:{color:'#948366',fontSize:8,letterSpacing:1}});
