import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from 'react-native';
import { useHnkAuth } from '../auth/AuthContext';
import { LeuviahDay094WaterFocusExperience } from './LeuviahDay094WaterFocusExperience';
import { LeuviahDays095to096Experience } from './LeuviahDays095to096Experience';
import { LeuviahDay097EquivalenceExperience } from './LeuviahDay097EquivalenceExperience';
import { LeuviahDay098RitualWashExperience } from './LeuviahDay098RitualWashExperience';
const DAYS=[94,95,96,97,98] as const; type Day=(typeof DAYS)[number];
export function BinahCycle05Leuviah(){
 const auth=useHnkAuth(); const [currentDay,setCurrentDay]=useState(94); const [xp,setXp]=useState(0); const [title,setTitle]=useState('Teurgo'); const [display,setDisplay]=useState<Day>(94); const [loading,setLoading]=useState(true);
 const refresh=useCallback(async()=>{if(!auth.client||auth.phase!=='signed-in'){setLoading(false);return;}const {data,error}=await auth.client.from('user_progress').select('current_day,xp_total,initiatory_title').maybeSingle();if(!error&&data){setCurrentDay(data.current_day);setXp(data.xp_total);setTitle(data.initiatory_title);if(data.current_day>=94&&data.current_day<=98)setDisplay(data.current_day as Day);if(data.current_day>98)setDisplay(98);}setLoading(false);},[auth.client,auth.phase]);
 useEffect(()=>{void refresh();},[refresh]); useEffect(()=>{if(!auth.client||auth.phase!=='signed-in')return;const id=setInterval(()=>void refresh(),4000);return()=>clearInterval(id);},[auth.client,auth.phase,refresh]);
 if(loading&&auth.phase==='signed-in')return <View style={s.loading}><ActivityIndicator color="#8dd4c8"/><Text style={s.loadingText}>ABRINDO O CICLO DE LEUVIAH</Text></View>; const completed=Math.max(0,Math.min(5,currentDay-94));
 return <View style={s.screen}><View style={s.rail}><View style={s.railLine}/>{DAYS.map((day,index)=>{const done=index<completed,available=day<=currentDay,active=display===day;return <Pressable key={day} disabled={!available} onPress={()=>setDisplay(day)} style={s.nodeWrap}><View style={[s.node,done&&s.nodeDone,active&&s.nodeActive,!available&&s.nodeLocked]}><Text style={[s.nodeText,(done||active)&&s.nodeTextActive]}>{done?'✓':day}</Text></View><Text style={[s.nodeLabel,active&&s.nodeLabelActive]}>{day===94?'ÁGUA':day===95?'NEGRA':day===96?'BRANCA':day===97?'EQUIV.':'LAVAGEM'}</Text></Pressable>;})}</View><View style={s.header}><View><Text style={s.eyebrow}>BINAH · CICLO V · ÁGUA E DISCERNIMENTO DE LEUVIAH</Text><Text style={s.heading}>DIA {String(display).padStart(3,'0')}</Text></View><View style={s.stats}><Text style={s.stat}>{title.toUpperCase()}</Text><Text style={s.stat}>{xp} XP</Text><Text style={s.stat}>LEVEL 3</Text></View></View>{display===94?<LeuviahDay094WaterFocusExperience/>:null}{display>=95&&display<=96?<LeuviahDays095to096Experience day={display}/>:null}{display===97?<LeuviahDay097EquivalenceExperience/>:null}{display===98?<LeuviahDay098RitualWashExperience/>:null}</View>;
}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:'#06100f'},loading:{flex:1,alignItems:'center',justifyContent:'center',gap:16,backgroundColor:'#06100f'},loadingText:{color:'#6f9e97',fontSize:9,letterSpacing:1.5},rail:{flexDirection:'row',justifyContent:'space-between',paddingHorizontal:18,paddingTop:18,paddingBottom:10,backgroundColor:'#061310',position:'relative'},railLine:{position:'absolute',left:44,right:44,top:33,height:1,backgroundColor:'#285148'},nodeWrap:{flex:1,alignItems:'center',gap:7},node:{width:30,height:30,borderRadius:15,borderWidth:1,borderColor:'#35655b',backgroundColor:'#092019',alignItems:'center',justifyContent:'center'},nodeDone:{borderColor:'#5d9d8f',backgroundColor:'#123b31'},nodeActive:{borderColor:'#98dacc',backgroundColor:'#1a5849'},nodeLocked:{opacity:.3},nodeText:{color:'#719b91',fontSize:8,fontWeight:'700'},nodeTextActive:{color:'#edfffb'},nodeLabel:{color:'#5d8279',fontSize:6,letterSpacing:.7},nodeLabelActive:{color:'#a9ddd2'},header:{flexDirection:'row',justifyContent:'space-between',gap:16,paddingHorizontal:24,paddingVertical:14,borderBottomWidth:1,borderBottomColor:'#21473e'},eyebrow:{color:'#70a99d',fontSize:8,letterSpacing:1.5},heading:{color:'#eefbf8',fontSize:14,letterSpacing:2.1,marginTop:5},stats:{alignItems:'flex-end',gap:3},stat:{color:'#759990',fontSize:8,letterSpacing:1}});
