import { useEffect, useState } from 'react';
import { ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { saveEncryptedVaultEntry } from '@hnk/supabase-client';
import { encryptVaultText } from '../vault/vault-crypto';
import { loadCanonicalDay, type CanonicalDaySnapshot } from '../kether/canonical-day';
import { CanonicalText, RuntimeCard, RuntimeChoice, RuntimeCompletion, RuntimeCounter, RuntimeNotice, RuntimePrimary, runtimeTextStyles } from '../kether/KetherRuntimePrimitives';
import { useHnkDayRuntime } from '../kether/useHnkDayRuntime';
import { usePersistentWallClock } from '../chokmah/usePersistentWallClock';
import { CALIEL_DAY_089 } from './runtime-definitions/caliel';

const SIX_HOURS=6*60*60;
function clock(seconds:number){const h=Math.floor(seconds/3600),m=Math.floor((seconds%3600)/60),s=seconds%60;return `${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;}
export function CalielDay089SilenceExperience(){
 const controller=useHnkDayRuntime(CALIEL_DAY_089); const wall=usePersistentWallClock('hnk-binah-day089-silence-v1',SIX_HOURS); const [canon,setCanon]=useState<CanonicalDaySnapshot|null>(null),[error,setError]=useState<string|null>(null); const [necessarySpeech,setNecessarySpeech]=useState(0),[impulses,setImpulses]=useState(0),[windowDone,setWindowDone]=useState(false),[necessaryAllowed,setNecessaryAllowed]=useState(false),[notFailure,setNotFailure]=useState(false),[duties,setDuties]=useState(false),[noPunishment,setNoPunishment]=useState(false),[noCoercion,setNoCoercion]=useState(false),[antiAscetic,setAntiAscetic]=useState(false),[returnSpeech,setReturnSpeech]=useState(false),[safe,setSafe]=useState(false),[orientation,setOrientation]=useState(false),[objects,setObjects]=useState(0); const [note,setNote]=useState(''),[vaultSaved,setVaultSaved]=useState(false),[vaultSkipped,setVaultSkipped]=useState(false),[checksum,setChecksum]=useState<string|null>(null);
 useEffect(()=>{let active=true;if(!controller.auth.client||controller.auth.phase!=='signed-in')return()=>{active=false;};void loadCanonicalDay(controller.auth.client,89).then(v=>{if(active)setCanon(v);}).catch(e=>{if(active)setError(e instanceof Error?e.message:'canonical_day_load_failed');});return()=>{active=false;};},[controller.auth.client,controller.auth.phase]);
 const phase=controller.phase?.id; const begin=async()=>{try{await controller.begin();await wall.start();controller.nextPhase();}catch(e){setError(e instanceof Error?e.message:'day089_begin_failed');}}; const finishWindow=async()=>{if(!wall.atCap)return;await wall.finish();setWindowDone(true);controller.nextPhase();}; const stop=()=>controller.interrupt({durationSeconds:wall.elapsedSeconds,evidence:{safety_stop:true},metrics:{necessary_speech_count:necessarySpeech,speech_impulse_count:impulses}});
 const saveVault=async()=>{if(!controller.auth.client||!controller.auth.userId||note.trim().length<2)return;try{const enc=await encryptVaultText({userId:controller.auth.userId,day:89,kind:'caliel-day089-private-reflection',plaintext:JSON.stringify({schema:'hnk-caliel-day089-v1',private_reflection:note.trim()})});await saveEncryptedVaultEntry(controller.auth.client,{day:89,payload:enc});setChecksum(enc.checksumSha256);setVaultSaved(true);controller.nextPhase();}catch(e){setError(e instanceof Error?e.message:'day089_vault_failed');}};
 if(controller.loading||wall.loading)return <View style={s.loading}><Text style={s.meta}>ABRINDO CALIEL · DIA 089</Text></View>;
 return <ScrollView style={s.screen} contentContainerStyle={s.content}><View style={s.header}><Text style={s.eyebrow}>BINAH · CALIEL 1/5 · DIA 089</Text><Text style={s.title}>{canon?.title??'A PALAVRA JUSTA'}</Text><Text style={s.meta}>{canon?`${canon.sourcePath} · ${canon.sourceSha.slice(0,10)} · +${canon.xp} XP`:'CÂNONE SINCRONIZANDO'}</Text></View>
 {controller.error||error?<RuntimeNotice title="RUNTIME">{error??controller.error}</RuntimeNotice>:null}{controller.runtime?.status==='locked'?<RuntimeCard label="GATE" title="Dia 089 bloqueado pela sequência"><Text style={runtimeTextStyles.body}>A primeira conclusão exige o Dia 088 confirmado no servidor.</Text></RuntimeCard>:null}
 {phase==='threshold'?<RuntimeCard label="CALIEL 1/5" title="Seis horas de silêncio sem negligência"><CanonicalText>{canon?.blocks['jachin-kavanah']??''}</CanonicalText><RuntimeNotice title="REGRA DE SEGURANÇA">Fala por emergência, cuidado, trabalho crítico, saúde, consentimento ou comunicação indispensável é permitida e não invalida a prática. O silêncio nunca pode punir ou manipular terceiros.</RuntimeNotice><RuntimeChoice selected={necessaryAllowed} label="FALA NECESSÁRIA CONTINUARÁ PERMITIDA" onPress={()=>setNecessaryAllowed(v=>!v)}/><RuntimeChoice selected={duties} label="CUIDADO, TRABALHO, SAÚDE E CONSENTIMENTO TÊM PRIORIDADE" onPress={()=>setDuties(v=>!v)}/><RuntimeChoice selected={noPunishment} label="NÃO USAREI SILÊNCIO PARA PUNIR/IGNORAR PEDIDO IMPORTANTE" onPress={()=>setNoPunishment(v=>!v)}/><RuntimeChoice selected={noCoercion} label="NÃO EXIGIREI QUE OUTRAS PESSOAS PARTICIPEM" onPress={()=>setNoCoercion(v=>!v)}/><RuntimePrimary label="INICIAR JANELA DE 6H" disabled={!canon||!necessaryAllowed||!duties||!noPunishment||!noCoercion||controller.busy} onPress={()=>void begin()}/></RuntimeCard>:null}
 {phase==='window'?<RuntimeCard label="JANELA PERSISTENTE" title={clock(wall.elapsedSeconds)}><RuntimeNotice title="6 HORAS EXATAS">O relógio usa timestamp persistente. Fechar o app não reinicia a janela. Comunicação necessária é registrada e a janela continua.</RuntimeNotice><RuntimeCounter label="FALAS NECESSÁRIAS / FUNCIONAIS" value={necessarySpeech} onPress={()=>setNecessarySpeech(v=>v+1)}/><RuntimeCounter label="IMPULSOS DE FALAR OBSERVADOS" value={impulses} onPress={()=>setImpulses(v=>v+1)}/><RuntimeChoice selected={notFailure} label="SE EU PRECISAR FALAR POR FUNÇÃO REAL, ISSO NÃO É FALHA MORAL" onPress={()=>setNotFailure(v=>!v)}/><RuntimePrimary label="SAFETY STOP" onPress={stop}/><RuntimePrimary label={wall.atCap?'ENCERRAR JANELA':'AGUARDAR 06:00:00'} disabled={!wall.atCap||!notFailure} onPress={()=>void finishWindow()}/></RuntimeCard>:null}
 {phase==='review'?<RuntimeCard label="REVISÃO" title="Silêncio temporário, não identidade superior"><RuntimeChoice selected={antiAscetic} label="NÃO USEI SOFRIMENTO/ISOLAMENTO COMO SCORE ASCÉTICO" onPress={()=>setAntiAscetic(v=>!v)}/><RuntimeChoice selected={necessaryAllowed} label="FALA NECESSÁRIA PERMANECEU LEGÍTIMA" onPress={()=>setNecessaryAllowed(v=>!v)}/><RuntimeChoice selected={duties} label="RESPONSABILIDADES CONCRETAS FORAM PRESERVADAS" onPress={()=>setDuties(v=>!v)}/><RuntimeChoice selected={noPunishment} label="O SILÊNCIO NÃO FOI USADO COMO PUNIÇÃO" onPress={()=>setNoPunishment(v=>!v)}/><RuntimeChoice selected={noCoercion} label="NINGUÉM FOI COAGIDO A PARTICIPAR" onPress={()=>setNoCoercion(v=>!v)}/><RuntimeChoice selected={safe} label="ESTOU SEGURO PARA RETORNAR À FALA" onPress={()=>setSafe(v=>!v)}/><RuntimePrimary label="RETORNAR À FALA" disabled={!windowDone||!antiAscetic||!necessaryAllowed||!duties||!noPunishment||!noCoercion||!safe} onPress={()=>{setReturnSpeech(true);controller.nextPhase();}}/></RuntimeCard>:null}
 {phase==='grounding'?<RuntimeCard label="RETURN GATE" title="A palavra volta conscientemente"><RuntimeCounter label="OBJETOS REAIS NOMEADOS" value={objects} onPress={()=>setObjects(v=>Math.min(5,v+1))}/><RuntimeChoice selected={orientation} label="ORIENTAÇÃO RESTAURADA E FALA RETOMADA" onPress={()=>setOrientation(v=>!v)}/><RuntimePrimary label="RETORNO CONFIRMADO" disabled={objects<3||!orientation||!returnSpeech} onPress={()=>{controller.setReturnConfirmed();controller.nextPhase();}}/></RuntimeCard>:null}
 {phase==='vault'?<RuntimeCard label="VAULT OPCIONAL" title="Pensamentos/conflitos não vão para telemetria"><TextInput value={note} onChangeText={setNote} placeholder="Reflexão privada opcional" placeholderTextColor="#665f70" style={runtimeTextStyles.input}/><RuntimePrimary label="CIFRAR E SALVAR" disabled={note.trim().length<2||vaultSaved||vaultSkipped} onPress={()=>void saveVault()}/><RuntimePrimary label="SEM NOTA PRIVADA" disabled={vaultSaved||vaultSkipped} onPress={()=>{setVaultSkipped(true);controller.nextPhase();}}/></RuntimeCard>:null}
 {phase==='seal'?<RuntimeCard label="SELO SERVER-SIDE" title="Caliel 1/5"><RuntimePrimary label={controller.busy?'SELANDO…':'SELAR DIA 089'} disabled={controller.busy||!windowDone||!returnSpeech||!orientation||!safe||(!vaultSaved&&!vaultSkipped)} onPress={()=>void controller.seal({localRecordHash:checksum??undefined,durationSeconds:SIX_HOURS,evidence:{protocol_completed:true,return_confirmed:true,six_hour_window_completed:windowDone,necessary_speech_allowed:necessaryAllowed,necessary_speech_not_failure:notFailure,care_work_health_consent_preserved:duties,silence_not_used_as_punishment:noPunishment,others_not_coerced:noCoercion,return_to_speech_completed:returnSpeech,anti_ascetic_scoring:antiAscetic,safety_clear:safe,necessary_speech_count:necessarySpeech,speech_impulse_count:impulses,monitoring_seconds:SIX_HOURS},metrics:{vault_used:vaultSaved}}).then(controller.nextPhase).catch(e=>setError(e instanceof Error?e.message:'day089_seal_failed'))}/></RuntimeCard>:null}
 {phase==='complete'?<RuntimeCompletion completion={controller.runtime?.serverCompletion} label="CALIEL 1/5"/>:null}</ScrollView>;
}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:'#06080b'},content:{padding:24,gap:18,paddingBottom:52},loading:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:'#06080b'},header:{gap:6},eyebrow:{color:'#86a7bf',fontSize:8,letterSpacing:1.5},title:{color:'#edf6fb',fontSize:25,lineHeight:31,fontWeight:'300'},meta:{color:'#718897',fontSize:8,letterSpacing:.8}});
