import { useEffect, useMemo, useState } from 'react';
import { ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { saveEncryptedVaultEntry } from '@hnk/supabase-client';
import { encryptVaultText } from '../vault/vault-crypto';
import { loadCanonicalDay, type CanonicalDaySnapshot } from '../kether/canonical-day';
import { CanonicalText, RuntimeCard, RuntimeChoice, RuntimeCompletion, RuntimeCounter, RuntimeNotice, RuntimePrimary, runtimeTextStyles } from '../kether/KetherRuntimePrimitives';
import { useHnkDayRuntime } from '../kether/useHnkDayRuntime';
import { HAKAMIAH_DAY_080, HAKAMIAH_DAY_081, HAKAMIAH_DAY_082 } from './runtime-definitions/hakamiah';

type Day=80|81|82; type Row={a:string;b:string;c:string};
const DEF={80:HAKAMIAH_DAY_080,81:HAKAMIAH_DAY_081,82:HAKAMIAH_DAY_082} as const;
const META={
 80:{label:'HAKAMIAH 2/5 · DIA 080',count:5,title:'Quebrando o “Tenho Que”',a:'Regra: tenho que / devo…',b:'Fonte + consequência prevista + evidência',c:'Categoria: necessária / escolhida / negociável / incerta / descartável'},
 81:{label:'HAKAMIAH 3/5 · DIA 081',count:3,title:'Desafiando o “Não Consigo”',a:'Limitação autodeclarada',b:'Impedimentos conhecidos + tentativas já feitas',c:'Classificação: física / contextual / aprendida / emocional / desconhecida / mista'},
 82:{label:'HAKAMIAH 4/5 · DIA 082',count:5,title:'O “Sempre” e o “Nunca”',a:'Generalização universal',b:'Contraexemplo + período observado',c:'Nova formulação com frequência/contexto mais fiel'},
} as const;

export function HakamiahDays080to082Experience({day}:{day:Day}){
 const meta=META[day],controller=useHnkDayRuntime(DEF[day]); const [canon,setCanon]=useState<CanonicalDaySnapshot|null>(null),[error,setError]=useState<string|null>(null); const [rows,setRows]=useState<Row[]>(()=>Array.from({length:meta.count},()=>({a:'',b:'',c:''}))); const [vault,setVault]=useState(false),[checksum,setChecksum]=useState<string|null>(null),[safe,setSafe]=useState(false),[orientation,setOrientation]=useState(false),[objects,setObjects]=useState(0);
 const [maintained,setMaintained]=useState(false),[reformulated,setReformulated]=useState(false),[questioned,setQuestioned]=useState(false),[duties,setDuties]=useState(false),[noReaction,setNoReaction]=useState(false),[noRebellion,setNoRebellion]=useState(false);
 const [microtest,setMicrotest]=useState<boolean|null>(null),[alternative,setAlternative]=useState<boolean|null>(null),[unsafeAvoided,setUnsafeAvoided]=useState(false),[medicalRespected,setMedicalRespected]=useState(false),[noUniversalOvercoming,setNoUniversalOvercoming]=useState(false),[safePath,setSafePath]=useState(false),[pathNote,setPathNote]=useState('');
 const [patternPreserved,setPatternPreserved]=useState(false),[sparseUncertainty,setSparseUncertainty]=useState(false),[noStats,setNoStats]=useState(false),[responsibility,setResponsibility]=useState(false);
 useEffect(()=>{let active=true;if(!controller.auth.client||controller.auth.phase!=='signed-in')return()=>{active=false;};void loadCanonicalDay(controller.auth.client,day).then(v=>{if(active)setCanon(v);}).catch(e=>{if(active)setError(e instanceof Error?e.message:'canonical_day_load_failed');});return()=>{active=false;};},[controller.auth.client,controller.auth.phase,day]);
 const complete=useMemo(()=>rows.filter(r=>r.a.trim()&&r.b.trim()&&r.c.trim()).length,[rows]); const patch=(i:number,k:keyof Row,v:string)=>setRows(cur=>cur.map((r,x)=>x===i?{...r,[k]:v}:r));
 const save=async()=>{if(!controller.auth.client||!controller.auth.userId||complete!==meta.count)return;if(day===81&&(pathNote.trim().length<2||microtest===null||alternative===null))return;try{const enc=await encryptVaultText({userId:controller.auth.userId,day,kind:`hakamiah-day${day}-language`,plaintext:JSON.stringify({schema:`hnk-hakamiah-day${day}-v1`,rows,path_note:day===81?pathNote.trim():undefined})});await saveEncryptedVaultEntry(controller.auth.client,{day,payload:enc});setChecksum(enc.checksumSha256);setVault(true);controller.nextPhase();}catch(e){setError(e instanceof Error?e.message:`day${day}_vault_failed`);}};
 const reviewReady=day===80?maintained&&reformulated&&questioned&&duties&&noReaction&&noRebellion:day===81?microtest!==null&&alternative!==null&&(microtest||alternative)&&unsafeAvoided&&medicalRespected&&noUniversalOvercoming&&safePath:patternPreserved&&sparseUncertainty&&noStats&&responsibility;
 const evidence:Record<string,boolean|number>=day===80?{protocol_completed:true,return_confirmed:true,five_rules_recorded:true,sources_recorded:true,consequences_recorded:true,classifications_recorded:true,one_rule_maintained:maintained,one_rule_reformulated:reformulated,one_rule_questioned:questioned,legal_family_professional_safety_duties_preserved:duties,third_party_reaction_not_inferred:noReaction,automatic_rebellion_avoided:noRebellion,vault_saved:vault,safety_clear:safe,rules_count:5,classifications_count:5}:day===81?{protocol_completed:true,return_confirmed:true,three_limitations_recorded:true,impediments_recorded:true,classifications_recorded:true,unsafe_tests_avoided:unsafeAvoided,medical_limits_respected:medicalRespected,universal_overcoming_not_claimed:noUniversalOvercoming,safe_path_selected:safePath,vault_saved:vault,safety_clear:safe,microtest_performed:microtest??false,alternative_path_used:alternative??false,limitations_count:3,classifications_count:3}:{protocol_completed:true,return_confirmed:true,five_universals_recorded:true,counterexamples_recorded:true,periods_recorded:true,five_rewrites_recorded:true,frequent_pattern_not_erased:patternPreserved,sparse_data_uncertainty_preserved:sparseUncertainty,statistical_certainty_not_claimed:noStats,responsibility_preserved:responsibility,vault_saved:vault,safety_clear:safe,universals_count:5,rewrites_count:5};
 const stop=()=>controller.interrupt({evidence:{safety_stop:true},metrics:{items_completed:complete}}); const phase=controller.phase?.id;
 if(controller.loading)return <View style={s.loading}><Text style={s.meta}>ABRINDO {meta.label}</Text></View>;
 return <ScrollView style={s.screen} contentContainerStyle={s.content}><View style={s.header}><Text style={s.eyebrow}>BINAH · {meta.label}</Text><Text style={s.title}>{canon?.title??meta.title}</Text><Text style={s.meta}>{canon?`${canon.sourcePath} · ${canon.sourceSha.slice(0,10)} · +${canon.xp} XP`:'CÂNONE SINCRONIZANDO'}</Text></View>
 {controller.error||error?<RuntimeNotice title="RUNTIME">{error??controller.error}</RuntimeNotice>:null}{controller.runtime?.status==='locked'?<RuntimeCard label="GATE" title={`Dia ${day} bloqueado pela sequência`}><Text style={runtimeTextStyles.body}>A primeira conclusão depende do Day anterior confirmado no servidor.</Text></RuntimeCard>:null}
 {phase==='threshold'?<RuntimeCard label={meta.label} title={meta.title}><CanonicalText>{canon?.blocks['jachin-kavanah']??''}</CanonicalText><RuntimeNotice title="VAULT-FIRST">Conteúdo pessoal permanece cifrado. O Practice Record recebe apenas contagens, decisões estruturais e limites éticos.</RuntimeNotice><RuntimePrimary label="INICIAR" disabled={!canon||controller.busy} onPress={()=>void controller.begin().then(controller.nextPhase)}/></RuntimeCard>:null}
 {phase==='vault'?<RuntimeCard label="VAULT" title={`${meta.count} registros privados`}>{rows.map((r,i)=><View key={i} style={s.row}><Text style={s.rowTitle}>{i+1}/{meta.count}</Text><TextInput value={r.a} onChangeText={v=>patch(i,'a',v)} placeholder={meta.a} placeholderTextColor="#665f70" style={runtimeTextStyles.input}/><TextInput value={r.b} onChangeText={v=>patch(i,'b',v)} placeholder={meta.b} placeholderTextColor="#665f70" style={runtimeTextStyles.input}/><TextInput value={r.c} onChangeText={v=>patch(i,'c',v)} placeholder={meta.c} placeholderTextColor="#665f70" style={runtimeTextStyles.input}/></View>)}{day===81?<TextInput value={pathNote} onChangeText={setPathNote} placeholder="Microteste seguro OU alternativa: pesquisa / ajuda / observação" placeholderTextColor="#665f70" style={runtimeTextStyles.input}/>:null}<Text style={runtimeTextStyles.body}>Completos: {complete}/{meta.count}</Text><RuntimePrimary label="SAFETY STOP" onPress={stop}/><RuntimePrimary label="CIFRAR E CONTINUAR" disabled={complete!==meta.count||(day===81&&pathNote.trim().length<2)} onPress={()=>void save()}/></RuntimeCard>:null}
 {phase==='review'||phase==='path'?<RuntimeCard label="REVISÃO" title="Limite, verdade e responsabilidade">{day===80?<><RuntimeChoice selected={maintained} label="IDENTIFIQUEI UMA REGRA LEGÍTIMA A MANTER" onPress={()=>setMaintained(v=>!v)}/><RuntimeChoice selected={reformulated} label="REFORMULEI AO MENOS UMA REGRA" onPress={()=>setReformulated(v=>!v)}/><RuntimeChoice selected={questioned} label="IDENTIFIQUEI AO MENOS UMA REGRA A QUESTIONAR" onPress={()=>setQuestioned(v=>!v)}/><RuntimeChoice selected={duties} label="NÃO ABANDONEI DEVERES LEGAIS, FAMILIARES, PROFISSIONAIS OU DE SEGURANÇA" onPress={()=>setDuties(v=>!v)}/><RuntimeChoice selected={noReaction} label="NÃO INVENTEI A REAÇÃO DE TERCEIROS" onPress={()=>setNoReaction(v=>!v)}/><RuntimeChoice selected={noRebellion} label="QUESTIONAR REGRAS NÃO VIROU REBELDIA AUTOMÁTICA" onPress={()=>setNoRebellion(v=>!v)}/></>:day===81?<><RuntimeChoice selected={microtest===true} label="REALIZEI/DEFINI UM MICROTESTE SEGURO E REVERSÍVEL" onPress={()=>setMicrotest(true)}/><RuntimeChoice selected={microtest===false} label="NÃO HÁ MICROTESTE SEGURO/NECESSÁRIO" onPress={()=>setMicrotest(false)}/><RuntimeChoice selected={alternative===true} label="USEI ALTERNATIVA: PESQUISA, AJUDA OU OBSERVAÇÃO" onPress={()=>setAlternative(true)}/><RuntimeChoice selected={alternative===false} label="ALTERNATIVA NÃO FOI NECESSÁRIA" onPress={()=>setAlternative(false)}/><RuntimeChoice selected={unsafeAvoided} label="NÃO TESTEI DOR, PRIVAÇÃO, DIREÇÃO, SUBSTÂNCIAS OU EXPOSIÇÃO PERIGOSA" onPress={()=>setUnsafeAvoided(v=>!v)}/><RuntimeChoice selected={medicalRespected} label="LIMITES MÉDICOS/CORPORAIS REAIS FORAM RESPEITADOS" onPress={()=>setMedicalRespected(v=>!v)}/><RuntimeChoice selected={noUniversalOvercoming} label="NÃO PROMETI SUPERAÇÃO UNIVERSAL PELA VONTADE" onPress={()=>setNoUniversalOvercoming(v=>!v)}/><RuntimeChoice selected={safePath} label="ESCOLHI UM CAMINHO PROPORCIONAL E SEGURO" onPress={()=>setSafePath(v=>!v)}/></>:<><RuntimeChoice selected={patternPreserved} label="UM CONTRAEXEMPLO NÃO FOI USADO PARA APAGAR PADRÃO FREQUENTE" onPress={()=>setPatternPreserved(v=>!v)}/><RuntimeChoice selected={sparseUncertainty} label="POUCOS DADOS CONTINUAM MARCADOS COMO INCERTOS" onPress={()=>setSparseUncertainty(v=>!v)}/><RuntimeChoice selected={noStats} label="NÃO DECLAREI CERTEZA ESTATÍSTICA COM AMOSTRA INSUFICIENTE" onPress={()=>setNoStats(v=>!v)}/><RuntimeChoice selected={responsibility} label="PRECISÃO NÃO FOI USADA PARA MINIMIZAR RESPONSABILIDADE" onPress={()=>setResponsibility(v=>!v)}/></>}<RuntimeChoice selected={safe} label="ESTOU ORIENTADO E SEGURO PARA ENCERRAR" onPress={()=>setSafe(v=>!v)}/><RuntimePrimary label="GROUNDING" disabled={!reviewReady||!safe} onPress={controller.nextPhase}/></RuntimeCard>:null}
 {phase==='grounding'?<RuntimeCard label="RETURN GATE" title="Limite e possibilidade sob realidade"><RuntimeCounter label="OBJETOS REAIS NOMEADOS" value={objects} onPress={()=>setObjects(v=>Math.min(5,v+1))}/><RuntimeChoice selected={orientation} label="ORIENTAÇÃO RESTAURADA" onPress={()=>setOrientation(v=>!v)}/><RuntimePrimary label="RETORNO CONFIRMADO" disabled={objects<3||!orientation} onPress={()=>{controller.setReturnConfirmed();controller.nextPhase();}}/></RuntimeCard>:null}
 {phase==='seal'?<RuntimeCard label="SELO SERVER-SIDE" title={meta.label}><RuntimePrimary label={controller.busy?'SELANDO…':`SELAR DIA ${day}`} disabled={controller.busy||!vault||!checksum||!safe||!orientation} onPress={()=>void controller.seal({localRecordHash:checksum??undefined,evidence}).then(controller.nextPhase).catch(e=>setError(e instanceof Error?e.message:`day${day}_seal_failed`))}/></RuntimeCard>:null}
 {phase==='complete'?<RuntimeCompletion completion={controller.runtime?.serverCompletion} label={meta.label}/>:null}</ScrollView>;
}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:'#08050b'},content:{padding:24,gap:18,paddingBottom:52},loading:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:'#08050b'},header:{gap:6},eyebrow:{color:'#a05d6b',fontSize:8,letterSpacing:1.5},title:{color:'#f5e9ed',fontSize:25,lineHeight:31,fontWeight:'300'},meta:{color:'#8a6972',fontSize:8,letterSpacing:.8},row:{gap:8,padding:12,borderWidth:1,borderColor:'#3a252c',borderRadius:10},rowTitle:{color:'#b48691',fontSize:9,letterSpacing:1.2}});
