import { useEffect, useState } from 'react';
import { ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { saveEncryptedVaultEntry } from '@hnk/supabase-client';
import { encryptVaultText } from '../vault/vault-crypto';
import { loadCanonicalDay, type CanonicalDaySnapshot } from '../kether/canonical-day';
import { CanonicalText, RuntimeCard, RuntimeChoice, RuntimeCompletion, RuntimeCounter, RuntimeNotice, RuntimeOpenTimer, RuntimePrimary, RuntimeScale, runtimeTextStyles } from '../kether/KetherRuntimePrimitives';
import { useHnkDayRuntime } from '../kether/useHnkDayRuntime';
import { HAKAMIAH_DAY_079 } from './runtime-definitions/hakamiah';
import { ThurisazMasterV1, THURISAZ_MASTER_ID, THURISAZ_MASTER_SHA256 } from './ThurisazMasterV1';

export function HakamiahDay079ThurisazExperience(){
 const controller=useHnkDayRuntime(HAKAMIAH_DAY_079); const [canon,setCanon]=useState<CanonicalDaySnapshot|null>(null); const [error,setError]=useState<string|null>(null); const [seconds,setSeconds]=useState(0),[fear,setFear]=useState(5),[calm,setCalm]=useState(5); const [effect,setEffect]=useState(false),[effectRecorded,setEffectRecorded]=useState(false);
 const [master,setMaster]=useState(false),[sha,setSha]=useState(false),[upright,setUpright]=useState(false),[done,setDone]=useState(false),[dissolved,setDissolved]=useState(false),[noAttack,setNoAttack]=useState(false),[noInvulnerability,setNoInvulnerability]=useState(false),[noAccusation,setNoAccusation]=useState(false),[realSafety,setRealSafety]=useState(false),[safe,setSafe]=useState(false),[orientation,setOrientation]=useState(false); const [objects,setObjects]=useState(0); const [note,setNote]=useState(''),[vaultSaved,setVaultSaved]=useState(false),[vaultSkipped,setVaultSkipped]=useState(false),[checksum,setChecksum]=useState<string|null>(null);
 useEffect(()=>{let active=true;if(!controller.auth.client||controller.auth.phase!=='signed-in')return()=>{active=false;};void loadCanonicalDay(controller.auth.client,79).then(v=>{if(active)setCanon(v);}).catch(e=>{if(active)setError(e instanceof Error?e.message:'canonical_day_load_failed');});return()=>{active=false;};},[controller.auth.client,controller.auth.phase]);
 const phase=controller.phase?.id; const saveVault=async()=>{if(!controller.auth.client||!controller.auth.userId||note.trim().length<2)return;try{const enc=await encryptVaultText({userId:controller.auth.userId,day:79,kind:'hakamiah-day079-interpretation',plaintext:JSON.stringify({schema:'hnk-hakamiah-day079-v1',private_interpretation:note.trim()})});await saveEncryptedVaultEntry(controller.auth.client,{day:79,payload:enc});setChecksum(enc.checksumSha256);setVaultSaved(true);controller.nextPhase();}catch(e){setError(e instanceof Error?e.message:'day079_vault_failed');}}; const stop=()=>controller.interrupt({durationSeconds:seconds,evidence:{safety_stop:true},metrics:{active_seconds:seconds,fear,calm}});
 if(controller.loading)return <View style={s.loading}><Text style={s.meta}>ABRINDO HAKAMIAH · DIA 079</Text></View>;
 return <ScrollView style={s.screen} contentContainerStyle={s.content}><View style={s.header}><Text style={s.eyebrow}>BINAH · HAKAMIAH 1/5 · DIA 079</Text><Text style={s.title}>{canon?.title??'A RUNA THURISAZ'}</Text><Text style={s.meta}>{canon?`${canon.sourcePath} · ${canon.sourceSha.slice(0,10)} · +${canon.xp} XP`:'CÂNONE SINCRONIZANDO'}</Text></View>
 {controller.error||error?<RuntimeNotice title="RUNTIME">{error??controller.error}</RuntimeNotice>:null}{controller.runtime?.status==='locked'?<RuntimeCard label="GATE" title="Dia 079 bloqueado pela sequência"><Text style={runtimeTextStyles.body}>A primeira conclusão exige o Dia 078 confirmado no servidor.</Text></RuntimeCard>:null}
 {phase==='threshold'?<RuntimeCard label="HAKAMIAH 1/5" title="Thurisaz como limite simbólico, não detector de ataque"><CanonicalText>{canon?.blocks['jachin-kavanah']??''}</CanonicalText><ThurisazMasterV1/><RuntimeNotice title="MASTER CANÔNICO">{THURISAZ_MASTER_ID} · U+16A6 · SHA-256 {THURISAZ_MASTER_SHA256.slice(0,16)}… · ereta · não espelhada.</RuntimeNotice><RuntimeChoice selected={master} label="CONFIRMEI O MASTER HNK APROVADO" onPress={()=>setMaster(v=>!v)}/><RuntimeChoice selected={sha} label="CONFIRMEI A VERSÃO/CHECKSUM EXIBIDOS" onPress={()=>setSha(v=>!v)}/><RuntimeChoice selected={upright} label="A FORMA ESTÁ ERETA E NÃO ESPELHADA" onPress={()=>setUpright(v=>!v)}/><RuntimePrimary label="INICIAR" disabled={!canon||!master||!sha||!upright||controller.busy} onPress={()=>void controller.begin().then(controller.nextPhase)}/></RuntimeCard>:null}
 {phase==='active'?<RuntimeCard label="VISUALIZAÇÃO" title="Vermelho e negro · respiração natural"><RuntimeOpenTimer value={seconds} onChange={setSeconds}/><RuntimeNotice title="SEM DURAÇÃO INVENTADA">O cânone diz “alguns minutos”; o relógio registra o tempo real e não impõe uma meta artificial.</RuntimeNotice><RuntimeScale label="MEDO / VIGILÂNCIA" value={fear} onChange={setFear}/><RuntimeScale label="CALMA / FIRMEZA" value={calm} onChange={setCalm}/><RuntimeChoice selected={effectRecorded&&effect} label="PERCEBI ALGUMA SENSAÇÃO DE LIMITE" onPress={()=>{setEffect(true);setEffectRecorded(true);}}/><RuntimeChoice selected={effectRecorded&&!effect} label="NÃO PERCEBI MUDANÇA MARCANTE" onPress={()=>{setEffect(false);setEffectRecorded(true);}}/><RuntimeChoice selected={done} label="EXECUTEI A VISUALIZAÇÃO SEM PROCURAR AMEAÇA" onPress={()=>setDone(v=>!v)}/><RuntimePrimary label="SAFETY STOP" onPress={stop}/><RuntimePrimary label="REVISAR" disabled={seconds<1||!effectRecorded||!done} onPress={controller.nextPhase}/></RuntimeCard>:null}
 {phase==='review'?<RuntimeCard label="REVISÃO" title="Símbolo, sensação e fato permanecem separados"><RuntimeChoice selected={noAttack} label="NÃO TRATEI SENSAÇÃO COMO PROVA DE ATAQUE PSÍQUICO" onPress={()=>setNoAttack(v=>!v)}/><RuntimeChoice selected={noInvulnerability} label="NÃO TRATEI A RUNA COMO INVULNERABILIDADE OBJETIVA" onPress={()=>setNoInvulnerability(v=>!v)}/><RuntimeChoice selected={noAccusation} label="NÃO IDENTIFIQUEI OU ACUSEI TERCEIROS COMO FONTES INVISÍVEIS" onPress={()=>setNoAccusation(v=>!v)}/><RuntimeChoice selected={realSafety} label="MEDIDAS CONCRETAS DE SEGURANÇA CONTINUAM VÁLIDAS" onPress={()=>setRealSafety(v=>!v)}/><RuntimeChoice selected={safe} label="SEM MEDO CRESCENTE OU VIGILÂNCIA COMPULSIVA" onPress={()=>setSafe(v=>!v)}/><RuntimePrimary label="DISSOLVER E RETORNAR" disabled={!noAttack||!noInvulnerability||!noAccusation||!realSafety||!safe} onPress={()=>{setDissolved(true);controller.nextPhase();}}/></RuntimeCard>:null}
 {phase==='grounding'?<RuntimeCard label="RETURN GATE" title="Desfazer a imagem e voltar ao ambiente"><RuntimeCounter label="OBJETOS REAIS NOMEADOS" value={objects} onPress={()=>setObjects(v=>Math.min(5,v+1))}/><RuntimeChoice selected={orientation} label="ORIENTAÇÃO RESTAURADA" onPress={()=>setOrientation(v=>!v)}/><RuntimePrimary label="RETORNO CONFIRMADO" disabled={!dissolved||objects<3||!orientation} onPress={()=>{controller.setReturnConfirmed();controller.nextPhase();}}/></RuntimeCard>:null}
 {phase==='vault'?<RuntimeCard label="VAULT OPCIONAL" title="Interpretação privada, se quiser conservar"><TextInput value={note} onChangeText={setNote} placeholder="Interpretação pessoal · opcional e cifrada" placeholderTextColor="#665f70" style={runtimeTextStyles.input}/><RuntimePrimary label="CIFRAR E SALVAR" disabled={note.trim().length<2||vaultSaved||vaultSkipped} onPress={()=>void saveVault()}/><RuntimePrimary label="SEM NOTA PRIVADA" disabled={vaultSaved||vaultSkipped} onPress={()=>{setVaultSkipped(true);controller.nextPhase();}}/></RuntimeCard>:null}
 {phase==='seal'?<RuntimeCard label="SELO SERVER-SIDE" title="Hakamiah 1/5"><RuntimePrimary label={controller.busy?'SELANDO…':'SELAR DIA 079'} disabled={controller.busy||(!vaultSaved&&!vaultSkipped)||!safe||!orientation} onPress={()=>void controller.seal({localRecordHash:checksum??undefined,durationSeconds:seconds,evidence:{protocol_completed:true,return_confirmed:true,master_verified:master,asset_sha_verified:sha,upright_not_mirrored:upright,visualization_completed:done,visualization_dissolved:dissolved,attack_not_claimed:noAttack,invulnerability_not_claimed:noInvulnerability,third_party_accusation_avoided:noAccusation,concrete_safety_preserved:realSafety,safety_clear:safe,effect_present:effect,active_seconds:seconds},metrics:{fear,calm,vault_used:vaultSaved}}).then(controller.nextPhase).catch(e=>setError(e instanceof Error?e.message:'day079_seal_failed'))}/></RuntimeCard>:null}
 {phase==='complete'?<RuntimeCompletion completion={controller.runtime?.serverCompletion} label="HAKAMIAH 1/5"/>:null}</ScrollView>;
}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:'#08050b'},content:{padding:24,gap:18,paddingBottom:52},loading:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:'#08050b'},header:{gap:6},eyebrow:{color:'#a05d6b',fontSize:8,letterSpacing:1.5},title:{color:'#f5e9ed',fontSize:25,lineHeight:31,fontWeight:'300'},meta:{color:'#8a6972',fontSize:8,letterSpacing:.8}});
