import { useEffect, useState } from 'react';
import { ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { saveEncryptedVaultEntry } from '@hnk/supabase-client';
import { encryptVaultText } from '../vault/vault-crypto';
import { loadCanonicalDay, type CanonicalDaySnapshot } from '../kether/canonical-day';
import { CanonicalText, RuntimeCard, RuntimeChoice, RuntimeCompletion, RuntimeCounter, RuntimeNotice, RuntimeOpenTimer, RuntimePrimary, RuntimeScale, runtimeTextStyles } from '../kether/KetherRuntimePrimitives';
import { useHnkDayRuntime } from '../kether/useHnkDayRuntime';
import { HARIEL_DAY_078 } from './runtime-definitions/hariel';

export function HarielDay078SilentVeilExperience(){
 const controller=useHnkDayRuntime(HARIEL_DAY_078); const [canon,setCanon]=useState<CanonicalDaySnapshot|null>(null); const [error,setError]=useState<string|null>(null); const [seconds,setSeconds]=useState(0),[returns,setReturns]=useState(0),[comfort,setComfort]=useState(5),[effort,setEffort]=useState(5);
 const [practiceDone,setPracticeDone]=useState(false),[noSuppression,setNoSuppression]=useState(false),[zeroGoal,setZeroGoal]=useState(false),[naturalBreath,setNaturalBreath]=useState(false),[importantContent,setImportantContent]=useState(false),[antiComp,setAntiComp]=useState(false),[safe,setSafe]=useState(false),[orientation,setOrientation]=useState(false); const [objects,setObjects]=useState(0);
 const [note,setNote]=useState(''),[vaultSaved,setVaultSaved]=useState(false),[vaultSkipped,setVaultSkipped]=useState(false),[checksum,setChecksum]=useState<string|null>(null);
 useEffect(()=>{let active=true;if(!controller.auth.client||controller.auth.phase!=='signed-in')return()=>{active=false;};void loadCanonicalDay(controller.auth.client,78).then(v=>{if(active)setCanon(v);}).catch(e=>{if(active)setError(e instanceof Error?e.message:'canonical_day_load_failed');});return()=>{active=false;};},[controller.auth.client,controller.auth.phase]);
 const phase=controller.phase?.id;
 const saveVault=async()=>{if(!controller.auth.client||!controller.auth.userId||note.trim().length<2)return;try{const enc=await encryptVaultText({userId:controller.auth.userId,day:78,kind:'hariel-day078-important-content',plaintext:JSON.stringify({schema:'hnk-hariel-day078-v1',important_content:note.trim()})});await saveEncryptedVaultEntry(controller.auth.client,{day:78,payload:enc});setChecksum(enc.checksumSha256);setVaultSaved(true);controller.nextPhase();}catch(e){setError(e instanceof Error?e.message:'day078_vault_failed');}};
 const stop=()=>controller.interrupt({durationSeconds:seconds,evidence:{safety_stop:true},metrics:{practice_seconds:seconds,attention_returns:returns,comfort,effort}});
 if(controller.loading)return <View style={s.loading}><Text style={s.meta}>ABRINDO HARIEL · DIA 078</Text></View>;
 return <ScrollView style={s.screen} contentContainerStyle={s.content}><View style={s.header}><Text style={s.eyebrow}>BINAH · HARIEL 5/5 · DIA 078</Text><Text style={s.title}>{canon?.title??'BANIMENTO SILENCIOSO'}</Text><Text style={s.meta}>{canon?`${canon.sourcePath} · ${canon.sourceSha.slice(0,10)} · +${canon.xp} XP`:'CÂNONE SINCRONIZANDO'}</Text></View>
 {controller.error||error?<RuntimeNotice title="RUNTIME">{error??controller.error}</RuntimeNotice>:null}{controller.runtime?.status==='locked'?<RuntimeCard label="GATE" title="Dia 078 bloqueado pela sequência"><Text style={runtimeTextStyles.body}>A primeira conclusão exige o Dia 077 confirmado no servidor.</Text></RuntimeCard>:null}
 {phase==='threshold'?<RuntimeCard label="HARIEL 5/5" title="O véu é limite atencional, não guerra contra pensamentos"><CanonicalText>{canon?.blocks['jachin-kavanah']??''}</CanonicalText><RuntimeNotice title="SEM META INVENTADA">O cânone não fixa duração. O relógio é aberto e serve apenas para registrar prática real. Pensamentos continuam válidos; zero pensamentos não concede bônus.</RuntimeNotice><RuntimePrimary label="INICIAR" disabled={!canon||controller.busy} onPress={()=>void controller.begin().then(controller.nextPhase)}/></RuntimeCard>:null}
 {phase==='silence'?<RuntimeCard label="SILÊNCIO" title="Reconhecer palavra → retornar à atenção"><RuntimeOpenTimer value={seconds} onChange={setSeconds}/><RuntimeCounter label="RETORNOS DE ATENÇÃO" value={returns} onPress={()=>setReturns(v=>v+1)}/><RuntimeScale label="CONFORTO" value={comfort} onChange={setComfort}/><RuntimeScale label="ESFORÇO" value={effort} onChange={setEffort}/><RuntimeChoice selected={naturalBreath} label="MANTIVE RESPIRAÇÃO NATURAL · SEM RETENÇÃO" onPress={()=>setNaturalBreath(v=>!v)}/><RuntimePrimary label="SAFETY STOP" onPress={stop}/><RuntimePrimary label="ENCERRAR PRÁTICA" disabled={seconds<1||!naturalBreath} onPress={()=>{setPracticeDone(true);controller.nextPhase();}}/></RuntimeCard>:null}
 {phase==='review'?<RuntimeCard label="REVISÃO" title="Silêncio sem compulsão"><RuntimeChoice selected={noSuppression} label="NÃO TRATEI PENSAMENTOS COMO FALHA A SER EXPULSA" onPress={()=>setNoSuppression(v=>!v)}/><RuntimeChoice selected={zeroGoal} label="REJEITEI A META DE ZERO PENSAMENTOS" onPress={()=>setZeroGoal(v=>!v)}/><RuntimeChoice selected={importantContent} label="CONTEÚDO IMPORTANTE OU DE RISCO NÃO FOI IGNORADO" onPress={()=>setImportantContent(v=>!v)}/><RuntimeChoice selected={antiComp} label="NÃO REPETIREI A PRÁTICA PARA NEUTRALIZAR MEDO OU BUSCAR CERTEZA" onPress={()=>setAntiComp(v=>!v)}/><RuntimeChoice selected={safe} label="ESTOU CONFORTÁVEL E POSSO RETORNAR" onPress={()=>setSafe(v=>!v)}/><RuntimePrimary label="GROUNDING" disabled={!practiceDone||!noSuppression||!zeroGoal||!importantContent||!antiComp||!safe} onPress={controller.nextPhase}/></RuntimeCard>:null}
 {phase==='grounding'?<RuntimeCard label="RETURN GATE" title="O ciclo termina em orientação comum"><RuntimeCounter label="OBJETOS REAIS NOMEADOS" value={objects} onPress={()=>setObjects(v=>Math.min(5,v+1))}/><RuntimeChoice selected={orientation} label="ABRI OS OLHOS, MOVI MÃOS/PÉS E ESTOU ORIENTADO" onPress={()=>setOrientation(v=>!v)}/><RuntimePrimary label="RETORNO CONFIRMADO" disabled={objects<3||!orientation} onPress={()=>{controller.setReturnConfirmed();controller.nextPhase();}}/></RuntimeCard>:null}
 {phase==='vault'?<RuntimeCard label="VAULT OPCIONAL" title="Somente se houve conteúdo que deseja conservar"><TextInput value={note} onChangeText={setNote} placeholder="Conteúdo importante que deseja preservar cifrado · opcional" placeholderTextColor="#665f70" style={runtimeTextStyles.input}/><RuntimePrimary label="CIFRAR E SALVAR" disabled={note.trim().length<2||vaultSaved||vaultSkipped} onPress={()=>void saveVault()}/><RuntimePrimary label="NÃO HÁ CONTEÚDO A SALVAR" disabled={vaultSaved||vaultSkipped} onPress={()=>{setVaultSkipped(true);controller.nextPhase();}}/></RuntimeCard>:null}
 {phase==='seal'?<RuntimeCard label="SELO SERVER-SIDE" title="Hariel 5/5"><RuntimePrimary label={controller.busy?'SELANDO…':'SELAR DIA 078'} disabled={controller.busy||(!vaultSaved&&!vaultSkipped)||!practiceDone||!safe||!orientation} onPress={()=>void controller.seal({localRecordHash:checksum??undefined,durationSeconds:seconds,evidence:{protocol_completed:true,return_confirmed:true,silence_practice_completed:practiceDone,thought_suppression_not_required:noSuppression,zero_thought_goal_rejected:zeroGoal,natural_breath_preserved:naturalBreath,important_content_not_ignored:importantContent,anti_compulsion_rule_confirmed:antiComp,orientation_restored:orientation,safety_clear:safe,practice_seconds:seconds,attention_returns:returns},metrics:{comfort,effort,vault_used:vaultSaved}}).then(controller.nextPhase).catch(e=>setError(e instanceof Error?e.message:'day078_seal_failed'))}/></RuntimeCard>:null}
 {phase==='complete'?<RuntimeCompletion completion={controller.runtime?.serverCompletion} label="HARIEL 5/5"/>:null}</ScrollView>;
}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:'#08050b'},content:{padding:24,gap:18,paddingBottom:52},loading:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:'#08050b'},header:{gap:6},eyebrow:{color:'#9a78ad',fontSize:8,letterSpacing:1.5},title:{color:'#f4eafa',fontSize:25,lineHeight:31,fontWeight:'300'},meta:{color:'#806d8a',fontSize:8,letterSpacing:0.8}});
