import { useEffect, useMemo, useState } from 'react';
import { ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { saveEncryptedVaultEntry } from '@hnk/supabase-client';
import { encryptVaultText } from '../vault/vault-crypto';
import { loadCanonicalDay, type CanonicalDaySnapshot } from '../kether/canonical-day';
import { CanonicalText, RuntimeCard, RuntimeChoice, RuntimeCompletion, RuntimeCounter, RuntimeNotice, RuntimePrimary, runtimeTextStyles } from '../kether/KetherRuntimePrimitives';
import { useHnkDayRuntime } from '../kether/useHnkDayRuntime';
import { LAUVIAH_BINAH_DAY_085, LAUVIAH_BINAH_DAY_086, LAUVIAH_BINAH_DAY_087 } from './runtime-definitions/lauviah';

type Day=85|86|87; type Row={a:string;b:string;c:string;count:string};
const DEF={85:LAUVIAH_BINAH_DAY_085,86:LAUVIAH_BINAH_DAY_086,87:LAUVIAH_BINAH_DAY_087} as const;
const META={
 85:{label:'LAUVIAH 2/5 · DIA 085',title:'Catalogando o Fogo Negro',rows:['IRA','IMPACIÊNCIA','ORGULHO ESPIRITUAL','ARROGÂNCIA INTELECTUAL'] as const,a:'Situação/episódio lembrado — ou “nenhum lembrado”',b:'Emoção · comportamento · consequência',c:'Incerteza, padrão ou reparação proporcional'},
 86:{label:'LAUVIAH 3/5 · DIA 086',title:'Catalogando o Fogo Branco',rows:['INICIATIVA','CORAGEM','DINAMISMO MENTAL','DEVOÇÃO VIGOROSA'] as const,a:'Evidência concreta — ou “ainda não identifiquei”',b:'Quando esta força deixa de servir?',c:'Aplicação pequena, proporcional e sustentável'},
 87:{label:'LAUVIAH 4/5 · DIA 087',title:'Quebrando a Leitura de Mente',rows:['HIPÓTESE 1','HIPÓTESE 2','HIPÓTESE 3'] as const,a:'O que suponho que a outra pessoa pensa?',b:'Fala direta · comportamento observado · inferência · não sei',c:'Formulação mais precisa / pergunta neutra não enviada'},
} as const;
function parseCount(v:string){const n=Number(v.trim());return Number.isInteger(n)&&n>=0?n:null;}
export function LauviahDays085to087Experience({day}:{day:Day}){
 const meta=META[day],controller=useHnkDayRuntime(DEF[day]); const [canon,setCanon]=useState<CanonicalDaySnapshot|null>(null),[error,setError]=useState<string|null>(null); const [rows,setRows]=useState<Row[]>(()=>Array.from({length:meta.rows.length},()=>({a:'',b:'',c:'',count:'0'}))); const [vault,setVault]=useState(false),[checksum,setChecksum]=useState<string|null>(null),[safe,setSafe]=useState(false),[orientation,setOrientation]=useState(false),[objects,setObjects]=useState(0);
 const [memory,setMemory]=useState(false),[uncertainty,setUncertainty]=useState(false),[identity,setIdentity]=useState(false),[rumination,setRumination]=useState(false),[repair,setRepair]=useState(false); const [noRanking,setNoRanking]=useState(false),[noSuperiority,setNoSuperiority]=useState(false),[restConsent,setRestConsent]=useState(false),[limits,setLimits]=useState(false),[application,setApplication]=useState(false); const [directSpeech,setDirectSpeech]=useState(false),[inference,setInference]=useState(false),[unknown,setUnknown]=useState(false),[privacy,setPrivacy]=useState(false),[noSurveillance,setNoSurveillance]=useState(false),[noInterrogation,setNoInterrogation]=useState(false),[noIdentity,setNoIdentity]=useState(false);
 useEffect(()=>{let active=true;if(!controller.auth.client||controller.auth.phase!=='signed-in')return()=>{active=false;};void loadCanonicalDay(controller.auth.client,day).then(v=>{if(active)setCanon(v);}).catch(e=>{if(active)setError(e instanceof Error?e.message:'canonical_day_load_failed');});return()=>{active=false;};},[controller.auth.client,controller.auth.phase,day]);
 const patch=(i:number,k:keyof Row,v:string)=>setRows(cur=>cur.map((r,x)=>x===i?{...r,[k]:v}:r)); const complete=useMemo(()=>rows.every(r=>r.a.trim().length>1&&r.b.trim().length>1&&r.c.trim().length>1&&(day===87||parseCount(r.count)!==null)),[rows,day]);
 const counts=rows.map(r=>parseCount(r.count)??0); const reviewReady=day===85?memory&&uncertainty&&identity&&rumination&&repair:day===86?noRanking&&noSuperiority&&restConsent&&limits&&application:directSpeech&&inference&&unknown&&privacy&&noSurveillance&&noInterrogation&&noIdentity;
 const save=async()=>{if(!controller.auth.client||!controller.auth.userId||!complete)return;try{const enc=await encryptVaultText({userId:controller.auth.userId,day,kind:`lauviah-day${day}-review`,plaintext:JSON.stringify({schema:`hnk-lauviah-day${day}-v1`,rows})});await saveEncryptedVaultEntry(controller.auth.client,{day,payload:enc});setChecksum(enc.checksumSha256);setVault(true);controller.nextPhase();}catch(e){setError(e instanceof Error?e.message:`day${day}_vault_failed`);}}; const stop=()=>controller.interrupt({evidence:{safety_stop:true},metrics:{rows_complete:rows.filter(r=>r.a.trim()&&r.b.trim()&&r.c.trim()).length}}); const phase=controller.phase?.id;
 const evidence:Record<string,boolean|number>=day===85?{protocol_completed:true,return_confirmed:true,year_review_completed:true,anger_reviewed:true,impatience_reviewed:true,spiritual_pride_reviewed:true,intellectual_arrogance_reviewed:true,memory_not_fabricated:memory,uncertainty_preserved:uncertainty,emotion_behavior_identity_separated:identity,rumination_avoided:rumination,safe_repair_considered:repair,vault_saved:vault,safety_clear:safe,anger_count:counts[0]??0,impatience_count:counts[1]??0,spiritual_pride_count:counts[2]??0,intellectual_arrogance_count:counts[3]??0}:day===86?{protocol_completed:true,return_confirmed:true,initiative_reviewed:true,courage_reviewed:true,mental_dynamism_reviewed:true,vigorous_devotion_reviewed:true,evidence_or_gap_recorded:true,limits_recorded:limits,no_spiritual_ranking:noRanking,no_superiority_claim:noSuperiority,rest_and_consent_preserved:restConsent,proportional_application_defined:application,vault_saved:vault,safety_clear:safe,categories_reviewed:4,evidence_examples_count:counts.reduce((a,b)=>a+b,0)}:{protocol_completed:true,return_confirmed:true,three_hypotheses_recorded:true,evidence_types_separated:true,direct_speech_not_erased:directSpeech,inference_named_as_inference:inference,unknown_acknowledged:unknown,privacy_preserved:privacy,no_surveillance:noSurveillance,no_compulsive_interrogation:noInterrogation,third_party_identity_not_sent:noIdentity,vault_saved:vault,safety_clear:safe,hypotheses_count:3};
 if(controller.loading)return <View style={s.loading}><Text style={s.meta}>ABRINDO {meta.label}</Text></View>;
 return <ScrollView style={s.screen} contentContainerStyle={s.content}><View style={s.header}><Text style={s.eyebrow}>BINAH · {meta.label}</Text><Text style={s.title}>{canon?.title??meta.title}</Text><Text style={s.meta}>{canon?`${canon.sourcePath} · ${canon.sourceSha.slice(0,10)} · +${canon.xp} XP`:'CÂNONE SINCRONIZANDO'}</Text></View>
 {controller.error||error?<RuntimeNotice title="RUNTIME">{error??controller.error}</RuntimeNotice>:null}{controller.runtime?.status==='locked'?<RuntimeCard label="GATE" title={`Dia ${day} bloqueado pela sequência`}><Text style={runtimeTextStyles.body}>A primeira conclusão exige o Day anterior confirmado no servidor.</Text></RuntimeCard>:null}
 {phase==='threshold'?<RuntimeCard label={meta.label} title={meta.title}><CanonicalText>{canon?.blocks['jachin-kavanah']??''}</CanonicalText><RuntimeNotice title="VAULT-FIRST">Narrativas, nomes e detalhes relacionais permanecem cifrados. O servidor recebe apenas contagens e flags estruturais.</RuntimeNotice><RuntimePrimary label="INICIAR" disabled={!canon||controller.busy} onPress={()=>void controller.begin().then(controller.nextPhase)}/></RuntimeCard>:null}
 {phase==='vault'?<RuntimeCard label="VAULT" title={day===87?'Três hipóteses privadas':'Quatro categorias revisadas'}>{rows.map((r,i)=><View key={i} style={s.row}><Text style={s.rowTitle}>{meta.rows[i]}</Text>{day!==87?<TextInput keyboardType="number-pad" value={r.count} onChangeText={v=>patch(i,'count',v)} placeholder="Quantidade lembrada · zero é válido" placeholderTextColor="#665f70" style={runtimeTextStyles.input}/>:null}<TextInput value={r.a} onChangeText={v=>patch(i,'a',v)} placeholder={meta.a} placeholderTextColor="#665f70" style={runtimeTextStyles.input}/><TextInput value={r.b} onChangeText={v=>patch(i,'b',v)} placeholder={meta.b} placeholderTextColor="#665f70" style={runtimeTextStyles.input}/><TextInput value={r.c} onChangeText={v=>patch(i,'c',v)} placeholder={meta.c} placeholderTextColor="#665f70" style={runtimeTextStyles.input}/></View>)}{day===85?<RuntimeNotice title="ZERO É DADO">Uma categoria pode ter contagem zero. Isso não reduz XP e não autoriza fabricar memória.</RuntimeNotice>:null}{day===86?<RuntimeNotice title="LACUNA É VÁLIDA">“Ainda não identifiquei” é resposta válida. Virtude não vira ranking ou essência superior.</RuntimeNotice>:null}{day===87?<RuntimeNotice title="SEM VIGILÂNCIA">Não procure confirmação invadindo privacidade, microexpressões, status online ou interrogatório compulsivo.</RuntimeNotice>:null}<RuntimePrimary label="SAFETY STOP" onPress={stop}/><RuntimePrimary label="CIFRAR E CONTINUAR" disabled={!complete} onPress={()=>void save()}/></RuntimeCard>:null}
 {phase==='review'?<RuntimeCard label="REVISÃO" title="Fogo sob verdade, limite e responsabilidade">{day===85?<><RuntimeChoice selected={memory} label="NÃO FABRIQUEI EPISÓDIOS PARA COMPLETAR CATEGORIAS" onPress={()=>setMemory(v=>!v)}/><RuntimeChoice selected={uncertainty} label="MEMÓRIA INCERTA CONTINUA MARCADA COMO INCERTA" onPress={()=>setUncertainty(v=>!v)}/><RuntimeChoice selected={identity} label="SEPAREI EMOÇÃO, COMPORTAMENTO, CONSEQUÊNCIA E IDENTIDADE" onPress={()=>setIdentity(v=>!v)}/><RuntimeChoice selected={rumination} label="NÃO TRANSFORMEI A REVISÃO EM RUMINAÇÃO/PENITÊNCIA COMPULSIVA" onPress={()=>setRumination(v=>!v)}/><RuntimeChoice selected={repair} label="CONSIDEREI REPARAÇÃO SOMENTE QUANDO SEGURA E PROPORCIONAL" onPress={()=>setRepair(v=>!v)}/></>:day===86?<><RuntimeChoice selected={limits} label="REGISTREI O LIMITE/EXCESSO POSSÍVEL DE CADA FORÇA" onPress={()=>setLimits(v=>!v)}/><RuntimeChoice selected={noRanking} label="NÃO CRIEI RANKING ESPIRITUAL" onPress={()=>setNoRanking(v=>!v)}/><RuntimeChoice selected={noSuperiority} label="NÃO TRATEI VIRTUDE COMO SUPERIORIDADE OU APROVAÇÃO DIVINA AUTOMÁTICA" onPress={()=>setNoSuperiority(v=>!v)}/><RuntimeChoice selected={restConsent} label="DESCANSO, CONSENTIMENTO E PRUDÊNCIA CONTINUAM LIMITES" onPress={()=>setRestConsent(v=>!v)}/><RuntimeChoice selected={application} label="DEFINI UMA APLICAÇÃO PEQUENA E PROPORCIONAL" onPress={()=>setApplication(v=>!v)}/></>:<><RuntimeChoice selected={directSpeech} label="FALA DIRETA NÃO FOI APAGADA COMO MERA INFERÊNCIA" onPress={()=>setDirectSpeech(v=>!v)}/><RuntimeChoice selected={inference} label="INFERÊNCIA FOI NOMEADA COMO INFERÊNCIA" onPress={()=>setInference(v=>!v)}/><RuntimeChoice selected={unknown} label="RECONHECI AO MENOS UMA PARTE QUE REALMENTE NÃO SEI" onPress={()=>setUnknown(v=>!v)}/><RuntimeChoice selected={privacy} label="PRIVACIDADE DE TERCEIROS FOI PRESERVADA" onPress={()=>setPrivacy(v=>!v)}/><RuntimeChoice selected={noSurveillance} label="NÃO USEI VIGILÂNCIA/MICROEXPRESSÃO/STATUS ONLINE COMO LEITURA AUTOMÁTICA" onPress={()=>setNoSurveillance(v=>!v)}/><RuntimeChoice selected={noInterrogation} label="NÃO INTERROGUEI ALGUÉM COMPULSIVAMENTE" onPress={()=>setNoInterrogation(v=>!v)}/><RuntimeChoice selected={noIdentity} label="IDENTIDADE DE TERCEIROS NÃO SERÁ ENVIADA AO SERVIDOR" onPress={()=>setNoIdentity(v=>!v)}/></>}<RuntimeChoice selected={safe} label="ESTOU SEGURO E FORA DE ESPIRAL DE ATIVAÇÃO/RUMINAÇÃO" onPress={()=>setSafe(v=>!v)}/><RuntimePrimary label="GROUNDING" disabled={!reviewReady||!safe} onPress={controller.nextPhase}/></RuntimeCard>:null}
 {phase==='grounding'?<RuntimeCard label="RETURN GATE" title="Retornar ao ambiente comum"><RuntimeCounter label="OBJETOS REAIS NOMEADOS" value={objects} onPress={()=>setObjects(v=>Math.min(5,v+1))}/><RuntimeChoice selected={orientation} label="ORIENTAÇÃO RESTAURADA" onPress={()=>setOrientation(v=>!v)}/><RuntimePrimary label="RETORNO CONFIRMADO" disabled={objects<3||!orientation} onPress={()=>{controller.setReturnConfirmed();controller.nextPhase();}}/></RuntimeCard>:null}
 {phase==='seal'?<RuntimeCard label="SELO SERVER-SIDE" title={meta.label}><RuntimePrimary label={controller.busy?'SELANDO…':`SELAR DIA ${day}`} disabled={controller.busy||!vault||!checksum||!reviewReady||!safe||!orientation} onPress={()=>void controller.seal({localRecordHash:checksum??undefined,evidence,metrics:{vault_saved:true}}).then(controller.nextPhase).catch(e=>setError(e instanceof Error?e.message:`day${day}_seal_failed`))}/></RuntimeCard>:null}
 {phase==='complete'?<RuntimeCompletion completion={controller.runtime?.serverCompletion} label={meta.label}/>:null}</ScrollView>;
}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:'#08050b'},content:{padding:24,gap:18,paddingBottom:52},loading:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:'#08050b'},header:{gap:6},eyebrow:{color:'#b27762',fontSize:8,letterSpacing:1.5},title:{color:'#f8ece5',fontSize:25,lineHeight:31,fontWeight:'300'},meta:{color:'#8d756b',fontSize:8,letterSpacing:.8},row:{gap:8,padding:12,borderWidth:1,borderColor:'#442b24',borderRadius:10},rowTitle:{color:'#c18a74',fontSize:9,letterSpacing:1.2}});
