import { useEffect, useState } from 'react';
import { ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { saveEncryptedVaultEntry } from '@hnk/supabase-client';
import { encryptVaultText } from '../vault/vault-crypto';
import { loadCanonicalDay, type CanonicalDaySnapshot } from '../kether/canonical-day';
import { CanonicalText, RuntimeCard, RuntimeChoice, RuntimeCompletion, RuntimeCounter, RuntimeNotice, RuntimeOpenTimer, RuntimePrimary, RuntimeScale, runtimeTextStyles } from '../kether/KetherRuntimePrimitives';
import { useHnkDayRuntime } from '../kether/useHnkDayRuntime';
import { LAUVIAH_BINAH_DAY_084 } from './runtime-definitions/lauviah';

type IlluminationPath=1|2;
export function LauviahDay084MirrorExperience(){
 const controller=useHnkDayRuntime(LAUVIAH_BINAH_DAY_084); const [canon,setCanon]=useState<CanonicalDaySnapshot|null>(null),[error,setError]=useState<string|null>(null); const [seconds,setSeconds]=useState(0),[illumination,setIllumination]=useState<IlluminationPath|null>(null),[effect,setEffect]=useState(false),[effectRecorded,setEffectRecorded]=useState(false),[comparison,setComparison]=useState(false),[comparisonRecorded,setComparisonRecorded]=useState(false),[tension,setTension]=useState(5),[comfort,setComfort]=useState(5);
 const [setup,setSetup]=useState(false),[fireSafe,setFireSafe]=useState(false),[fallbackLabel,setFallbackLabel]=useState(false),[blinking,setBlinking]=useState(false),[stopAvailable,setStopAvailable]=useState(false),[completed,setCompleted]=useState(false),[noEntity,setNoEntity]=useState(false),[noDiagnosis,setNoDiagnosis]=useState(false),[noIntensityScore,setNoIntensityScore]=useState(false),[safe,setSafe]=useState(false),[orientation,setOrientation]=useState(false),[objects,setObjects]=useState(0); const [note,setNote]=useState(''),[vaultSaved,setVaultSaved]=useState(false),[vaultSkipped,setVaultSkipped]=useState(false),[checksum,setChecksum]=useState<string|null>(null);
 useEffect(()=>{let active=true;if(!controller.auth.client||controller.auth.phase!=='signed-in')return()=>{active=false;};void loadCanonicalDay(controller.auth.client,84).then(v=>{if(active)setCanon(v);}).catch(e=>{if(active)setError(e instanceof Error?e.message:'canonical_day_load_failed');});return()=>{active=false;};},[controller.auth.client,controller.auth.phase]);
 const phase=controller.phase?.id, fallbackOk=illumination!==2||fallbackLabel, preflight=setup&&fireSafe&&fallbackOk&&illumination!==null; const stop=()=>controller.interrupt({durationSeconds:seconds,evidence:{safety_stop:true},metrics:{active_seconds:seconds,tension,comfort}});
 const saveVault=async()=>{if(!controller.auth.client||!controller.auth.userId||note.trim().length<2)return;try{const enc=await encryptVaultText({userId:controller.auth.userId,day:84,kind:'lauviah-day084-mirror-interpretation',plaintext:JSON.stringify({schema:'hnk-lauviah-day084-v1',private_interpretation:note.trim()})});await saveEncryptedVaultEntry(controller.auth.client,{day:84,payload:enc});setChecksum(enc.checksumSha256);setVaultSaved(true);controller.nextPhase();}catch(e){setError(e instanceof Error?e.message:'day084_vault_failed');}};
 if(controller.loading)return <View style={s.loading}><Text style={s.meta}>ABRINDO LAUVIAH · DIA 084</Text></View>;
 return <ScrollView style={s.screen} contentContainerStyle={s.content}><View style={s.header}><Text style={s.eyebrow}>BINAH · LAUVIAH 1/5 · DIA 084</Text><Text style={s.title}>{canon?.title??'REVELAÇÃO POR ESPELHO'}</Text><Text style={s.meta}>{canon?`${canon.sourcePath} · ${canon.sourceSha.slice(0,10)} · +${canon.xp} XP`:'CÂNONE SINCRONIZANDO'}</Text></View>
 {controller.error||error?<RuntimeNotice title="RUNTIME">{error??controller.error}</RuntimeNotice>:null}{controller.runtime?.status==='locked'?<RuntimeCard label="GATE" title="Dia 084 bloqueado pela sequência"><Text style={runtimeTextStyles.body}>A primeira conclusão exige o Dia 083 confirmado no servidor.</Text></RuntimeCard>:null}
 {phase==='threshold'?<RuntimeCard label="LAUVIAH 1/5" title="Espelho de Fogo com saída voluntária"><CanonicalText>{canon?.blocks['jachin-kavanah']??''}</CanonicalText><RuntimeNotice title="SAFETY">Piscar, ajustar postura e parar são sempre válidos. Dor ocular, tontura, ansiedade crescente, desorientação ou dificuldade de retorno encerram a prática.</RuntimeNotice><RuntimeChoice selected={illumination===1} label="1 · VELA REAL — somente estável, supervisionada e longe de inflamáveis" onPress={()=>setIllumination(1)}/><RuntimeChoice selected={illumination===2} label="2 · LUZ ELÉTRICA SUAVE — adaptação de produto" onPress={()=>setIllumination(2)}/>{illumination===2?<RuntimeChoice selected={fallbackLabel} label="RECONHEÇO A LUZ ELÉTRICA COMO ADAPTAÇÃO, NÃO EXECUÇÃO TEXTUAL IDÊNTICA" onPress={()=>setFallbackLabel(v=>!v)}/>:null}<RuntimeChoice selected={setup} label="ESPELHO, ASSENTO E ILUMINAÇÃO ESTÃO ESTÁVEIS" onPress={()=>setSetup(v=>!v)}/><RuntimeChoice selected={fireSafe} label="SEGURANÇA DE CHAMA/AMBIENTE ESTÁ PRESERVADA" onPress={()=>setFireSafe(v=>!v)}/><RuntimePrimary label="INICIAR" disabled={!canon||!preflight||controller.busy} onPress={()=>void controller.begin().then(controller.nextPhase)}/></RuntimeCard>:null}
 {phase==='active'?<RuntimeCard label="OBSERVAÇÃO" title="Olhos, penumbra e respiração natural"><RuntimeOpenTimer value={seconds} onChange={setSeconds}/><RuntimeNotice title="SEM DURAÇÃO INVENTADA">O cânone não fixa minutos. O tempo real é registrado sem transformar resistência ocular em meta.</RuntimeNotice><RuntimeScale label="TENSÃO" value={tension} onChange={setTension}/><RuntimeScale label="CONFORTO" value={comfort} onChange={setComfort}/><RuntimeChoice selected={blinking} label="PISQUEI/AJUSTEI POSTURA LIVREMENTE" onPress={()=>setBlinking(v=>!v)}/><RuntimeChoice selected={stopAvailable} label="MANTIVE PARADA VOLUNTÁRIA DISPONÍVEL" onPress={()=>setStopAvailable(v=>!v)}/><RuntimeChoice selected={effectRecorded&&effect} label="PERCEBI ALTERAÇÃO VISUAL LEVE" onPress={()=>{setEffect(true);setEffectRecorded(true);}}/><RuntimeChoice selected={effectRecorded&&!effect} label="NÃO PERCEBI ALTERAÇÃO MARCANTE" onPress={()=>{setEffect(false);setEffectRecorded(true);}}/><RuntimePrimary label="SAFETY STOP" onPress={stop}/><RuntimePrimary label="REVISAR" disabled={seconds<1||!effectRecorded||!blinking||!stopAvailable} onPress={()=>{setCompleted(true);controller.nextPhase();}}/></RuntimeCard>:null}
 {phase==='review'?<RuntimeCard label="REVISÃO" title="Percepção não vira revelação automática"><RuntimeChoice selected={noEntity} label="NÃO TRATEI DISTORÇÃO COMO PROVA DE ENTIDADE/AURA/MENSAGEM" onPress={()=>setNoEntity(v=>!v)}/><RuntimeChoice selected={noDiagnosis} label="NÃO TRATEI A EXPERIÊNCIA COMO DIAGNÓSTICO DO INCONSCIENTE" onPress={()=>setNoDiagnosis(v=>!v)}/><RuntimeChoice selected={noIntensityScore} label="INTENSIDADE VISUAL NÃO VIROU SCORE ESPIRITUAL" onPress={()=>setNoIntensityScore(v=>!v)}/><Text style={runtimeTextStyles.body}>Extensão comparativa com objeto neutro:</Text><RuntimeChoice selected={comparisonRecorded&&comparison} label="USEI A COMPARAÇÃO OPCIONAL" onPress={()=>{setComparison(true);setComparisonRecorded(true);}}/><RuntimeChoice selected={comparisonRecorded&&!comparison} label="NÃO USEI A COMPARAÇÃO OPCIONAL" onPress={()=>{setComparison(false);setComparisonRecorded(true);}}/><RuntimeChoice selected={safe} label="SEM SINTOMAS QUE EXIJAM ENCERRAMENTO/SAÍDA" onPress={()=>setSafe(v=>!v)}/><RuntimePrimary label="GROUNDING" disabled={!completed||!noEntity||!noDiagnosis||!noIntensityScore||!comparisonRecorded||!safe} onPress={controller.nextPhase}/></RuntimeCard>:null}
 {phase==='grounding'?<RuntimeCard label="RETURN GATE" title="Aumentar a luz e voltar ao ambiente"><RuntimeCounter label="OBJETOS REAIS NOMEADOS" value={objects} onPress={()=>setObjects(v=>Math.min(5,v+1))}/><RuntimeChoice selected={orientation} label="ORIENTAÇÃO RESTAURADA" onPress={()=>setOrientation(v=>!v)}/><RuntimePrimary label="RETORNO CONFIRMADO" disabled={objects<3||!orientation} onPress={()=>{controller.setReturnConfirmed();controller.nextPhase();}}/></RuntimeCard>:null}
 {phase==='vault'?<RuntimeCard label="VAULT OPCIONAL" title="Interpretação íntima permanece cifrada"><TextInput value={note} onChangeText={setNote} placeholder="Interpretação pessoal opcional" placeholderTextColor="#665f70" style={runtimeTextStyles.input}/><RuntimePrimary label="CIFRAR E SALVAR" disabled={note.trim().length<2||vaultSaved||vaultSkipped} onPress={()=>void saveVault()}/><RuntimePrimary label="SEM NOTA PRIVADA" disabled={vaultSaved||vaultSkipped} onPress={()=>{setVaultSkipped(true);controller.nextPhase();}}/></RuntimeCard>:null}
 {phase==='seal'?<RuntimeCard label="SELO SERVER-SIDE" title="Lauviah 1/5"><RuntimePrimary label={controller.busy?'SELANDO…':'SELAR DIA 084'} disabled={controller.busy||illumination===null||!fallbackOk||!safe||!orientation||(!vaultSaved&&!vaultSkipped)} onPress={()=>void controller.seal({localRecordHash:checksum??undefined,durationSeconds:seconds,evidence:{protocol_completed:true,return_confirmed:true,setup_checked:setup,mirror_practice_completed:completed,blinking_allowed:blinking,voluntary_stop_available:stopAvailable,objective_entity_not_claimed:noEntity,diagnosis_not_claimed:noDiagnosis,intensity_not_scored:noIntensityScore,fire_safety_preserved:fireSafe,electric_fallback_truthfully_labeled:fallbackOk,orientation_restored:orientation,safety_clear:safe,illumination_path_code:illumination,effect_present:effect,comparison_used:comparison,active_seconds:seconds},metrics:{tension,comfort,vault_used:vaultSaved}}).then(controller.nextPhase).catch(e=>setError(e instanceof Error?e.message:'day084_seal_failed'))}/></RuntimeCard>:null}
 {phase==='complete'?<RuntimeCompletion completion={controller.runtime?.serverCompletion} label="LAUVIAH 1/5"/>:null}</ScrollView>;
}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:'#08050b'},content:{padding:24,gap:18,paddingBottom:52},loading:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:'#08050b'},header:{gap:6},eyebrow:{color:'#b27762',fontSize:8,letterSpacing:1.5},title:{color:'#f8ece5',fontSize:25,lineHeight:31,fontWeight:'300'},meta:{color:'#8d756b',fontSize:8,letterSpacing:.8}});
