import { useEffect, useState } from 'react';
import { ScrollView, StyleSheet, Text, View } from 'react-native';
import { loadCanonicalDay, type CanonicalDaySnapshot } from '../kether/canonical-day';
import { CanonicalText, RuntimeCard, RuntimeChoice, RuntimeCompletion, RuntimeCounter, RuntimeNotice, RuntimeOpenTimer, RuntimePrimary, runtimeTextStyles } from '../kether/KetherRuntimePrimitives';
import { useHnkDayRuntime } from '../kether/useHnkDayRuntime';
import { LEUVIAH_DAY_094 } from './runtime-definitions/leuviah';

export function LeuviahDay094WaterFocusExperience(){
 const controller=useHnkDayRuntime(LEUVIAH_DAY_094); const [canon,setCanon]=useState<CanonicalDaySnapshot|null>(null),[error,setError]=useState<string|null>(null); const [seconds,setSeconds]=useState(0),[prepared,setPrepared]=useState(false),[observed,setObserved]=useState(false),[effect,setEffect]=useState(false),[effectRecorded,setEffectRecorded]=useState(false),[separated,setSeparated]=useState(false),[noHidden,setNoHidden]=useState(false),[noTransfer,setNoTransfer]=useState(false),[noScore,setNoScore]=useState(false),[orientation,setOrientation]=useState(false),[safe,setSafe]=useState(false),[objects,setObjects]=useState(0);
 useEffect(()=>{let active=true;if(!controller.auth.client||controller.auth.phase!=='signed-in')return()=>{active=false;};void loadCanonicalDay(controller.auth.client,94).then(v=>{if(active)setCanon(v);}).catch(e=>{if(active)setError(e instanceof Error?e.message:'canonical_day_load_failed');});return()=>{active=false;};},[controller.auth.client,controller.auth.phase]); const phase=controller.phase?.id; const stop=()=>controller.interrupt({durationSeconds:seconds,evidence:{safety_stop:true},metrics:{practice_seconds:seconds}});
 if(controller.loading)return <View style={s.loading}><Text style={s.meta}>ABRINDO LEUVIAH · DIA 094</Text></View>;
 return <ScrollView style={s.screen} contentContainerStyle={s.content}><View style={s.header}><Text style={s.eyebrow}>BINAH · LEUVIAH 1/5 · DIA 094</Text><Text style={s.title}>{canon?.title??'A FLUIDEZ DA SACERDOTISA'}</Text><Text style={s.meta}>{canon?`${canon.sourcePath} · ${canon.sourceSha.slice(0,10)} · +${canon.xp} XP`:'CÂNONE SINCRONIZANDO'}</Text></View>{controller.error||error?<RuntimeNotice title="RUNTIME">{error??controller.error}</RuntimeNotice>:null}{controller.runtime?.status==='locked'?<RuntimeCard label="GATE" title="Dia 094 bloqueado pela sequência"><Text style={runtimeTextStyles.body}>A primeira conclusão exige o Dia 093 confirmado no servidor.</Text></RuntimeCard>:null}
 {phase==='threshold'?<RuntimeCard label="LEUVIAH 1/5" title="Água como objeto de foco, não instrumento de medição oculta"><CanonicalText>{canon?.blocks['jachin-kavanah']??''}</CanonicalText><RuntimeChoice selected={prepared} label="PREPAREI UM COPO ESTÁVEL DE ÁGUA COMO OBJETO DE FOCO" onPress={()=>setPrepared(v=>!v)}/><RuntimeNotice title="LIMITE EPISTÊMICO">Alteração visual, sensação ou coincidência não prova propriedade oculta da água nem transferência energética mensurada.</RuntimeNotice><RuntimePrimary label="INICIAR" disabled={!canon||!prepared||controller.busy} onPress={()=>void controller.begin().then(controller.nextPhase)}/></RuntimeCard>:null}
 {phase==='practice'?<RuntimeCard label="FOCO CONTEMPLATIVO" title="Observar sem intensificar"><RuntimeOpenTimer value={seconds} onChange={setSeconds}/><RuntimeNotice title="SEM DURAÇÃO INVENTADA">O cânone não fixa minutos para o Day 094. O relógio registra somente o tempo realmente praticado.</RuntimeNotice><RuntimeChoice selected={effectRecorded&&effect} label="PERCEBI ALGUMA MUDANÇA SUBJETIVA" onPress={()=>{setEffect(true);setEffectRecorded(true);}}/><RuntimeChoice selected={effectRecorded&&!effect} label="NÃO PERCEBI MUDANÇA MARCANTE" onPress={()=>{setEffect(false);setEffectRecorded(true);}}/><RuntimeChoice selected={observed} label="CONCLUÍ A OBSERVAÇÃO SEM FORÇAR FENÔMENO" onPress={()=>setObserved(v=>!v)}/><RuntimePrimary label="SAFETY STOP" onPress={stop}/><RuntimePrimary label="REVISAR" disabled={seconds<1||!effectRecorded||!observed} onPress={controller.nextPhase}/></RuntimeCard>:null}
 {phase==='review'?<RuntimeCard label="REVISÃO" title="Fato, sensação e interpretação separados"><RuntimeChoice selected={separated} label="SEPAREI O QUE OBSERVEI DO QUE INTERPRETEI" onPress={()=>setSeparated(v=>!v)}/><RuntimeChoice selected={noHidden} label="NÃO ATRIBUÍ PROPRIEDADES OCULTAS OBJETIVAS À ÁGUA" onPress={()=>setNoHidden(v=>!v)}/><RuntimeChoice selected={noTransfer} label="NÃO DECLAREI TRANSFERÊNCIA ENERGÉTICA MENSURADA" onPress={()=>setNoTransfer(v=>!v)}/><RuntimeChoice selected={noScore} label="INTENSIDADE/AUSÊNCIA DE EFEITO NÃO VIROU SCORE ESPIRITUAL" onPress={()=>setNoScore(v=>!v)}/><RuntimeChoice selected={safe} label="ESTOU SEGURO PARA RETORNAR" onPress={()=>setSafe(v=>!v)}/><RuntimePrimary label="GROUNDING" disabled={!separated||!noHidden||!noTransfer||!noScore||!safe} onPress={controller.nextPhase}/></RuntimeCard>:null}
 {phase==='grounding'?<RuntimeCard label="RETURN GATE" title="Voltar ao ambiente"><RuntimeCounter label="OBJETOS REAIS NOMEADOS" value={objects} onPress={()=>setObjects(v=>Math.min(5,v+1))}/><RuntimeChoice selected={orientation} label="ORIENTAÇÃO RESTAURADA" onPress={()=>setOrientation(v=>!v)}/><RuntimePrimary label="RETORNO CONFIRMADO" disabled={objects<3||!orientation} onPress={()=>{controller.setReturnConfirmed();controller.nextPhase();}}/></RuntimeCard>:null}
 {phase==='seal'?<RuntimeCard label="SELO SERVER-SIDE" title="Leuviah 1/5"><RuntimePrimary label={controller.busy?'SELANDO…':'SELAR DIA 094'} disabled={controller.busy||!orientation||!safe} onPress={()=>void controller.seal({durationSeconds:seconds,evidence:{protocol_completed:true,return_confirmed:true,focus_object_prepared:prepared,observation_completed:observed,fact_interpretation_separated:separated,water_hidden_properties_not_claimed:noHidden,energy_transfer_not_claimed:noTransfer,intensity_not_scored:noScore,orientation_restored:orientation,safety_clear:safe,effect_present:effect,practice_seconds:seconds}}).then(controller.nextPhase).catch(e=>setError(e instanceof Error?e.message:'day094_seal_failed'))}/></RuntimeCard>:null}{phase==='complete'?<RuntimeCompletion completion={controller.runtime?.serverCompletion} label="LEUVIAH 1/5"/>:null}</ScrollView>;
}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:'#06100f'},content:{padding:24,gap:18,paddingBottom:52},loading:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:'#06100f'},header:{gap:6},eyebrow:{color:'#6ca7a0',fontSize:8,letterSpacing:1.5},title:{color:'#eaf8f6',fontSize:25,lineHeight:31,fontWeight:'300'},meta:{color:'#708f8b',fontSize:8,letterSpacing:.8}});
