import { useEffect, useState } from 'react';
import { ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { saveEncryptedVaultEntry } from '@hnk/supabase-client';
import { encryptVaultText } from '../vault/vault-crypto';
import { loadCanonicalDay, type CanonicalDaySnapshot } from '../kether/canonical-day';
import { CanonicalText, RuntimeCard, RuntimeChoice, RuntimeCompletion, RuntimeCounter, RuntimeNotice, RuntimePrimary, runtimeTextStyles } from '../kether/KetherRuntimePrimitives';
import { useHnkDayRuntime } from '../kether/useHnkDayRuntime';
import { LEUVIAH_DAY_097 } from './runtime-definitions/leuviah';

export function LeuviahDay097EquivalenceExperience(){
 const controller=useHnkDayRuntime(LEUVIAH_DAY_097); const [canon,setCanon]=useState<CanonicalDaySnapshot|null>(null),[error,setError]=useState<string|null>(null); const [behavior,setBehavior]=useState(''),[meaning,setMeaning]=useState(''),[context,setContext]=useState(''),[alt1,setAlt1]=useState(''),[alt2,setAlt2]=useState(''); const [vault,setVault]=useState(false),[checksum,setChecksum]=useState<string|null>(null),[contextDone,setContextDone]=useState(false),[crying,setCrying]=useState(false),[serenity,setSerenity]=useState(false),[noFixed,setNoFixed]=useState(false),[noDiagnosis,setNoDiagnosis]=useState(false),[orientation,setOrientation]=useState(false),[safe,setSafe]=useState(false),[objects,setObjects]=useState(0);
 useEffect(()=>{let active=true;if(!controller.auth.client||controller.auth.phase!=='signed-in')return()=>{active=false;};void loadCanonicalDay(controller.auth.client,97).then(v=>{if(active)setCanon(v);}).catch(e=>{if(active)setError(e instanceof Error?e.message:'canonical_day_load_failed');});return()=>{active=false;};},[controller.auth.client,controller.auth.phase]); const phase=controller.phase?.id; const complete=[behavior,meaning,context,alt1,alt2].every(v=>v.trim().length>1);
 const save=async()=>{if(!controller.auth.client||!controller.auth.userId||!complete)return;try{const enc=await encryptVaultText({userId:controller.auth.userId,day:97,kind:'leuviah-day097-equivalence',plaintext:JSON.stringify({schema:'hnk-leuviah-day097-v1',behavior:behavior.trim(),automatic_meaning:meaning.trim(),context:context.trim(),alternatives:[alt1.trim(),alt2.trim()]})});await saveEncryptedVaultEntry(controller.auth.client,{day:97,payload:enc});setChecksum(enc.checksumSha256);setVault(true);controller.nextPhase();}catch(e){setError(e instanceof Error?e.message:'day097_vault_failed');}};
 if(controller.loading)return <View style={s.loading}><Text style={s.meta}>ABRINDO LEUVIAH · DIA 097</Text></View>;
 return <ScrollView style={s.screen} contentContainerStyle={s.content}><View style={s.header}><Text style={s.eyebrow}>BINAH · LEUVIAH 4/5 · DIA 097</Text><Text style={s.title}>{canon?.title??'DESFAZENDO EQUIVALÊNCIAS COMPLEXAS'}</Text><Text style={s.meta}>{canon?`${canon.sourcePath} · ${canon.sourceSha.slice(0,10)} · +${canon.xp} XP`:'CÂNONE SINCRONIZANDO'}</Text></View>{controller.error||error?<RuntimeNotice title="RUNTIME">{error??controller.error}</RuntimeNotice>:null}{controller.runtime?.status==='locked'?<RuntimeCard label="GATE" title="Dia 097 bloqueado pela sequência"><Text style={runtimeTextStyles.body}>A primeira conclusão exige o Dia 096 confirmado no servidor.</Text></RuntimeCard>:null}
 {phase==='threshold'?<RuntimeCard label="LEUVIAH 4/5" title="Um comportamento não determina sozinho uma identidade"><CanonicalText>{canon?.blocks['jachin-kavanah']??''}</CanonicalText><RuntimeNotice title="SEM QUOTA INVENTADA">O cânone pede identificar equivalências e gerar alternativas, mas não fixa uma quantidade. V1 trabalha uma equivalência completa e bem documentada.</RuntimeNotice><RuntimePrimary label="INICIAR" disabled={!canon||controller.busy} onPress={()=>void controller.begin().then(controller.nextPhase)}/></RuntimeCard>:null}
 {phase==='vault'?<RuntimeCard label="VAULT" title="Equivalência · contexto · alternativas"><TextInput value={behavior} onChangeText={setBehavior} placeholder="Comportamento/ausência observada — ex.: não chorei" placeholderTextColor="#55736f" style={runtimeTextStyles.input}/><TextInput value={meaning} onChangeText={setMeaning} placeholder="Significado automático atribuído — ex.: então sou frio" placeholderTextColor="#55736f" style={runtimeTextStyles.input}/><TextInput value={context} onChangeText={setContext} placeholder="Contexto que pode mudar a interpretação" placeholderTextColor="#55736f" style={runtimeTextStyles.input}/><TextInput value={alt1} onChangeText={setAlt1} placeholder="Interpretação alternativa 1" placeholderTextColor="#55736f" style={runtimeTextStyles.input}/><TextInput value={alt2} onChangeText={setAlt2} placeholder="Interpretação alternativa 2" placeholderTextColor="#55736f" style={runtimeTextStyles.input}/><RuntimePrimary label="SAFETY STOP" onPress={()=>controller.interrupt({evidence:{safety_stop:true}})}/><RuntimePrimary label="CIFRAR E CONTINUAR" disabled={!complete} onPress={()=>void save()}/></RuntimeCard>:null}
 {phase==='review'?<RuntimeCard label="REVISÃO" title="Alternativas ampliam hipótese; não apagam emoção"><RuntimeChoice selected={contextDone} label="CONSIDEREI CONTEXTO ANTES DE CONCLUIR O SIGNIFICADO" onPress={()=>setContextDone(v=>!v)}/><RuntimeChoice selected={crying} label="NÃO INVALIDO CHORO, LUTO OU EMOÇÃO" onPress={()=>setCrying(v=>!v)}/><RuntimeChoice selected={serenity} label="NÃO IMPUS SERENIDADE COMO OBRIGAÇÃO MORAL" onPress={()=>setSerenity(v=>!v)}/><RuntimeChoice selected={noFixed} label="NÃO TRANSFORMEI UM COMPORTAMENTO EM IDENTIDADE FIXA" onPress={()=>setNoFixed(v=>!v)}/><RuntimeChoice selected={noDiagnosis} label="NÃO PRODUZI DIAGNÓSTICO PRÓPRIO OU ALHEIO" onPress={()=>setNoDiagnosis(v=>!v)}/><RuntimeChoice selected={safe} label="ESTOU SEGURO PARA RETORNAR" onPress={()=>setSafe(v=>!v)}/><RuntimePrimary label="GROUNDING" disabled={!contextDone||!crying||!serenity||!noFixed||!noDiagnosis||!safe} onPress={controller.nextPhase}/></RuntimeCard>:null}
 {phase==='grounding'?<RuntimeCard label="RETURN GATE" title="Retorno com hipótese aberta"><RuntimeCounter label="OBJETOS REAIS NOMEADOS" value={objects} onPress={()=>setObjects(v=>Math.min(5,v+1))}/><RuntimeChoice selected={orientation} label="ORIENTAÇÃO RESTAURADA" onPress={()=>setOrientation(v=>!v)}/><RuntimePrimary label="RETORNO CONFIRMADO" disabled={objects<3||!orientation} onPress={()=>{controller.setReturnConfirmed();controller.nextPhase();}}/></RuntimeCard>:null}
 {phase==='seal'?<RuntimeCard label="SELO SERVER-SIDE" title="Leuviah 4/5"><RuntimePrimary label={controller.busy?'SELANDO…':'SELAR DIA 097'} disabled={controller.busy||!vault||!checksum||!contextDone||!crying||!serenity||!noFixed||!noDiagnosis||!orientation||!safe} onPress={()=>void controller.seal({localRecordHash:checksum??undefined,evidence:{protocol_completed:true,return_confirmed:true,equivalence_recorded:true,alternatives_generated:true,context_considered:contextDone,crying_grief_not_invalidated:crying,serenity_not_required:serenity,fixed_identity_not_claimed:noFixed,diagnosis_not_claimed:noDiagnosis,vault_saved:vault,orientation_restored:orientation,safety_clear:safe}}).then(controller.nextPhase).catch(e=>setError(e instanceof Error?e.message:'day097_seal_failed'))}/></RuntimeCard>:null}{phase==='complete'?<RuntimeCompletion completion={controller.runtime?.serverCompletion} label="LEUVIAH 4/5"/>:null}</ScrollView>;
}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:'#06100f'},content:{padding:24,gap:18,paddingBottom:52},loading:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:'#06100f'},header:{gap:6},eyebrow:{color:'#6ca7a0',fontSize:8,letterSpacing:1.5},title:{color:'#eaf8f6',fontSize:25,lineHeight:31,fontWeight:'300'},meta:{color:'#708f8b',fontSize:8,letterSpacing:.8}});
