import { useEffect, useState } from 'react';
import { ScrollView, StyleSheet, Text, View } from 'react-native';
import { loadCanonicalDay, type CanonicalDaySnapshot } from '../kether/canonical-day';
import { CanonicalText, RuntimeCard, RuntimeChoice, RuntimeCompletion, RuntimeCounter, RuntimeNotice, RuntimeOpenTimer, RuntimePrimary, runtimeTextStyles } from '../kether/KetherRuntimePrimitives';
import { useHnkDayRuntime } from '../kether/useHnkDayRuntime';
import { PAHALIAH_DAY_103 } from './runtime-definitions/pahaliah';

export function PahaliahDay103AltarExperience(){
 const controller=useHnkDayRuntime(PAHALIAH_DAY_103); const [canon,setCanon]=useState<CanonicalDaySnapshot|null>(null),[error,setError]=useState<string|null>(null),[seconds,setSeconds]=useState(0),[done,setDone]=useState(false),[effect,setEffect]=useState(false),[effectRecorded,setEffectRecorded]=useState(false),[noPerfect,setNoPerfect]=useState(false),[antiCompulsion,setAntiCompulsion]=useState(false),[domestic,setDomestic]=useState(false),[access,setAccess]=useState(false),[cohab,setCohab]=useState(false),[noAestheticRank,setNoAestheticRank]=useState(false),[orientation,setOrientation]=useState(false),[safe,setSafe]=useState(false),[objects,setObjects]=useState(0);
 useEffect(()=>{let active=true;if(!controller.auth.client||controller.auth.phase!=='signed-in')return()=>{active=false;};void loadCanonicalDay(controller.auth.client,103).then(v=>{if(active)setCanon(v);}).catch(e=>{if(active)setError(e instanceof Error?e.message:'canonical_day_load_failed');});return()=>{active=false;};},[controller.auth.client,controller.auth.phase]); const phase=controller.phase?.id; const stop=()=>controller.interrupt({durationSeconds:seconds,evidence:{safety_stop:true},metrics:{practice_seconds:seconds}});
 if(controller.loading)return <View style={s.loading}><Text style={s.meta}>ABRINDO PAHALIAH · DIA 103</Text></View>; return <ScrollView style={s.screen} contentContainerStyle={s.content}><View style={s.header}><Text style={s.eyebrow}>BINAH · PAHALIAH 5/5 · DIA 103</Text><Text style={s.title}>{canon?.title??'FIXAÇÃO NO ALTAR'}</Text><Text style={s.meta}>{canon?`${canon.sourcePath} · ${canon.sourceSha.slice(0,10)} · +${canon.xp} XP`:'CÂNONE SINCRONIZANDO'}</Text></View>{controller.error||error?<RuntimeNotice title="RUNTIME">{error??controller.error}</RuntimeNotice>:null}{controller.runtime?.status==='locked'?<RuntimeCard label="GATE" title="Dia 103 bloqueado pela sequência"><Text style={runtimeTextStyles.body}>A primeira conclusão exige o Dia 102 confirmado no servidor.</Text></RuntimeCard>:null}
 {phase==='threshold'?<RuntimeCard label="PAHALIAH 5/5" title="Organizar para funcionar, não para atingir perfeição"><CanonicalText>{canon?.blocks['jachin-kavanah']??''}</CanonicalText><RuntimeNotice title="SEGURANÇA DOMÉSTICA PRIMEIRO">Acessibilidade, convivência, circulação e segurança têm prioridade sobre estética ritual. A limpeza pode ser suficiente sem ser perfeita.</RuntimeNotice><RuntimePrimary label="INICIAR" disabled={!canon||controller.busy} onPress={()=>void controller.begin().then(controller.nextPhase)}/></RuntimeCard>:null}
 {phase==='practice'?<RuntimeCard label="ORGANIZAÇÃO / LIMPEZA" title="Tempo aberto e objetivo funcional"><RuntimeOpenTimer value={seconds} onChange={setSeconds}/><RuntimeNotice title="SEM DURAÇÃO INVENTADA">O Day não fixa minutos nem quantidade de itens. Pare quando o espaço estiver funcional e seguro.</RuntimeNotice><RuntimeChoice selected={effectRecorded&&effect} label="PERCEBI ALGUMA MUDANÇA NA EXPERIÊNCIA DO ESPAÇO" onPress={()=>{setEffect(true);setEffectRecorded(true);}}/><RuntimeChoice selected={effectRecorded&&!effect} label="NÃO PERCEBI MUDANÇA SUBJETIVA MARCANTE" onPress={()=>{setEffect(false);setEffectRecorded(true);}}/><RuntimeChoice selected={done} label="CONCLUÍ UMA ORGANIZAÇÃO/LIMPEZA FUNCIONAL" onPress={()=>setDone(v=>!v)}/><RuntimePrimary label="SAFETY STOP" onPress={stop}/><RuntimePrimary label="REVISAR" disabled={seconds<1||!effectRecorded||!done} onPress={controller.nextPhase}/></RuntimeCard>:null}
 {phase==='review'?<RuntimeCard label="REVISÃO" title="Funcionalidade sem compulsão"><RuntimeChoice selected={noPerfect} label="PERFEIÇÃO NÃO FOI EXIGIDA" onPress={()=>setNoPerfect(v=>!v)}/><RuntimeChoice selected={antiCompulsion} label="NÃO PRECISO RECOMEÇAR/LIMPAR ATÉ SENTIR CERTEZA PERFEITA" onPress={()=>setAntiCompulsion(v=>!v)}/><RuntimeChoice selected={domestic} label="SEGURANÇA DOMÉSTICA FOI PRESERVADA" onPress={()=>setDomestic(v=>!v)}/><RuntimeChoice selected={access} label="ACESSIBILIDADE E CIRCULAÇÃO FORAM PRESERVADAS" onPress={()=>setAccess(v=>!v)}/><RuntimeChoice selected={cohab} label="CONVIVÊNCIA E ESPAÇO COMPARTILHADO FORAM RESPEITADOS" onPress={()=>setCohab(v=>!v)}/><RuntimeChoice selected={noAestheticRank} label="ESTÉTICA RITUAL NÃO VIROU RANKING ESPIRITUAL" onPress={()=>setNoAestheticRank(v=>!v)}/><RuntimeChoice selected={safe} label="O ESPAÇO ESTÁ SEGURO PARA ENCERRAR" onPress={()=>setSafe(v=>!v)}/><RuntimePrimary label="GROUNDING" disabled={!noPerfect||!antiCompulsion||!domestic||!access||!cohab||!noAestheticRank||!safe} onPress={controller.nextPhase}/></RuntimeCard>:null}
 {phase==='grounding'?<RuntimeCard label="RETURN GATE" title="Voltar ao uso cotidiano"><RuntimeCounter label="OBJETOS REAIS NOMEADOS" value={objects} onPress={()=>setObjects(v=>Math.min(5,v+1))}/><RuntimeChoice selected={orientation} label="ORIENTAÇÃO RESTAURADA" onPress={()=>setOrientation(v=>!v)}/><RuntimePrimary label="RETORNO CONFIRMADO" disabled={objects<3||!orientation} onPress={()=>{controller.setReturnConfirmed();controller.nextPhase();}}/></RuntimeCard>:null}
 {phase==='seal'?<RuntimeCard label="SELO SERVER-SIDE" title="Pahaliah 5/5"><RuntimePrimary label={controller.busy?'SELANDO…':'SELAR DIA 103'} disabled={controller.busy||!done||!noPerfect||!antiCompulsion||!domestic||!access||!cohab||!noAestheticRank||!orientation||!safe} onPress={()=>void controller.seal({durationSeconds:seconds,evidence:{protocol_completed:true,return_confirmed:true,organization_or_cleaning_completed:done,perfection_not_required:noPerfect,anti_compulsion_rule_confirmed:antiCompulsion,domestic_safety_preserved:domestic,accessibility_preserved:access,cohabitation_preserved:cohab,aesthetic_ranking_avoided:noAestheticRank,orientation_restored:orientation,safety_clear:safe,effect_present:effect,practice_seconds:seconds},metrics:{practice_seconds:seconds}}).then(controller.nextPhase).catch(e=>setError(e instanceof Error?e.message:'day103_seal_failed'))}/></RuntimeCard>:null}{phase==='complete'?<RuntimeCompletion completion={controller.runtime?.serverCompletion} label="PAHALIAH 5/5"/>:null}</ScrollView>;
}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:'#0d0b07'},content:{padding:24,gap:18,paddingBottom:52},loading:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:'#0d0b07'},header:{gap:6},eyebrow:{color:'#b39a63',fontSize:8,letterSpacing:1.5},title:{color:'#f7f0df',fontSize:25,lineHeight:31,fontWeight:'300'},meta:{color:'#928267',fontSize:8,letterSpacing:.8}});
