import { useEffect, useMemo, useState } from 'react';
import { ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { saveEncryptedVaultEntry } from '@hnk/supabase-client';
import { encryptVaultText } from '../vault/vault-crypto';
import { loadCanonicalDay, type CanonicalDaySnapshot } from '../kether/canonical-day';
import { CanonicalText, RuntimeCard, RuntimeChoice, RuntimeCompletion, RuntimeCounter, RuntimeNotice, RuntimePrimary, runtimeTextStyles } from '../kether/KetherRuntimePrimitives';
import { useHnkDayRuntime } from '../kether/useHnkDayRuntime';
import { PAHALIAH_DAY_100, PAHALIAH_DAY_101 } from './runtime-definitions/pahaliah';

type Day=100|101; type Row={count:string;note:string};
const DEF={100:PAHALIAH_DAY_100,101:PAHALIAH_DAY_101} as const;
const META={100:{label:'PAHALIAH 2/5 · DIA 100',title:'Catalogando a Terra Negra',rows:['PREGUIÇA','ADIAMENTO DE PRÁTICAS','APEGO MATERIAL','TEIMOSIA DE IDEIAS'] as const},101:{label:'PAHALIAH 3/5 · DIA 101',title:'Catalogando a Terra Branca',rows:['PERSEVERANÇA NO CODEX','CONFIABILIDADE','ESTABILIDADE PRÁTICA','DISCIPLINA DE HORÁRIOS'] as const}};
function n(v:string){const x=Number(v.trim());return Number.isInteger(x)&&x>=0?x:null;}
export function PahaliahDays100to101Experience({day}:{day:Day}){
 const meta=META[day],controller=useHnkDayRuntime(DEF[day]); const [canon,setCanon]=useState<CanonicalDaySnapshot|null>(null),[error,setError]=useState<string|null>(null),[rows,setRows]=useState<Row[]>(()=>meta.rows.map(()=>({count:'0',note:''}))),[vault,setVault]=useState(false),[checksum,setChecksum]=useState<string|null>(null),[orientation,setOrientation]=useState(false),[safe,setSafe]=useState(false),[objects,setObjects]=useState(0);
 const [context,setContext]=useState(false),[fatigue,setFatigue]=useState(false),[poverty,setPoverty]=useState(false),[illness,setIllness]=useState(false),[rest,setRest]=useState(false),[executive,setExecutive]=useState(false),[noDiagnosis,setNoDiagnosis]=useState(false); const [gaps,setGaps]=useState(false),[noObsess,setNoObsess]=useState(false),[noRank,setNoRank]=useState(false),[family,setFamily]=useState(false),[unforeseen,setUnforeseen]=useState(false),[repair,setRepair]=useState(false);
 useEffect(()=>{let active=true;if(!controller.auth.client||controller.auth.phase!=='signed-in')return()=>{active=false;};void loadCanonicalDay(controller.auth.client,day).then(v=>{if(active)setCanon(v);}).catch(e=>{if(active)setError(e instanceof Error?e.message:'canonical_day_load_failed');});return()=>{active=false;};},[controller.auth.client,controller.auth.phase,day]); const patch=(i:number,k:keyof Row,v:string)=>setRows(cur=>cur.map((r,x)=>x===i?{...r,[k]:v}:r)); const complete=useMemo(()=>rows.every(r=>n(r.count)!==null&&r.note.trim().length>1),[rows]); const total=rows.reduce((a,r)=>a+(n(r.count)??0),0); const phase=controller.phase?.id;
 const save=async()=>{if(!controller.auth.client||!controller.auth.userId||!complete)return;try{const enc=await encryptVaultText({userId:controller.auth.userId,day,kind:`pahaliah-day${day}-inventory`,plaintext:JSON.stringify({schema:`hnk-pahaliah-day${day}-v1`,categories:meta.rows.map((label,i)=>({label,count:n(rows[i]?.count??'0')??0,note:rows[i]?.note.trim()}))})});await saveEncryptedVaultEntry(controller.auth.client,{day,payload:enc});setChecksum(enc.checksumSha256);setVault(true);controller.nextPhase();}catch(e){setError(e instanceof Error?e.message:`day${day}_vault_failed`);}};
 const reviewReady=day===100?context&&fatigue&&poverty&&illness&&rest&&executive&&noDiagnosis:gaps&&noObsess&&noRank&&family&&unforeseen&&repair;
 const evidence:Record<string,boolean|number>=day===100?{protocol_completed:true,return_confirmed:true,laziness_reviewed:true,practice_delay_reviewed:true,material_attachment_reviewed:true,idea_stubbornness_reviewed:true,context_recorded:context,fatigue_not_moralized:fatigue,poverty_not_moralized:poverty,illness_not_moralized:illness,necessary_rest_not_moralized:rest,executive_difficulty_not_moralized:executive,diagnosis_not_claimed:noDiagnosis,vault_saved:vault,orientation_restored:orientation,safety_clear:safe,categories_reviewed:4,total_examples_count:total}:{protocol_completed:true,return_confirmed:true,perseverance_reviewed:true,reliability_reviewed:true,practical_stability_reviewed:true,schedule_discipline_reviewed:true,evidence_or_gap_recorded:gaps,obsession_avoided:noObsess,ranking_avoided:noRank,family_work_health_flexibility_preserved:family,unforeseen_events_flexibility_preserved:unforeseen,repair_path_defined:repair,vault_saved:vault,orientation_restored:orientation,safety_clear:safe,categories_reviewed:4,total_examples_count:total};
 if(controller.loading)return <View style={s.loading}><Text style={s.meta}>ABRINDO {meta.label}</Text></View>; return <ScrollView style={s.screen} contentContainerStyle={s.content}><View style={s.header}><Text style={s.eyebrow}>BINAH · {meta.label}</Text><Text style={s.title}>{canon?.title??meta.title}</Text><Text style={s.meta}>{canon?`${canon.sourcePath} · ${canon.sourceSha.slice(0,10)} · +${canon.xp} XP`:'CÂNONE SINCRONIZANDO'}</Text></View>{controller.error||error?<RuntimeNotice title="RUNTIME">{error??controller.error}</RuntimeNotice>:null}{controller.runtime?.status==='locked'?<RuntimeCard label="GATE" title={`Dia ${day} bloqueado pela sequência`}><Text style={runtimeTextStyles.body}>A primeira conclusão exige o Day anterior confirmado no servidor.</Text></RuntimeCard>:null}
 {phase==='threshold'?<RuntimeCard label={meta.label} title={meta.title}><CanonicalText>{canon?.blocks['jachin-kavanah']??''}</CanonicalText><RuntimeNotice title="VAULT-FIRST">Contextos pessoais permanecem cifrados. Zero exemplos é válido; nenhuma categoria precisa ser fabricada para XP.</RuntimeNotice><RuntimePrimary label="INICIAR" disabled={!canon||controller.busy} onPress={()=>void controller.begin().then(controller.nextPhase)}/></RuntimeCard>:null}
 {phase==='vault'?<RuntimeCard label="VAULT" title="Quatro categorias">{meta.rows.map((label,i)=><View key={label} style={s.row}><Text style={s.rowTitle}>{label}</Text><TextInput keyboardType="number-pad" value={rows[i]?.count??'0'} onChangeText={v=>patch(i,'count',v)} placeholder="Quantidade · zero é válido" placeholderTextColor="#746b56" style={runtimeTextStyles.input}/><TextInput value={rows[i]?.note??''} onChangeText={v=>patch(i,'note',v)} placeholder={day===100?'Contexto — ou “nenhum exemplo / incerto”':'Evidência — ou “ainda não identificado”'} placeholderTextColor="#746b56" style={runtimeTextStyles.input}/></View>)}<RuntimePrimary label="SAFETY STOP" onPress={()=>controller.interrupt({evidence:{safety_stop:true},metrics:{categories_completed:rows.filter(r=>r.note.trim().length>1).length}})}/><RuntimePrimary label="CIFRAR E CONTINUAR" disabled={!complete} onPress={()=>void save()}/></RuntimeCard>:null}
 {phase==='review'?<RuntimeCard label="REVISÃO" title={day===100?'Contexto antes do rótulo':'Regularidade com flexibilidade'}>{day===100?<><RuntimeChoice selected={context} label="REGISTREI CONTEXTO ANTES DE CHAMAR ALGO DE VÍCIO" onPress={()=>setContext(v=>!v)}/><RuntimeChoice selected={fatigue} label="FADIGA NÃO VIROU PREGUIÇA MORAL AUTOMÁTICA" onPress={()=>setFatigue(v=>!v)}/><RuntimeChoice selected={poverty} label="POBREZA/RESTRIÇÃO MATERIAL NÃO VIROU VÍCIO AUTOMÁTICO" onPress={()=>setPoverty(v=>!v)}/><RuntimeChoice selected={illness} label="DOENÇA/MAL-ESTAR NÃO VIROU CULPA MORAL" onPress={()=>setIllness(v=>!v)}/><RuntimeChoice selected={rest} label="DESCANSO NECESSÁRIO CONTINUA LEGÍTIMO" onPress={()=>setRest(v=>!v)}/><RuntimeChoice selected={executive} label="DIFICULDADE EXECUTIVA NÃO FOI MORALIZADA" onPress={()=>setExecutive(v=>!v)}/><RuntimeChoice selected={noDiagnosis} label="NÃO PRODUZI DIAGNÓSTICO" onPress={()=>setNoDiagnosis(v=>!v)}/></>:<><RuntimeChoice selected={gaps} label="REGISTREI EVIDÊNCIA OU LACUNA HONESTAMENTE" onPress={()=>setGaps(v=>!v)}/><RuntimeChoice selected={noObsess} label="REGULARIDADE NÃO VIROU OBSESSÃO" onPress={()=>setNoObsess(v=>!v)}/><RuntimeChoice selected={noRank} label="NÃO CRIEI RANKING DE DISCIPLINA/ESPIRITUALIDADE" onPress={()=>setNoRank(v=>!v)}/><RuntimeChoice selected={family} label="FAMÍLIA, TRABALHO E SAÚDE PODEM EXIGIR FLEXIBILIDADE" onPress={()=>setFamily(v=>!v)}/><RuntimeChoice selected={unforeseen} label="IMPREVISTOS LEGÍTIMOS NÃO VIRARAM FALHA MORAL" onPress={()=>setUnforeseen(v=>!v)}/><RuntimeChoice selected={repair} label="DEFINI UMA ROTA DE REPARO/RETOMADA SEM PUNIÇÃO" onPress={()=>setRepair(v=>!v)}/></>}<RuntimeChoice selected={safe} label="ESTOU SEGURO PARA ENCERRAR" onPress={()=>setSafe(v=>!v)}/><RuntimePrimary label="GROUNDING" disabled={!reviewReady||!safe} onPress={controller.nextPhase}/></RuntimeCard>:null}
 {phase==='grounding'?<RuntimeCard label="RETURN GATE" title="Voltar ao ambiente"><RuntimeCounter label="OBJETOS REAIS NOMEADOS" value={objects} onPress={()=>setObjects(v=>Math.min(5,v+1))}/><RuntimeChoice selected={orientation} label="ORIENTAÇÃO RESTAURADA" onPress={()=>setOrientation(v=>!v)}/><RuntimePrimary label="RETORNO CONFIRMADO" disabled={objects<3||!orientation} onPress={()=>{controller.setReturnConfirmed();controller.nextPhase();}}/></RuntimeCard>:null}
 {phase==='seal'?<RuntimeCard label="SELO SERVER-SIDE" title={meta.label}><RuntimePrimary label={controller.busy?'SELANDO…':`SELAR DIA ${day}`} disabled={controller.busy||!vault||!checksum||!reviewReady||!safe||!orientation} onPress={()=>void controller.seal({localRecordHash:checksum??undefined,evidence,metrics:{total_examples_count:total}}).then(controller.nextPhase).catch(e=>setError(e instanceof Error?e.message:`day${day}_seal_failed`))}/></RuntimeCard>:null}{phase==='complete'?<RuntimeCompletion completion={controller.runtime?.serverCompletion} label={meta.label}/>:null}</ScrollView>;
}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:'#0d0b07'},content:{padding:24,gap:18,paddingBottom:52},loading:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:'#0d0b07'},header:{gap:6},eyebrow:{color:'#b39a63',fontSize:8,letterSpacing:1.5},title:{color:'#f7f0df',fontSize:25,lineHeight:31,fontWeight:'300'},meta:{color:'#928267',fontSize:8,letterSpacing:.8},row:{gap:8,padding:12,borderWidth:1,borderColor:'#433921',borderRadius:10},rowTitle:{color:'#c0aa77',fontSize:9,letterSpacing:1.1}});
