import { useEffect, useState } from 'react';
import { ScrollView, StyleSheet, Text, View } from 'react-native';
import { loadCanonicalDay, type CanonicalDaySnapshot } from '../kether/canonical-day';
import { CanonicalText, RuntimeCard, RuntimeChoice, RuntimeCompletion, RuntimeCounter, RuntimeNotice, RuntimeOpenTimer, RuntimePrimary, runtimeTextStyles } from '../kether/KetherRuntimePrimitives';
import { useHnkDayRuntime } from '../kether/useHnkDayRuntime';
import { PAHALIAH_DAY_099 } from './runtime-definitions/pahaliah';

type MovementPath=1|2;
export function PahaliahDay099AssiahBodyExperience(){
 const controller=useHnkDayRuntime(PAHALIAH_DAY_099); const [canon,setCanon]=useState<CanonicalDaySnapshot|null>(null),[error,setError]=useState<string|null>(null); const [path,setPath]=useState<MovementPath|null>(null),[seconds,setSeconds]=useState(0),[preflight,setPreflight]=useState(false),[done,setDone]=useState(false),[effect,setEffect]=useState(false),[effectRecorded,setEffectRecorded]=useState(false),[noPain,setNoPain]=useState(false),[noExtreme,setNoExtreme]=useState(false),[noPunishment,setNoPunishment]=useState(false),[noXpRace,setNoXpRace]=useState(false),[limits,setLimits]=useState(false),[orientation,setOrientation]=useState(false),[safe,setSafe]=useState(false),[objects,setObjects]=useState(0);
 useEffect(()=>{let active=true;if(!controller.auth.client||controller.auth.phase!=='signed-in')return()=>{active=false;};void loadCanonicalDay(controller.auth.client,99).then(v=>{if(active)setCanon(v);}).catch(e=>{if(active)setError(e instanceof Error?e.message:'canonical_day_load_failed');});return()=>{active=false;};},[controller.auth.client,controller.auth.phase]); const phase=controller.phase?.id; const stop=()=>controller.interrupt({durationSeconds:seconds,evidence:{safety_stop:true},metrics:{practice_seconds:seconds,movement_path_code:path??0}});
 if(controller.loading)return <View style={s.loading}><Text style={s.meta}>ABRINDO PAHALIAH · DIA 099</Text></View>;
 return <ScrollView style={s.screen} contentContainerStyle={s.content}><View style={s.header}><Text style={s.eyebrow}>BINAH · PAHALIAH 1/5 · DIA 099</Text><Text style={s.title}>{canon?.title??'O TEMPLO DE ASSIAH'}</Text><Text style={s.meta}>{canon?`${canon.sourcePath} · ${canon.sourceSha.slice(0,10)} · +${canon.xp} XP`:'CÂNONE SINCRONIZANDO'}</Text></View>{controller.error||error?<RuntimeNotice title="RUNTIME">{error??controller.error}</RuntimeNotice>:null}{controller.runtime?.status==='locked'?<RuntimeCard label="GATE" title="Dia 099 bloqueado pela sequência"><Text style={runtimeTextStyles.body}>A primeira conclusão exige o Dia 098 confirmado no servidor.</Text></RuntimeCard>:null}
 {phase==='threshold'?<RuntimeCard label="PAHALIAH 1/5" title="Disciplina corporal sem punição"><CanonicalText>{canon?.blocks['jachin-kavanah']??''}</CanonicalText><RuntimeNotice title="ADAPTAÇÃO DE SEGURANÇA">A fonte menciona alongamento rígido; o runtime exige alongamento dentro do limite confortável. Corrida também só é usada quando o contexto é seguro. Dor, esforço extremo ou competição por XP nunca são meta.</RuntimeNotice><RuntimeChoice selected={path===1} label="ROTA 1 · ALONGAMENTO SEGURO E VOLUNTÁRIO" onPress={()=>setPath(1)}/><RuntimeChoice selected={path===2} label="ROTA 2 · CORRIDA DENTRO DO MEU LIMITE E CONTEXTO SEGURO" onPress={()=>setPath(2)}/><RuntimeChoice selected={preflight} label="FIZ PREFLIGHT DO CORPO, ESPAÇO E CONTEXTO" onPress={()=>setPreflight(v=>!v)}/><RuntimePrimary label="INICIAR" disabled={!canon||path===null||!preflight||controller.busy} onPress={()=>void controller.begin().then(controller.nextPhase)}/></RuntimeCard>:null}
 {phase==='practice'?<RuntimeCard label="MOVIMENTO" title="Tempo real, sem meta artificial"><RuntimeOpenTimer value={seconds} onChange={setSeconds}/><RuntimeNotice title="SEM DURAÇÃO INVENTADA">O cânone não fixa minutos. A prática termina quando o bloco escolhido foi feito com segurança, não quando um número arbitrário é atingido.</RuntimeNotice><RuntimeChoice selected={effectRecorded&&effect} label="PERCEBI ALGUMA MUDANÇA CORPORAL/ATENCIONAL" onPress={()=>{setEffect(true);setEffectRecorded(true);}}/><RuntimeChoice selected={effectRecorded&&!effect} label="NÃO PERCEBI MUDANÇA MARCANTE" onPress={()=>{setEffect(false);setEffectRecorded(true);}}/><RuntimeChoice selected={done} label="CONCLUÍ O BLOCO SEM FORÇAR O CORPO" onPress={()=>setDone(v=>!v)}/><RuntimePrimary label="SAFETY STOP" onPress={stop}/><RuntimePrimary label="REVISAR" disabled={seconds<1||!effectRecorded||!done} onPress={controller.nextPhase}/></RuntimeCard>:null}
 {phase==='review'?<RuntimeCard label="REVISÃO" title="Constância não é sofrimento"><RuntimeChoice selected={noPain} label="DOR NÃO FOI META NEM PROVA DE VONTADE" onPress={()=>setNoPain(v=>!v)}/><RuntimeChoice selected={noExtreme} label="EVITEI ESFORÇO EXTREMO" onPress={()=>setNoExtreme(v=>!v)}/><RuntimeChoice selected={noPunishment} label="NÃO USEI O CORPO COMO PUNIÇÃO" onPress={()=>setNoPunishment(v=>!v)}/><RuntimeChoice selected={noXpRace} label="NÃO COMPETI POR INTENSIDADE/XP" onPress={()=>setNoXpRace(v=>!v)}/><RuntimeChoice selected={limits} label="RESPEITEI LIMITES DO CORPO E DO CONTEXTO" onPress={()=>setLimits(v=>!v)}/><RuntimeChoice selected={safe} label="ESTOU SEGURO PARA ENCERRAR" onPress={()=>setSafe(v=>!v)}/><RuntimePrimary label="GROUNDING" disabled={!noPain||!noExtreme||!noPunishment||!noXpRace||!limits||!safe} onPress={controller.nextPhase}/></RuntimeCard>:null}
 {phase==='grounding'?<RuntimeCard label="RETURN GATE" title="Corpo e ambiente"><RuntimeCounter label="OBJETOS REAIS NOMEADOS" value={objects} onPress={()=>setObjects(v=>Math.min(5,v+1))}/><RuntimeChoice selected={orientation} label="ORIENTAÇÃO RESTAURADA" onPress={()=>setOrientation(v=>!v)}/><RuntimePrimary label="RETORNO CONFIRMADO" disabled={objects<3||!orientation} onPress={()=>{controller.setReturnConfirmed();controller.nextPhase();}}/></RuntimeCard>:null}
 {phase==='seal'?<RuntimeCard label="SELO SERVER-SIDE" title="Pahaliah 1/5"><RuntimePrimary label={controller.busy?'SELANDO…':'SELAR DIA 099'} disabled={controller.busy||path===null||!done||!noPain||!noExtreme||!noPunishment||!noXpRace||!limits||!orientation||!safe} onPress={()=>void controller.seal({durationSeconds:seconds,evidence:{protocol_completed:true,return_confirmed:true,safe_preflight_completed:preflight,movement_completed:done,pain_not_goal:noPain,extreme_effort_avoided:noExtreme,corporal_punishment_avoided:noPunishment,xp_competition_avoided:noXpRace,body_limits_respected:limits,orientation_restored:orientation,safety_clear:safe,movement_path_code:path??0,effect_present:effect,practice_seconds:seconds},metrics:{practice_seconds:seconds,movement_path_code:path??0}}).then(controller.nextPhase).catch(e=>setError(e instanceof Error?e.message:'day099_seal_failed'))}/></RuntimeCard>:null}{phase==='complete'?<RuntimeCompletion completion={controller.runtime?.serverCompletion} label="PAHALIAH 1/5"/>:null}</ScrollView>;
}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:'#0d0b07'},content:{padding:24,gap:18,paddingBottom:52},loading:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:'#0d0b07'},header:{gap:6},eyebrow:{color:'#b39a63',fontSize:8,letterSpacing:1.5},title:{color:'#f7f0df',fontSize:25,lineHeight:31,fontWeight:'300'},meta:{color:'#928267',fontSize:8,letterSpacing:.8}});
