import { useEffect, useState } from 'react';
import { ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { saveEncryptedVaultEntry } from '@hnk/supabase-client';
import { encryptVaultText } from '../vault/vault-crypto';
import { loadCanonicalDay, type CanonicalDaySnapshot } from '../kether/canonical-day';
import { CanonicalText, RuntimeCard, RuntimeChoice, RuntimeCompletion, RuntimeCounter, RuntimeNotice, RuntimePrimary, runtimeTextStyles } from '../kether/KetherRuntimePrimitives';
import { useHnkDayRuntime } from '../kether/useHnkDayRuntime';
import { PAHALIAH_DAY_102 } from './runtime-definitions/pahaliah';

type Decision=1|2|3;
export function PahaliahDay102FatigueExperience(){
 const controller=useHnkDayRuntime(PAHALIAH_DAY_102); const [canon,setCanon]=useState<CanonicalDaySnapshot|null>(null),[error,setError]=useState<string|null>(null),[claim,setClaim]=useState(''),[domain,setDomain]=useState(''),[evidenceText,setEvidenceText]=useState(''),[context,setContext]=useState(''),[decision,setDecision]=useState<Decision|null>(null),[vault,setVault]=useState(false),[checksum,setChecksum]=useState<string|null>(null),[physical,setPhysical]=useState(false),[realExhaustion,setRealExhaustion]=useState(false),[symptoms,setSymptoms]=useState(false),[noForce,setNoForce]=useState(false),[noDiagnosis,setNoDiagnosis]=useState(false),[decisionContext,setDecisionContext]=useState(false),[orientation,setOrientation]=useState(false),[safe,setSafe]=useState(false),[objects,setObjects]=useState(0);
 useEffect(()=>{let active=true;if(!controller.auth.client||controller.auth.phase!=='signed-in')return()=>{active=false;};void loadCanonicalDay(controller.auth.client,102).then(v=>{if(active)setCanon(v);}).catch(e=>{if(active)setError(e instanceof Error?e.message:'canonical_day_load_failed');});return()=>{active=false;};},[controller.auth.client,controller.auth.phase]); const phase=controller.phase?.id; const textReady=[claim,domain,evidenceText,context].every(v=>v.trim().length>1);
 const save=async()=>{if(!controller.auth.client||!controller.auth.userId||!textReady)return;try{const enc=await encryptVaultText({userId:controller.auth.userId,day:102,kind:'pahaliah-day102-fatigue-context',plaintext:JSON.stringify({schema:'hnk-pahaliah-day102-v1',claim:claim.trim(),specific_tired_domain:domain.trim(),evidence:evidenceText.trim(),context:context.trim()})});await saveEncryptedVaultEntry(controller.auth.client,{day:102,payload:enc});setChecksum(enc.checksumSha256);setVault(true);controller.nextPhase();}catch(e){setError(e instanceof Error?e.message:'day102_vault_failed');}};
 if(controller.loading)return <View style={s.loading}><Text style={s.meta}>ABRINDO PAHALIAH · DIA 102</Text></View>; return <ScrollView style={s.screen} contentContainerStyle={s.content}><View style={s.header}><Text style={s.eyebrow}>BINAH · PAHALIAH 4/5 · DIA 102</Text><Text style={s.title}>{canon?.title??'QUEBRANDO A PRESSUPOSIÇÃO DE CANSAÇO'}</Text><Text style={s.meta}>{canon?`${canon.sourcePath} · ${canon.sourceSha.slice(0,10)} · +${canon.xp} XP`:'CÂNONE SINCRONIZANDO'}</Text></View>{controller.error||error?<RuntimeNotice title="RUNTIME">{error??controller.error}</RuntimeNotice>:null}{controller.runtime?.status==='locked'?<RuntimeCard label="GATE" title="Dia 102 bloqueado pela sequência"><Text style={runtimeTextStyles.body}>A primeira conclusão exige o Dia 101 confirmado no servidor.</Text></RuntimeCard>:null}
 {phase==='threshold'?<RuntimeCard label="PAHALIAH 4/5" title="Precisar o cansaço sem negar o corpo"><CanonicalText>{canon?.blocks['jachin-kavanah']??''}</CanonicalText><RuntimeNotice title="DESCANSAR É UMA DECISÃO VÁLIDA">O método pergunta “o que especificamente está cansado?” para aumentar precisão. Ele nunca manda ignorar exaustão, sono, dor, doença ou mal-estar.</RuntimeNotice><RuntimePrimary label="INICIAR" disabled={!canon||controller.busy} onPress={()=>void controller.begin().then(controller.nextPhase)}/></RuntimeCard>:null}
 {phase==='vault'?<RuntimeCard label="VAULT" title="Cansaço · evidência · contexto"><TextInput value={claim} onChangeText={setClaim} placeholder="Frase atual — ex.: estou exausto demais para praticar" placeholderTextColor="#746b56" style={runtimeTextStyles.input}/><TextInput value={domain} onChangeText={setDomain} placeholder="O que especificamente está cansado? Corpo, atenção, sono, emoção, outro…" placeholderTextColor="#746b56" style={runtimeTextStyles.input}/><TextInput value={evidenceText} onChangeText={setEvidenceText} placeholder="Que evidência concreta sustenta isso agora?" placeholderTextColor="#746b56" style={runtimeTextStyles.input}/><TextInput value={context} onChangeText={setContext} placeholder="Contexto relevante sem autodiagnóstico" placeholderTextColor="#746b56" style={runtimeTextStyles.input}/><RuntimePrimary label="SAFETY STOP" onPress={()=>controller.interrupt({evidence:{safety_stop:true}})}/><RuntimePrimary label="CIFRAR E CONTINUAR" disabled={!textReady} onPress={()=>void save()}/></RuntimeCard>:null}
 {phase==='decision'?<RuntimeCard label="DECISÃO" title="Praticar, adaptar ou descansar"><RuntimeChoice selected={physical} label="SINAIS FÍSICOS REAIS TÊM PRIORIDADE SOBRE PRESSÃO DE COMPLETAR" onPress={()=>setPhysical(v=>!v)}/><RuntimeChoice selected={realExhaustion} label="EXAUSTÃO REAL PODE JUSTIFICAR PAUSA/DESCANSO" onPress={()=>setRealExhaustion(v=>!v)}/><RuntimeChoice selected={symptoms} label="SONO, DOR, DOENÇA OU MAL-ESTAR NÃO SERÃO IGNORADOS" onPress={()=>setSymptoms(v=>!v)}/><RuntimeChoice selected={noForce} label="A PRÁTICA NÃO SERÁ FORÇADA" onPress={()=>setNoForce(v=>!v)}/><RuntimeChoice selected={noDiagnosis} label="NÃO USEI O APP PARA PRODUZIR DIAGNÓSTICO" onPress={()=>setNoDiagnosis(v=>!v)}/><RuntimeNotice title="TRÊS SAÍDAS IGUALMENTE VÁLIDAS">Escolha o que o melhor dado disponível permite hoje. Nenhuma opção recebe XP extra.</RuntimeNotice><RuntimeChoice selected={decision===1} label="1 · PRATICAR AGORA, DENTRO DOS LIMITES" onPress={()=>setDecision(1)}/><RuntimeChoice selected={decision===2} label="2 · ADAPTAR A PRÁTICA DE FORMA SEGURA" onPress={()=>setDecision(2)}/><RuntimeChoice selected={decision===3} label="3 · DESCANSAR / ADIAR LEGITIMAMENTE" onPress={()=>setDecision(3)}/><RuntimeChoice selected={decisionContext} label="REGISTREI A DECISÃO PELO CONTEXTO, NÃO POR CULPA OU HEROÍSMO" onPress={()=>setDecisionContext(v=>!v)}/><RuntimeChoice selected={safe} label="ESTOU SEGURO PARA ENCERRAR ESTA DECISÃO" onPress={()=>setSafe(v=>!v)}/><RuntimePrimary label="GROUNDING" disabled={decision===null||!physical||!realExhaustion||!symptoms||!noForce||!noDiagnosis||!decisionContext||!safe} onPress={controller.nextPhase}/></RuntimeCard>:null}
 {phase==='grounding'?<RuntimeCard label="RETURN GATE" title="Decisão proporcional, corpo respeitado"><RuntimeCounter label="OBJETOS REAIS NOMEADOS" value={objects} onPress={()=>setObjects(v=>Math.min(5,v+1))}/><RuntimeChoice selected={orientation} label="ORIENTAÇÃO RESTAURADA" onPress={()=>setOrientation(v=>!v)}/><RuntimePrimary label="RETORNO CONFIRMADO" disabled={objects<3||!orientation} onPress={()=>{controller.setReturnConfirmed();controller.nextPhase();}}/></RuntimeCard>:null}
 {phase==='seal'?<RuntimeCard label="SELO SERVER-SIDE" title="Pahaliah 4/5"><RuntimePrimary label={controller.busy?'SELANDO…':'SELAR DIA 102'} disabled={controller.busy||!vault||!checksum||decision===null||!physical||!realExhaustion||!symptoms||!noForce||!noDiagnosis||!decisionContext||!orientation||!safe} onPress={()=>void controller.seal({localRecordHash:checksum??undefined,evidence:{protocol_completed:true,return_confirmed:true,fatigue_claim_recorded:true,specific_tired_domain_recorded:true,evidence_reviewed:true,physical_signals_respected:physical,real_exhaustion_allowed:realExhaustion,sleep_pain_illness_malaise_respected:symptoms,practice_not_forced:noForce,diagnosis_not_claimed:noDiagnosis,decision_context_recorded:decisionContext,vault_saved:vault,orientation_restored:orientation,safety_clear:safe,decision_code:decision??0},metrics:{decision_code:decision??0}}).then(controller.nextPhase).catch(e=>setError(e instanceof Error?e.message:'day102_seal_failed'))}/></RuntimeCard>:null}{phase==='complete'?<RuntimeCompletion completion={controller.runtime?.serverCompletion} label="PAHALIAH 4/5"/>:null}</ScrollView>;
}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:'#0d0b07'},content:{padding:24,gap:18,paddingBottom:52},loading:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:'#0d0b07'},header:{gap:6},eyebrow:{color:'#b39a63',fontSize:8,letterSpacing:1.5},title:{color:'#f7f0df',fontSize:25,lineHeight:31,fontWeight:'300'},meta:{color:'#928267',fontSize:8,letterSpacing:.8}});
