'use client';
import {useEffect,useMemo,useRef,useState,type CSSProperties} from 'react';
import {ExperienceDirector,QuestRuntime,createQuestCatalog,type ExperienceDirective,type PlayerContext,type SessionSnapshot} from '@hnk/quest-engine';
import {createBundledQuestLibrary,type RuntimeQuestBundle} from '@hnk/quest-library';
import {assertSitaelProgress,loadDay014PracticeSessionV1,sealDay014V1,startDay014PracticeSessionV1} from '@hnk/supabase-client';
import {createWebQuestSnapshotStore} from '../_runtime/quest-snapshot-store';
import {createWebVaultTextPort} from '../_runtime/WebVaultTextPort';
import {useWebHnkRuntime} from '../_runtime/WebHnkRuntime';

type Session=NonNullable<Awaited<ReturnType<typeof loadDay014PracticeSessionV1>>>;
type Seal=Extract<Awaited<ReturnType<typeof sealDay014V1>>,{ok:true}>['response'];
type Block='jachin_visualization'|'boaz_visualization'|'middle_visualization';
interface Draft{jachinDone:boolean;jachinDistractions:number;jachinMaxStability:number;jachinReturned:boolean;jachinRef:string|null;boazDone:boolean;boazReturns:number;boazChanges:number;boazRelaxed:boolean;boazNoPunishment:boolean;boazBoundary:boolean;boazRef:string|null;middleDone:boolean;prayer:boolean;attentionScore:number;imageDismissed:boolean;threeObjects:boolean;distinguished:boolean;middleRef:string|null;soulRef:string|null;safetyStopped:boolean}
const emptyDraft:Draft={jachinDone:false,jachinDistractions:0,jachinMaxStability:0,jachinReturned:false,jachinRef:null,boazDone:false,boazReturns:0,boazChanges:0,boazRelaxed:false,boazNoPunishment:false,boazBoundary:false,boazRef:null,middleDone:false,prayer:false,attentionScore:5,imageDismissed:false,threeObjects:false,distinguished:false,middleRef:null,soulRef:null,safetyStopped:false};
function canon(bundle:RuntimeQuestBundle,d:ExperienceDirective){return(d.phase.source.block_ids??[]).map(id=>{const b=bundle.canon.blocks.find(x=>x.id===id);if(!b)throw new Error(`canonical_block_missing:${id}`);return b.text})}
function keys(userId:string){return{snapshot:`hnk:quest:d014:${userId}:snapshot:v1`,session:`hnk:quest:d014:${userId}:session:v1`,cache:`hnk:quest:d014:${userId}:session-cache:v1`,draft:`hnk:quest:d014:${userId}:draft:v1`}}
function parse<T>(key:string):T|null{try{const raw=localStorage.getItem(key);return raw?JSON.parse(raw) as T:null}catch{return null}}
function clientId(u:string){return`hnk-web-d014-v1-${u}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`}
function clock(v:number){const s=Math.max(0,300-v);return`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}

export function Day014GoldenV1Web(){
 const auth=useWebHnkRuntime();const live=Boolean(auth.configured&&auth.phase==='signed-in'&&auth.client&&auth.userId);const runtimeRef=useRef<QuestRuntime|null>(null);
 const[bundle,setBundle]=useState<RuntimeQuestBundle|null>(null);const[snapshot,setSnapshot]=useState<SessionSnapshot|null>(null);const[session,setSession]=useState<Session|null>(null);const[draft,setDraft]=useState<Draft>(emptyDraft);const[loaded,setLoaded]=useState(false);
 const[active,setActive]=useState<Block|null>(null);const[started,setStarted]=useState<number|null>(null);const[now,setNow]=useState(Date.now());const[jachinNote,setJachinNote]=useState('');const[boazNote,setBoazNote]=useState('');const[middleNote,setMiddleNote]=useState('');const[soulNote,setSoulNote]=useState('');const[voluntary,setVoluntary]=useState(false);const[busy,setBusy]=useState(false);const[error,setError]=useState<string|null>(null);const[sealed,setSealed]=useState<Seal|null>(null);
 const context=useMemo<PlayerContext>(()=>({mediationMode:'HNK_CANONICAL',accessibility:{reducedMotion:typeof window!=='undefined'&&matchMedia?.('(prefers-reduced-motion: reduce)').matches===true,audioEnabled:false,microphoneAvailable:false},offline:!live}),[live]);
 const vault=useMemo(()=>auth.userId?createWebVaultTextPort(auth.client??null):null,[auth.client,auth.userId]);
 useEffect(()=>{if(!auth.userId)return;let ok=true;const lib=createBundledQuestLibrary();const cat=createQuestCatalog(lib);const store=createWebQuestSnapshotStore();const k=keys(auth.userId);void Promise.all([cat.requireDay(14),lib.loadBundle(14),store.load(k.snapshot)]).then(([def,b,saved])=>{if(!ok||!b)return;const r=new QuestRuntime(def);runtimeRef.current=r;setBundle(b);setSnapshot(saved?r.restore(saved):r.start());setDraft(parse<Draft>(k.draft)??emptyDraft);const c=parse<Session>(k.cache);if(c)setSession(c);setLoaded(true)}).catch(e=>ok&&setError(e instanceof Error?e.message:'day014_load_failed'));return()=>{ok=false}},[auth.userId]);
 useEffect(()=>{if(!auth.userId||!snapshot)return;const k=keys(auth.userId),store=createWebQuestSnapshotStore();if(snapshot.runState==='COMPLETE'){void store.remove(k.snapshot);localStorage.removeItem(k.draft);localStorage.removeItem(k.session);localStorage.removeItem(k.cache)}else void store.save(k.snapshot,snapshot)},[auth.userId,snapshot]);
 useEffect(()=>{if(auth.userId&&loaded&&snapshot?.runState!=='COMPLETE')localStorage.setItem(keys(auth.userId).draft,JSON.stringify(draft))},[auth.userId,draft,loaded,snapshot?.runState]);
 useEffect(()=>{if(!live||!auth.client||!auth.userId)return;const k=keys(auth.userId),id=localStorage.getItem(k.session);if(!id)return;void loadDay014PracticeSessionV1(auth.client,id).then(s=>{if(s){setSession(s);localStorage.setItem(k.cache,JSON.stringify(s))}}).catch(()=>undefined)},[auth.client,auth.userId,live]);
 useEffect(()=>{const i=window.setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(i)},[]);
 useEffect(()=>{const f=()=>{if(document.visibilityState!=='visible'&&started){setStarted(null);setActive(null);setError('bloco_interrompido_ao_sair_da_tela__reinicie_os_5_minutos')}};document.addEventListener('visibilitychange',f);return()=>document.removeEventListener('visibilitychange',f)},[started]);
 const director=useMemo(()=>bundle?new ExperienceDirector(bundle.quest):null,[bundle]);const directive=useMemo(()=>director&&snapshot?.currentPhaseId?director.resolvePhase(snapshot.currentPhaseId,context,snapshot):null,[director,context,snapshot]);const elapsed=started?Math.min(300,Math.floor((now-started)/1000)):0;
 async function ensureSession(){if(session)return session;if(!live||!auth.client||!auth.userId)throw new Error('online_session_required_before_day014_practice');const s=await startDay014PracticeSessionV1(auth.client,{clientSessionId:clientId(auth.userId),appVersion:'0.1.0-web-day014-golden-v1'});setSession(s);const k=keys(auth.userId);localStorage.setItem(k.session,s.id);localStorage.setItem(k.cache,JSON.stringify(s));return s}
 async function complete(id:string){setError(null);try{if(id==='jachin_reading')await ensureSession();const r=runtimeRef.current;if(r)setSnapshot(r.completePhase(id))}catch(e){setError(e instanceof Error?e.message:'phase_failed')}}
 function startBlock(b:Block){setError(null);setActive(b);setStarted(Date.now());setNow(Date.now())}
 function finishBlock(b:Block){if(active!==b||!started||Math.floor((Date.now()-started)/1000)<300){setError('complete_5_minutes_before_advancing');return}setDraft(d=>b==='jachin_visualization'?{...d,jachinDone:true}:b==='boaz_visualization'?{...d,boazDone:true}:{...d,middleDone:true});setActive(null);setStarted(null)}
 function safetyStop(){setActive(null);setStarted(null);setDraft(d=>({...d,safetyStopped:true}));setError('safety_stop__descanse_e_reoriente_no_ambiente');if(runtimeRef.current)setSnapshot(runtimeRef.current.safetyStop())}
 function resume(){setError(null);if(runtimeRef.current)setSnapshot(runtimeRef.current.resume())}
 async function saveJachin(){if(!vault||!auth.userId||!draft.jachinDone||!draft.jachinReturned||!jachinNote.trim())throw new Error('jachin_evidence_required');const e=await vault.saveText({userId:auth.userId,day:14,kind:'journal',plaintext:JSON.stringify({schema:'hnk-day014-jachin-v1',returnStrategy:jachinNote.trim()})});setDraft(d=>({...d,jachinRef:e.entryId}));setJachinNote('');await complete('jachin_visualization')}
 async function saveBoaz(){if(!vault||!auth.userId||!draft.boazDone||!draft.boazRelaxed||!draft.boazNoPunishment||!draft.boazBoundary||!boazNote.trim())throw new Error('boaz_evidence_required');const e=await vault.saveText({userId:auth.userId,day:14,kind:'journal',plaintext:JSON.stringify({schema:'hnk-day014-boaz-v1',persistentDistraction:boazNote.trim()})});setDraft(d=>({...d,boazRef:e.entryId}));setBoazNote('');await complete('boaz_visualization')}
 async function saveMiddle(){if(!vault||!auth.userId||!draft.middleDone||!draft.prayer||!draft.imageDismissed||!draft.threeObjects||!draft.distinguished||!middleNote.trim())throw new Error('middle_grounding_required');const e=await vault.saveText({userId:auth.userId,day:14,kind:'journal',plaintext:JSON.stringify({schema:'hnk-day014-middle-v1',finalNote:middleNote.trim(),attentionScore:draft.attentionScore})});setDraft(d=>({...d,middleRef:e.entryId}));setMiddleNote('');await complete('middle_visualization')}
 async function saveSoul(){if(!vault||!auth.userId||!soulNote.trim())throw new Error('soul_mirror_required');const e=await vault.saveText({userId:auth.userId,day:14,kind:'journal',plaintext:JSON.stringify({schema:'hnk-day014-soul-v1',stabilityChangeReturn:soulNote.trim()})});setDraft(d=>({...d,soulRef:e.entryId}));setSoulNote('');await complete('soul_mirror')}
 async function seal(){if(!runtimeRef.current||!live||!auth.client||!auth.userId||!session||!vault||!draft.jachinRef||!draft.boazRef||!draft.middleRef||!draft.soulRef||!voluntary)return;setBusy(true);setError(null);try{await vault.flushPending(auth.userId);const jr=await vault.resolveEntryId(auth.userId,draft.jachinRef),br=await vault.resolveEntryId(auth.userId,draft.boazRef),mr=await vault.resolveEntryId(auth.userId,draft.middleRef),sr=await vault.resolveEntryId(auth.userId,draft.soulRef);if(!jr||!br||!mr||!sr)throw new Error('vault_sync_required_before_completion');const result=await sealDay014V1(auth.client,{evidence:{sessionId:session.id,mode:'first_completion',jachinDurationSeconds:300,jachinDistractionCount:draft.jachinDistractions,jachinMaxStabilitySeconds:draft.jachinMaxStability,jachinReturnedWithoutIrritationConfirmed:draft.jachinReturned,jachinReturnStrategyVaultEntryRef:jr,boazDurationSeconds:300,boazReturnCount:draft.boazReturns,boazSpontaneousChangeCount:draft.boazChanges,boazRelaxedBodyConfirmed:draft.boazRelaxed,boazNoPunishmentConfirmed:draft.boazNoPunishment,boazSpontaneousChangeNotAutomaticRevelationConfirmed:draft.boazBoundary,boazPersistentDistractionVaultEntryRef:br,middleDurationSeconds:300,psalm912PrayerConfirmed:draft.prayer,attentionStabilityScore:draft.attentionScore,imageDismissedVoluntarily:draft.imageDismissed,threeRealObjectsObserved:draft.threeObjects,imaginePerceiveInterpretDistinguished:draft.distinguished,middleFinalVaultEntryRef:mr,soulMirrorCompleted:true,stabilityChangeReturnVaultEntryRef:sr,safetyStopOccurred:draft.safetyStopped},totalDurationSeconds:Math.max(900,Math.floor((Date.now()-new Date(session.started_at).getTime())/1000))});if(!result.ok)throw new Error(result.code);assertSitaelProgress(result.response.crown,4);setSealed(result.response);setSnapshot(runtimeRef.current.confirmServerCompletion())}catch(e){setError(e instanceof Error?e.message:'day014_completion_failed')}finally{setBusy(false)}}
 const shell:CSSProperties={maxWidth:860,margin:'0 auto',padding:'28px 20px 80px',background:'#090910',color:'#eee7d7',minHeight:'100vh',fontFamily:'system-ui'};const panel:CSSProperties={border:'1px solid #456f9b',borderRadius:18,padding:22,display:'grid',gap:14,background:'#111018'};
 if(!auth.userId)return <main style={shell}>ENTRE NO ÁTRIO PARA INICIAR O DIA 014.</main>;if(!bundle||!snapshot||!director)return <main style={shell}>CARREGANDO DAY 014…{error?<p>{error}</p>:null}</main>;if(snapshot.runState==='SAFETY_STOP')return <main style={shell}><h1>Prática interrompida.</h1><p>Abra os olhos, observe o ambiente real e retome somente quando estiver confortável.</p><button onClick={resume}>RETOMAR</button></main>;if(snapshot.runState==='COMPLETE')return <main style={shell}><small>DIA 014 · SITAEL 4/5</small><h1>CONCENTRAÇÃO UNIDIRECIONAL CONCLUÍDA</h1><p>{sealed?.first_completion?`+${sealed.xp_awarded} XP canônicos.`:'Revisita sem novo XP.'}</p><p>Sitael 4/5 confirmado pelo servidor · fragmento III ainda apagado · Coroa {sealed?.crown.fragments_lit??2}/7.</p><p>0 ganho de atributo: não existe regra congelada para Day 014.</p></main>;if(!directive)return <main style={shell}>FASE INDISPONÍVEL.</main>;
 const p=directive.phase,texts=directive.requiresCanonicalContent?canon(bundle,directive):[],block=p.id as Block;const isBlock=['jachin_visualization','boaz_visualization','middle_visualization'].includes(p.id);const done=block==='jachin_visualization'?draft.jachinDone:block==='boaz_visualization'?draft.boazDone:draft.middleDone;
 return <main style={shell}><header><small>DIA 014 · KETHER · SITAEL 4/5</small><h1>CONCENTRAÇÃO UNIDIRECIONAL</h1><p>CÍRCULO AZUL · {live?'VAULT E2EE ONLINE':'FILA CIFRADA OFFLINE'}</p></header>{error?<p style={{color:'#ffb4ab'}}>{error}</p>:null}<section style={panel}><small>{p.type} · {p.id}</small>{p.type==='NARRATIVE'?<><h2>Um símbolo como alvo, não como autoridade.</h2><p>O círculo azul é um objeto mental de treino. Mudanças espontâneas são experiência interna, não revelação automática.</p></>:null}{p.type==='READ'?texts.map((t,i)=><p key={i} style={{lineHeight:1.75}}>{t}</p>):null}{isBlock?<><div style={{fontSize:34}}>{done?'00:00':clock(active===block?elapsed:0)}</div>{done?<strong>5 MINUTOS CONCLUÍDOS ✓</strong>:active===block?<button disabled={elapsed<300} onClick={()=>finishBlock(block)}>{elapsed>=300?'CONFIRMAR 5 MINUTOS':'MANTER FOCO'}</button>:<button onClick={()=>startBlock(block)}>INICIAR 5 MINUTOS</button>}<button onClick={safetyStop}>INTERROMPER COM SEGURANÇA</button></>:null}
 {p.id==='jachin_visualization'?<><label>Distrações <input type="number" min={0} value={draft.jachinDistractions} onChange={e=>setDraft(d=>({...d,jachinDistractions:Number(e.target.value)}))}/></label><label>Maior estabilidade contínua em segundos (0–300) <input type="number" min={0} max={300} value={draft.jachinMaxStability} onChange={e=>setDraft(d=>({...d,jachinMaxStability:Number(e.target.value)}))}/></label><label><input type="checkbox" checked={draft.jachinReturned} onChange={e=>setDraft(d=>({...d,jachinReturned:e.target.checked}))}/> Retornei sem irritação.</label><textarea value={jachinNote} onChange={e=>setJachinNote(e.target.value)} placeholder="O que ajudou no retorno — será cifrado"/><button onClick={()=>void saveJachin()}>CIFRAR · AVANÇAR</button></>:null}
 {p.id==='boaz_visualization'?<><label>Retornos <input type="number" min={0} value={draft.boazReturns} onChange={e=>setDraft(d=>({...d,boazReturns:Number(e.target.value)}))}/></label><label>Mudanças espontâneas <input type="number" min={0} value={draft.boazChanges} onChange={e=>setDraft(d=>({...d,boazChanges:Number(e.target.value)}))}/></label><label><input type="checkbox" checked={draft.boazRelaxed} onChange={e=>setDraft(d=>({...d,boazRelaxed:e.target.checked}))}/> Mantive o corpo relaxado.</label><label><input type="checkbox" checked={draft.boazNoPunishment} onChange={e=>setDraft(d=>({...d,boazNoPunishment:e.target.checked}))}/> Não usei distração como punição.</label><label><input type="checkbox" checked={draft.boazBoundary} onChange={e=>setDraft(d=>({...d,boazBoundary:e.target.checked}))}/> Mudanças espontâneas da imagem não são revelação automática.</label><textarea value={boazNote} onChange={e=>setBoazNote(e.target.value)} placeholder="Distração persistente — será cifrada"/><button onClick={()=>void saveBoaz()}>CIFRAR · AVANÇAR</button></>:null}
 {p.id==='middle_visualization'?<><label><input type="checkbox" checked={draft.prayer} onChange={e=>setDraft(d=>({...d,prayer:e.target.checked}))}/> Recordei o Salmo 91:2 dirigindo confiança a Deus.</label><label>Estabilidade {draft.attentionScore}/10 <input type="range" min={0} max={10} step={1} value={draft.attentionScore} onChange={e=>setDraft(d=>({...d,attentionScore:Number(e.target.value)}))}/></label><label><input type="checkbox" checked={draft.imageDismissed} onChange={e=>setDraft(d=>({...d,imageDismissed:e.target.checked}))}/> Deixei a imagem desaparecer voluntariamente.</label><label><input type="checkbox" checked={draft.threeObjects} onChange={e=>setDraft(d=>({...d,threeObjects:e.target.checked}))}/> Abri os olhos e observei três objetos reais.</label><label><input type="checkbox" checked={draft.distinguished} onChange={e=>setDraft(d=>({...d,distinguished:e.target.checked}))}/> Distingui imaginar, perceber e interpretar.</label><textarea value={middleNote} onChange={e=>setMiddleNote(e.target.value)} placeholder="Foco, distração e retorno — será cifrado"/><button onClick={()=>void saveMiddle()}>CIFRAR · AVANÇAR</button></>:null}
 {p.id==='soul_mirror'?<><textarea value={soulNote} onChange={e=>setSoulNote(e.target.value)} placeholder="O que se manteve, mudou e como retornou — Vault E2EE"/><button onClick={()=>void saveSoul()}>CIFRAR ESPELHO · AVANÇAR</button></>:null}
 {p.id==='completion'?<><label><input type="checkbox" checked={voluntary} onChange={e=>setVoluntary(e.target.checked)}/> Confirmo voluntariamente a conclusão.</label><p>Somente o servidor concede +100 XP e confirma Sitael 4/5.</p><button disabled={!voluntary||busy||!live} onClick={()=>void seal()}>{busy?'SELANDO…':'SINCRONIZAR · SELAR DAY 014'}</button></>:null}
 {p.id==='sitael_progress'?<button onClick={()=>void complete(p.id)}>CONFIRMAR PROGRESSO</button>:null}{!['jachin_visualization','boaz_visualization','middle_visualization','soul_mirror','completion','sitael_progress'].includes(p.id)?<button onClick={()=>void complete(p.id)}>CONTINUAR</button>:null}</section></main>
}
