export const DAY001_CANON_SOURCE_SHA = 'a01d13b43cbddb92236fc1e3b6c2a7e140d87d29' as const;

/**
 * Runtime projection of the immutable Day 001 counted core.
 * Source: docs/experience/kether/day-001/day-001.canon-blocks.json
 * Do not edit prose here without updating the canonical manifest/source SHA.
 */
export const DAY001_CANON = Object.freeze({
  jachinDoctrine: 'No primeiro dia da sua travessia, você depara-se com o abismo silencioso de Kether, a Coroa inacessível onde a existência repousa antes de qualquer forma. Aqui não há pensamentos, conceitos ou imagens; existe apenas a pulsação pura da Vida Zoe, o sopro divino incriado que sustenta a realidade inteira. O Louco ergue o seu bastão à beira do precipício, convidando-o a dar o salto de fé em direção ao absoluto esvaziamento da mente lógica. Para que a luz perpétua possa preencher o seu templo, a sua Psuche deve render-se de forma voluntária ao silêncio. Esqueça tudo o que aprendeu; apague as definições mundanas e as amarras intelectuais que limitam a sua percepção espiritual. Hoje, sintonizamos o símbolo mestre Dai Koo Myo, abrindo todos os canais sutis para receber a torrente ilimitada do Espírito Santo na terra sagrada.',
  jachinKavanah: 'Sente-se em postura ereta, respirando de forma profunda e pausada. Feche os olhos e visualize o símbolo Dai Koo Myo brilhando em ouro incandescente no topo da sua cabeça. Sinta a luz fluir para baixo, inundando o seu cérebro e silenciando o fluxo de palavras. Mantenha o foco fixo nesse ponto de luz por dez minutos, permitindo que a sua consciência se expanda até fundir-se com o vazio primordial divino e eterno.',
  jachinOrdalia: 'Abra o aplicativo HNK, escaneie o código do dia e ative o som solfeggio de 528Hz para selar a sua sintonia espiritual no banco de dados.',
  boazDoctrine: 'A descida da força exige um vaso purificado e estruturado sob as leis do Rigor. No pilar de Boaz, compreendemos que a mente racional é o guardião cioso que impede o livre fluxo da verdade interior. O Fator Crítico ergue barreiras lógicas para proteger o ego decaído, mantendo-o preso aos condicionamentos mundanos da carne. Para desarmar essa fortaleza sem gerar conflito biológico, aplicamos o método de auto-hipnose de Dave Elman, provocando a fadiga pálpebral e o relaxamento muscular profundo. Esta restrição voluntária desliga a tagarelice da Psuche e prepara o terreno biológico para o descanso onírico consciente. O silêncio físico é o selo que protege a sua bioenergia das larvas e dispersões do cotidiano. Guarde a sua mente com severidade, eliminando todas as distrações, dúvidas, medos e ruídos desnecessários que tentarem invadir o seu próprio templo sagrado.',
  boazKavanah: 'Deite-se confortavelmente em um quarto totalmente escuro e silencioso. Force o relaxamento completo dos músculos ao redor dos seus olhos, certificando-se de que é impossível abrir as pálpebras de forma voluntária. Transfira essa sensação de paralisia muscular para o resto do corpo, descendo em transe profundo por cinco minutos. Ao final, determine mentalmente que todos os seus sonhos desta noite serão recordados com nitidez absoluta no seu próprio diário de bordo pessoal.',
  boazOrdalia: 'Escreva agora no seu diário de bordo digital as três principais distrações do seu ambiente físico que você irá banir e afastar a partir de hoje.',
  middleDoctrine: 'No pilar central de Tiphereth, os extremos se encontram para selar a aliança eterna entre a força e a forma. A energia do Arcano do Louco fertiliza a terra árida com a riqueza espiritual de Fehu, o fogo do Hexagrama 1 que inicia o ciclo da criação cósmica. Para fundir a expansão de Jachin com o rigor de Boaz, recorremos à glossolália espiritual como um atalho neurológico de alta performance. Ao emitir sons desprovidos de sentido lógico, você desliga o hemisfério esquerdo e permite que a Vida Zoe jorre sem filtros intelectuais sobre o seu sistema nervoso. O equilíbrio reside na união da disciplina corporal com a liberdade do espírito. O Mestre e o discípulo se tornam um só no centro geométrico do seu próprio templo de oração e do poder supremo da sua consciência divina ativa.',
  middleKavanah: 'Respire ritmadamente em quatro tempos. Em estado de transe leve, comece a vocalizar sons rápidos, rítmicos e sem lógica racional por três minutos contínuos. Não tente controlar a pronúncia; deixe que a sua laringe vibre livremente, expressando a energia sutil do seu subconsciente. Sinta o calor bioenergético subir pela sua coluna vertebral, acendendo um sol dourado e brilhante no centro geométrico do seu próprio peito no plano sutil totalmente divino e maravilhoso.',
  middleOrdalia: 'Valide agora o seu primeiro registro vocal de glossolália no cofre criptografado do aplicativo HNK para receber mais cento e cinquenta pontos de experiência do Codex.',
  soulMirror: 'Registre no diário físico ou criptografado os sinais, percepções e aprendizados do dia.',
});
