'use client';
import {useEffect,useMemo,useRef,useState,type CSSProperties} from 'react';
import {ExperienceDirector,QuestRuntime,createQuestCatalog,type ExperienceDirective,type PlayerContext,type SessionSnapshot} from '@hnk/quest-engine';
import {createBundledQuestLibrary,type RuntimeQuestBundle} from '@hnk/quest-library';
import {assertElemiahProgress,loadDay016PracticeSessionV1,sealDay016V1,startDay016PracticeSessionV1} from '@hnk/supabase-client';
import {createWebQuestSnapshotStore} from '../_runtime/quest-snapshot-store';
import {createWebVaultTextPort} from '../_runtime/WebVaultTextPort';
import {useWebHnkRuntime} from '../_runtime/WebHnkRuntime';

type Session=NonNullable<Awaited<ReturnType<typeof loadDay016PracticeSessionV1>>>;
type Seal=Extract<Awaited<ReturnType<typeof sealDay016V1>>,{ok:true}>['response'];
type Block='jachin_preverbal_observation'|'boaz_layer_separation'|'middle_silence_word_prayer';
interface Draft{jachinDone:boolean;automaticLabel:boolean;returnedDirect:boolean;jachinRef:string|null;boazDone:boolean;layersSeparated:boolean;spokenCompared:boolean;associationBoundary:boolean;boazRef:string|null;middleDone:boolean;psalm64:boolean;wordBoundary:boolean;middleRef:string|null;soulRef:string|null;safetyStopped:boolean}
const emptyDraft:Draft={jachinDone:false,automaticLabel:false,returnedDirect:false,jachinRef:null,boazDone:false,layersSeparated:false,spokenCompared:false,associationBoundary:false,boazRef:null,middleDone:false,psalm64:false,wordBoundary:false,middleRef:null,soulRef:null,safetyStopped:false};
function canon(bundle:RuntimeQuestBundle,d:ExperienceDirective){return(d.phase.source.block_ids??[]).map(id=>{const b=bundle.canon.blocks.find(x=>x.id===id);if(!b)throw new Error(`canonical_block_missing:${id}`);return b.text})}
function keys(u:string){return{snapshot:`hnk:quest:d016:${u}:snapshot:v1`,session:`hnk:quest:d016:${u}:session:v1`,cache:`hnk:quest:d016:${u}:session-cache:v1`,draft:`hnk:quest:d016:${u}:draft:v1`}}
function parse<T>(k:string):T|null{try{const raw=localStorage.getItem(k);return raw?JSON.parse(raw) as T:null}catch{return null}}
function clientId(u:string){return`hnk-web-d016-v1-${u}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`}
function clock(elapsed:number){const left=Math.max(0,300-elapsed);return`${String(Math.floor(left/60)).padStart(2,'0')}:${String(left%60).padStart(2,'0')}`}
function middleStage(elapsed:number){if(elapsed<120)return'SILÊNCIO E ESCUTA · 2 MIN';if(elapsed<240)return'PALAVRA ESCOLHIDA · 2 MIN';return'ORAÇÃO / SALMO 6:4 · 1 MIN'}

export function Day016GoldenV1Web(){
 const auth=useWebHnkRuntime();const live=Boolean(auth.configured&&auth.phase==='signed-in'&&auth.client&&auth.userId);const runtimeRef=useRef<QuestRuntime|null>(null);
 const[bundle,setBundle]=useState<RuntimeQuestBundle|null>(null);const[snapshot,setSnapshot]=useState<SessionSnapshot|null>(null);const[session,setSession]=useState<Session|null>(null);const[draft,setDraft]=useState<Draft>(emptyDraft);const[loaded,setLoaded]=useState(false);
 const[active,setActive]=useState<Block|null>(null);const[started,setStarted]=useState<number|null>(null);const[now,setNow]=useState(Date.now());const[jachinNote,setJachinNote]=useState('');const[boazNote,setBoazNote]=useState('');const[middleNote,setMiddleNote]=useState('');const[soulNote,setSoulNote]=useState('');const[voluntary,setVoluntary]=useState(false);const[busy,setBusy]=useState(false);const[error,setError]=useState<string|null>(null);const[sealed,setSealed]=useState<Seal|null>(null);
 const context=useMemo<PlayerContext>(()=>({mediationMode:'HNK_CANONICAL',accessibility:{reducedMotion:typeof window!=='undefined'&&window.matchMedia?.('(prefers-reduced-motion: reduce)').matches===true,audioEnabled:false,microphoneAvailable:false},offline:!live}),[live]);
 const vault=useMemo(()=>auth.userId?createWebVaultTextPort(auth.client??null):null,[auth.client,auth.userId]);
 useEffect(()=>{if(!auth.userId)return;let ok=true;const lib=createBundledQuestLibrary(),cat=createQuestCatalog(lib),store=createWebQuestSnapshotStore(),k=keys(auth.userId);void Promise.all([cat.requireDay(16),lib.loadBundle(16),store.load(k.snapshot)]).then(([def,b,saved])=>{if(!ok||!b)return;const r=new QuestRuntime(def);runtimeRef.current=r;setBundle(b);setSnapshot(saved?r.restore(saved):r.start());setDraft(parse<Draft>(k.draft)??emptyDraft);const c=parse<Session>(k.cache);if(c)setSession(c);setLoaded(true)}).catch(e=>ok&&setError(e instanceof Error?e.message:'day016_load_failed'));return()=>{ok=false}},[auth.userId]);
 useEffect(()=>{if(!auth.userId||!snapshot)return;const k=keys(auth.userId),store=createWebQuestSnapshotStore();if(snapshot.runState==='COMPLETE'){void store.remove(k.snapshot);localStorage.removeItem(k.draft);localStorage.removeItem(k.session);localStorage.removeItem(k.cache)}else void store.save(k.snapshot,snapshot)},[auth.userId,snapshot]);
 useEffect(()=>{if(auth.userId&&loaded&&snapshot?.runState!=='COMPLETE')localStorage.setItem(keys(auth.userId).draft,JSON.stringify(draft))},[auth.userId,draft,loaded,snapshot?.runState]);
 useEffect(()=>{if(!live||!auth.client||!auth.userId)return;const k=keys(auth.userId),id=localStorage.getItem(k.session);if(!id)return;void loadDay016PracticeSessionV1(auth.client,id).then(s=>{if(s){setSession(s);localStorage.setItem(k.cache,JSON.stringify(s))}}).catch(()=>undefined)},[auth.client,auth.userId,live]);
 useEffect(()=>{const id=window.setInterval(()=>setNow(Date.now()),1000);return()=>window.clearInterval(id)},[]);
 useEffect(()=>{const onVisibility=()=>{if(document.visibilityState!=='visible'&&started!==null){setStarted(null);setActive(null);setError('bloco_interrompido_ao_sair_da_tela__reinicie_os_5_minutos')}};document.addEventListener('visibilitychange',onVisibility);return()=>document.removeEventListener('visibilitychange',onVisibility)},[started]);
 const director=useMemo(()=>bundle?new ExperienceDirector(bundle.quest):null,[bundle]);const directive=useMemo(()=>director&&snapshot?.currentPhaseId?director.resolvePhase(snapshot.currentPhaseId,context,snapshot):null,[director,context,snapshot]);const elapsed=started===null?0:Math.min(300,Math.max(0,Math.floor((now-started)/1000)));
 async function ensureSession(){if(session)return session;if(!live||!auth.client||!auth.userId)throw new Error('online_session_required_before_day016_practice');const s=await startDay016PracticeSessionV1(auth.client,{clientSessionId:clientId(auth.userId),appVersion:'0.1.0-web-day016-golden-v1'});setSession(s);const k=keys(auth.userId);localStorage.setItem(k.session,s.id);localStorage.setItem(k.cache,JSON.stringify(s));return s}
 async function complete(id:string){setError(null);try{if(id==='jachin_reading')await ensureSession();const r=runtimeRef.current;if(r)setSnapshot(r.completePhase(id));window.scrollTo({top:0,behavior:'smooth'})}catch(e){setError(e instanceof Error?e.message:'phase_failed')}}
 function startBlock(block:Block){if(started!==null)return;setError(null);setActive(block);setStarted(Date.now());setNow(Date.now())}
 function finishBlock(block:Block){if(active!==block||started===null||Math.floor((Date.now()-started)/1000)<300){setError('complete_5_minutes_before_advancing');return}setDraft(d=>block==='jachin_preverbal_observation'?{...d,jachinDone:true}:block==='boaz_layer_separation'?{...d,boazDone:true}:{...d,middleDone:true});setActive(null);setStarted(null)}
 function safetyStop(){setActive(null);setStarted(null);setDraft(d=>({...d,safetyStopped:true}));setError('safety_stop__abra_os_olhos__oriente_se_no_ambiente__retome_quando_confortavel');if(runtimeRef.current)setSnapshot(runtimeRef.current.safetyStop())}
 function resume(){setError(null);if(runtimeRef.current)setSnapshot(runtimeRef.current.resume())}
 async function saveJachin(){if(!vault||!auth.userId||!draft.jachinDone||!draft.automaticLabel||!draft.returnedDirect||!jachinNote.trim())throw new Error('jachin_evidence_required');const e=await vault.saveText({userId:auth.userId,day:16,kind:'journal',plaintext:JSON.stringify({schema:'hnk-day016-jachin-v1',threePrelabelPerceptionsAndAutomaticLabel:jachinNote.trim()})});setDraft(d=>({...d,jachinRef:e.entryId}));setJachinNote('');await complete('jachin_preverbal_observation')}
 async function saveBoaz(){if(!vault||!auth.userId||!draft.boazDone||!draft.layersSeparated||!draft.spokenCompared||!draft.associationBoundary||!boazNote.trim())throw new Error('boaz_layers_required');const e=await vault.saveText({userId:auth.userId,day:16,kind:'journal',plaintext:JSON.stringify({schema:'hnk-day016-boaz-v1',perceptionInterpretationBelief:boazNote.trim()})});setDraft(d=>({...d,boazRef:e.entryId}));setBoazNote('');await complete('boaz_layer_separation')}
 async function saveMiddle(){if(!vault||!auth.userId||!draft.middleDone||!draft.psalm64||!draft.wordBoundary||!middleNote.trim())throw new Error('middle_integration_required');const e=await vault.saveText({userId:auth.userId,day:16,kind:'journal',plaintext:JSON.stringify({schema:'hnk-day016-middle-v1',limitOfWordsPrelabelExperienceAndPrayer:middleNote.trim()})});setDraft(d=>({...d,middleRef:e.entryId}));setMiddleNote('');await complete('middle_silence_word_prayer')}
 async function saveSoul(){if(!vault||!auth.userId||!soulNote.trim())throw new Error('soul_mirror_required');const e=await vault.saveText({userId:auth.userId,day:16,kind:'journal',plaintext:JSON.stringify({schema:'hnk-day016-soul-v1',helpfulWordVsReplacingLabel:soulNote.trim()})});setDraft(d=>({...d,soulRef:e.entryId}));setSoulNote('');await complete('soul_mirror')}
 async function seal(){if(!runtimeRef.current||!live||!auth.client||!auth.userId||!session||!vault||!draft.jachinRef||!draft.boazRef||!draft.middleRef||!draft.soulRef||!voluntary)return;setBusy(true);setError(null);try{await vault.flushPending(auth.userId);const jr=await vault.resolveEntryId(auth.userId,draft.jachinRef),br=await vault.resolveEntryId(auth.userId,draft.boazRef),mr=await vault.resolveEntryId(auth.userId,draft.middleRef),sr=await vault.resolveEntryId(auth.userId,draft.soulRef);if(!jr||!br||!mr||!sr)throw new Error('vault_sync_required_before_completion');const result=await sealDay016V1(auth.client,{evidence:{sessionId:session.id,mode:'first_completion',jachinDurationSeconds:300,prelabelPerceptionCount:3,automaticLabelNoticed:draft.automaticLabel,returnedToDirectExperience:draft.returnedDirect,prelabelAndLabelVaultEntryRef:jr,boazDurationSeconds:300,perceptionInterpretationBeliefSeparated:draft.layersSeparated,spokenDescriptionCompared:draft.spokenCompared,associationNotExternalFactConfirmed:draft.associationBoundary,layersVaultEntryRef:br,middleDurationSeconds:300,silenceListeningSeconds:120,chosenWordObservationSeconds:120,finalPrayerSeconds:60,psalm64PrayerConfirmed:draft.psalm64,wordNotTotalRealityConfirmed:draft.wordBoundary,integrationVaultEntryRef:mr,soulMirrorCompleted:true,helpfulWordVsReplacingLabelVaultEntryRef:sr,safetyStopOccurred:draft.safetyStopped},totalDurationSeconds:Math.max(900,Math.floor((Date.now()-new Date(session.started_at).getTime())/1000))});if(!result.ok)throw new Error(result.code);assertElemiahProgress(result.response.crown,1);setSealed(result.response);setSnapshot(runtimeRef.current.confirmServerCompletion())}catch(e){setError(e instanceof Error?e.message:'day016_completion_failed')}finally{setBusy(false)}}
 const shell:CSSProperties={maxWidth:880,margin:'0 auto',padding:'28px 20px 80px',background:'#090910',color:'#eee7d7',minHeight:'100vh',fontFamily:'system-ui'};const panel:CSSProperties={border:'1px solid #6b657f',borderRadius:18,padding:22,display:'grid',gap:14,background:'#111018'};const btn:CSSProperties={padding:'11px 14px',borderRadius:10};
 if(!auth.userId)return <main style={shell}>ENTRE NO ÁTRIO PARA INICIAR O DIA 016.</main>;if(!bundle||!snapshot||!director)return <main style={shell}>CARREGANDO DAY 016…{error?<p>{error}</p>:null}</main>;if(snapshot.runState==='SAFETY_STOP')return <main style={shell}><h1>Prática interrompida.</h1><p>Abra os olhos, oriente-se no ambiente e retome apenas quando estiver confortável.</p><button onClick={resume}>RETOMAR</button></main>;if(snapshot.runState==='COMPLETE')return <main style={shell}><small>DIA 016 · ELEMIAH 1/5</small><h1>RUÍNA DO CONTROLE VERBAL CONCLUÍDA</h1><p>{sealed?.first_completion?`+${sealed.xp_awarded} XP canônicos.`:'Revisita sem novo XP.'}</p><p>Elemiah 1/5 confirmado pelo servidor · fragmento IV ainda apagado · Coroa {sealed?.crown.fragments_lit??3}/7.</p><p>Palavras continuam úteis; o treino foi distinguir linguagem, experiência e interpretação.</p></main>;if(!directive)return <main style={shell}>FASE INDISPONÍVEL.</main>;
 const p=directive.phase,texts=directive.requiresCanonicalContent?canon(bundle,directive):[],block=p.id as Block,isBlock=['jachin_preverbal_observation','boaz_layer_separation','middle_silence_word_prayer'].includes(p.id),done=block==='jachin_preverbal_observation'?draft.jachinDone:block==='boaz_layer_separation'?draft.boazDone:draft.middleDone;
 return <main style={shell}><header><small>DIA 016 · KETHER · ELEMIAH 1/5</small><h1>RUÍNA DO CONTROLE VERBAL</h1><p>{live?'VAULT E2EE · ONLINE':'VAULT E2EE · FILA CIFRADA OFFLINE'} · ÁUDIO DESATIVADO V1</p></header>{error?<p style={{color:'#ffb4ab'}}>{error}</p>:null}<section style={panel}><small>{p.type} · {p.id}</small>{p.type==='NARRATIVE'?<><h2>Perceber antes de nomear.</h2><p>A linguagem não é inimiga. Um rótulo orienta, mas não esgota a experiência.</p></>:null}{p.type==='READ'?texts.map((t,i)=><p key={i} style={{lineHeight:1.75}}>{t}</p>):null}
 {isBlock?<><div style={{fontSize:34}}>{done?'00:00':clock(active===block?elapsed:0)}</div>{block==='middle_silence_word_prayer'&&active===block?<strong>{middleStage(elapsed)}</strong>:null}{done?<strong>5 MINUTOS CONCLUÍDOS ✓</strong>:active===block?<button style={btn} disabled={elapsed<300} onClick={()=>finishBlock(block)}>{elapsed>=300?'CONFIRMAR 5 MINUTOS':'MANTER PRÁTICA'}</button>:<button style={btn} onClick={()=>startBlock(block)}>INICIAR 5 MINUTOS</button>}<button onClick={safetyStop}>SAFETY STOP</button></>:null}
 {p.id==='jachin_preverbal_observation'?<><label><input type="checkbox" checked={draft.automaticLabel} onChange={e=>setDraft(d=>({...d,automaticLabel:e.target.checked}))}/> Notei um rótulo automático</label><label><input type="checkbox" checked={draft.returnedDirect} onChange={e=>setDraft(d=>({...d,returnedDirect:e.target.checked}))}/> Voltei aos dados da experiência direta</label><textarea placeholder="3 percepções antes de nomear + rótulo automático + mudança de atenção" value={jachinNote} onChange={e=>setJachinNote(e.target.value)}/><button style={btn} onClick={()=>void saveJachin()}>CIFRAR E CONTINUAR</button></>:null}
 {p.id==='boaz_layer_separation'?<><label><input type="checkbox" checked={draft.layersSeparated} onChange={e=>setDraft(d=>({...d,layersSeparated:e.target.checked}))}/> Separei percepção, interpretação e crença</label><label><input type="checkbox" checked={draft.spokenCompared} onChange={e=>setDraft(d=>({...d,spokenCompared:e.target.checked}))}/> Comparei a descrição falada com a experiência</label><label><input type="checkbox" checked={draft.associationBoundary} onChange={e=>setDraft(d=>({...d,associationBoundary:e.target.checked}))}/> Associação pessoal não é automaticamente fato externo</label><textarea placeholder="Percepção / interpretação / crença" value={boazNote} onChange={e=>setBoazNote(e.target.value)}/><button style={btn} onClick={()=>void saveBoaz()}>CIFRAR CAMADAS</button></>:null}
 {p.id==='middle_silence_word_prayer'?<><label><input type="checkbox" checked={draft.psalm64} onChange={e=>setDraft(d=>({...d,psalm64:e.target.checked}))}/> Concluí a oração orientada pelo Salmo 6:4</label><label><input type="checkbox" checked={draft.wordBoundary} onChange={e=>setDraft(d=>({...d,wordBoundary:e.target.checked}))}/> Reconheço que uma palavra orienta sem conter toda a realidade</label><textarea placeholder="Limite das palavras + experiência antes de nomear + oração curta" value={middleNote} onChange={e=>setMiddleNote(e.target.value)}/><button style={btn} onClick={()=>void saveMiddle()}>CIFRAR INTEGRAÇÃO</button></>:null}
 {p.id==='soul_mirror'?<><textarea placeholder="Onde uma palavra ajudou e onde um rótulo tentou substituir a experiência" value={soulNote} onChange={e=>setSoulNote(e.target.value)}/><button style={btn} onClick={()=>void saveSoul()}>CIFRAR ESPELHO DA ALMA</button></>:null}
 {p.id==='completion'?<><label><input type="checkbox" checked={voluntary} onChange={e=>setVoluntary(e.target.checked)}/> Confirmo voluntariamente a conclusão</label><button style={btn} disabled={busy||!voluntary||!live} onClick={()=>void seal()}>{busy?'SELANDO…':'SELAR DAY 016'}</button></>:null}
 {!['jachin_preverbal_observation','boaz_layer_separation','middle_silence_word_prayer','soul_mirror','completion'].includes(p.id)?<button style={btn} onClick={()=>void complete(p.id)}>CONTINUAR</button>:null}</section></main>
}
