import type {Json} from '@hnk/database';
import {CompletionService,buildDay040CompletionRequest,type CompleteDayResponseV1,type CompletionRpcArgsV2,type CompletionResult} from '@hnk/completion-contract';
import {buildDay040EvidenceV2,buildDay040SafeMetrics,DAY040_VERBAL_SECONDS,DAY040_SILENT_SECONDS,type Day040EvidenceInput} from '@hnk/practice-contract';
import type {HnkSupabaseClient} from './index';
export interface SealDay040V2Input{evidence:Day040EvidenceInput;localRecordHash?:string|null;clientCompletedAt?:string;clientCompletionId?:string}
function asJson(v:unknown):Json{return v as Json}
function parse(v:Json):CompleteDayResponseV1{if(typeof v!=='object'||v===null||Array.isArray(v))throw new Error('invalid_completion_response');const r=v as Record<string,Json|undefined>;if(r.day!==40||r.completion_contract_id!=='HNK-CHOKMAH-D040-COMP-V2'||r.quest_definition_id!=='HNK-CHOKMAH-D040-V2'||r.canonical_source_sha!=='7a26302a35aa87b309e94abf516834019df29737'||typeof r.first_completion!=='boolean'||typeof r.xp_awarded!=='number'||typeof r.xp_total!=='number'||!Array.isArray(r.progression_events))throw new Error('invalid_completion_response');if(r.first_completion===true){const p=r.progress;if(typeof p!=='object'||p===null||Array.isArray(p))throw new Error('invalid_progress_response');const pr=p as Record<string,Json|undefined>;if(pr.current_day!==41||pr.current_chapter!==2||pr.current_sephira!=='Chokmah'||pr.initiatory_grade!==2||pr.initiatory_title!=='Iniciado')throw new Error('invalid_day040_progress_response');if(!(r.progression_events as Json[]).includes('NEXT_DAY_UNLOCKED'))throw new Error('missing_next_day_unlocked_event')}return v as unknown as CompleteDayResponseV1}
export function createDay040ClientCompletionId(sessionId:string){if(!sessionId.trim())throw new Error('practice_session_id_required');return`hnk:d040:completion:v2:${sessionId}`}
export async function startDay040PracticeSessionV2(client:HnkSupabaseClient,input:{clientSessionId:string;appVersion?:string|null;startedAt?:string}){if(!input.clientSessionId.trim())throw new Error('client_session_id_required');const{data:auth,error:authError}=await client.auth.getUser();if(authError)throw authError;if(!auth.user?.id)throw new Error('authentication_required');const{data,error}=await client.from('practice_sessions').insert({user_id:auth.user.id,day:40,client_session_id:input.clientSessionId,mode:'first_completion',state:'active',started_at:input.startedAt??new Date().toISOString(),app_version:input.appVersion??null,metrics:{},evidence:{}}).select('id,user_id,day,client_session_id,mode,state,started_at,ended_at,duration_seconds,metrics,evidence').single();if(error)throw error;return data}
export async function loadDay040PracticeSessionV2(client:HnkSupabaseClient,sessionId:string){if(!sessionId.trim())throw new Error('practice_session_id_required');const{data:auth,error:authError}=await client.auth.getUser();if(authError)throw authError;if(!auth.user?.id)throw new Error('authentication_required');const{data,error}=await client.from('practice_sessions').select('id,user_id,day,client_session_id,mode,state,started_at,ended_at,duration_seconds,metrics,evidence').eq('id',sessionId).eq('user_id',auth.user.id).eq('day',40).maybeSingle();if(error)throw error;return data}
export async function sealDay040V2(client:HnkSupabaseClient,input:SealDay040V2Input):Promise<CompletionResult>{const evidence=buildDay040EvidenceV2(input.evidence),metrics=buildDay040SafeMetrics(evidence),timedSeconds=DAY040_VERBAL_SECONDS+DAY040_SILENT_SECONDS;const{error:e}=await client.from('practice_sessions').update({duration_seconds:timedSeconds,metrics:asJson(metrics),evidence:asJson(evidence),state:'evidence_pending',ended_at:input.clientCompletedAt??new Date().toISOString(),local_record_hash:input.localRecordHash??null}).eq('id',evidence.session_id);if(e)throw e;const req=buildDay040CompletionRequest({sessionId:evidence.session_id,clientCompletionId:input.clientCompletionId??createDay040ClientCompletionId(evidence.session_id),...(input.localRecordHash?{localRecordHash:input.localRecordHash}:{}),clientCompletedAt:input.clientCompletedAt??new Date().toISOString()});const rpc=client.rpc.bind(client) as unknown as(name:'complete_codex_day_v2',args:CompletionRpcArgsV2)=>Promise<{data:Json;error:{message:string;code?:string}|null}>;return new CompletionService({async completeCodexDayV2(args){const{data,error}=await rpc('complete_codex_day_v2',args);if(error)throw new Error(error.message||error.code||'completion_rpc_failed');return parse(data)}}).complete(req)}
