import type {Json} from '@hnk/database';
import {CompletionService,buildDay036CompletionRequest,type CompleteDayResponseV1,type CompletionRpcArgsV2,type CompletionResult} from '@hnk/completion-contract';
import {buildDay036EvidenceV1,buildDay036SafeMetrics,DAY036_FOREGROUND_WALL_SECONDS,type Day036EvidenceInput} from '@hnk/practice-contract';
import type {HnkSupabaseClient} from './index';
export interface SealDay036V1Input{evidence:Day036EvidenceInput;localRecordHash?:string|null;clientCompletedAt?:string;clientCompletionId?:string}
function asJson(v:unknown):Json{return v as Json}
function parse(v:Json):CompleteDayResponseV1{if(typeof v!=='object'||v===null||Array.isArray(v))throw new Error('invalid_completion_response');const r=v as Record<string,Json|undefined>;if(r.day!==36||r.completion_contract_id!=='HNK-KETHER-D036-COMP-V1'||r.quest_definition_id!=='HNK-KETHER-D036-V1'||r.canonical_source_sha!=='cfb52771830f1f004c9eded69fb91846da313607'||typeof r.first_completion!=='boolean'||typeof r.xp_awarded!=='number'||typeof r.xp_total!=='number'||!Array.isArray(r.progression_events))throw new Error('invalid_completion_response');if(r.first_completion===true){const p=r.progress;if(typeof p!=='object'||p===null||Array.isArray(p))throw new Error('invalid_promotion_response');const pr=p as Record<string,Json|undefined>;if(pr.current_day!==37||pr.current_chapter!==2||pr.current_sephira!=='Chokmah'||pr.initiatory_grade!==2||pr.initiatory_title!=='Iniciado')throw new Error('invalid_kether_promotion_response');for(const event of ['KETHER_COMPLETE','INITIATORY_GRADE_CHANGED'])if(!(r.progression_events as Json[]).includes(event))throw new Error(`missing_${event.toLowerCase()}_event`)}return v as unknown as CompleteDayResponseV1}
export function createDay036ClientCompletionId(sessionId:string){if(!sessionId.trim())throw new Error('practice_session_id_required');return`hnk:d036:completion:v1:${sessionId}`}
export async function startDay036PracticeSessionV1(client:HnkSupabaseClient,input:{clientSessionId:string;appVersion?:string|null;startedAt?:string}){if(!input.clientSessionId.trim())throw new Error('client_session_id_required');const{data:auth,error:authError}=await client.auth.getUser();if(authError)throw authError;if(!auth.user?.id)throw new Error('authentication_required');const{data,error}=await client.from('practice_sessions').insert({user_id:auth.user.id,day:36,client_session_id:input.clientSessionId,mode:'first_completion',state:'active',started_at:input.startedAt??new Date().toISOString(),app_version:input.appVersion??null,metrics:{},evidence:{}}).select('id,user_id,day,client_session_id,mode,state,started_at,ended_at,duration_seconds,metrics,evidence').single();if(error)throw error;return data}
export async function loadDay036PracticeSessionV1(client:HnkSupabaseClient,sessionId:string){if(!sessionId.trim())throw new Error('practice_session_id_required');const{data:auth,error:authError}=await client.auth.getUser();if(authError)throw authError;if(!auth.user?.id)throw new Error('authentication_required');const{data,error}=await client.from('practice_sessions').select('id,user_id,day,client_session_id,mode,state,started_at,ended_at,duration_seconds,metrics,evidence').eq('id',sessionId).eq('user_id',auth.user.id).eq('day',36).maybeSingle();if(error)throw error;return data}
export async function sealDay036V1(client:HnkSupabaseClient,input:SealDay036V1Input):Promise<CompletionResult>{const evidence=buildDay036EvidenceV1(input.evidence),metrics=buildDay036SafeMetrics({portalDistractions:evidence.portal.distraction_count,portalFailures:evidence.portal.sequence_failure_count,portalRecoveries:evidence.portal.recovery_count,baselineDistractions:evidence.baseline.distraction_count});const{error:e}=await client.from('practice_sessions').update({duration_seconds:DAY036_FOREGROUND_WALL_SECONDS,metrics:asJson(metrics),evidence:asJson(evidence),state:'evidence_pending',ended_at:input.clientCompletedAt??new Date().toISOString(),local_record_hash:input.localRecordHash??null}).eq('id',evidence.session_id);if(e)throw e;const req=buildDay036CompletionRequest({sessionId:evidence.session_id,clientCompletionId:input.clientCompletionId??createDay036ClientCompletionId(evidence.session_id),...(input.localRecordHash?{localRecordHash:input.localRecordHash}:{}),clientCompletedAt:input.clientCompletedAt??new Date().toISOString()});const rpc=client.rpc.bind(client) as unknown as(name:'complete_codex_day_v2',args:CompletionRpcArgsV2)=>Promise<{data:Json;error:{message:string;code?:string}|null}>;return new CompletionService({async completeCodexDayV2(args){const{data,error}=await rpc('complete_codex_day_v2',args);if(error)throw new Error(error.message||error.code||'completion_rpc_failed');return parse(data)}}).complete(req)}
