import type {Json} from '@hnk/database';
import {CompletionService,buildDay070CompletionRequest,type CompleteDayResponseV1,type CompletionRpcArgsV2,type CompletionResult} from '@hnk/completion-contract';
import {DAY070_MASTER_ASSET_KEY,DAY070_MASTER_PATH,DAY070_MASTER_SHA256,buildDay070EvidenceV2,buildDay070SafeMetrics,type Day070EvidenceInput,type Day070ReferenceGate} from '@hnk/practice-contract';
import type {HnkSupabaseClient} from './index';
export interface SealDay070V2Input{evidence:Day070EvidenceInput;localRecordHash?:string|null;clientCompletedAt?:string;clientCompletionId?:string}
function asJson(v:unknown):Json{return v as Json}
function parse(v:Json):CompleteDayResponseV1{if(typeof v!=='object'||v===null||Array.isArray(v))throw new Error('invalid_completion_response');const r=v as Record<string,Json|undefined>;if(r.day!==70||r.completion_contract_id!=='HNK-CHOKMAH-D070-COMP-V2'||r.quest_definition_id!=='HNK-CHOKMAH-D070-V2'||r.canonical_source_sha!=='bb1e47aee510fe9df58a46f697ebafb9005e223e'||typeof r.first_completion!=='boolean'||typeof r.xp_awarded!=='number'||typeof r.xp_total!=='number'||!Array.isArray(r.progression_events))throw new Error('invalid_completion_response');if(r.first_completion===true){const p=r.progress;if(typeof p!=='object'||p===null||Array.isArray(p))throw new Error('invalid_progress_response');const pr=p as Record<string,Json|undefined>;if(pr.current_day!==71||pr.current_chapter!==2||pr.current_sephira!=='Chokmah'||pr.initiatory_grade!==2||pr.initiatory_title!=='Iniciado')throw new Error('invalid_day070_progress_response');if(!(r.progression_events as Json[]).includes('NEXT_DAY_UNLOCKED'))throw new Error('missing_next_day_unlocked_event')}return v as unknown as CompleteDayResponseV1}
export async function loadDay070ReferenceGate(client:HnkSupabaseClient):Promise<Day070ReferenceGate>{const{data,error}=await client.from('asset_registry').select('asset_key,approval_state,checksum_sha256,metadata').eq('asset_key',DAY070_MASTER_ASSET_KEY).maybeSingle();if(error)throw error;if(!data)return{canonicalReferenceReady:false,assetKey:null,approvalState:null,checksumSha256:null,repoPath:null,upright:false,mirrored:false};const meta=(data.metadata&&typeof data.metadata==='object'&&!Array.isArray(data.metadata)?data.metadata:{}) as Record<string,unknown>;const repoPath=typeof meta.repo_path==='string'?meta.repo_path:null,upright=meta.upright===true,mirrored=meta.mirrored===true;return{canonicalReferenceReady:data.approval_state==='approved'&&data.checksum_sha256===DAY070_MASTER_SHA256&&repoPath===DAY070_MASTER_PATH&&upright&&!mirrored,assetKey:data.asset_key,approvalState:data.approval_state,checksumSha256:data.checksum_sha256,repoPath,upright,mirrored}}
export function createDay070ClientCompletionId(sessionId:string){if(!sessionId.trim())throw new Error('practice_session_id_required');return`hnk:d070:completion:v2:${sessionId}`}
export async function startDay070PracticeSessionV2(client:HnkSupabaseClient,input:{clientSessionId:string;appVersion?:string|null;startedAt?:string}){if(!input.clientSessionId.trim())throw new Error('client_session_id_required');const gate=await loadDay070ReferenceGate(client);if(!gate.canonicalReferenceReady)throw new Error('day070_reference_not_ready');const{data:auth,error:authError}=await client.auth.getUser();if(authError)throw authError;if(!auth.user?.id)throw new Error('authentication_required');const{data,error}=await client.from('practice_sessions').insert({user_id:auth.user.id,day:70,client_session_id:input.clientSessionId,mode:'first_completion',state:'active',started_at:input.startedAt??new Date().toISOString(),app_version:input.appVersion??null,metrics:{},evidence:{}}).select('id,user_id,day,client_session_id,mode,state,started_at,ended_at,duration_seconds,metrics,evidence').single();if(error)throw error;return data}
export async function loadDay070PracticeSessionV2(client:HnkSupabaseClient,sessionId:string){if(!sessionId.trim())throw new Error('practice_session_id_required');const{data:auth,error:authError}=await client.auth.getUser();if(authError)throw authError;if(!auth.user?.id)throw new Error('authentication_required');const{data,error}=await client.from('practice_sessions').select('id,user_id,day,client_session_id,mode,state,started_at,ended_at,duration_seconds,metrics,evidence').eq('id',sessionId).eq('user_id',auth.user.id).eq('day',70).maybeSingle();if(error)throw error;return data}
export async function sealDay070V2(client:HnkSupabaseClient,input:SealDay070V2Input):Promise<CompletionResult>{const gate=await loadDay070ReferenceGate(client);if(!gate.canonicalReferenceReady)throw new Error('day070_reference_not_ready');const evidence=buildDay070EvidenceV2(input.evidence),metrics=buildDay070SafeMetrics(input.evidence);const{error:e}=await client.from('practice_sessions').update({metrics:asJson(metrics),evidence:asJson(evidence),state:'evidence_pending',ended_at:input.clientCompletedAt??new Date().toISOString(),local_record_hash:input.localRecordHash??null}).eq('id',evidence.session_id);if(e)throw e;const req=buildDay070CompletionRequest({sessionId:evidence.session_id,clientCompletionId:input.clientCompletionId??createDay070ClientCompletionId(evidence.session_id),...(input.localRecordHash?{localRecordHash:input.localRecordHash}:{}),clientCompletedAt:input.clientCompletedAt??new Date().toISOString()});const rpc=client.rpc.bind(client) as unknown as(name:'complete_codex_day_v2',args:CompletionRpcArgsV2)=>Promise<{data:Json;error:{message:string;code?:string}|null}>;return new CompletionService({async completeCodexDayV2(args){const{data,error}=await rpc('complete_codex_day_v2',args);if(error)throw new Error(error.message||error.code||'completion_rpc_failed');return parse(data)}}).complete(req)}
