'use client';
import {useEffect,useMemo,useRef,useState,type CSSProperties} from 'react';
import {ExperienceDirector,QuestRuntime,createQuestCatalog,type ExperienceDirective,type PlayerContext,type SessionSnapshot} from '@hnk/quest-engine';
import {createBundledQuestLibrary,type RuntimeQuestBundle} from '@hnk/quest-library';
import {assertElemiahProgress,loadDay017PracticeSessionV1,sealDay017V1,startDay017PracticeSessionV1} from '@hnk/supabase-client';
import {createWebQuestSnapshotStore} from '../_runtime/quest-snapshot-store';
import {createWebVaultTextPort} from '../_runtime/WebVaultTextPort';
import {useWebHnkRuntime} from '../_runtime/WebHnkRuntime';

type Session=NonNullable<Awaited<ReturnType<typeof loadDay017PracticeSessionV1>>>;
type Seal=Extract<Awaited<ReturnType<typeof sealDay017V1>>,{ok:true}>['response'];
type Block='jachin_vocal_flow'|'boaz_vocal_safety'|'middle_vocal_integration';
type SafetyResponse='NONE'|'ADJUSTED'|'STOPPED';
interface Draft{jachinDuration:number;comfort:number;spontaneity:number;breathingComfort:boolean;voluntaryFlow:boolean;noExternalDivine:boolean;jachinRef:string|null;boazDuration:number;lowModerate:boolean;breathingThroatChecks:boolean;agency:boolean;safetyResponse:SafetyResponse;boazRef:string|null;middleDuration:number;slowedToSilence:boolean;normalBreathing:boolean;psalm64:boolean;noProphecy:boolean;grounding:boolean;presence:number;middleRef:string|null;soulRef:string|null;safetyStopped:boolean}
const emptyDraft:Draft={jachinDuration:0,comfort:5,spontaneity:5,breathingComfort:false,voluntaryFlow:false,noExternalDivine:false,jachinRef:null,boazDuration:0,lowModerate:false,breathingThroatChecks:false,agency:false,safetyResponse:'NONE',boazRef:null,middleDuration:0,slowedToSilence:false,normalBreathing:false,psalm64:false,noProphecy:false,grounding:false,presence:5,middleRef:null,soulRef:null,safetyStopped:false};
function canon(bundle:RuntimeQuestBundle,d:ExperienceDirective){return(d.phase.source.block_ids??[]).map(id=>{const b=bundle.canon.blocks.find(x=>x.id===id);if(!b)throw new Error(`canonical_block_missing:${id}`);return b.text})}
function keys(u:string){return{snapshot:`hnk:quest:d017:${u}:snapshot:v1`,session:`hnk:quest:d017:${u}:session:v1`,cache:`hnk:quest:d017:${u}:session-cache:v1`,draft:`hnk:quest:d017:${u}:draft:v1`}}
function parse<T>(k:string):T|null{try{const raw=localStorage.getItem(k);return raw?JSON.parse(raw) as T:null}catch{return null}}
function clientId(u:string){return`hnk-web-d017-v1-${u}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`}
function score(v:string){const n=Number(v);return Number.isInteger(n)?Math.max(0,Math.min(10,n)):0}
function clock(elapsed:number,max:number){const left=Math.max(0,max-elapsed);return`${String(Math.floor(left/60)).padStart(2,'0')}:${String(left%60).padStart(2,'0')}`}

export function Day017GoldenV1Web(){
 const auth=useWebHnkRuntime();const live=Boolean(auth.configured&&auth.phase==='signed-in'&&auth.client&&auth.userId);const runtimeRef=useRef<QuestRuntime|null>(null);
 const[bundle,setBundle]=useState<RuntimeQuestBundle|null>(null);const[snapshot,setSnapshot]=useState<SessionSnapshot|null>(null);const[session,setSession]=useState<Session|null>(null);const[draft,setDraft]=useState<Draft>(emptyDraft);const[loaded,setLoaded]=useState(false);
 const[active,setActive]=useState<Block|null>(null);const[started,setStarted]=useState<number|null>(null);const[now,setNow]=useState(Date.now());const[jachinNote,setJachinNote]=useState('');const[boazNote,setBoazNote]=useState('');const[middleNote,setMiddleNote]=useState('');const[soulNote,setSoulNote]=useState('');const[voluntary,setVoluntary]=useState(false);const[busy,setBusy]=useState(false);const[error,setError]=useState<string|null>(null);const[sealed,setSealed]=useState<Seal|null>(null);
 const context=useMemo<PlayerContext>(()=>({mediationMode:'HNK_CANONICAL',accessibility:{reducedMotion:typeof window!=='undefined'&&window.matchMedia?.('(prefers-reduced-motion: reduce)').matches===true,audioEnabled:false,microphoneAvailable:false},offline:!live}),[live]);
 const vault=useMemo(()=>auth.userId?createWebVaultTextPort(auth.client??null):null,[auth.client,auth.userId]);
 useEffect(()=>{if(!auth.userId)return;let ok=true;const lib=createBundledQuestLibrary(),cat=createQuestCatalog(lib),store=createWebQuestSnapshotStore(),k=keys(auth.userId);void Promise.all([cat.requireDay(17),lib.loadBundle(17),store.load(k.snapshot)]).then(([def,b,saved])=>{if(!ok||!b)return;const r=new QuestRuntime(def);runtimeRef.current=r;setBundle(b);setSnapshot(saved?r.restore(saved):r.start());setDraft(parse<Draft>(k.draft)??emptyDraft);const c=parse<Session>(k.cache);if(c)setSession(c);setLoaded(true)}).catch(e=>ok&&setError(e instanceof Error?e.message:'day017_load_failed'));return()=>{ok=false}},[auth.userId]);
 useEffect(()=>{if(!auth.userId||!snapshot)return;const k=keys(auth.userId),store=createWebQuestSnapshotStore();if(snapshot.runState==='COMPLETE'){void store.remove(k.snapshot);localStorage.removeItem(k.draft);localStorage.removeItem(k.session);localStorage.removeItem(k.cache)}else void store.save(k.snapshot,snapshot)},[auth.userId,snapshot]);
 useEffect(()=>{if(auth.userId&&loaded&&snapshot?.runState!=='COMPLETE')localStorage.setItem(keys(auth.userId).draft,JSON.stringify(draft))},[auth.userId,draft,loaded,snapshot?.runState]);
 useEffect(()=>{if(!live||!auth.client||!auth.userId)return;const k=keys(auth.userId),id=localStorage.getItem(k.session);if(!id)return;void loadDay017PracticeSessionV1(auth.client,id).then(s=>{if(s){setSession(s);localStorage.setItem(k.cache,JSON.stringify(s))}}).catch(()=>undefined)},[auth.client,auth.userId,live]);
 useEffect(()=>{const id=window.setInterval(()=>setNow(Date.now()),1000);return()=>window.clearInterval(id)},[]);
 useEffect(()=>{const f=()=>{if(document.visibilityState!=='visible'&&started!==null){setStarted(null);setActive(null);setError('bloco_interrompido_ao_sair_da_tela__tempo_corrente_descartado')}};document.addEventListener('visibilitychange',f);return()=>document.removeEventListener('visibilitychange',f)},[started]);
 const director=useMemo(()=>bundle?new ExperienceDirector(bundle.quest):null,[bundle]);const directive=useMemo(()=>director&&snapshot?.currentPhaseId?director.resolvePhase(snapshot.currentPhaseId,context,snapshot):null,[director,context,snapshot]);
 const max=active==='middle_vocal_integration'?180:600;const elapsed=started===null?0:Math.min(max,Math.max(0,Math.floor((now-started)/1000)));
 async function ensureSession(){if(session)return session;if(!live||!auth.client||!auth.userId)throw new Error('online_session_required_before_day017_practice');const s=await startDay017PracticeSessionV1(auth.client,{clientSessionId:clientId(auth.userId),appVersion:'0.1.0-web-day017-golden-v1'});setSession(s);const k=keys(auth.userId);localStorage.setItem(k.session,s.id);localStorage.setItem(k.cache,JSON.stringify(s));return s}
 async function complete(id:string){setError(null);try{if(id==='jachin_reading')await ensureSession();const r=runtimeRef.current;if(r)setSnapshot(r.completePhase(id));window.scrollTo({top:0,behavior:'smooth'})}catch(e){setError(e instanceof Error?e.message:'phase_failed')}}
 function startBlock(b:Block){if(started!==null)return;setError(null);setActive(b);setStarted(Date.now());setNow(Date.now())}
 function finishBlock(b:Block){if(active!==b||started===null)return;const e=Math.min(b==='middle_vocal_integration'?180:600,Math.max(0,Math.floor((Date.now()-started)/1000)));const min=b==='middle_vocal_integration'?120:1;if(e<min){setError(b==='middle_vocal_integration'?'middle_requires_at_least_120_seconds':'practice_requires_at_least_1_second');return}setDraft(d=>b==='jachin_vocal_flow'?{...d,jachinDuration:e}:b==='boaz_vocal_safety'?{...d,boazDuration:e}:{...d,middleDuration:e});setActive(null);setStarted(null)}
 function safetyStop(){setActive(null);setStarted(null);setDraft(d=>({...d,safetyStopped:true}));setError('safety_stop__respire_normalmente__hidrate_se__oriente_se_no_ambiente');if(runtimeRef.current)setSnapshot(runtimeRef.current.safetyStop())}
 function resume(){setError(null);if(runtimeRef.current)setSnapshot(runtimeRef.current.resume())}
 async function saveJachin(){if(!vault||!auth.userId||draft.jachinDuration<1||!draft.breathingComfort||!draft.voluntaryFlow||!draft.noExternalDivine||!jachinNote.trim())throw new Error('jachin_evidence_required');const e=await vault.saveText({userId:auth.userId,day:17,kind:'journal',plaintext:JSON.stringify({schema:'hnk-day017-jachin-v1',experience:jachinNote.trim()})});setDraft(d=>({...d,jachinRef:e.entryId}));setJachinNote('');await complete('jachin_vocal_flow')}
 async function saveBoaz(){if(!vault||!auth.userId||draft.boazDuration<1||!draft.lowModerate||!draft.breathingThroatChecks||!draft.agency||!boazNote.trim())throw new Error('boaz_safety_evidence_required');const e=await vault.saveText({userId:auth.userId,day:17,kind:'journal',plaintext:JSON.stringify({schema:'hnk-day017-boaz-v1',experience:boazNote.trim()})});setDraft(d=>({...d,boazRef:e.entryId}));setBoazNote('');await complete('boaz_vocal_safety')}
 async function saveMiddle(){if(!vault||!auth.userId||draft.middleDuration<120||!draft.slowedToSilence||!draft.normalBreathing||!draft.psalm64||!draft.noProphecy||!draft.grounding||!middleNote.trim())throw new Error('middle_integration_required');const e=await vault.saveText({userId:auth.userId,day:17,kind:'journal',plaintext:JSON.stringify({schema:'hnk-day017-middle-v1',integration:middleNote.trim()})});setDraft(d=>({...d,middleRef:e.entryId}));setMiddleNote('');await complete('middle_vocal_integration')}
 async function saveSoul(){if(!vault||!auth.userId||!soulNote.trim())throw new Error('soul_mirror_required');const e=await vault.saveText({userId:auth.userId,day:17,kind:'journal',plaintext:JSON.stringify({schema:'hnk-day017-soul-v1',soundEmotionInterpretationDiscernment:soulNote.trim()})});setDraft(d=>({...d,soulRef:e.entryId}));setSoulNote('');await complete('soul_mirror')}
 async function seal(){if(!runtimeRef.current||!live||!auth.client||!auth.userId||!session||!vault||!draft.jachinRef||!draft.boazRef||!draft.middleRef||!draft.soulRef||!voluntary)return;setBusy(true);setError(null);try{await vault.flushPending(auth.userId);const jr=await vault.resolveEntryId(auth.userId,draft.jachinRef),br=await vault.resolveEntryId(auth.userId,draft.boazRef),mr=await vault.resolveEntryId(auth.userId,draft.middleRef),sr=await vault.resolveEntryId(auth.userId,draft.soulRef);if(!jr||!br||!mr||!sr)throw new Error('vault_sync_required_before_completion');const result=await sealDay017V1(auth.client,{evidence:{sessionId:session.id,mode:'first_completion',jachinDurationSeconds:draft.jachinDuration,comfortScore:draft.comfort,spontaneityScore:draft.spontaneity,breathingComfortConfirmed:draft.breathingComfort,voluntaryNonsemanticFlowConfirmed:draft.voluntaryFlow,soundNotExternalOrDivineMessageConfirmed:draft.noExternalDivine,jachinSessionVaultEntryRef:jr,boazDurationSeconds:draft.boazDuration,lowOrModerateVolumeConfirmed:draft.lowModerate,breathingAndThroatChecksConfirmed:draft.breathingThroatChecks,agencyPreservedConfirmed:draft.agency,safetyResponse:draft.safetyResponse,boazExperienceVaultEntryRef:br,middleDurationSeconds:draft.middleDuration,slowedToSilenceConfirmed:draft.slowedToSilence,normalBreathingConfirmed:draft.normalBreathing,psalm64PrayerConfirmed:draft.psalm64,soundNotProphecyOrCommandConfirmed:draft.noProphecy,groundingConfirmed:draft.grounding,presenceScore:draft.presence,middleIntegrationVaultEntryRef:mr,soulMirrorCompleted:true,soundEmotionInterpretationDiscernmentVaultEntryRef:sr,safetyStopOccurred:draft.safetyStopped},totalDurationSeconds:draft.jachinDuration+draft.boazDuration+draft.middleDuration});if(!result.ok)throw new Error(result.code);assertElemiahProgress(result.response.crown,2);setSealed(result.response);setSnapshot(runtimeRef.current.confirmServerCompletion())}catch(e){setError(e instanceof Error?e.message:'day017_completion_failed')}finally{setBusy(false)}}
 const shell:CSSProperties={maxWidth:900,margin:'0 auto',padding:'28px 20px 80px',background:'#090910',color:'#eee7d7',minHeight:'100vh',fontFamily:'system-ui'};const panel:CSSProperties={border:'1px solid #7b638b',borderRadius:18,padding:22,display:'grid',gap:14,background:'#111018'};const btn:CSSProperties={padding:'11px 14px',borderRadius:10};
 if(!auth.userId)return <main style={shell}>ENTRE NO ÁTRIO PARA INICIAR O DIA 017.</main>;if(!bundle||!snapshot||!director)return <main style={shell}>CARREGANDO DAY 017…{error?<p>{error}</p>:null}</main>;if(snapshot.runState==='SAFETY_STOP')return <main style={shell}><h1>PRÁTICA INTERROMPIDA</h1><p>Respire normalmente, hidrate-se e oriente-se no ambiente. Retome somente se desejar e estiver confortável.</p><button onClick={resume}>RETOMAR</button></main>;if(snapshot.runState==='COMPLETE')return <main style={shell}><small>DIA 017 · ELEMIAH 2/5</small><h1>ATIVAÇÃO DA GLOSSOLÁLIA CONCLUÍDA</h1><p>{sealed?.first_completion?`+${sealed.xp_awarded} XP canônicos.`:'Revisita sem novo XP.'}</p><p>Elemiah 2/5 confirmado pelo servidor · fragmento IV ainda apagado · Coroa {sealed?.crown.fragments_lit??3}/7.</p><p>HIP é aplicado pelo servidor. Intensidade e gravação não concedem atributo.</p></main>;if(!directive)return <main style={shell}>FASE INDISPONÍVEL.</main>;
 const p=directive.phase,texts=directive.requiresCanonicalContent?canon(bundle,directive):[],block=p.id as Block,isBlock=['jachin_vocal_flow','boaz_vocal_safety','middle_vocal_integration'].includes(p.id),done=block==='jachin_vocal_flow'?draft.jachinDuration>0:block==='boaz_vocal_safety'?draft.boazDuration>0:draft.middleDuration>=120,blockMax=block==='middle_vocal_integration'?180:600,blockMin=block==='middle_vocal_integration'?120:1;
 const toggle=(label:string,key:keyof Draft)=><label><input type="checkbox" checked={Boolean(draft[key])} onChange={e=>setDraft(d=>({...d,[key]:e.target.checked}))}/> {label}</label>;
 return <main style={shell}><header><small>DIA 017 · KETHER · ELEMIAH 2/5</small><h1>ATIVAÇÃO DA GLOSSOLÁLIA</h1><p>{live?'VAULT E2EE · ONLINE':'VAULT E2EE · FILA CIFRADA OFFLINE'} · ÁUDIO DESATIVADO V1</p></header>{error?<p style={{color:'#ffb4ab'}}>{error}</p>:null}<section style={panel}><small>{p.type} · {p.id}</small>{p.type==='NARRATIVE'?<><h2>Fluxo vocal com agência.</h2><p>Fluidez não é prova espiritual. Volume não é mérito. Você decide iniciar, modular, pausar e encerrar.</p></>:null}{p.type==='READ'?texts.map((t,i)=><p key={i} style={{lineHeight:1.75}}>{t}</p>):null}
 {isBlock?<><div style={{fontSize:34}}>{done?`${block==='middle_vocal_integration'?draft.middleDuration:block==='jachin_vocal_flow'?draft.jachinDuration:draft.boazDuration}s`:clock(active===block?elapsed:0,blockMax)}</div>{active===block?<button style={btn} disabled={elapsed<blockMin} onClick={()=>finishBlock(block)}>{elapsed<blockMin?'CONTINUE CONFORTAVELMENTE':'ENCERRAR ESTE BLOCO'}</button>:done?<strong>BLOCO REGISTRADO ✓</strong>:<button style={btn} onClick={()=>startBlock(block)}>INICIAR BLOCO</button>}<button onClick={safetyStop}>SAFETY STOP</button></>:null}
 {p.id==='jachin_vocal_flow'?<><label>Conforto vocal 0–10 <input type="number" min={0} max={10} value={draft.comfort} onChange={e=>setDraft(d=>({...d,comfort:score(e.target.value)}))}/></label><label>Espontaneidade 0–10 <input type="number" min={0} max={10} value={draft.spontaneity} onChange={e=>setDraft(d=>({...d,spontaneity:score(e.target.value)}))}/></label>{toggle('Respiração permaneceu confortável','breathingComfort')}{toggle('O fluxo foi voluntário','voluntaryFlow')}{toggle('Não tratei os sons como mensagem externa ou divina automática','noExternalDivine')}<textarea value={jachinNote} onChange={e=>setJachinNote(e.target.value)} placeholder="Ritmo, respiração, atenção e experiência — sem atribuir causa externa automática"/><button onClick={()=>void saveJachin()}>CIFRAR E CONTINUAR</button></>:null}
 {p.id==='boaz_vocal_safety'?<>{toggle('Mantive volume baixo ou moderado','lowModerate')}{toggle('Chequei respiração e garganta','breathingThroatChecks')}{toggle('Mantive agência para pausar ou parar','agency')}<label>Resposta de segurança <select value={draft.safetyResponse} onChange={e=>setDraft(d=>({...d,safetyResponse:e.target.value as SafetyResponse}))}><option value="NONE">Sem ajuste</option><option value="ADJUSTED">Ajustei intensidade/pausa</option><option value="STOPPED">Encerrei por segurança</option></select></label><textarea value={boazNote} onChange={e=>setBoazNote(e.target.value)} placeholder="Tensão, emoção, expectativa e como preservou conforto e escolha"/><button onClick={()=>void saveBoaz()}>CIFRAR BOAZ</button></>:null}
 {p.id==='middle_vocal_integration'?<>{toggle('Reduzi gradualmente até o silêncio','slowedToSilence')}{toggle('Respiração voltou ao ritmo normal','normalBreathing')}{toggle('Concluí oração orientada pelo Salmo 6:4','psalm64')}{toggle('Som significativo não foi tratado como profecia ou comando automático','noProphecy')}{toggle('Reorientei-me no ambiente','grounding')}<label>Presença 0–10 <input type="number" min={0} max={10} value={draft.presence} onChange={e=>setDraft(d=>({...d,presence:score(e.target.value)}))}/></label><textarea value={middleNote} onChange={e=>setMiddleNote(e.target.value)} placeholder="Som, emoção e interpretação — separados"/><button onClick={()=>void saveMiddle()}>CIFRAR INTEGRAÇÃO</button></>:null}
 {p.id==='soul_mirror'?<><textarea value={soulNote} onChange={e=>setSoulNote(e.target.value)} placeholder="O que foi som, emoção e interpretação posterior; critérios de discernimento usados"/><button onClick={()=>void saveSoul()}>CIFRAR ESPELHO DA ALMA</button></>:null}
 {p.id==='completion'?<><label><input type="checkbox" checked={voluntary} onChange={e=>setVoluntary(e.target.checked)}/> Concluo voluntariamente; intensidade, êxtase e gravação não são requisitos de progresso.</label><button disabled={!live||busy||!voluntary} onClick={()=>void seal()}>{busy?'SELANDO…':'SINCRONIZAR · SELAR DAY 017'}</button></>:null}
 {!['jachin_vocal_flow','boaz_vocal_safety','middle_vocal_integration','soul_mirror','completion'].includes(p.id)&&p.type!=='READ'&&p.type!=='NARRATIVE'?<button onClick={()=>void complete(p.id)}>CONTINUAR</button>:null}</section></main>
}
