'use client';

import { useEffect, useMemo, useRef, useState, type CSSProperties } from 'react';
import { ExperienceDirector, QuestRuntime, createQuestCatalog, type ExperienceDirective, type PlayerContext, type SessionSnapshot } from '@hnk/quest-engine';
import { createBundledQuestLibrary, type RuntimeQuestBundle } from '@hnk/quest-library';
import { sealDay007V1, startDay007PracticeSessionV1 } from '@hnk/supabase-client';
import { QuestBehavioralExperimentPhase, type BehavioralExperimentResult } from '../_runtime/QuestBehavioralExperimentPhase';
import { useWebHnkRuntime } from '../_runtime/WebHnkRuntime';

type Session=Awaited<ReturnType<typeof startDay007PracticeSessionV1>>; type Seal=Extract<Awaited<ReturnType<typeof sealDay007V1>>,{ok:true}>['response'];
function canon(bundle:RuntimeQuestBundle,d:ExperienceDirective){return(d.phase.source.block_ids??[]).map(id=>{const b=bundle.canon.blocks.find(x=>x.id===id);if(!b)throw new Error(`canonical_block_missing:${id}`);return b.text})}
function key(userId:string){return `hnk-web-d007-v1-${userId}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`}
export function Day007GoldenV1Web(){
 const auth=useWebHnkRuntime();const live=Boolean(auth.configured&&auth.phase==='signed-in'&&auth.client&&auth.userId);const runtimeRef=useRef<QuestRuntime|null>(null);
 const[bundle,setBundle]=useState<RuntimeQuestBundle|null>(null);const[snapshot,setSnapshot]=useState<SessionSnapshot|null>(null);const[session,setSession]=useState<Session|null>(null);const[jachinDone,setJachinDone]=useState(false);const[relaxationRating,setRelaxationRating]=useState(5);const[jachinCatalepsy,setJachinCatalepsy]=useState(false);const[boaz,setBoaz]=useState<BehavioralExperimentResult|null>(null);const[boazCatalepsy,setBoazCatalepsy]=useState(false);const[secondAttempt,setSecondAttempt]=useState(false);const[middleSeconds,setMiddleSeconds]=useState(0);const[mirrorRelax,setMirrorRelax]=useState(5);const[mirrorEffort,setMirrorEffort]=useState(5);const[mirrorChange,setMirrorChange]=useState(5);const[voluntary,setVoluntary]=useState(false);const[safetyStopped,setSafetyStopped]=useState(false);const[sealed,setSealed]=useState<Seal|null>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState<string|null>(null);
 const context=useMemo<PlayerContext>(()=>({mediationMode:'HNK_CANONICAL',accessibility:{reducedMotion:typeof window!=='undefined'&&window.matchMedia?.('(prefers-reduced-motion: reduce)').matches===true,audioEnabled:true,microphoneAvailable:false},offline:!live}),[live]);
 useEffect(()=>{let active=true;const library=createBundledQuestLibrary();const catalog=createQuestCatalog(library);void Promise.all([catalog.requireDay(7),library.loadBundle(7)]).then(([definition,loaded])=>{if(!active||!loaded)return;const r=new QuestRuntime(definition);runtimeRef.current=r;setBundle(loaded);setSnapshot(r.start())}).catch(c=>active&&setError(c instanceof Error?c.message:'day007_bundle_load_failed'));return()=>{active=false}},[]);
 const director=useMemo(()=>bundle?new ExperienceDirector(bundle.quest):null,[bundle]);const directive=useMemo(()=>director&&snapshot?.currentPhaseId?director.resolvePhase(snapshot.currentPhaseId,context,snapshot):null,[director,context,snapshot]);
 async function ensureSession(){if(session)return session;if(!live||!auth.client||!auth.userId)return null;const created=await startDay007PracticeSessionV1(auth.client,{clientSessionId:key(auth.userId),appVersion:'0.1.0-web-day007-golden-v1'});setSession(created);return created}
 async function completePhase(id:string){const r=runtimeRef.current;if(!r)return;if(id==='jachin_reading')await ensureSession();setSnapshot(r.completePhase(id));window.scrollTo({top:0,behavior:'smooth'})}
 function safetyStop(reason?:string){setSafetyStopped(true);setError(reason??'safety_stop');if(runtimeRef.current)setSnapshot(runtimeRef.current.safetyStop())}
 function resume(){if(runtimeRef.current){setError(null);setSnapshot(runtimeRef.current.resume())}}
 async function seal(){if(!auth.client||!session||!runtimeRef.current||!jachinDone||!boaz||middleSeconds<60||!voluntary)return;setBusy(true);setError(null);try{const result=await sealDay007V1(auth.client,{evidence:{sessionId:session.id,mode:'first_completion',jachin:{relaxationRating,catalepsyReported:jachinCatalepsy},boaz:{spontaneousSensationRating:boaz.after.spontaneous_sensation_rating??5,muscularEffortRating:boaz.after.muscular_effort_rating??5,secondAttemptPerformed:secondAttempt,catalepsyReported:boazCatalepsy},middle:{silentObservationSeconds:middleSeconds},soulMirror:{relaxationSpontaneousRating:mirrorRelax,muscularEffortRating:mirrorEffort,perceptionChangeRating:mirrorChange},safetyStopOccurred:safetyStopped},totalDurationSeconds:middleSeconds+6,secondAttemptPerformed:secondAttempt});if(!result.ok)throw new Error(result.code);setSealed(result.response);setSnapshot(runtimeRef.current.confirmServerCompletion())}catch(c){setError(c instanceof Error?c.message:'day007_completion_failed')}finally{setBusy(false)}}
 const shell:CSSProperties={maxWidth:860,margin:'0 auto',padding:'28px 20px 80px',color:'#eee7d7',background:'#090910',minHeight:'100vh',fontFamily:'system-ui'};const panel:CSSProperties={border:'1px solid #6f5f29',borderRadius:18,padding:22,display:'grid',gap:14,background:'#111018'};
 if(!bundle||!snapshot||!director)return <main style={shell}>CARREGANDO DAY 007…{error?<p>{error}</p>:null}</main>;
 if(snapshot.runState==='SAFETY_STOP')return <main style={shell}><h1>Prática pausada com segurança.</h1><button onClick={resume}>RETOMAR</button></main>;
 if(snapshot.runState==='COMPLETE')return <main style={shell}><p>DIA 007 · JELIEL 2/5</p><h1>DAVE ELMAN I · REGISTRADO</h1><p>{sealed?.first_completion?`+${sealed.xp_awarded} XP canônicos.`:'Revisita sem novo XP.'}</p><p>+1 HIP é servidor-side. Nenhuma catalepsia era necessária.</p></main>;
 if(!directive)return <main style={shell}>FASE INDISPONÍVEL.</main>; const p=directive.phase;const texts=directive.requiresCanonicalContent?canon(bundle,directive):[];
 return <main style={shell}><header><small>DIA 007 · KETHER · JELIEL 2/5</small><h1>DAVE ELMAN I</h1><span>{live?'BACKEND':'OFFLINE'}</span></header>{error?<p style={{color:'#ffb4ab'}}>{error}</p>:null}<section style={panel}><small>{p.type} · {p.id}</small>
  {p.type==='NARRATIVE'?<><h2>Relaxar, testar, liberar.</h2><p>Você mantém controle total. Não existe efeito obrigatório.</p></>:null}
  {p.type==='TERM_REVEAL'?<p>{(p.terms??[]).join(' · ')}</p>:null}
  {p.type==='READ'?texts.map((t,i)=><p key={i} style={{lineHeight:1.75}}>{t}</p>):null}
  {p.type==='FOCUS'&&p.id==='jachin_relaxation'?<ElmanSequence silentSeconds={0} onFinish={()=>{setJachinDone(true);void completePhase(p.id)}} onSafetyStop={()=>safetyStop('elman_jachin_stop')}/>:null}
  {p.type==='JOURNAL'?<><label>Relaxamento · {relaxationRating}<input type="range" min="0" max="10" step="1" value={relaxationRating} onChange={e=>setRelaxationRating(Number(e.target.value))}/></label><label><input type="checkbox" checked={jachinCatalepsy} onChange={e=>setJachinCatalepsy(e.target.checked)}/> Relatei catalepsia subjetiva (opcional; desmarcado também é válido).</label><p>A frase livre permanece no Vault.</p><button onClick={()=>void completePhase(p.id)}>REGISTRAR · CONTINUAR</button></>:null}
  {p.type==='EXPERIMENT'?<><QuestBehavioralExperimentPhase directive={directive} onResult={setBoaz} onCompletePhase={completePhase} onSafetyStop={safetyStop}/><label><input type="checkbox" checked={secondAttempt} onChange={e=>setSecondAttempt(e.target.checked)}/> Fiz uma segunda tentativa porque estava confortável.</label><label><input type="checkbox" checked={boazCatalepsy} onChange={e=>setBoazCatalepsy(e.target.checked)}/> Relatei catalepsia subjetiva nesta comparação.</label></>:null}
  {p.type==='FOCUS'&&p.id==='middle_sequence'?<ElmanSequence silentSeconds={60} onFinish={s=>{setMiddleSeconds(s);void completePhase(p.id)}} onSafetyStop={()=>safetyStop('elman_middle_stop')}/>:null}
  {p.type==='RETURN'?<><p>Libere qualquer sugestão, abra os olhos normalmente, respire e oriente-se.</p><button onClick={()=>void completePhase(p.id)}>ESTOU ORIENTADO · CONTINUAR</button></>:null}
  {p.type==='STRUCTURED_JOURNAL'?<><Rating label="RELAXAMENTO ESPONTÂNEO" value={mirrorRelax} setValue={setMirrorRelax}/><Rating label="ESFORÇO MUSCULAR" value={mirrorEffort} setValue={setMirrorEffort}/><Rating label="MUDANÇA DE PERCEPÇÃO" value={mirrorChange} setValue={setMirrorChange}/><button onClick={()=>void completePhase(p.id)}>CONCLUIR ESPELHO</button></>:null}
  {p.type==='COMPLETION'?<><h2>Selo canônico</h2><p>O servidor valida execução; catalepsia não é requisito.</p><label><input type="checkbox" checked={voluntary} onChange={e=>setVoluntary(e.target.checked)}/> Confirmo conclusão voluntária</label><button disabled={busy||!voluntary} onClick={()=>void seal()}>{busy?'SELANDO…':'SELAR DAY 007'}</button></>:null}
  {['NARRATIVE','TERM_REVEAL','READ','UNLOCK'].includes(p.type)?<button onClick={()=>void completePhase(p.id)}>CONTINUAR</button>:null}
 </section></main>;
}
function Rating({label,value,setValue}:{label:string;value:number;setValue:(v:number)=>void}){return <label>{label} · {value}<input type="range" min="0" max="10" step="1" value={value} onChange={e=>setValue(Number(e.target.value))}/></label>}
function ElmanSequence({silentSeconds,onFinish,onSafetyStop}:{silentSeconds:number;onFinish:(seconds:number)=>void;onSafetyStop:()=>void}){const[testRemaining,setTestRemaining]=useState(3);const[testing,setTesting]=useState(false);const[tested,setTested]=useState(false);const[released,setReleased]=useState(false);const[silent,setSilent]=useState(0);const[silentRunning,setSilentRunning]=useState(false);useEffect(()=>{if(!testing)return;const id=window.setInterval(()=>setTestRemaining(v=>{if(v<=1){window.clearInterval(id);setTesting(false);setTested(true);return 0}return v-1}),1000);return()=>window.clearInterval(id)},[testing]);useEffect(()=>{if(!silentRunning)return;const id=window.setInterval(()=>setSilent(v=>v+1),1000);return()=>window.clearInterval(id)},[silentRunning]);const canFinish=tested&&released&&(silentSeconds===0||silent>=silentSeconds);return <div style={{display:'grid',gap:10}}><p>Relaxe sem apertar os olhos. Você pode abrir os olhos a qualquer momento.</p><button disabled={testing||tested} onClick={()=>setTesting(true)}>{testing?`TESTE VOLUNTÁRIO · ${testRemaining}s`:'INICIAR TESTE VOLUNTÁRIO · 3s'}</button><button disabled={!tested||released} onClick={()=>setReleased(true)}>LIBERAR SUGESTÃO · ABRIR OLHOS NORMALMENTE</button>{silentSeconds>0&&released?<><p>Observação silenciosa: {silent}s / {silentSeconds}s</p><button onClick={()=>setSilentRunning(v=>!v)}>{silentRunning?'PAUSAR':'INICIAR / RETOMAR 1 MINUTO'}</button></>:null}<button disabled={!canFinish} onClick={()=>onFinish(silentSeconds?Math.max(silent,silentSeconds):3)}>CONCLUIR SEQUÊNCIA</button><button onClick={onSafetyStop}>SAFETY STOP</button></div>}
