import {useEffect,useMemo,useRef,useState} from 'react';
import {AppState,Pressable,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';
import * as SecureStore from 'expo-secure-store';
import {ExperienceDirector,QuestRuntime,createQuestCatalog,type ExperienceDirective,type PlayerContext,type SessionSnapshot} from '@hnk/quest-engine';
import {createBundledQuestLibrary,type RuntimeQuestBundle} from '@hnk/quest-library';
import {assertSitaelProgress,loadDay012PracticeSessionV1,sealDay012V1,startDay012PracticeSessionV1,type Day012DiscomfortResponse} from '@hnk/supabase-client';
import {useHnkAuth} from '../auth/AuthContext';
import {createMobileVaultTextPort} from '../../runtime/MobileVaultTextPort';

type Session=NonNullable<Awaited<ReturnType<typeof loadDay012PracticeSessionV1>>>;
type Seal=Extract<Awaited<ReturnType<typeof sealDay012V1>>,{ok:true}>['response'];
type BlockKey='jachin_trataka'|'boaz_trataka'|'middle_trataka';
interface Draft{
 stableSurface:boolean;flammablesClear:boolean;childrenAnimalsClear:boolean;supervised:boolean;alertNotSleepy:boolean;naturalBlinking:boolean;
 jachinDuration:number;jachinDistractions:number;jachinReturned:boolean;jachinRef:string|null;
 boazDuration:number;boazDistractions:number;competitionAvoided:boolean;discomfort:Day012DiscomfortResponse;noForcedEyeStrain:boolean;boazRef:string|null;
 middleDuration:number;thoughtReturnNoRestart:boolean;simultaneousAwareness:boolean;prayer:boolean;attentionScore:number;flameExtinguished:boolean;middleRef:string|null;
 soulRef:string|null;safetyStopped:boolean;
}
const emptyDraft:Draft={stableSurface:false,flammablesClear:false,childrenAnimalsClear:false,supervised:false,alertNotSleepy:false,naturalBlinking:false,jachinDuration:0,jachinDistractions:0,jachinReturned:false,jachinRef:null,boazDuration:0,boazDistractions:0,competitionAvoided:false,discomfort:'NONE',noForcedEyeStrain:false,boazRef:null,middleDuration:0,thoughtReturnNoRestart:false,simultaneousAwareness:false,prayer:false,attentionScore:5,flameExtinguished:false,middleRef:null,soulRef:null,safetyStopped:false};
function canon(bundle:RuntimeQuestBundle,d:ExperienceDirective){return(d.phase.source.block_ids??[]).map(id=>{const b=bundle.canon.blocks.find(x=>x.id===id);if(!b)throw new Error(`canonical_block_missing:${id}`);return b.text})}
function clientId(userId:string){return`hnk-mobile-d012-v1-${userId}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`}
function keys(userId:string){return{snapshot:`hnk.quest.d012.${userId}.snapshot.v1`,session:`hnk.quest.d012.${userId}.session.v1`,draft:`hnk.quest.d012.${userId}.draft.v1`}}
async function loadJson<T>(key:string):Promise<T|null>{try{const raw=await SecureStore.getItemAsync(key);return raw?JSON.parse(raw) as T:null}catch{return null}}
async function saveJson(key:string,value:unknown){await SecureStore.setItemAsync(key,JSON.stringify(value))}
function time(total:number){const s=Math.max(0,Math.min(600,total));return`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}

export function Day012GoldenV1Mobile(){
 const auth=useHnkAuth();const live=Boolean(auth.configured&&auth.phase==='signed-in'&&auth.client&&auth.userId);const runtimeRef=useRef<QuestRuntime|null>(null);
 const[bundle,setBundle]=useState<RuntimeQuestBundle|null>(null);const[snapshot,setSnapshot]=useState<SessionSnapshot|null>(null);const[session,setSession]=useState<Session|null>(null);const[draft,setDraft]=useState<Draft>(emptyDraft);const[draftLoaded,setDraftLoaded]=useState(false);
 const[activeBlock,setActiveBlock]=useState<BlockKey|null>(null);const[activeStartedAt,setActiveStartedAt]=useState<number|null>(null);const[now,setNow]=useState(Date.now());
 const[jachinNote,setJachinNote]=useState('');const[boazNote,setBoazNote]=useState('');const[middleNote,setMiddleNote]=useState('');const[soulNote,setSoulNote]=useState('');const[voluntary,setVoluntary]=useState(false);const[sealed,setSealed]=useState<Seal|null>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState<string|null>(null);
 const context=useMemo<PlayerContext>(()=>({mediationMode:'HNK_CANONICAL',accessibility:{reducedMotion:false,audioEnabled:false,microphoneAvailable:false},offline:!live}),[live]);
 const vault=useMemo(()=>auth.userId?createMobileVaultTextPort(auth.client??null):null,[auth.client,auth.userId]);

 useEffect(()=>{if(!auth.userId)return;let active=true;const library=createBundledQuestLibrary();const catalog=createQuestCatalog(library);const k=keys(auth.userId);void Promise.all([catalog.requireDay(12),library.loadBundle(12),loadJson<SessionSnapshot>(k.snapshot),loadJson<Session>(k.session),loadJson<Draft>(k.draft)]).then(([definition,b,savedSnapshot,savedSession,savedDraft])=>{if(!active||!b)return;const r=new QuestRuntime(definition);runtimeRef.current=r;setBundle(b);setSnapshot(savedSnapshot?r.restore(savedSnapshot):r.start());if(savedSession)setSession(savedSession);setDraft(savedDraft??emptyDraft);setDraftLoaded(true)}).catch(e=>active&&setError(e instanceof Error?e.message:'day012_bundle_load_failed'));return()=>{active=false}},[auth.userId]);
 useEffect(()=>{if(!auth.userId||!snapshot)return;const k=keys(auth.userId);if(snapshot.runState==='COMPLETE'){void SecureStore.deleteItemAsync(k.snapshot);void SecureStore.deleteItemAsync(k.draft);void SecureStore.deleteItemAsync(k.session)}else void saveJson(k.snapshot,snapshot)},[auth.userId,snapshot]);
 useEffect(()=>{if(!auth.userId||!draftLoaded||snapshot?.runState==='COMPLETE')return;void saveJson(keys(auth.userId).draft,draft)},[auth.userId,draft,draftLoaded,snapshot?.runState]);
 useEffect(()=>{const id=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(id)},[]);
 useEffect(()=>{const sub=AppState.addEventListener('change',state=>{if(state!=='active'&&activeStartedAt){setActiveStartedAt(null);setActiveBlock(null);setError('bloco_interrompido_ao_sair_do_app__apague_a_chama_e_reinicie')}});return()=>sub.remove()},[activeStartedAt]);

 const director=useMemo(()=>bundle?new ExperienceDirector(bundle.quest):null,[bundle]);const directive=useMemo(()=>director&&snapshot?.currentPhaseId?director.resolvePhase(snapshot.currentPhaseId,context,snapshot):null,[director,context,snapshot]);
 const elapsed=activeStartedAt?Math.min(600,Math.max(0,Math.floor((now-activeStartedAt)/1000))):0;
 async function ensureSession(){if(session)return session;if(!live||!auth.client||!auth.userId)throw new Error('online_session_required_before_day012_practice');const created=await startDay012PracticeSessionV1(auth.client,{clientSessionId:clientId(auth.userId),appVersion:'0.1.0-mobile-day012-golden-v1'});setSession(created);await saveJson(keys(auth.userId).session,created);return created}
 async function complete(id:string){setError(null);try{if(id==='jachin_reading')await ensureSession();const r=runtimeRef.current;if(r)setSnapshot(r.completePhase(id))}catch(e){setError(e instanceof Error?e.message:'phase_completion_failed')}}
 function startBlock(id:BlockKey){if(activeStartedAt)return;setError(null);setActiveBlock(id);setActiveStartedAt(Date.now());setNow(Date.now())}
 function endBlock(id:BlockKey){if(activeBlock!==id||!activeStartedAt)throw new Error('practice_timer_not_started');const seconds=Math.min(600,Math.floor((Date.now()-activeStartedAt)/1000));if(seconds<1)throw new Error('practice_duration_too_short');setDraft(d=>id==='jachin_trataka'?{...d,jachinDuration:seconds}:id==='boaz_trataka'?{...d,boazDuration:seconds}:{...d,middleDuration:seconds});setActiveStartedAt(null);setActiveBlock(null)}
 function safetyStop(){setActiveStartedAt(null);setActiveBlock(null);setDraft(d=>({...d,safetyStopped:true}));setError('safety_stop__apague_a_chama_e_afaste_o_olhar');if(runtimeRef.current)setSnapshot(runtimeRef.current.safetyStop())}
 function resume(){setError(null);if(runtimeRef.current)setSnapshot(runtimeRef.current.resume())}
 async function saveJachin(){if(!vault||!auth.userId||draft.jachinDuration<1)throw new Error('jachin_practice_required');if(!draft.jachinReturned||!jachinNote.trim())throw new Error('jachin_return_note_required');const e=await vault.saveText({userId:auth.userId,day:12,kind:'journal',plaintext:JSON.stringify({schema:'hnk-day012-jachin-v1',returnAfterDistraction:jachinNote.trim()})});setDraft(d=>({...d,jachinRef:e.entryId}));setJachinNote('');await complete('jachin_trataka')}
 async function saveBoaz(){if(!vault||!auth.userId||draft.boazDuration<1)throw new Error('boaz_practice_required');if(!draft.competitionAvoided||!draft.noForcedEyeStrain||!boazNote.trim())throw new Error('boaz_safety_note_required');const e=await vault.saveText({userId:auth.userId,day:12,kind:'journal',plaintext:JSON.stringify({schema:'hnk-day012-boaz-v1',distractionAndDiscomfort:boazNote.trim()})});setDraft(d=>({...d,boazRef:e.entryId}));setBoazNote('');await complete('boaz_trataka')}
 async function saveMiddle(){if(!vault||!auth.userId||draft.middleDuration<1)throw new Error('middle_practice_required');if(!draft.thoughtReturnNoRestart||!draft.simultaneousAwareness||!draft.prayer||!draft.flameExtinguished||!middleNote.trim())throw new Error('middle_safety_and_integration_required');const e=await vault.saveText({userId:auth.userId,day:12,kind:'journal',plaintext:JSON.stringify({schema:'hnk-day012-middle-v1',finalNote:middleNote.trim(),attentionStabilityScore:draft.attentionScore})});setDraft(d=>({...d,middleRef:e.entryId}));setMiddleNote('');await complete('middle_trataka')}
 async function saveSoul(){if(!vault||!auth.userId||!soulNote.trim())throw new Error('soul_mirror_note_required');const e=await vault.saveText({userId:auth.userId,day:12,kind:'journal',plaintext:JSON.stringify({schema:'hnk-day012-soul-v1',attentionDistractionReturn:soulNote.trim()})});setDraft(d=>({...d,soulRef:e.entryId}));setSoulNote('');await complete('soul_mirror')}
 async function seal(){if(!runtimeRef.current||!live||!auth.client||!auth.userId||!session||!vault||!draft.jachinRef||!draft.boazRef||!draft.middleRef||!draft.soulRef||!draft.flameExtinguished||!voluntary)return;setBusy(true);setError(null);try{await vault.flushPending(auth.userId);const jr=await vault.resolveEntryId(auth.userId,draft.jachinRef);const br=await vault.resolveEntryId(auth.userId,draft.boazRef);const mr=await vault.resolveEntryId(auth.userId,draft.middleRef);const sr=await vault.resolveEntryId(auth.userId,draft.soulRef);if(!jr||!br||!mr||!sr)throw new Error('vault_sync_required_before_completion');const total=Math.max(0,Math.floor((Date.now()-new Date(session.started_at).getTime())/1000));const result=await sealDay012V1(auth.client,{evidence:{sessionId:session.id,mode:'first_completion',stableSurfaceConfirmed:draft.stableSurface,flammablesClearConfirmed:draft.flammablesClear,childrenAnimalsClearConfirmed:draft.childrenAnimalsClear,continuousSupervisionConfirmed:draft.supervised,alertNotSleepyConfirmed:draft.alertNotSleepy,naturalBlinkingConfirmed:draft.naturalBlinking,jachinDurationSeconds:draft.jachinDuration,jachinDistractionCount:draft.jachinDistractions,jachinReturnedWithoutJudgmentConfirmed:draft.jachinReturned,jachinReturnVaultEntryRef:jr,boazDurationSeconds:draft.boazDuration,boazDistractionCount:draft.boazDistractions,boazCompetitionAvoidanceConfirmed:draft.competitionAvoided,boazDiscomfortResponse:draft.discomfort,boazNoForcedEyeStrainConfirmed:draft.noForcedEyeStrain,boazDistractionDiscomfortVaultEntryRef:br,middleDurationSeconds:draft.middleDuration,middleThoughtReturnWithoutRestartConfirmed:draft.thoughtReturnNoRestart,middleSimultaneousAwarenessConfirmed:draft.simultaneousAwareness,psalm912PrayerConfirmed:draft.prayer,attentionStabilityScore:draft.attentionScore,middleFinalVaultEntryRef:mr,flameExtinguishedConfirmed:draft.flameExtinguished,soulMirrorCompleted:true,attentionDistractionReturnVaultEntryRef:sr,safetyStopOccurred:draft.safetyStopped},totalDurationSeconds:total});if(!result.ok)throw new Error(result.code);assertSitaelProgress(result.response.crown,2);setSealed(result.response);setSnapshot(runtimeRef.current.confirmServerCompletion())}catch(e){setError(e instanceof Error?e.message:'day012_completion_failed')}finally{setBusy(false)}}
 const safetyReady=draft.stableSurface&&draft.flammablesClear&&draft.childrenAnimalsClear&&draft.supervised&&draft.alertNotSleepy&&draft.naturalBlinking;
 if(!auth.userId)return <Center text="ENTRE NO ÁTRIO PARA INICIAR O DIA 012."/>;if(!bundle||!snapshot||!director)return <Center text={error??'CARREGANDO DAY 012…'}/>;if(snapshot.runState==='SAFETY_STOP')return <View style={s.center}><Text style={s.title}>PRÁTICA INTERROMPIDA COM SEGURANÇA</Text><Text style={s.text}>Apague a vela, afaste o olhar e cuide do conforto ocular. Ao retomar, o bloco interrompido começa novamente.</Text><Action label="RETOMAR SOMENTE SEM CHAMA ACESA" onPress={resume}/></View>;if(snapshot.runState==='COMPLETE')return <View style={s.center}><Text style={s.eyebrow}>DIA 012 · SITAEL 2/5</Text><Text style={s.title}>TRATAKA PRIMAL CONCLUÍDO</Text><Text style={s.text}>{sealed?.first_completion?`+${sealed.xp_awarded} XP canônicos.`:'Revisita sem novo XP.'}</Text><Text style={s.text}>Sitael 2/5 confirmado pelo servidor · fragmento III ainda apagado · Coroa {sealed?.crown.fragments_lit??2}/7.</Text><Text style={s.text}>Matriz: +1 PER solicitado ao servidor, sujeito ao cap 20; DIS é secundário, sem ponto automático.</Text></View>;if(!directive)return <Center text="FASE INDISPONÍVEL."/>;
 const p=directive.phase;const texts=directive.requiresCanonicalContent?canon(bundle,directive):[];const current=p.id as BlockKey;
 return <ScrollView contentContainerStyle={s.shell}><Text style={s.eyebrow}>DIA 012 · KETHER · SITAEL 2/5</Text><Text style={s.header}>TRATAKA PRIMAL</Text><Text style={s.status}>{live?'VAULT E2EE · ONLINE':'VAULT E2EE · FILA CIFRADA OFFLINE'}</Text>{error?<Text style={s.error}>{error}</Text>:null}<View style={s.panel}><Text style={s.eyebrow}>{p.type} · {p.id}</Text>
 {p.type==='NARRATIVE'?<><Text style={s.title}>Foco sem violência.</Text><Text style={s.text}>Pensamentos não invalidam a prática. Piscar é permitido. Dez minutos são teto, não obrigação.</Text></>:null}
 {p.type==='READ'?texts.map((t,i)=><Text key={i} style={s.canon}>{t}</Text>):null}
 {p.id==='fire_safety_gate'?<><Text style={s.title}>GATE DE SEGURANÇA DA CHAMA</Text><Toggle label="Vela em superfície firme" value={draft.stableSurface} on={()=>setDraft(d=>({...d,stableSurface:!d.stableSurface}))}/><Toggle label="Inflamáveis afastados" value={draft.flammablesClear} on={()=>setDraft(d=>({...d,flammablesClear:!d.flammablesClear}))}/><Toggle label="Fora do alcance de crianças e animais" value={draft.childrenAnimalsClear} on={()=>setDraft(d=>({...d,childrenAnimalsClear:!d.childrenAnimalsClear}))}/><Toggle label="Supervisão contínua da chama" value={draft.supervised} on={()=>setDraft(d=>({...d,supervised:!d.supervised}))}/><Toggle label="Estou desperto, sem sono intenso" value={draft.alertNotSleepy} on={()=>setDraft(d=>({...d,alertNotSleepy:!d.alertNotSleepy}))}/><Toggle label="Vou piscar naturalmente" value={draft.naturalBlinking} on={()=>setDraft(d=>({...d,naturalBlinking:!d.naturalBlinking}))}/><Action disabled={!safetyReady} label="SEGURANÇA CONFIRMADA · CONTINUAR" onPress={()=>void complete(p.id)}/></>:null}
 {['jachin_trataka','boaz_trataka','middle_trataka'].includes(p.id)?<><Text style={s.timer}>{time(activeBlock===current?elapsed:current==='jachin_trataka'?draft.jachinDuration:current==='boaz_trataka'?draft.boazDuration:draft.middleDuration)}</Text>{activeBlock===current?<><Text style={s.text}>Chama supervisionada · permaneça no app. Máximo 10:00.</Text><Action label="ENCERRAR COM SEGURANÇA · REGISTRAR TEMPO" onPress={()=>{try{endBlock(current)}catch(e){setError(e instanceof Error?e.message:'timer_end_failed')}}}/></>:<Action disabled={Boolean(activeBlock)} label="INICIAR BLOCO · ATÉ 10 MIN" onPress={()=>startBlock(current)}/>}<Action danger label="INTERROMPER · APAGAR CHAMA" onPress={safetyStop}/></>:null}
 {p.id==='jachin_trataka'?<><Counter label="DISTRAÇÕES PERCEBIDAS" value={draft.jachinDistractions} set={v=>setDraft(d=>({...d,jachinDistractions:v}))}/><Toggle label="Retornei sem irritação ou julgamento" value={draft.jachinReturned} on={()=>setDraft(d=>({...d,jachinReturned:!d.jachinReturned}))}/><Input value={jachinNote} set={setJachinNote} placeholder="Como foi retornar à chama? (cifrado)"/><Action disabled={draft.jachinDuration<1||!draft.jachinReturned} label={draft.jachinRef?'REGISTRO CIFRADO ✓':'CIFRAR · CONTINUAR'} onPress={()=>void saveJachin().catch(e=>setError(e instanceof Error?e.message:'vault_save_failed'))}/></>:null}
 {p.id==='boaz_trataka'?<><Counter label="DISTRAÇÕES PERCEBIDAS" value={draft.boazDistractions} set={v=>setDraft(d=>({...d,boazDistractions:v}))}/><Toggle label="Não competi com o temporizador" value={draft.competitionAvoided} on={()=>setDraft(d=>({...d,competitionAvoided:!d.competitionAvoided}))}/><Toggle label="Não forcei os olhos nem evitei piscar" value={draft.noForcedEyeStrain} on={()=>setDraft(d=>({...d,noForcedEyeStrain:!d.noForcedEyeStrain}))}/><Text style={s.text}>RESPOSTA AO DESCONFORTO · {draft.discomfort}</Text><View style={s.row}>{(['NONE','ADJUSTED','STOPPED'] as Day012DiscomfortResponse[]).map(v=><Small key={v} label={v} on={()=>setDraft(d=>({...d,discomfort:v}))}/>)}</View><Input value={boazNote} set={setBoazNote} placeholder="Distrações e ajustes de conforto (cifrado)"/><Action disabled={draft.boazDuration<1||!draft.competitionAvoided||!draft.noForcedEyeStrain} label={draft.boazRef?'REGISTRO CIFRADO ✓':'CIFRAR · CONTINUAR'} onPress={()=>void saveBoaz().catch(e=>setError(e instanceof Error?e.message:'vault_save_failed'))}/></>:null}
 {p.id==='middle_trataka'?<><Toggle label="Retornei sem reiniciar toda a prática" value={draft.thoughtReturnNoRestart} on={()=>setDraft(d=>({...d,thoughtReturnNoRestart:!d.thoughtReturnNoRestart}))}/><Toggle label="Percebi chama, respiração e corpo sem rigidez" value={draft.simultaneousAwareness} on={()=>setDraft(d=>({...d,simultaneousAwareness:!d.simultaneousAwareness}))}/><Toggle label="Concluí a oração com Salmo 91:2" value={draft.prayer} on={()=>setDraft(d=>({...d,prayer:!d.prayer}))}/><Score value={draft.attentionScore} set={v=>setDraft(d=>({...d,attentionScore:v}))}/><Input value={middleNote} set={setMiddleNote} placeholder="Distração, retorno e segurança (cifrado)"/><Toggle label="A vela está APAGADA" value={draft.flameExtinguished} on={()=>setDraft(d=>({...d,flameExtinguished:!d.flameExtinguished}))}/><Action disabled={draft.middleDuration<1||!draft.thoughtReturnNoRestart||!draft.simultaneousAwareness||!draft.prayer||!draft.flameExtinguished} label={draft.middleRef?'REGISTRO CIFRADO ✓':'CIFRAR · CONTINUAR'} onPress={()=>void saveMiddle().catch(e=>setError(e instanceof Error?e.message:'vault_save_failed'))}/></>:null}
 {p.id==='soul_mirror'?<><Input value={soulNote} set={setSoulNote} placeholder="Atenção, distração e retorno sem controlar pensamentos (cifrado)"/><Action label={draft.soulRef?'ESPELHO CIFRADO ✓':'CIFRAR ESPELHO · CONTINUAR'} onPress={()=>void saveSoul().catch(e=>setError(e instanceof Error?e.message:'vault_save_failed'))}/></>:null}
 {p.type==='COMPLETION'?<><Text style={s.title}>SELO DE SITAEL 2/5</Text><Text style={s.text}>Somente o servidor concede XP e aplica a matriz. O cliente não incrementa PER.</Text><Toggle label="Vela apagada e conclusão voluntária" value={voluntary} on={()=>setVoluntary(v=>!v)}/><Action disabled={busy||!voluntary||!draft.flameExtinguished||!draft.soulRef} label={busy?'SINCRONIZANDO E SELANDO…':'SINCRONIZAR · SELAR DAY 012'} onPress={()=>void seal()}/></>:null}
 {['NARRATIVE','READ','UNLOCK'].includes(p.type)?<Action label="CONTINUAR" onPress={()=>void complete(p.id)}/>:null}
 </View></ScrollView>
}
function Center({text}:{text:string}){return <View style={s.center}><Text style={s.text}>{text}</Text></View>}
function Action({label,onPress,disabled=false,danger=false}:{label:string;onPress:()=>void;disabled?:boolean;danger?:boolean}){return <Pressable disabled={disabled} onPress={onPress} style={[s.button,danger&&s.danger,disabled&&s.disabled]}><Text style={[s.buttonText,danger&&s.dangerText]}>{label}</Text></Pressable>}
function Small({label,on}:{label:string;on:()=>void}){return <Pressable onPress={on} style={s.small}><Text style={s.buttonText}>{label}</Text></Pressable>}
function Toggle({label,value,on}:{label:string;value:boolean;on:()=>void}){return <Action label={`${value?'✓':'○'} ${label}`} onPress={on}/>}
function Input({value,set,placeholder}:{value:string;set:(v:string)=>void;placeholder:string}){return <TextInput multiline value={value} onChangeText={set} placeholder={placeholder} placeholderTextColor="#817967" style={s.input}/>}
function Counter({label,value,set}:{label:string;value:number;set:(v:number)=>void}){return <View><Text style={s.text}>{label} · {value}</Text><View style={s.row}><Small label="−" on={()=>set(Math.max(0,value-1))}/><Small label="+" on={()=>set(value+1)}/></View></View>}
function Score({value,set}:{value:number;set:(v:number)=>void}){return <View><Text style={s.text}>ESTABILIDADE DA ATENÇÃO · {value}/10</Text><View style={s.row}>{[0,2,4,6,8,10].map(v=><Small key={v} label={String(v)} on={()=>set(v)}/>)}</View></View>}
const s=StyleSheet.create({shell:{padding:20,paddingBottom:80,backgroundColor:'#090910',minHeight:'100%',gap:14},center:{flex:1,padding:28,justifyContent:'center',backgroundColor:'#090910',gap:14},panel:{borderWidth:1,borderColor:'#80622f',borderRadius:18,padding:18,gap:14,backgroundColor:'#111018'},row:{flexDirection:'row',flexWrap:'wrap',gap:6},eyebrow:{color:'#d9bd67',fontSize:12,letterSpacing:1.3},status:{color:'#b6aa87',fontSize:12},header:{color:'#f4e6b2',fontSize:25,fontWeight:'800'},title:{color:'#f4e6b2',fontSize:21,fontWeight:'700'},text:{color:'#eee7d7',lineHeight:21},canon:{color:'#eee7d7',lineHeight:24,fontSize:15},timer:{color:'#f4e6b2',fontSize:36,fontVariant:['tabular-nums']},input:{borderWidth:1,borderColor:'#6f5f29',borderRadius:10,padding:12,color:'#eee7d7',minHeight:90,textAlignVertical:'top'},error:{color:'#ffb4ab'},button:{borderWidth:1,borderColor:'#9a8240',borderRadius:10,padding:12},small:{borderWidth:1,borderColor:'#9a8240',borderRadius:8,paddingVertical:8,paddingHorizontal:12},danger:{borderColor:'#8e4d4d'},dangerText:{color:'#ffb4ab'},disabled:{opacity:.4},buttonText:{color:'#f4e6b2',fontWeight:'700'}});
