import {useEffect,useMemo,useRef,useState} from 'react';
import {Pressable,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';
import * as SecureStore from 'expo-secure-store';
import {ExperienceDirector,QuestRuntime,createQuestCatalog,type ExperienceDirective,type PlayerContext,type SessionSnapshot} from '@hnk/quest-engine';
import {createBundledQuestLibrary,type RuntimeQuestBundle} from '@hnk/quest-library';
import {assertSitaelProgress,loadDay011PracticeSessionV1,sealDay011V1,startDay011PracticeSessionV1} from '@hnk/supabase-client';
import {useHnkAuth} from '../auth/AuthContext';
import {createMobileVaultTextPort} from '../../runtime/MobileVaultTextPort';

type Session=NonNullable<Awaited<ReturnType<typeof loadDay011PracticeSessionV1>>>;
type Seal=Extract<Awaited<ReturnType<typeof sealDay011V1>>,{ok:true}>['response'];
interface Draft{
 jachinRef:string|null;jachinDone:boolean;
 boazRef:string|null;boazDone:boolean;judgmentLabeling:boolean;returnedToObservation:boolean;strangenessConfirmed:boolean;safeLimit:boolean;
 middleRef:string|null;middleDone:boolean;seeBeforeJudge:boolean;prayer:boolean;attentionScore:number;
 soulRef:string|null;safetyStopped:boolean;timerEndsAt:Record<string,number>;
}
const emptyDraft:Draft={jachinRef:null,jachinDone:false,boazRef:null,boazDone:false,judgmentLabeling:false,returnedToObservation:false,strangenessConfirmed:false,safeLimit:false,middleRef:null,middleDone:false,seeBeforeJudge:false,prayer:false,attentionScore:5,soulRef:null,safetyStopped:false,timerEndsAt:{}};
function canon(bundle:RuntimeQuestBundle,d:ExperienceDirective){return(d.phase.source.block_ids??[]).map(id=>{const b=bundle.canon.blocks.find(x=>x.id===id);if(!b)throw new Error(`canonical_block_missing:${id}`);return b.text})}
function clientId(userId:string){return`hnk-mobile-d011-v1-${userId}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`}
function keys(userId:string){return{snapshot:`hnk.quest.d011.${userId}.snapshot.v1`,session:`hnk.quest.d011.${userId}.session.v1`,draft:`hnk.quest.d011.${userId}.draft.v1`}}
async function loadJson<T>(key:string):Promise<T|null>{try{const raw=await SecureStore.getItemAsync(key);return raw?JSON.parse(raw) as T:null}catch{return null}}
async function saveJson(key:string,value:unknown){await SecureStore.setItemAsync(key,JSON.stringify(value))}
function formatTime(total:number){const m=Math.floor(total/60);const s=total%60;return`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}

export function Day011GoldenV1Mobile(){
 const auth=useHnkAuth();const live=Boolean(auth.configured&&auth.phase==='signed-in'&&auth.client&&auth.userId);const runtimeRef=useRef<QuestRuntime|null>(null);
 const[bundle,setBundle]=useState<RuntimeQuestBundle|null>(null);const[snapshot,setSnapshot]=useState<SessionSnapshot|null>(null);const[session,setSession]=useState<Session|null>(null);const[draft,setDraft]=useState<Draft>(emptyDraft);const[draftLoaded,setDraftLoaded]=useState(false);
 const[feature1,setFeature1]=useState('');const[feature2,setFeature2]=useState('');const[feature3,setFeature3]=useState('');const[relationship,setRelationship]=useState('');const[judgment,setJudgment]=useState('');const[finalNote,setFinalNote]=useState('');const[soulNote,setSoulNote]=useState('');
 const[voluntary,setVoluntary]=useState(false);const[sealed,setSealed]=useState<Seal|null>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState<string|null>(null);const[now,setNow]=useState(Date.now());
 const context=useMemo<PlayerContext>(()=>({mediationMode:'HNK_CANONICAL',accessibility:{reducedMotion:false,audioEnabled:false,microphoneAvailable:false},offline:!live}),[live]);
 const vault=useMemo(()=>auth.userId?createMobileVaultTextPort(auth.client??null):null,[auth.client,auth.userId]);

 useEffect(()=>{if(!auth.userId)return;let active=true;const library=createBundledQuestLibrary();const catalog=createQuestCatalog(library);const k=keys(auth.userId);void Promise.all([catalog.requireDay(11),library.loadBundle(11),loadJson<SessionSnapshot>(k.snapshot),loadJson<Session>(k.session),loadJson<Draft>(k.draft)]).then(([definition,b,savedSnapshot,savedSession,savedDraft])=>{if(!active||!b)return;const r=new QuestRuntime(definition);runtimeRef.current=r;setBundle(b);setSnapshot(savedSnapshot?r.restore(savedSnapshot):r.start());if(savedSession)setSession(savedSession);setDraft(savedDraft??emptyDraft);setDraftLoaded(true)}).catch(e=>active&&setError(e instanceof Error?e.message:'day011_bundle_load_failed'));return()=>{active=false}},[auth.userId]);
 useEffect(()=>{if(!auth.userId||!snapshot)return;const k=keys(auth.userId);if(snapshot.runState==='COMPLETE'){void SecureStore.deleteItemAsync(k.snapshot);void SecureStore.deleteItemAsync(k.draft);void SecureStore.deleteItemAsync(k.session)}else void saveJson(k.snapshot,snapshot)},[auth.userId,snapshot]);
 useEffect(()=>{if(!auth.userId||!draftLoaded||snapshot?.runState==='COMPLETE')return;void saveJson(keys(auth.userId).draft,draft)},[auth.userId,draft,draftLoaded,snapshot?.runState]);
 useEffect(()=>{const id=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(id)},[]);

 const director=useMemo(()=>bundle?new ExperienceDirector(bundle.quest):null,[bundle]);const directive=useMemo(()=>director&&snapshot?.currentPhaseId?director.resolvePhase(snapshot.currentPhaseId,context,snapshot):null,[director,context,snapshot]);
 const phaseId=directive?.phase.id??'';const timerEnd=phaseId?draft.timerEndsAt[phaseId]??null:null;const timerRemaining=timerEnd?Math.max(0,Math.ceil((timerEnd-now)/1000)):300;const timerReady=Boolean(timerEnd&&timerRemaining===0);
 async function ensureSession(){if(session)return session;if(!live||!auth.client||!auth.userId)throw new Error('online_session_required_before_day011_practice');const created=await startDay011PracticeSessionV1(auth.client,{clientSessionId:clientId(auth.userId),appVersion:'0.1.0-mobile-day011-golden-v1'});setSession(created);await saveJson(keys(auth.userId).session,created);return created}
 async function complete(id:string){setError(null);try{if(id==='jachin_reading')await ensureSession();const r=runtimeRef.current;if(r)setSnapshot(r.completePhase(id))}catch(e){setError(e instanceof Error?e.message:'phase_completion_failed')}}
 function startTimer(id:string){setDraft(d=>({...d,timerEndsAt:{...d.timerEndsAt,[id]:Date.now()+300000}}));setNow(Date.now())}
 function stop(reason='safety_stop'){setError(reason);setDraft(d=>{const timers={...d.timerEndsAt};if(snapshot?.currentPhaseId)delete timers[snapshot.currentPhaseId];return{...d,safetyStopped:true,timerEndsAt:timers}});if(runtimeRef.current)setSnapshot(runtimeRef.current.safetyStop())}
 function resume(){setError(null);if(runtimeRef.current)setSnapshot(runtimeRef.current.resume())}
 async function saveJachin(){if(!vault||!auth.userId)throw new Error('vault_unavailable');if(!timerReady)throw new Error('five_minute_observation_not_complete');const features=[feature1.trim(),feature2.trim(),feature3.trim()];if(features.some(x=>!x)||!relationship.trim())throw new Error('three_features_and_relationship_required');const e=await vault.saveText({userId:auth.userId,day:11,kind:'journal',plaintext:JSON.stringify({schema:'hnk-day011-jachin-v1',nonEvaluativeCharacteristics:features,relationshipChange:relationship.trim()})});setDraft(d=>({...d,jachinRef:e.entryId,jachinDone:true}));setFeature1('');setFeature2('');setFeature3('');setRelationship('');await complete('jachin_observation')}
 async function saveBoaz(){if(!vault||!auth.userId)throw new Error('vault_unavailable');if(!timerReady)throw new Error('five_minute_observation_not_complete');if(!judgment.trim())throw new Error('predominant_judgment_required');if(!draft.judgmentLabeling||!draft.returnedToObservation||!draft.strangenessConfirmed||!draft.safeLimit)throw new Error('boaz_confirmations_required');const e=await vault.saveText({userId:auth.userId,day:11,kind:'journal',plaintext:JSON.stringify({schema:'hnk-day011-boaz-v1',predominantJudgment:judgment.trim()})});setDraft(d=>({...d,boazRef:e.entryId,boazDone:true}));setJudgment('');await complete('boaz_judgment_observation')}
 async function saveMiddle(){if(!vault||!auth.userId)throw new Error('vault_unavailable');if(!timerReady)throw new Error('five_minute_observation_not_complete');if(!draft.seeBeforeJudge||!draft.prayer||!finalNote.trim())throw new Error('middle_confirmations_required');const e=await vault.saveText({userId:auth.userId,day:11,kind:'journal',plaintext:JSON.stringify({schema:'hnk-day011-middle-v1',finalObservation:finalNote.trim(),attentionStabilityScore:draft.attentionScore})});setDraft(d=>({...d,middleRef:e.entryId,middleDone:true}));setFinalNote('');await complete('middle_observation')}
 async function saveSoul(){if(!vault||!auth.userId)throw new Error('vault_unavailable');if(!soulNote.trim())throw new Error('observation_vs_interpretation_required');const e=await vault.saveText({userId:auth.userId,day:11,kind:'journal',plaintext:JSON.stringify({schema:'hnk-day011-soul-mirror-v1',observationVsInterpretation:soulNote.trim()})});setDraft(d=>({...d,soulRef:e.entryId}));setSoulNote('');await complete('soul_mirror')}
 async function seal(){if(!runtimeRef.current||!live||!auth.client||!auth.userId||!session||!vault||!draft.jachinRef||!draft.boazRef||!draft.middleRef||!draft.soulRef||!draft.jachinDone||!draft.boazDone||!draft.middleDone||!voluntary)return;setBusy(true);setError(null);try{await vault.flushPending(auth.userId);const jr=await vault.resolveEntryId(auth.userId,draft.jachinRef);const br=await vault.resolveEntryId(auth.userId,draft.boazRef);const mr=await vault.resolveEntryId(auth.userId,draft.middleRef);const sr=await vault.resolveEntryId(auth.userId,draft.soulRef);if(!jr||!br||!mr||!sr)throw new Error('vault_sync_required_before_completion');const elapsed=Math.max(0,Math.floor((Date.now()-new Date(session.started_at).getTime())/1000));const result=await sealDay011V1(auth.client,{evidence:{sessionId:session.id,mode:'first_completion',jachinFiveMinutesCompleted:true,blinkAndNaturalBreathingConfirmed:true,threeNonEvaluativeCharacteristicsRecorded:true,relationshipChangeVaultEntryRef:jr,boazFiveMinutesCompleted:true,judgmentLabelingCompleted:draft.judgmentLabeling,predominantJudgmentVaultEntryRef:br,returnedToObservationConfirmed:draft.returnedToObservation,visualStrangenessNotAutomaticRevelationConfirmed:draft.strangenessConfirmed,safeLimitConfirmed:draft.safeLimit,middleFiveMinutesCompleted:true,seeBeforeJudgeCompleted:draft.seeBeforeJudge,psalm912PrayerConfirmed:draft.prayer,attentionStabilityScore:draft.attentionScore,finalObservationVaultEntryRef:mr,soulMirrorCompleted:true,observationVsInterpretationVaultEntryRef:sr,safetyStopOccurred:draft.safetyStopped},totalDurationSeconds:elapsed});if(!result.ok)throw new Error(result.code);assertSitaelProgress(result.response.crown,1);setSealed(result.response);setSnapshot(runtimeRef.current.confirmServerCompletion())}catch(e){setError(e instanceof Error?e.message:'day011_completion_failed')}finally{setBusy(false)}}

 if(!auth.userId)return <Center text="ENTRE NO ÁTRIO PARA INICIAR O DIA 011."/>;if(!bundle||!snapshot||!director)return <Center text={error??'CARREGANDO DAY 011…'}/>;if(snapshot.runState==='SAFETY_STOP')return <View style={s.center}><Text style={s.title}>PRÁTICA INTERROMPIDA COM SEGURANÇA</Text><Text style={s.text}>Afaste o olhar do espelho, reconheça o ambiente e respire normalmente. Retome somente se estiver confortável.</Text><Action label="RETOMAR QUANDO ESTIVER BEM" onPress={resume}/></View>;if(snapshot.runState==='COMPLETE')return <View style={s.center}><Text style={s.eyebrow}>DIA 011 · SITAEL 1/5</Text><Text style={s.title}>VER ANTES DE JULGAR</Text><Text style={s.text}>{sealed?.first_completion?`+${sealed.xp_awarded} XP canônicos.`:'Revisita sem novo XP.'}</Text><Text style={s.text}>Sitael 1/5 confirmado pelo servidor · fragmento III ainda apagado · Coroa {sealed?.crown.fragments_lit??2}/7.</Text><Text style={s.text}>0 ganho de atributo.</Text></View>;if(!directive)return <Center text="FASE INDISPONÍVEL."/>;
 const p=directive.phase;const texts=directive.requiresCanonicalContent?canon(bundle,directive):[];const timed=['jachin_observation','boaz_judgment_observation','middle_observation'].includes(p.id);
 return <ScrollView contentContainerStyle={s.shell}><Text style={s.eyebrow}>DIA 011 · KETHER · SITAEL 1/5</Text><Text style={s.header}>ESPELHO DO OBSERVADOR</Text><Text style={s.status}>{live?'VAULT E2EE · ONLINE':'VAULT E2EE · FILA CIFRADA OFFLINE'}</Text>{error?<Text style={s.error}>{error}</Text>:null}<View style={s.panel}><Text style={s.eyebrow}>{p.type} · {p.id}</Text>
 {p.type==='NARRATIVE'?<><Text style={s.title}>O espelho não é tribunal nem detector espiritual.</Text><Text style={s.text}>Observe antes de avaliar. Estranheza visual pode surgir de atenção e adaptação; não é prova automática de presença, revelação ou fenômeno externo.</Text></>:null}
 {p.type==='READ'?texts.map((t,i)=><Text key={i} style={s.canon}>{t}</Text>):null}
 {timed?<><Text style={s.timer}>{formatTime(timerRemaining)}</Text>{!timerEnd?<Action label="INICIAR 5 MINUTOS" onPress={()=>startTimer(p.id)}/>:timerReady?<Text style={s.success}>BLOCO DE 5 MINUTOS CONCLUÍDO ✓</Text>:<Text style={s.text}>Pisque quando precisar, respire naturalmente e não fixe agressivamente o olhar.</Text>}<Action danger label="INTERROMPER POR SEGURANÇA" onPress={()=>stop('safety_stop_user_requested')}/></>:null}
 {p.id==='jachin_observation'?<><Input value={feature1} set={setFeature1} placeholder="Característica observada 1 — sem avaliação"/><Input value={feature2} set={setFeature2} placeholder="Característica observada 2 — sem avaliação"/><Input value={feature3} set={setFeature3} placeholder="Característica observada 3 — sem avaliação"/><Input multiline value={relationship} set={setRelationship} placeholder="Como sua relação com a imagem mudou? (será cifrado)"/><Action disabled={!timerReady} label={draft.jachinRef?'REGISTRO CIFRADO ✓':'CIFRAR REGISTRO · CONTINUAR'} onPress={()=>void saveJachin().catch(e=>setError(e instanceof Error?e.message:'vault_save_failed'))}/></>:null}
 {p.id==='boaz_judgment_observation'?<><Input multiline value={judgment} set={setJudgment} placeholder="Qual julgamento apareceu mais vezes? (será cifrado)"/><Toggle label="Nomeei o julgamento como avaliação" value={draft.judgmentLabeling} on={()=>setDraft(d=>({...d,judgmentLabeling:!d.judgmentLabeling}))}/><Toggle label="Retornei aos dados visuais presentes" value={draft.returnedToObservation} on={()=>setDraft(d=>({...d,returnedToObservation:!d.returnedToObservation}))}/><Toggle label="Estranheza visual não é revelação automática" value={draft.strangenessConfirmed} on={()=>setDraft(d=>({...d,strangenessConfirmed:!d.strangenessConfirmed}))}/><Toggle label="Mantive limite seguro e poderia me afastar" value={draft.safeLimit} on={()=>setDraft(d=>({...d,safeLimit:!d.safeLimit}))}/><Action disabled={!timerReady||!draft.judgmentLabeling||!draft.returnedToObservation||!draft.strangenessConfirmed||!draft.safeLimit} label={draft.boazRef?'REGISTRO CIFRADO ✓':'CIFRAR TESTE · CONTINUAR'} onPress={()=>void saveBoaz().catch(e=>setError(e instanceof Error?e.message:'vault_save_failed'))}/></>:null}
 {p.id==='middle_observation'?<><Toggle label="Pratiquei ‘vejo antes de julgar’" value={draft.seeBeforeJudge} on={()=>setDraft(d=>({...d,seeBeforeJudge:!d.seeBeforeJudge}))}/><Toggle label="Concluí a oração devocional com Salmo 91:2" value={draft.prayer} on={()=>setDraft(d=>({...d,prayer:!d.prayer}))}/><Score value={draft.attentionScore} set={v=>setDraft(d=>({...d,attentionScore:v}))}/><Input multiline value={finalNote} set={setFinalNote} placeholder="Nota final de observação (será cifrada)"/><Action disabled={!timerReady||!draft.seeBeforeJudge||!draft.prayer} label={draft.middleRef?'REGISTRO CIFRADO ✓':'CIFRAR INTEGRAÇÃO · CONTINUAR'} onPress={()=>void saveMiddle().catch(e=>setError(e instanceof Error?e.message:'vault_save_failed'))}/></>:null}
 {p.id==='soul_mirror'?<><Input multiline value={soulNote} set={setSoulNote} placeholder="O que observei × o que minha mente interpretou (cifrado)"/><Action label={draft.soulRef?'ESPELHO CIFRADO ✓':'CIFRAR ESPELHO · CONTINUAR'} onPress={()=>void saveSoul().catch(e=>setError(e instanceof Error?e.message:'vault_save_failed'))}/></>:null}
 {p.type==='COMPLETION'?<><Text style={s.title}>Selo de Sitael 1/5</Text><Text style={s.text}>O servidor concede +100 XP, abre o Day 012 e confirma Sitael 1/5. O fragmento III permanece apagado até 5/5.</Text><Toggle label="Conclusão voluntária" value={voluntary} on={()=>setVoluntary(v=>!v)}/><Action disabled={busy||!voluntary||!draft.soulRef} label={busy?'SINCRONIZANDO E SELANDO…':'SINCRONIZAR · SELAR DAY 011'} onPress={()=>void seal()}/></>:null}
 {['NARRATIVE','READ','UNLOCK'].includes(p.type)?<Action label="CONTINUAR" onPress={()=>void complete(p.id)}/>:null}
 </View></ScrollView>
}
function Center({text}:{text:string}){return <View style={s.center}><Text style={s.text}>{text}</Text></View>}
function Action({label,onPress,disabled=false,danger=false}:{label:string;onPress:()=>void;disabled?:boolean;danger?:boolean}){return <Pressable disabled={disabled} onPress={onPress} style={[s.button,danger&&s.danger,disabled&&s.disabled]}><Text style={[s.buttonText,danger&&s.dangerText]}>{label}</Text></Pressable>}
function Toggle({label,value,on}:{label:string;value:boolean;on:()=>void}){return <Action label={`${value?'✓':'○'} ${label}`} onPress={on}/>}
function Input({value,set,placeholder,multiline=false}:{value:string;set:(v:string)=>void;placeholder:string;multiline?:boolean}){return <TextInput multiline={multiline} value={value} onChangeText={set} placeholder={placeholder} placeholderTextColor="#817967" style={[s.input,multiline&&s.multiline]}/>}
function Score({value,set}:{value:number;set:(v:number)=>void}){return <View><Text style={s.text}>ESTABILIDADE DA ATENÇÃO · {value}/10</Text><View style={s.row}>{[0,2,4,6,8,10].map(v=><Pressable key={v} onPress={()=>set(v)} style={s.score}><Text style={s.buttonText}>{v}</Text></Pressable>)}</View></View>}
const s=StyleSheet.create({shell:{padding:20,paddingBottom:80,backgroundColor:'#090910',minHeight:'100%',gap:14},center:{flex:1,padding:28,justifyContent:'center',backgroundColor:'#090910',gap:14},panel:{borderWidth:1,borderColor:'#7f6d36',borderRadius:18,padding:18,gap:14,backgroundColor:'#111018'},row:{flexDirection:'row',flexWrap:'wrap',gap:6},eyebrow:{color:'#d9bd67',fontSize:12,letterSpacing:1.3},status:{color:'#b6aa87',fontSize:12},header:{color:'#f4e6b2',fontSize:25,fontWeight:'800'},title:{color:'#f4e6b2',fontSize:21,fontWeight:'700'},text:{color:'#eee7d7',lineHeight:21},canon:{color:'#eee7d7',lineHeight:24,fontSize:15},timer:{color:'#f4e6b2',fontSize:36,fontVariant:['tabular-nums']},success:{color:'#d9bd67',fontWeight:'700'},input:{borderWidth:1,borderColor:'#6f5f29',borderRadius:10,padding:12,color:'#eee7d7'},multiline:{minHeight:90,textAlignVertical:'top'},error:{color:'#ffb4ab'},button:{borderWidth:1,borderColor:'#9a8240',borderRadius:10,padding:12},danger:{borderColor:'#8e4d4d'},dangerText:{color:'#ffb4ab'},disabled:{opacity:.4},buttonText:{color:'#f4e6b2',fontWeight:'700'},score:{borderWidth:1,borderColor:'#9a8240',borderRadius:8,paddingVertical:8,paddingHorizontal:10}});
