import { useEffect, useMemo, useRef, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { ExperienceDirector, QuestRuntime, createQuestCatalog, type ExperienceDirective, type PlayerContext, type SessionSnapshot } from '@hnk/quest-engine';
import { createBundledQuestLibrary, type RuntimeQuestBundle } from '@hnk/quest-library';
import { sealDay007V1, startDay007PracticeSessionV1 } from '@hnk/supabase-client';
import { useHnkAuth } from '../auth/AuthContext';
import { QuestBehavioralExperimentPhase, type BehavioralExperimentResult } from '../../runtime/QuestBehavioralExperimentPhase';

type Session=Awaited<ReturnType<typeof startDay007PracticeSessionV1>>; type Seal=Extract<Awaited<ReturnType<typeof sealDay007V1>>,{ok:true}>['response'];
function canon(bundle:RuntimeQuestBundle,d:ExperienceDirective){return(d.phase.source.block_ids??[]).map(id=>{const b=bundle.canon.blocks.find(x=>x.id===id);if(!b)throw new Error(`canonical_block_missing:${id}`);return b.text})}
function key(userId:string){return`hnk-mobile-d007-v1-${userId}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`}
export function Day007GoldenV1Mobile(){
 const auth=useHnkAuth();const live=Boolean(auth.configured&&auth.phase==='signed-in'&&auth.client&&auth.userId);const runtimeRef=useRef<QuestRuntime|null>(null);
 const[bundle,setBundle]=useState<RuntimeQuestBundle|null>(null);const[snapshot,setSnapshot]=useState<SessionSnapshot|null>(null);const[session,setSession]=useState<Session|null>(null);const[jachinDone,setJachinDone]=useState(false);const[relaxationRating,setRelaxationRating]=useState(5);const[jachinCatalepsy,setJachinCatalepsy]=useState(false);const[boaz,setBoaz]=useState<BehavioralExperimentResult|null>(null);const[boazCatalepsy,setBoazCatalepsy]=useState(false);const[secondAttempt,setSecondAttempt]=useState(false);const[middleSeconds,setMiddleSeconds]=useState(0);const[mirrorRelax,setMirrorRelax]=useState(5);const[mirrorEffort,setMirrorEffort]=useState(5);const[mirrorChange,setMirrorChange]=useState(5);const[voluntary,setVoluntary]=useState(false);const[safetyStopped,setSafetyStopped]=useState(false);const[sealed,setSealed]=useState<Seal|null>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState<string|null>(null);
 const context=useMemo<PlayerContext>(()=>({mediationMode:'HNK_CANONICAL',accessibility:{reducedMotion:false,audioEnabled:true,microphoneAvailable:false},offline:!live}),[live]);
 useEffect(()=>{let active=true;const library=createBundledQuestLibrary();const catalog=createQuestCatalog(library);void Promise.all([catalog.requireDay(7),library.loadBundle(7)]).then(([definition,loaded])=>{if(!active||!loaded)return;const r=new QuestRuntime(definition);runtimeRef.current=r;setBundle(loaded);setSnapshot(r.start())}).catch(c=>active&&setError(c instanceof Error?c.message:'day007_bundle_load_failed'));return()=>{active=false}},[]);
 const director=useMemo(()=>bundle?new ExperienceDirector(bundle.quest):null,[bundle]);const directive=useMemo(()=>director&&snapshot?.currentPhaseId?director.resolvePhase(snapshot.currentPhaseId,context,snapshot):null,[director,context,snapshot]);
 async function ensureSession(){if(session)return session;if(!live||!auth.client||!auth.userId)return null;const created=await startDay007PracticeSessionV1(auth.client,{clientSessionId:key(auth.userId),appVersion:'0.1.0-mobile-day007-golden-v1'});setSession(created);return created}
 async function completePhase(id:string){const r=runtimeRef.current;if(!r)return;if(id==='jachin_reading')await ensureSession();setSnapshot(r.completePhase(id))}
 async function safetyStop(reason?:string){setSafetyStopped(true);setError(reason??'safety_stop');if(runtimeRef.current)setSnapshot(runtimeRef.current.safetyStop())}
 function resume(){if(runtimeRef.current){setError(null);setSnapshot(runtimeRef.current.resume())}}
 async function seal(){if(!auth.client||!session||!runtimeRef.current||!jachinDone||!boaz||middleSeconds<60||!voluntary)return;setBusy(true);setError(null);try{const result=await sealDay007V1(auth.client,{evidence:{sessionId:session.id,mode:'first_completion',jachin:{relaxationRating,catalepsyReported:jachinCatalepsy},boaz:{spontaneousSensationRating:boaz.after.spontaneous_sensation_rating??5,muscularEffortRating:boaz.after.muscular_effort_rating??5,secondAttemptPerformed:secondAttempt,catalepsyReported:boazCatalepsy},middle:{silentObservationSeconds:middleSeconds},soulMirror:{relaxationSpontaneousRating:mirrorRelax,muscularEffortRating:mirrorEffort,perceptionChangeRating:mirrorChange},safetyStopOccurred:safetyStopped},totalDurationSeconds:middleSeconds+6,secondAttemptPerformed:secondAttempt});if(!result.ok)throw new Error(result.code);setSealed(result.response);setSnapshot(runtimeRef.current.confirmServerCompletion())}catch(c){setError(c instanceof Error?c.message:'day007_completion_failed')}finally{setBusy(false)}}
 if(!bundle||!snapshot||!director)return <View style={styles.center}><Text style={styles.text}>CARREGANDO DAY 007…</Text>{error?<Text style={styles.error}>{error}</Text>:null}</View>;
 if(snapshot.runState==='SAFETY_STOP')return <View style={styles.center}><Text style={styles.title}>Prática pausada com segurança.</Text><Action label="RETOMAR" onPress={resume}/></View>;
 if(snapshot.runState==='COMPLETE')return <View style={styles.center}><Text style={styles.eyebrow}>DIA 007 · JELIEL 2/5</Text><Text style={styles.title}>Dave Elman I registrado.</Text><Text style={styles.text}>{sealed?.first_completion?`+${sealed.xp_awarded} XP canônicos.`:'Revisita sem novo XP.'}</Text><Text style={styles.text}>+1 HIP é servidor-side. Nenhuma catalepsia era necessária.</Text></View>;
 if(!directive)return <View style={styles.center}><Text style={styles.text}>FASE INDISPONÍVEL.</Text></View>;const p=directive.phase;const texts=directive.requiresCanonicalContent?canon(bundle,directive):[];
 return <ScrollView contentContainerStyle={styles.shell}><Text style={styles.eyebrow}>DIA 007 · KETHER · JELIEL 2/5</Text><Text style={styles.headerTitle}>DAVE ELMAN I</Text>{error?<Text style={styles.error}>{error}</Text>:null}<View style={styles.panel}><Text style={styles.eyebrow}>{p.type} · {p.id}</Text>
  {p.type==='NARRATIVE'?<><Text style={styles.title}>Relaxar, testar, liberar.</Text><Text style={styles.text}>Você mantém controle total. Não existe efeito obrigatório.</Text></>:null}
  {p.type==='TERM_REVEAL'?<Text style={styles.text}>{(p.terms??[]).join(' · ')}</Text>:null}
  {p.type==='READ'?texts.map((t,i)=><Text key={i} style={styles.canon}>{t}</Text>):null}
  {p.type==='FOCUS'&&p.id==='jachin_relaxation'?<ElmanSequence silentSeconds={0} onFinish={()=>{setJachinDone(true);void completePhase(p.id)}} onSafetyStop={()=>void safetyStop('elman_jachin_stop')}/>:null}
  {p.type==='JOURNAL'?<><Rating label="RELAXAMENTO" value={relaxationRating} setValue={setRelaxationRating}/><Action label={jachinCatalepsy?'CATALEPSIA RELATADA ✓':'NÃO RELATEI CATALEPSIA'} onPress={()=>setJachinCatalepsy(v=>!v)}/><Text style={styles.text}>A frase livre permanece no Vault.</Text><Action label="REGISTRAR · CONTINUAR" onPress={()=>void completePhase(p.id)}/></>:null}
  {p.type==='EXPERIMENT'?<><QuestBehavioralExperimentPhase directive={directive} onResult={setBoaz} onCompletePhase={completePhase} onSafetyStop={safetyStop}/><Action label={secondAttempt?'SEGUNDA TENTATIVA REGISTRADA ✓':'SEGUNDA TENTATIVA NÃO FEITA'} onPress={()=>setSecondAttempt(v=>!v)}/><Action label={boazCatalepsy?'CATALEPSIA RELATADA ✓':'NÃO RELATEI CATALEPSIA'} onPress={()=>setBoazCatalepsy(v=>!v)}/></>:null}
  {p.type==='FOCUS'&&p.id==='middle_sequence'?<ElmanSequence silentSeconds={60} onFinish={s=>{setMiddleSeconds(s);void completePhase(p.id)}} onSafetyStop={()=>void safetyStop('elman_middle_stop')}/>:null}
  {p.type==='RETURN'?<><Text style={styles.text}>Libere a sugestão, abra os olhos normalmente e confirme orientação.</Text><Action label="ESTOU ORIENTADO · CONTINUAR" onPress={()=>void completePhase(p.id)}/></>:null}
  {p.type==='STRUCTURED_JOURNAL'?<><Rating label="RELAXAMENTO ESPONTÂNEO" value={mirrorRelax} setValue={setMirrorRelax}/><Rating label="ESFORÇO MUSCULAR" value={mirrorEffort} setValue={setMirrorEffort}/><Rating label="MUDANÇA DE PERCEPÇÃO" value={mirrorChange} setValue={setMirrorChange}/><Action label="CONCLUIR ESPELHO" onPress={()=>void completePhase(p.id)}/></>:null}
  {p.type==='COMPLETION'?<><Text style={styles.title}>Selo canônico</Text><Text style={styles.text}>O servidor valida execução; catalepsia não é requisito.</Text><Action label={voluntary?'CONCLUSÃO VOLUNTÁRIA ✓':'CONFIRMAR CONCLUSÃO VOLUNTÁRIA'} onPress={()=>setVoluntary(v=>!v)}/><Action disabled={busy||!voluntary} label={busy?'SELANDO…':'SELAR DAY 007'} onPress={()=>void seal()}/></>:null}
  {['NARRATIVE','TERM_REVEAL','READ','UNLOCK'].includes(p.type)?<Action label="CONTINUAR" onPress={()=>void completePhase(p.id)}/>:null}
 </View></ScrollView>;
}
function Rating({label,value,setValue}:{label:string;value:number;setValue:(v:number)=>void}){return <View style={styles.row}><Text style={styles.text}>{label} · {value}</Text>{[0,2,4,6,8,10].map(v=><Action key={v} label={String(v)} onPress={()=>setValue(v)}/>)}</View>}
function ElmanSequence({silentSeconds,onFinish,onSafetyStop}:{silentSeconds:number;onFinish:(seconds:number)=>void;onSafetyStop:()=>void}){const[testRemaining,setTestRemaining]=useState(3);const[testing,setTesting]=useState(false);const[tested,setTested]=useState(false);const[released,setReleased]=useState(false);const[silent,setSilent]=useState(0);const[silentRunning,setSilentRunning]=useState(false);useEffect(()=>{if(!testing)return;const id=setInterval(()=>setTestRemaining(v=>{if(v<=1){clearInterval(id);setTesting(false);setTested(true);return 0}return v-1}),1000);return()=>clearInterval(id)},[testing]);useEffect(()=>{if(!silentRunning)return;const id=setInterval(()=>setSilent(v=>v+1),1000);return()=>clearInterval(id)},[silentRunning]);const can=tested&&released&&(silentSeconds===0||silent>=silentSeconds);return <View style={styles.practice}><Text style={styles.text}>Relaxe sem apertar os olhos. Você pode abri-los a qualquer momento.</Text><Action disabled={testing||tested} label={testing?`TESTE VOLUNTÁRIO · ${testRemaining}s`:'INICIAR TESTE VOLUNTÁRIO · 3s'} onPress={()=>setTesting(true)}/><Action disabled={!tested||released} label="LIBERAR SUGESTÃO · ABRIR OLHOS" onPress={()=>setReleased(true)}/>{silentSeconds>0&&released?<><Text style={styles.text}>Observação silenciosa: {silent}s / {silentSeconds}s</Text><Action label={silentRunning?'PAUSAR':'INICIAR / RETOMAR 1 MINUTO'} onPress={()=>setSilentRunning(v=>!v)}/></>:null}<Action disabled={!can} label="CONCLUIR SEQUÊNCIA" onPress={()=>onFinish(silentSeconds?Math.max(silent,silentSeconds):3)}/><Action label="SAFETY STOP" onPress={onSafetyStop}/></View>}
function Action({label,onPress,disabled=false}:{label:string;onPress:()=>void;disabled?:boolean}){return <Pressable disabled={disabled} onPress={onPress} style={[styles.button,disabled&&styles.disabled]}><Text style={styles.buttonText}>{label}</Text></Pressable>}
const styles=StyleSheet.create({shell:{padding:20,paddingBottom:80,backgroundColor:'#090910',minHeight:'100%'},center:{flex:1,padding:28,justifyContent:'center',backgroundColor:'#090910',gap:14},panel:{borderWidth:1,borderColor:'#6f5f29',borderRadius:18,padding:18,gap:14,backgroundColor:'#111018'},practice:{gap:10},row:{gap:6},eyebrow:{color:'#d9bd67',fontSize:12,letterSpacing:1.4},headerTitle:{color:'#f4e6b2',fontSize:25,fontWeight:'800'},title:{color:'#f4e6b2',fontSize:22,fontWeight:'700'},text:{color:'#eee7d7',lineHeight:21},canon:{color:'#eee7d7',lineHeight:24,fontSize:15},error:{color:'#ffb4ab'},button:{borderWidth:1,borderColor:'#9a8240',borderRadius:12,padding:12,alignItems:'center'},disabled:{opacity:.4},buttonText:{color:'#f4e6b2',fontWeight:'700'}});
