import {useEffect,useMemo,useRef,useState} from 'react';
import {AppState,Pressable,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';
import * as SecureStore from 'expo-secure-store';
import {ExperienceDirector,QuestRuntime,createQuestCatalog,type ExperienceDirective,type PlayerContext,type SessionSnapshot} from '@hnk/quest-engine';
import {createBundledQuestLibrary,type RuntimeQuestBundle} from '@hnk/quest-library';
import {assertElemiahProgress,loadDay016PracticeSessionV1,sealDay016V1,startDay016PracticeSessionV1} from '@hnk/supabase-client';
import {useHnkAuth} from '../auth/AuthContext';
import {createMobileVaultTextPort} from '../../runtime/MobileVaultTextPort';

type Session=NonNullable<Awaited<ReturnType<typeof loadDay016PracticeSessionV1>>>;
type Seal=Extract<Awaited<ReturnType<typeof sealDay016V1>>,{ok:true}>['response'];
type Block='jachin_preverbal_observation'|'boaz_layer_separation'|'middle_silence_word_prayer';
interface Draft{jachinDone:boolean;automaticLabel:boolean;returnedDirect:boolean;jachinRef:string|null;boazDone:boolean;layersSeparated:boolean;spokenCompared:boolean;associationBoundary:boolean;boazRef:string|null;middleDone:boolean;psalm64:boolean;wordBoundary:boolean;middleRef:string|null;soulRef:string|null;safetyStopped:boolean}
const emptyDraft:Draft={jachinDone:false,automaticLabel:false,returnedDirect:false,jachinRef:null,boazDone:false,layersSeparated:false,spokenCompared:false,associationBoundary:false,boazRef:null,middleDone:false,psalm64:false,wordBoundary:false,middleRef:null,soulRef:null,safetyStopped:false};
function canon(bundle:RuntimeQuestBundle,d:ExperienceDirective){return(d.phase.source.block_ids??[]).map(id=>{const b=bundle.canon.blocks.find(x=>x.id===id);if(!b)throw new Error(`canonical_block_missing:${id}`);return b.text})}
function keys(u:string){return{snapshot:`hnk.quest.d016.${u}.snapshot.v1`,session:`hnk.quest.d016.${u}.session.v1`,draft:`hnk.quest.d016.${u}.draft.v1`}}
async function loadJson<T>(k:string):Promise<T|null>{try{const raw=await SecureStore.getItemAsync(k);return raw?JSON.parse(raw) as T:null}catch{return null}}
async function saveJson(k:string,v:unknown){await SecureStore.setItemAsync(k,JSON.stringify(v))}
function clientId(u:string){return`hnk-mobile-d016-v1-${u}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`}
function clock(elapsed:number){const left=Math.max(0,300-elapsed);return`${String(Math.floor(left/60)).padStart(2,'0')}:${String(left%60).padStart(2,'0')}`}
function middleStage(elapsed:number){if(elapsed<120)return'SILÊNCIO E ESCUTA · 2 MIN';if(elapsed<240)return'PALAVRA ESCOLHIDA · 2 MIN';return'ORAÇÃO / SALMO 6:4 · 1 MIN'}

export function Day016GoldenV1Mobile(){
 const auth=useHnkAuth();const live=Boolean(auth.configured&&auth.phase==='signed-in'&&auth.client&&auth.userId);const runtimeRef=useRef<QuestRuntime|null>(null);
 const[bundle,setBundle]=useState<RuntimeQuestBundle|null>(null);const[snapshot,setSnapshot]=useState<SessionSnapshot|null>(null);const[session,setSession]=useState<Session|null>(null);const[draft,setDraft]=useState<Draft>(emptyDraft);const[loaded,setLoaded]=useState(false);
 const[active,setActive]=useState<Block|null>(null);const[started,setStarted]=useState<number|null>(null);const[now,setNow]=useState(Date.now());const[jachinNote,setJachinNote]=useState('');const[boazNote,setBoazNote]=useState('');const[middleNote,setMiddleNote]=useState('');const[soulNote,setSoulNote]=useState('');const[voluntary,setVoluntary]=useState(false);const[busy,setBusy]=useState(false);const[error,setError]=useState<string|null>(null);const[sealed,setSealed]=useState<Seal|null>(null);
 const context=useMemo<PlayerContext>(()=>({mediationMode:'HNK_CANONICAL',accessibility:{reducedMotion:false,audioEnabled:false,microphoneAvailable:false},offline:!live}),[live]);
 const vault=useMemo(()=>auth.userId?createMobileVaultTextPort(auth.client??null):null,[auth.client,auth.userId]);
 useEffect(()=>{if(!auth.userId)return;let ok=true;const lib=createBundledQuestLibrary(),cat=createQuestCatalog(lib),k=keys(auth.userId);void Promise.all([cat.requireDay(16),lib.loadBundle(16),loadJson<SessionSnapshot>(k.snapshot),loadJson<Session>(k.session),loadJson<Draft>(k.draft)]).then(([def,b,saved,ss,dd])=>{if(!ok||!b)return;const r=new QuestRuntime(def);runtimeRef.current=r;setBundle(b);setSnapshot(saved?r.restore(saved):r.start());if(ss)setSession(ss);setDraft(dd??emptyDraft);setLoaded(true)}).catch(e=>ok&&setError(e instanceof Error?e.message:'day016_load_failed'));return()=>{ok=false}},[auth.userId]);
 useEffect(()=>{if(!auth.userId||!snapshot)return;const k=keys(auth.userId);if(snapshot.runState==='COMPLETE'){void SecureStore.deleteItemAsync(k.snapshot);void SecureStore.deleteItemAsync(k.session);void SecureStore.deleteItemAsync(k.draft)}else void saveJson(k.snapshot,snapshot)},[auth.userId,snapshot]);
 useEffect(()=>{if(auth.userId&&loaded&&snapshot?.runState!=='COMPLETE')void saveJson(keys(auth.userId).draft,draft)},[auth.userId,draft,loaded,snapshot?.runState]);
 useEffect(()=>{const id=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(id)},[]);
 useEffect(()=>{const sub=AppState.addEventListener('change',state=>{if(state!=='active'&&started!==null){setStarted(null);setActive(null);setError('bloco_interrompido_ao_sair_do_app__reinicie_os_5_minutos')}});return()=>sub.remove()},[started]);
 const director=useMemo(()=>bundle?new ExperienceDirector(bundle.quest):null,[bundle]);const directive=useMemo(()=>director&&snapshot?.currentPhaseId?director.resolvePhase(snapshot.currentPhaseId,context,snapshot):null,[director,context,snapshot]);const elapsed=started===null?0:Math.min(300,Math.max(0,Math.floor((now-started)/1000)));
 async function ensureSession(){if(session)return session;if(!live||!auth.client||!auth.userId)throw new Error('online_session_required_before_day016_practice');const s=await startDay016PracticeSessionV1(auth.client,{clientSessionId:clientId(auth.userId),appVersion:'0.1.0-mobile-day016-golden-v1'});setSession(s);await saveJson(keys(auth.userId).session,s);return s}
 async function complete(id:string){setError(null);try{if(id==='jachin_reading')await ensureSession();const r=runtimeRef.current;if(r)setSnapshot(r.completePhase(id))}catch(e){setError(e instanceof Error?e.message:'phase_failed')}}
 function startBlock(block:Block){if(started!==null)return;setError(null);setActive(block);setStarted(Date.now());setNow(Date.now())}
 function finishBlock(block:Block){if(active!==block||started===null||Math.floor((Date.now()-started)/1000)<300){setError('complete_5_minutes_before_advancing');return}setDraft(d=>block==='jachin_preverbal_observation'?{...d,jachinDone:true}:block==='boaz_layer_separation'?{...d,boazDone:true}:{...d,middleDone:true});setStarted(null);setActive(null)}
 function safetyStop(){setStarted(null);setActive(null);setDraft(d=>({...d,safetyStopped:true}));setError('safety_stop__oriente_se_no_ambiente__retome_quando_confortavel');if(runtimeRef.current)setSnapshot(runtimeRef.current.safetyStop())}
 function resume(){setError(null);if(runtimeRef.current)setSnapshot(runtimeRef.current.resume())}
 async function saveJachin(){if(!vault||!auth.userId||!draft.jachinDone||!draft.automaticLabel||!draft.returnedDirect||!jachinNote.trim())throw new Error('jachin_evidence_required');const e=await vault.saveText({userId:auth.userId,day:16,kind:'journal',plaintext:JSON.stringify({schema:'hnk-day016-jachin-v1',threePrelabelPerceptionsAndAutomaticLabel:jachinNote.trim()})});setDraft(d=>({...d,jachinRef:e.entryId}));setJachinNote('');await complete('jachin_preverbal_observation')}
 async function saveBoaz(){if(!vault||!auth.userId||!draft.boazDone||!draft.layersSeparated||!draft.spokenCompared||!draft.associationBoundary||!boazNote.trim())throw new Error('boaz_layers_required');const e=await vault.saveText({userId:auth.userId,day:16,kind:'journal',plaintext:JSON.stringify({schema:'hnk-day016-boaz-v1',perceptionInterpretationBelief:boazNote.trim()})});setDraft(d=>({...d,boazRef:e.entryId}));setBoazNote('');await complete('boaz_layer_separation')}
 async function saveMiddle(){if(!vault||!auth.userId||!draft.middleDone||!draft.psalm64||!draft.wordBoundary||!middleNote.trim())throw new Error('middle_integration_required');const e=await vault.saveText({userId:auth.userId,day:16,kind:'journal',plaintext:JSON.stringify({schema:'hnk-day016-middle-v1',limitOfWordsPrelabelExperienceAndPrayer:middleNote.trim()})});setDraft(d=>({...d,middleRef:e.entryId}));setMiddleNote('');await complete('middle_silence_word_prayer')}
 async function saveSoul(){if(!vault||!auth.userId||!soulNote.trim())throw new Error('soul_mirror_required');const e=await vault.saveText({userId:auth.userId,day:16,kind:'journal',plaintext:JSON.stringify({schema:'hnk-day016-soul-v1',helpfulWordVsReplacingLabel:soulNote.trim()})});setDraft(d=>({...d,soulRef:e.entryId}));setSoulNote('');await complete('soul_mirror')}
 async function seal(){if(!runtimeRef.current||!live||!auth.client||!auth.userId||!session||!vault||!draft.jachinRef||!draft.boazRef||!draft.middleRef||!draft.soulRef||!voluntary)return;setBusy(true);setError(null);try{await vault.flushPending(auth.userId);const jr=await vault.resolveEntryId(auth.userId,draft.jachinRef),br=await vault.resolveEntryId(auth.userId,draft.boazRef),mr=await vault.resolveEntryId(auth.userId,draft.middleRef),sr=await vault.resolveEntryId(auth.userId,draft.soulRef);if(!jr||!br||!mr||!sr)throw new Error('vault_sync_required_before_completion');const result=await sealDay016V1(auth.client,{evidence:{sessionId:session.id,mode:'first_completion',jachinDurationSeconds:300,prelabelPerceptionCount:3,automaticLabelNoticed:draft.automaticLabel,returnedToDirectExperience:draft.returnedDirect,prelabelAndLabelVaultEntryRef:jr,boazDurationSeconds:300,perceptionInterpretationBeliefSeparated:draft.layersSeparated,spokenDescriptionCompared:draft.spokenCompared,associationNotExternalFactConfirmed:draft.associationBoundary,layersVaultEntryRef:br,middleDurationSeconds:300,silenceListeningSeconds:120,chosenWordObservationSeconds:120,finalPrayerSeconds:60,psalm64PrayerConfirmed:draft.psalm64,wordNotTotalRealityConfirmed:draft.wordBoundary,integrationVaultEntryRef:mr,soulMirrorCompleted:true,helpfulWordVsReplacingLabelVaultEntryRef:sr,safetyStopOccurred:draft.safetyStopped},totalDurationSeconds:Math.max(900,Math.floor((Date.now()-new Date(session.started_at).getTime())/1000))});if(!result.ok)throw new Error(result.code);assertElemiahProgress(result.response.crown,1);setSealed(result.response);setSnapshot(runtimeRef.current.confirmServerCompletion())}catch(e){setError(e instanceof Error?e.message:'day016_completion_failed')}finally{setBusy(false)}}
 if(!auth.userId)return <Center text="ENTRE NO ÁTRIO PARA INICIAR O DIA 016."/>;if(!bundle||!snapshot||!director)return <Center text={error??'CARREGANDO DAY 016…'}/>;if(snapshot.runState==='SAFETY_STOP')return <View style={s.center}><Text style={s.title}>PRÁTICA INTERROMPIDA</Text><Text style={s.text}>Oriente-se no ambiente real e retome quando estiver confortável.</Text><Action label="RETOMAR" onPress={resume}/></View>;if(snapshot.runState==='COMPLETE')return <View style={s.center}><Text style={s.eyebrow}>DIA 016 · ELEMIAH 1/5</Text><Text style={s.title}>RUÍNA DO CONTROLE VERBAL CONCLUÍDA</Text><Text style={s.text}>{sealed?.first_completion?`+${sealed.xp_awarded} XP canônicos.`:'Revisita sem novo XP.'}</Text><Text style={s.text}>Elemiah 1/5 confirmado pelo servidor · fragmento IV ainda apagado · Coroa {sealed?.crown.fragments_lit??3}/7.</Text></View>;if(!directive)return <Center text="FASE INDISPONÍVEL."/>;
 const p=directive.phase,texts=directive.requiresCanonicalContent?canon(bundle,directive):[],block=p.id as Block,isBlock=['jachin_preverbal_observation','boaz_layer_separation','middle_silence_word_prayer'].includes(p.id),done=block==='jachin_preverbal_observation'?draft.jachinDone:block==='boaz_layer_separation'?draft.boazDone:draft.middleDone;
 return <ScrollView contentContainerStyle={s.shell}><Text style={s.eyebrow}>DIA 016 · KETHER · ELEMIAH 1/5</Text><Text style={s.header}>RUÍNA DO CONTROLE VERBAL</Text><Text style={s.status}>{live?'VAULT E2EE · ONLINE':'VAULT E2EE · FILA CIFRADA OFFLINE'} · ÁUDIO DESATIVADO V1</Text>{error?<Text style={s.error}>{error}</Text>:null}<View style={s.panel}><Text style={s.eyebrow}>{p.type} · {p.id}</Text>{p.type==='NARRATIVE'?<><Text style={s.title}>Perceber antes de nomear.</Text><Text style={s.text}>A linguagem continua útil; o treino distingue rótulo, experiência e interpretação.</Text></>:null}{p.type==='READ'?texts.map((t,i)=><Text key={i} style={s.canon}>{t}</Text>):null}
 {isBlock?<><Text style={s.timer}>{done?'00:00':clock(active===block?elapsed:0)}</Text>{block==='middle_silence_word_prayer'&&active===block?<Text style={s.stage}>{middleStage(elapsed)}</Text>:null}{done?<Text style={s.stage}>5 MINUTOS CONCLUÍDOS ✓</Text>:active===block?<Action label={elapsed>=300?'CONFIRMAR 5 MINUTOS':'MANTER PRÁTICA'} onPress={()=>finishBlock(block)} disabled={elapsed<300}/>:<Action label="INICIAR 5 MINUTOS" onPress={()=>startBlock(block)}/>}<Action label="SAFETY STOP" onPress={safetyStop}/></>:null}
 {p.id==='jachin_preverbal_observation'?<><Toggle label="Notei um rótulo automático" value={draft.automaticLabel} on={()=>setDraft(d=>({...d,automaticLabel:!d.automaticLabel}))}/><Toggle label="Voltei à experiência direta" value={draft.returnedDirect} on={()=>setDraft(d=>({...d,returnedDirect:!d.returnedDirect}))}/><Input value={jachinNote} set={setJachinNote} placeholder="3 percepções antes de nomear + rótulo + mudança de atenção"/><Action label="CIFRAR E CONTINUAR" onPress={()=>void saveJachin()}/></>:null}
 {p.id==='boaz_layer_separation'?<><Toggle label="Separei percepção, interpretação e crença" value={draft.layersSeparated} on={()=>setDraft(d=>({...d,layersSeparated:!d.layersSeparated}))}/><Toggle label="Comparei descrição falada e experiência" value={draft.spokenCompared} on={()=>setDraft(d=>({...d,spokenCompared:!d.spokenCompared}))}/><Toggle label="Associação pessoal não é fato externo automático" value={draft.associationBoundary} on={()=>setDraft(d=>({...d,associationBoundary:!d.associationBoundary}))}/><Input value={boazNote} set={setBoazNote} placeholder="Percepção / interpretação / crença"/><Action label="CIFRAR CAMADAS" onPress={()=>void saveBoaz()}/></>:null}
 {p.id==='middle_silence_word_prayer'?<><Toggle label="Concluí a oração orientada pelo Salmo 6:4" value={draft.psalm64} on={()=>setDraft(d=>({...d,psalm64:!d.psalm64}))}/><Toggle label="A palavra orienta sem conter toda a realidade" value={draft.wordBoundary} on={()=>setDraft(d=>({...d,wordBoundary:!d.wordBoundary}))}/><Input value={middleNote} set={setMiddleNote} placeholder="Limite das palavras + experiência pré-rótulo + oração"/><Action label="CIFRAR INTEGRAÇÃO" onPress={()=>void saveMiddle()}/></>:null}
 {p.id==='soul_mirror'?<><Input value={soulNote} set={setSoulNote} placeholder="Onde a palavra ajudou e onde o rótulo tentou substituir a experiência"/><Action label="CIFRAR ESPELHO DA ALMA" onPress={()=>void saveSoul()}/></>:null}
 {p.id==='completion'?<><Toggle label="Confirmo voluntariamente a conclusão" value={voluntary} on={()=>setVoluntary(v=>!v)}/><Action label={busy?'SELANDO…':'SELAR DAY 016'} onPress={()=>void seal()} disabled={busy||!voluntary||!live}/></>:null}
 {!['jachin_preverbal_observation','boaz_layer_separation','middle_silence_word_prayer','soul_mirror','completion'].includes(p.id)?<Action label="CONTINUAR" onPress={()=>void complete(p.id)}/>:null}</View></ScrollView>
}
function Center({text}:{text:string}){return <View style={s.center}><Text style={s.title}>{text}</Text></View>}
function Action({label,onPress,disabled=false}:{label:string;onPress:()=>void;disabled?:boolean}){return <Pressable disabled={disabled} onPress={onPress} style={[s.action,disabled&&s.disabled]}><Text style={s.actionText}>{label}</Text></Pressable>}
function Toggle({label,value,on}:{label:string;value:boolean;on:()=>void}){return <Pressable onPress={on}><Text style={s.text}>{value?'☑':'☐'} {label}</Text></Pressable>}
function Input({value,set,placeholder}:{value:string;set:(v:string)=>void;placeholder:string}){return <TextInput style={s.input} value={value} onChangeText={set} placeholder={placeholder} placeholderTextColor="#77707d" multiline/>}
const s=StyleSheet.create({shell:{padding:22,paddingBottom:80,backgroundColor:'#090910',gap:14},center:{flex:1,minHeight:640,justifyContent:'center',padding:24,backgroundColor:'#090910'},panel:{borderWidth:1,borderColor:'#6b657f',borderRadius:18,padding:18,gap:12},eyebrow:{color:'#b7aacd',fontSize:12,letterSpacing:1.2},header:{color:'#f1ebf7',fontSize:29,fontWeight:'800'},title:{color:'#f1ebf7',fontSize:21,fontWeight:'700'},text:{color:'#ddd5e5',fontSize:16,lineHeight:23},canon:{color:'#ddd5e5',fontSize:16,lineHeight:26},status:{color:'#aca3b4'},error:{color:'#ffb4ab'},timer:{color:'#f1ebf7',fontSize:34,fontWeight:'700'},stage:{color:'#c6b6df',fontWeight:'700'},input:{minHeight:100,borderWidth:1,borderColor:'#57505e',borderRadius:10,padding:12,color:'#f1ebf7',textAlignVertical:'top'},action:{padding:13,borderRadius:10,borderWidth:1,borderColor:'#736589'},actionText:{color:'#f1ebf7',fontWeight:'700',textAlign:'center'},disabled:{opacity:.45}});
