import {useEffect,useMemo,useRef,useState} from 'react';
import {AppState,Pressable,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';
import * as SecureStore from 'expo-secure-store';
import {ExperienceDirector,QuestRuntime,createQuestCatalog,type ExperienceDirective,type PlayerContext,type SessionSnapshot} from '@hnk/quest-engine';
import {createBundledQuestLibrary,type RuntimeQuestBundle} from '@hnk/quest-library';
import {assertElemiahProgress,loadDay018PracticeSessionV1,sealDay018V1,startDay018PracticeSessionV1} from '@hnk/supabase-client';
import {useHnkAuth} from '../auth/AuthContext';
import {createMobileVaultTextPort} from '../../runtime/MobileVaultTextPort';

type Session=NonNullable<Awaited<ReturnType<typeof loadDay018PracticeSessionV1>>>;
type Seal=Extract<Awaited<ReturnType<typeof sealDay018V1>>,{ok:true}>['response'];
type Block='jachin_resonance_map'|'boaz_safety_comparison'|'middle_integration';
type Response='STRONG'|'WEAK'|'ABSENT';
interface Draft{jachinDuration:number;skull:Response;chest:Response;umbilical:Response;posture:boolean;moderate:boolean;noForce:boolean;mapRef:string|null;boazDuration:number;throat:boolean;jaw:boolean;breathing:boolean;noPain:boolean;noBreathManip:boolean;notActivation:boolean;adjustRef:string|null;middleDuration:number;threeRegions:boolean;slowed:boolean;normalBreathing:boolean;psalm64:boolean;specialNotRequired:boolean;distinguished:boolean;comfort:number;integrationRef:string|null;soulRef:string|null;safetyStopped:boolean}
const emptyDraft:Draft={jachinDuration:0,skull:'ABSENT',chest:'ABSENT',umbilical:'ABSENT',posture:false,moderate:false,noForce:false,mapRef:null,boazDuration:0,throat:false,jaw:false,breathing:false,noPain:false,noBreathManip:false,notActivation:false,adjustRef:null,middleDuration:0,threeRegions:false,slowed:false,normalBreathing:false,psalm64:false,specialNotRequired:false,distinguished:false,comfort:5,integrationRef:null,soulRef:null,safetyStopped:false};
function canon(bundle:RuntimeQuestBundle,d:ExperienceDirective){return(d.phase.source.block_ids??[]).map(id=>{const b=bundle.canon.blocks.find(x=>x.id===id);if(!b)throw new Error(`canonical_block_missing:${id}`);return b.text})}
function keys(u:string){return{snapshot:`hnk.quest.d018.${u}.snapshot.v1`,session:`hnk.quest.d018.${u}.session.v1`,draft:`hnk.quest.d018.${u}.draft.v1`}}
async function loadJson<T>(k:string):Promise<T|null>{try{const raw=await SecureStore.getItemAsync(k);return raw?JSON.parse(raw) as T:null}catch{return null}}
async function saveJson(k:string,v:unknown){await SecureStore.setItemAsync(k,JSON.stringify(v))}
function clientId(u:string){return`hnk-mobile-d018-v1-${u}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`}
function clock(elapsed:number,max:number){const left=Math.max(0,max-elapsed);return`${String(Math.floor(left/60)).padStart(2,'0')}:${String(left%60).padStart(2,'0')}`}

export function Day018GoldenV1Mobile(){
 const auth=useHnkAuth();const live=Boolean(auth.configured&&auth.phase==='signed-in'&&auth.client&&auth.userId);const runtimeRef=useRef<QuestRuntime|null>(null);
 const[bundle,setBundle]=useState<RuntimeQuestBundle|null>(null);const[snapshot,setSnapshot]=useState<SessionSnapshot|null>(null);const[session,setSession]=useState<Session|null>(null);const[draft,setDraft]=useState<Draft>(emptyDraft);const[loaded,setLoaded]=useState(false);
 const[active,setActive]=useState<Block|null>(null);const[started,setStarted]=useState<number|null>(null);const[now,setNow]=useState(Date.now());const[mapNote,setMapNote]=useState('');const[adjustNote,setAdjustNote]=useState('');const[integrationNote,setIntegrationNote]=useState('');const[soulNote,setSoulNote]=useState('');const[voluntary,setVoluntary]=useState(false);const[busy,setBusy]=useState(false);const[error,setError]=useState<string|null>(null);const[sealed,setSealed]=useState<Seal|null>(null);
 const context=useMemo<PlayerContext>(()=>({mediationMode:'HNK_CANONICAL',accessibility:{reducedMotion:false,audioEnabled:false,microphoneAvailable:false},offline:!live}),[live]);
 const vault=useMemo(()=>auth.userId?createMobileVaultTextPort(auth.client??null):null,[auth.client,auth.userId]);
 useEffect(()=>{if(!auth.userId)return;let ok=true;const lib=createBundledQuestLibrary(),cat=createQuestCatalog(lib),k=keys(auth.userId);void Promise.all([cat.requireDay(18),lib.loadBundle(18),loadJson<SessionSnapshot>(k.snapshot),loadJson<Session>(k.session),loadJson<Draft>(k.draft)]).then(([def,b,saved,ss,dd])=>{if(!ok||!b)return;const r=new QuestRuntime(def);runtimeRef.current=r;setBundle(b);setSnapshot(saved?r.restore(saved):r.start());if(ss)setSession(ss);setDraft(dd??emptyDraft);setLoaded(true)}).catch(e=>ok&&setError(e instanceof Error?e.message:'day018_load_failed'));return()=>{ok=false}},[auth.userId]);
 useEffect(()=>{if(!auth.userId||!snapshot)return;const k=keys(auth.userId);if(snapshot.runState==='COMPLETE'){void SecureStore.deleteItemAsync(k.snapshot);void SecureStore.deleteItemAsync(k.session);void SecureStore.deleteItemAsync(k.draft)}else void saveJson(k.snapshot,snapshot)},[auth.userId,snapshot]);
 useEffect(()=>{if(auth.userId&&loaded&&snapshot?.runState!=='COMPLETE')void saveJson(keys(auth.userId).draft,draft)},[auth.userId,draft,loaded,snapshot?.runState]);
 useEffect(()=>{const id=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(id)},[]);
 useEffect(()=>{const sub=AppState.addEventListener('change',state=>{if(state!=='active'&&started!==null){setStarted(null);setActive(null);setError('bloco_interrompido_ao_sair_do_app__tempo_corrente_descartado')}});return()=>sub.remove()},[started]);
 const director=useMemo(()=>bundle?new ExperienceDirector(bundle.quest):null,[bundle]);const directive=useMemo(()=>director&&snapshot?.currentPhaseId?director.resolvePhase(snapshot.currentPhaseId,context,snapshot):null,[director,context,snapshot]);const max=active==='middle_integration'?300:600;const elapsed=started===null?0:Math.min(max,Math.max(0,Math.floor((now-started)/1000)));
 async function ensureSession(){if(session)return session;if(!live||!auth.client||!auth.userId)throw new Error('online_session_required_before_day018_practice');const s=await startDay018PracticeSessionV1(auth.client,{clientSessionId:clientId(auth.userId),appVersion:'0.1.0-mobile-day018-golden-v1'});setSession(s);await saveJson(keys(auth.userId).session,s);return s}
 async function complete(id:string){setError(null);try{if(id==='jachin_reading')await ensureSession();if(runtimeRef.current)setSnapshot(runtimeRef.current.completePhase(id))}catch(e){setError(e instanceof Error?e.message:'phase_failed')}}
 function startBlock(b:Block){if(started!==null)return;setActive(b);setStarted(Date.now());setNow(Date.now());setError(null)}
 function finishBlock(b:Block){if(active!==b||started===null)return;const e=Math.min(b==='middle_integration'?300:600,Math.max(0,Math.floor((Date.now()-started)/1000)));if(e<1){setError('practice_requires_at_least_1_second');return}setDraft(d=>b==='jachin_resonance_map'?{...d,jachinDuration:e}:b==='boaz_safety_comparison'?{...d,boazDuration:e}:{...d,middleDuration:e});setStarted(null);setActive(null)}
 function safetyStop(){setStarted(null);setActive(null);setDraft(d=>({...d,safetyStopped:true}));setError('safety_stop__pare_a_vocalizacao__respire_normalmente__reoriente_se');if(runtimeRef.current)setSnapshot(runtimeRef.current.safetyStop())}
 function resume(){setError(null);if(runtimeRef.current)setSnapshot(runtimeRef.current.resume())}
 async function saveMap(){if(!vault||!auth.userId||draft.jachinDuration<1||!draft.posture||!draft.moderate||!draft.noForce||!mapNote.trim())throw new Error('resonance_map_required');const e=await vault.saveText({userId:auth.userId,day:18,kind:'journal',plaintext:JSON.stringify({schema:'hnk-day018-map-v1',note:mapNote.trim(),responses:{skull:draft.skull,chest:draft.chest,umbilical:draft.umbilical}})});setDraft(d=>({...d,mapRef:e.entryId}));setMapNote('');await complete('jachin_resonance_map')}
 async function saveBoaz(){if(!vault||!auth.userId||draft.boazDuration<1||!draft.throat||!draft.jaw||!draft.breathing||!draft.noPain||!draft.noBreathManip||!draft.notActivation||!adjustNote.trim())throw new Error('boaz_safety_required');const e=await vault.saveText({userId:auth.userId,day:18,kind:'journal',plaintext:JSON.stringify({schema:'hnk-day018-boaz-v1',adjustment:adjustNote.trim()})});setDraft(d=>({...d,adjustRef:e.entryId}));setAdjustNote('');await complete('boaz_safety_comparison')}
 async function saveMiddle(){if(!vault||!auth.userId||draft.middleDuration<1||!draft.threeRegions||!draft.slowed||!draft.normalBreathing||!draft.psalm64||!draft.specialNotRequired||!draft.distinguished||!integrationNote.trim())throw new Error('middle_integration_required');const e=await vault.saveText({userId:auth.userId,day:18,kind:'journal',plaintext:JSON.stringify({schema:'hnk-day018-middle-v1',integration:integrationNote.trim()})});setDraft(d=>({...d,integrationRef:e.entryId}));setIntegrationNote('');await complete('middle_integration')}
 async function saveSoul(){if(!vault||!auth.userId||!soulNote.trim())throw new Error('soul_mirror_required');const e=await vault.saveText({userId:auth.userId,day:18,kind:'journal',plaintext:JSON.stringify({schema:'hnk-day018-soul-v1',fourLayers:soulNote.trim()})});setDraft(d=>({...d,soulRef:e.entryId}));setSoulNote('');await complete('soul_mirror')}
 async function seal(){if(!runtimeRef.current||!live||!auth.client||!auth.userId||!session||!vault||!draft.mapRef||!draft.adjustRef||!draft.integrationRef||!draft.soulRef||!voluntary)return;setBusy(true);setError(null);try{await vault.flushPending(auth.userId);const a=await vault.resolveEntryId(auth.userId,draft.mapRef),b=await vault.resolveEntryId(auth.userId,draft.adjustRef),c=await vault.resolveEntryId(auth.userId,draft.integrationRef),d=await vault.resolveEntryId(auth.userId,draft.soulRef);if(!a||!b||!c||!d)throw new Error('vault_sync_required_before_completion');const result=await sealDay018V1(auth.client,{evidence:{sessionId:session.id,mode:'first_completion',jachinDurationSeconds:draft.jachinDuration,skullBase:draft.skull,chestCenter:draft.chest,umbilical:draft.umbilical,comfortablePostureConfirmed:draft.posture,moderateVolumeConfirmed:draft.moderate,noForcingConfirmed:draft.noForce,mapVaultEntryRef:a,boazDurationSeconds:draft.boazDuration,throatFreeConfirmed:draft.throat,jawRelaxedConfirmed:draft.jaw,breathingAvailableConfirmed:draft.breathing,noPainConfirmed:draft.noPain,noBreathRetentionOrHyperventilationConfirmed:draft.noBreathManip,perceptionNotSpiritualActivationConfirmed:draft.notActivation,adjustmentVaultEntryRef:b,middleDurationSeconds:draft.middleDuration,threeRegionsRevisitedConfirmed:draft.threeRegions,slowedToSilenceConfirmed:draft.slowed,normalBreathingConfirmed:draft.normalBreathing,psalm64PrayerConfirmed:draft.psalm64,specialSensationNotRequiredConfirmed:draft.specialNotRequired,sensationEmotionExpectationInterpretationDistinguished:draft.distinguished,comfortScore:draft.comfort,integrationVaultEntryRef:c,soulMirrorCompleted:true,fourLayersVaultEntryRef:d,safetyStopOccurred:draft.safetyStopped},totalDurationSeconds:draft.jachinDuration+draft.boazDuration+draft.middleDuration});if(!result.ok)throw new Error(result.code);assertElemiahProgress(result.response.crown,3);setSealed(result.response);setSnapshot(runtimeRef.current.confirmServerCompletion())}catch(e){setError(e instanceof Error?e.message:'day018_completion_failed')}finally{setBusy(false)}}
 if(!auth.userId)return <Center text="ENTRE NO ÁTRIO PARA INICIAR O DIA 018."/>;if(!bundle||!snapshot||!director)return <Center text={error??'CARREGANDO DAY 018…'}/>;if(snapshot.runState==='SAFETY_STOP')return <View style={s.center}><Text style={s.title}>PRÁTICA INTERROMPIDA</Text><Text style={s.text}>Pare a vocalização, respire normalmente e reoriente-se. Retome apenas se estiver confortável.</Text><Action label="RETOMAR" onPress={resume}/></View>;if(snapshot.runState==='COMPLETE')return <View style={s.center}><Text style={s.eyebrow}>DIA 018 · ELEMIAH 3/5</Text><Text style={s.title}>MAPA DE RESSONÂNCIA CONCLUÍDO</Text><Text style={s.text}>{sealed?.first_completion?`+${sealed.xp_awarded} XP canônicos.`:'Revisita sem novo XP.'}</Text><Text style={s.text}>Elemiah 3/5 confirmado pelo servidor · fragmento IV ainda apagado · Coroa {sealed?.crown.fragments_lit??3}/7.</Text><Text style={s.text}>Resposta ausente também é dado válido.</Text></View>;if(!directive)return <Center text="FASE INDISPONÍVEL."/>;
 const p=directive.phase,texts=directive.requiresCanonicalContent?canon(bundle,directive):[],block=p.id as Block,isBlock=['jachin_resonance_map','boaz_safety_comparison','middle_integration'].includes(p.id),done=block==='jachin_resonance_map'?draft.jachinDuration>0:block==='boaz_safety_comparison'?draft.boazDuration>0:draft.middleDuration>0,blockMax=block==='middle_integration'?300:600;
 return <ScrollView contentContainerStyle={s.shell}><Text style={s.eyebrow}>DIA 018 · KETHER · ELEMIAH 3/5</Text><Text style={s.header}>O SOM EXTÁTICO DO CORPO</Text><Text style={s.status}>{live?'VAULT E2EE · ONLINE':'VAULT E2EE · FILA CIFRADA OFFLINE'} · ÁUDIO DESATIVADO V1</Text>{error?<Text style={s.error}>{error}</Text>:null}<View style={s.panel}><Text style={s.eyebrow}>{p.type} · {p.id}</Text>{p.type==='NARRATIVE'?<><Text style={s.title}>Mapear não é fabricar sensação.</Text><Text style={s.text}>STRONG, WEAK e ABSENT são igualmente válidos. Sensação corporal não é diagnóstico nem ativação espiritual automática.</Text></>:null}{p.type==='READ'?texts.map((t,i)=><Text key={i} style={s.canon}>{t}</Text>):null}{isBlock?<><Text style={s.timer}>{done?`${block==='middle_integration'?draft.middleDuration:block==='jachin_resonance_map'?draft.jachinDuration:draft.boazDuration}s`:clock(active===block?elapsed:0,blockMax)}</Text>{active===block?<Action label={elapsed<1?'INICIANDO…':'ENCERRAR ESTE BLOCO'} onPress={()=>finishBlock(block)} disabled={elapsed<1}/>:done?<Text style={s.stage}>BLOCO REGISTRADO ✓</Text>:<Action label="INICIAR BLOCO" onPress={()=>startBlock(block)}/>}<Action label="SAFETY STOP" onPress={safetyStop}/></>:null}
 {p.id==='jachin_resonance_map'?<><ResponsePicker label="Base do crânio" value={draft.skull} set={v=>setDraft(d=>({...d,skull:v}))}/><ResponsePicker label="Centro do peito" value={draft.chest} set={v=>setDraft(d=>({...d,chest:v}))}/><ResponsePicker label="Região umbilical" value={draft.umbilical} set={v=>setDraft(d=>({...d,umbilical:v}))}/><Toggle label="Postura confortável" value={draft.posture} on={()=>setDraft(d=>({...d,posture:!d.posture}))}/><Toggle label="Volume moderado" value={draft.moderate} on={()=>setDraft(d=>({...d,moderate:!d.moderate}))}/><Toggle label="Não forcei a voz para produzir efeito" value={draft.noForce} on={()=>setDraft(d=>({...d,noForce:!d.noForce}))}/><Input value={mapNote} set={setMapNote} placeholder="Vibração, neutralidade, timbre, postura e experiência corporal"/><Action label="CIFRAR MAPA" onPress={()=>void saveMap()}/></>:null}
 {p.id==='boaz_safety_comparison'?<><Toggle label="Garganta livre" value={draft.throat} on={()=>setDraft(d=>({...d,throat:!d.throat}))}/><Toggle label="Mandíbula relaxada" value={draft.jaw} on={()=>setDraft(d=>({...d,jaw:!d.jaw}))}/><Toggle label="Respiração disponível" value={draft.breathing} on={()=>setDraft(d=>({...d,breathing:!d.breathing}))}/><Toggle label="Ausência de dor" value={draft.noPain} on={()=>setDraft(d=>({...d,noPain:!d.noPain}))}/><Toggle label="Não retive ar nem hiperventilei" value={draft.noBreathManip} on={()=>setDraft(d=>({...d,noBreathManip:!d.noBreathManip}))}/><Toggle label="Sensação corporal não é ativação espiritual automática" value={draft.notActivation} on={()=>setDraft(d=>({...d,notActivation:!d.notActivation}))}/><Input value={adjustNote} set={setAdjustNote} placeholder="Desconforto/ausência e ajuste usado para preservar a voz"/><Action label="CIFRAR BOAZ" onPress={()=>void saveBoaz()}/></>:null}
 {p.id==='middle_integration'?<><Toggle label="Revisitei as três regiões" value={draft.threeRegions} on={()=>setDraft(d=>({...d,threeRegions:!d.threeRegions}))}/><Toggle label="Reduzi o som até o silêncio" value={draft.slowed} on={()=>setDraft(d=>({...d,slowed:!d.slowed}))}/><Toggle label="Voltei à respiração normal" value={draft.normalBreathing} on={()=>setDraft(d=>({...d,normalBreathing:!d.normalBreathing}))}/><Toggle label="Concluí oração orientada pelo Salmo 6:4" value={draft.psalm64} on={()=>setDraft(d=>({...d,psalm64:!d.psalm64}))}/><Toggle label="Sensação especial não é requisito" value={draft.specialNotRequired} on={()=>setDraft(d=>({...d,specialNotRequired:!d.specialNotRequired}))}/><Toggle label="Distingui sensação, emoção, expectativa e interpretação" value={draft.distinguished} on={()=>setDraft(d=>({...d,distinguished:!d.distinguished}))}/><Score label="Conforto" value={draft.comfort} set={v=>setDraft(d=>({...d,comfort:v}))}/><Input value={integrationNote} set={setIntegrationNote} placeholder="Mapa final e distinção entre as quatro camadas"/><Action label="CIFRAR INTEGRAÇÃO" onPress={()=>void saveMiddle()}/></>:null}
 {p.id==='soul_mirror'?<><Input value={soulNote} set={setSoulNote} placeholder="Corpo / emoção / expectativa / significado atribuído depois"/><Action label="CIFRAR ESPELHO" onPress={()=>void saveSoul()}/></>:null}
 {p.id==='completion'?<><Toggle label="Concluo voluntariamente; nenhuma sensação especial foi exigida" value={voluntary} on={()=>setVoluntary(v=>!v)}/><Action label={busy?'SELANDO…':'SINCRONIZAR · SELAR DAY 018'} onPress={()=>void seal()} disabled={!live||busy||!voluntary}/></>:null}
 {!['jachin_resonance_map','boaz_safety_comparison','middle_integration','soul_mirror','completion'].includes(p.id)&&p.type!=='READ'&&p.type!=='NARRATIVE'?<Action label="CONTINUAR" onPress={()=>void complete(p.id)}/>:null}</View></ScrollView>
}
function Action({label,onPress,disabled=false}:{label:string;onPress:()=>void;disabled?:boolean}){return <Pressable disabled={disabled} onPress={onPress} style={[s.button,disabled&&s.disabled]}><Text style={s.buttonText}>{label}</Text></Pressable>}
function Toggle({label,value,on}:{label:string;value:boolean;on:()=>void}){return <Pressable onPress={on} style={s.toggle}><Text style={s.text}>{value?'☑':'☐'} {label}</Text></Pressable>}
function Input({value,set,placeholder}:{value:string;set:(v:string)=>void;placeholder:string}){return <TextInput multiline value={value} onChangeText={set} placeholder={placeholder} placeholderTextColor="#817d86" style={s.input}/>}function Score({label,value,set}:{label:string;value:number;set:(v:number)=>void}){return <View><Text style={s.text}>{label}: {value}/10</Text><View style={s.row}>{[0,2,4,6,8,10].map(v=><Pressable key={v} onPress={()=>set(v)} style={s.small}><Text style={s.buttonText}>{v}</Text></Pressable>)}</View></View>}function ResponsePicker({label,value,set}:{label:string;value:Response;set:(v:Response)=>void}){return <View><Text style={s.text}>{label}: {value}</Text><View style={s.row}>{(['ABSENT','WEAK','STRONG'] as Response[]).map(v=><Pressable key={v} onPress={()=>set(v)} style={s.small}><Text style={s.buttonText}>{v}</Text></Pressable>)}</View></View>}function Center({text}:{text:string}){return <View style={s.center}><Text style={s.text}>{text}</Text></View>}
const s=StyleSheet.create({shell:{padding:22,paddingBottom:80,backgroundColor:'#090910',minHeight:'100%'},center:{flex:1,justifyContent:'center',alignItems:'center',padding:24,backgroundColor:'#090910'},panel:{borderWidth:1,borderColor:'#607d79',borderRadius:18,padding:18,gap:12,backgroundColor:'#111018'},header:{fontSize:28,fontWeight:'800',color:'#f1ead9'},title:{fontSize:22,fontWeight:'700',color:'#f1ead9'},eyebrow:{fontSize:12,fontWeight:'700',color:'#a8c8c2'},status:{color:'#d0c7d6',marginBottom:16},text:{color:'#eee7d7',lineHeight:22},canon:{color:'#eee7d7',lineHeight:25},error:{color:'#ffb4ab',marginBottom:10},timer:{fontSize:34,color:'#f1ead9'},stage:{color:'#c5d8d4',fontWeight:'700'},input:{minHeight:100,borderWidth:1,borderColor:'#405553',borderRadius:12,padding:12,color:'#f1ead9',textAlignVertical:'top'},button:{padding:12,borderRadius:10,borderWidth:1,borderColor:'#607d79',backgroundColor:'#16201f'},small:{padding:8,borderRadius:8,borderWidth:1,borderColor:'#607d79'},disabled:{opacity:.45},buttonText:{color:'#f1ead9',fontWeight:'700'},toggle:{paddingVertical:5},row:{flexDirection:'row',flexWrap:'wrap',gap:8}});
