import { useEffect, useMemo, useRef, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { ExperienceDirector, QuestRuntime, createQuestCatalog, type ExperienceDirective, type PlayerContext, type SessionSnapshot } from '@hnk/quest-engine';
import { createBundledQuestLibrary, type RuntimeQuestBundle } from '@hnk/quest-library';
import { sealDay008V1, startDay008PracticeSessionV1 } from '@hnk/supabase-client';
import { useHnkAuth } from '../auth/AuthContext';
import { QuestCountdownPhase, type CountdownPracticeResult } from '../../runtime/QuestCountdownPhase';

type Session=Awaited<ReturnType<typeof startDay008PracticeSessionV1>>;type Seal=Extract<Awaited<ReturnType<typeof sealDay008V1>>,{ok:true}>['response'];
function canon(bundle:RuntimeQuestBundle,d:ExperienceDirective){return(d.phase.source.block_ids??[]).map(id=>{const b=bundle.canon.blocks.find(x=>x.id===id);if(!b)throw new Error(`canonical_block_missing:${id}`);return b.text})}
function key(userId:string){return`hnk-mobile-d008-v1-${userId}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`}
export function Day008GoldenV1Mobile(){
 const auth=useHnkAuth();const live=Boolean(auth.configured&&auth.phase==='signed-in'&&auth.client&&auth.userId);const runtimeRef=useRef<QuestRuntime|null>(null);
 const[bundle,setBundle]=useState<RuntimeQuestBundle|null>(null);const[snapshot,setSnapshot]=useState<SessionSnapshot|null>(null);const[session,setSession]=useState<Session|null>(null);const[jachin,setJachin]=useState<CountdownPracticeResult|null>(null);const[jachinRecorded,setJachinRecorded]=useState(false);const[boaz,setBoaz]=useState<CountdownPracticeResult|null>(null);const[boazRecorded,setBoazRecorded]=useState(false);const[middle,setMiddle]=useState<CountdownPracticeResult|null>(null);const[relaxation,setRelaxation]=useState(5);const[attention,setAttention]=useState(5);const[forcing,setForcing]=useState(5);const[voluntary,setVoluntary]=useState(false);const[safetyStopped,setSafetyStopped]=useState(false);const[sealed,setSealed]=useState<Seal|null>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState<string|null>(null);
 const context=useMemo<PlayerContext>(()=>({mediationMode:'HNK_CANONICAL',accessibility:{reducedMotion:false,audioEnabled:true,microphoneAvailable:false},offline:!live}),[live]);
 useEffect(()=>{let active=true;const library=createBundledQuestLibrary();const catalog=createQuestCatalog(library);void Promise.all([catalog.requireDay(8),library.loadBundle(8)]).then(([definition,loaded])=>{if(!active||!loaded)return;const r=new QuestRuntime(definition);runtimeRef.current=r;setBundle(loaded);setSnapshot(r.start())}).catch(c=>active&&setError(c instanceof Error?c.message:'day008_bundle_load_failed'));return()=>{active=false}},[]);
 const director=useMemo(()=>bundle?new ExperienceDirector(bundle.quest):null,[bundle]);const directive=useMemo(()=>director&&snapshot?.currentPhaseId?director.resolvePhase(snapshot.currentPhaseId,context,snapshot):null,[director,context,snapshot]);
 async function ensureSession(){if(session)return session;if(!live||!auth.client||!auth.userId)return null;const created=await startDay008PracticeSessionV1(auth.client,{clientSessionId:key(auth.userId),appVersion:'0.1.0-mobile-day008-golden-v1'});setSession(created);return created}
 async function completePhase(id:string){const r=runtimeRef.current;if(!r)return;if(id==='jachin_reading')await ensureSession();setSnapshot(r.completePhase(id))}
 async function safetyStop(reason?:string){setSafetyStopped(true);setError(reason??'safety_stop');if(runtimeRef.current)setSnapshot(runtimeRef.current.safetyStop())}
 function resume(){if(runtimeRef.current){setError(null);setSnapshot(runtimeRef.current.resume())}}
 async function seal(){if(!auth.client||!session||!runtimeRef.current||!jachin||!boaz||!middle||!jachinRecorded||!boazRecorded||!voluntary)return;setBusy(true);setError(null);try{const total=jachin.durationSeconds+boaz.durationSeconds+middle.durationSeconds+middle.silentObservationSeconds;const result=await sealDay008V1(auth.client,{evidence:{sessionId:session.id,mode:'first_completion',jachin:{finalNumber:jachin.finalNumber,attentionReturns:jachin.attentionReturns},boaz:{finalNumber:boaz.finalNumber,distractionsNotedCount:boaz.attentionReturns},middle:{finalNumber:middle.finalNumber,silentObservationSeconds:middle.silentObservationSeconds},soulMirror:{relaxationRating:relaxation,attentionStabilityRating:attention,forcingRating:forcing},safetyStopOccurred:safetyStopped},totalDurationSeconds:total,attentionReturns:jachin.attentionReturns,distractionsNotedCount:boaz.attentionReturns});if(!result.ok)throw new Error(result.code);setSealed(result.response);setSnapshot(runtimeRef.current.confirmServerCompletion())}catch(c){setError(c instanceof Error?c.message:'day008_completion_failed')}finally{setBusy(false)}}
 if(!bundle||!snapshot||!director)return <View style={styles.center}><Text style={styles.text}>CARREGANDO DAY 008…</Text>{error?<Text style={styles.error}>{error}</Text>:null}</View>;
 if(snapshot.runState==='SAFETY_STOP')return <View style={styles.center}><Text style={styles.title}>Prática pausada com segurança.</Text><Action label="RETOMAR" onPress={resume}/></View>;
 if(snapshot.runState==='COMPLETE')return <View style={styles.center}><Text style={styles.eyebrow}>DIA 008 · JELIEL 3/5</Text><Text style={styles.title}>Dave Elman II registrado.</Text><Text style={styles.text}>{sealed?.first_completion?`+${sealed.xp_awarded} XP canônicos.`:'Revisita sem novo XP.'}</Text><Text style={styles.text}>Nenhum ganho de atributo é aplicado no Day 008.</Text></View>;
 if(!directive)return <View style={styles.center}><Text style={styles.text}>FASE INDISPONÍVEL.</Text></View>;const p=directive.phase;const texts=directive.requiresCanonicalContent?canon(bundle,directive):[];
 return <ScrollView contentContainerStyle={styles.shell}><Text style={styles.eyebrow}>DIA 008 · KETHER · JELIEL 3/5</Text><Text style={styles.headerTitle}>DAVE ELMAN II</Text>{error?<Text style={styles.error}>{error}</Text>:null}<View style={styles.panel}><Text style={styles.eyebrow}>{p.type} · {p.id}</Text>
  {p.type==='NARRATIVE'?<><Text style={styles.title}>Relaxar e contar sem competir.</Text><Text style={styles.text}>Você pode parar longe do número 1. Perder a conta não é fracasso.</Text></>:null}
  {p.type==='TERM_REVEAL'?<Text style={styles.text}>{(p.terms??[]).join(' · ')}</Text>:null}
  {p.type==='READ'?texts.map((t,i)=><Text key={i} style={styles.canon}>{t}</Text>):null}
  {p.type==='FOCUS'&&['jachin_countdown','boaz_countdown','middle_countdown'].includes(p.id)?<QuestCountdownPhase directive={directive} onResult={r=>{if(p.id==='jachin_countdown')setJachin(r);else if(p.id==='boaz_countdown')setBoaz(r);else setMiddle(r)}} onCompletePhase={completePhase} onSafetyStop={safetyStop}/>:null}
  {p.type==='RETURN'?<><Text style={styles.text}>Abra os olhos quando quiser, mova mãos e pés e confirme orientação.</Text><Action label="ESTOU ORIENTADO · CONTINUAR" onPress={()=>void completePhase(p.id)}/></>:null}
  {p.type==='JOURNAL'&&p.id==='jachin_record'?<><Text style={styles.text}>Número final: {jachin?.finalNumber??'—'} · retornos: {jachin?.attentionReturns??0}. A região corporal percebida fica apenas no Vault.</Text><Action label={jachinRecorded?'OBSERVAÇÃO PRIVADA REGISTRADA ✓':'REGISTREI A OBSERVAÇÃO NO VAULT'} onPress={()=>setJachinRecorded(v=>!v)}/><Action disabled={!jachinRecorded} label="CONTINUAR" onPress={()=>void completePhase(p.id)}/></>:null}
  {p.type==='JOURNAL'&&p.id==='boaz_record'?<><Text style={styles.text}>Distrações percebidas: {boaz?.attentionReturns??0}. O ajuste que ajudou fica apenas no Vault.</Text><Action label={boazRecorded?'AJUSTE PRIVADO REGISTRADO ✓':'REGISTREI O AJUSTE NO VAULT'} onPress={()=>setBoazRecorded(v=>!v)}/><Action disabled={!boazRecorded} label="CONTINUAR" onPress={()=>void completePhase(p.id)}/></>:null}
  {p.type==='STRUCTURED_JOURNAL'?<><Rating label="RELAXAMENTO" value={relaxation} setValue={setRelaxation}/><Rating label="ATENÇÃO ESTÁVEL" value={attention} setValue={setAttention}/><Rating label="QUANTO FORCEI" value={forcing} setValue={setForcing}/><Action label="CONCLUIR ESPELHO" onPress={()=>void completePhase(p.id)}/></>:null}
  {p.type==='COMPLETION'?<><Text style={styles.title}>Selo canônico</Text><Text style={styles.text}>O servidor valida execução; chegar ao número 1 não é requisito.</Text><Action label={voluntary?'CONCLUSÃO VOLUNTÁRIA ✓':'CONFIRMAR CONCLUSÃO VOLUNTÁRIA'} onPress={()=>setVoluntary(v=>!v)}/><Action disabled={busy||!voluntary} label={busy?'SELANDO…':'SELAR DAY 008'} onPress={()=>void seal()}/></>:null}
  {['NARRATIVE','TERM_REVEAL','READ','UNLOCK'].includes(p.type)?<Action label="CONTINUAR" onPress={()=>void completePhase(p.id)}/>:null}
 </View></ScrollView>;
}
function Rating({label,value,setValue}:{label:string;value:number;setValue:(v:number)=>void}){return <View style={styles.row}><Text style={styles.text}>{label} · {value}</Text>{[0,2,4,6,8,10].map(v=><Action key={v} label={String(v)} onPress={()=>setValue(v)}/>)}</View>}
function Action({label,onPress,disabled=false}:{label:string;onPress:()=>void;disabled?:boolean}){return <Pressable disabled={disabled} onPress={onPress} style={[styles.button,disabled&&styles.disabled]}><Text style={styles.buttonText}>{label}</Text></Pressable>}
const styles=StyleSheet.create({shell:{padding:20,paddingBottom:80,backgroundColor:'#090910',minHeight:'100%'},center:{flex:1,padding:28,justifyContent:'center',backgroundColor:'#090910',gap:14},panel:{borderWidth:1,borderColor:'#6f5f29',borderRadius:18,padding:18,gap:14,backgroundColor:'#111018'},row:{gap:6},eyebrow:{color:'#d9bd67',fontSize:12,letterSpacing:1.4},headerTitle:{color:'#f4e6b2',fontSize:25,fontWeight:'800'},title:{color:'#f4e6b2',fontSize:22,fontWeight:'700'},text:{color:'#eee7d7',lineHeight:21},canon:{color:'#eee7d7',lineHeight:24,fontSize:15},error:{color:'#ffb4ab'},button:{borderWidth:1,borderColor:'#9a8240',borderRadius:12,padding:12,alignItems:'center'},disabled:{opacity:.4},buttonText:{color:'#f4e6b2',fontWeight:'700'}});
