import {useEffect,useMemo,useRef,useState} from 'react';
import {AppState,Pressable,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';
import * as SecureStore from 'expo-secure-store';
import {ExperienceDirector,QuestRuntime,createQuestCatalog,type ExperienceDirective,type PlayerContext,type SessionSnapshot} from '@hnk/quest-engine';
import {createBundledQuestLibrary,type RuntimeQuestBundle} from '@hnk/quest-library';
import {assertElemiahProgress,loadDay017PracticeSessionV1,sealDay017V1,startDay017PracticeSessionV1} from '@hnk/supabase-client';
import {useHnkAuth} from '../auth/AuthContext';
import {createMobileVaultTextPort} from '../../runtime/MobileVaultTextPort';

type Session=NonNullable<Awaited<ReturnType<typeof loadDay017PracticeSessionV1>>>;
type Seal=Extract<Awaited<ReturnType<typeof sealDay017V1>>,{ok:true}>['response'];
type Block='jachin_vocal_flow'|'boaz_vocal_safety'|'middle_vocal_integration';
type SafetyResponse='NONE'|'ADJUSTED'|'STOPPED';
interface Draft{jachinDuration:number;comfort:number;spontaneity:number;breathingComfort:boolean;voluntaryFlow:boolean;noExternalDivine:boolean;jachinRef:string|null;boazDuration:number;lowModerate:boolean;breathingThroatChecks:boolean;agency:boolean;safetyResponse:SafetyResponse;boazRef:string|null;middleDuration:number;slowedToSilence:boolean;normalBreathing:boolean;psalm64:boolean;noProphecy:boolean;grounding:boolean;presence:number;middleRef:string|null;soulRef:string|null;safetyStopped:boolean}
const emptyDraft:Draft={jachinDuration:0,comfort:5,spontaneity:5,breathingComfort:false,voluntaryFlow:false,noExternalDivine:false,jachinRef:null,boazDuration:0,lowModerate:false,breathingThroatChecks:false,agency:false,safetyResponse:'NONE',boazRef:null,middleDuration:0,slowedToSilence:false,normalBreathing:false,psalm64:false,noProphecy:false,grounding:false,presence:5,middleRef:null,soulRef:null,safetyStopped:false};
function canon(bundle:RuntimeQuestBundle,d:ExperienceDirective){return(d.phase.source.block_ids??[]).map(id=>{const b=bundle.canon.blocks.find(x=>x.id===id);if(!b)throw new Error(`canonical_block_missing:${id}`);return b.text})}
function keys(u:string){return{snapshot:`hnk.quest.d017.${u}.snapshot.v1`,session:`hnk.quest.d017.${u}.session.v1`,draft:`hnk.quest.d017.${u}.draft.v1`}}
async function loadJson<T>(k:string):Promise<T|null>{try{const raw=await SecureStore.getItemAsync(k);return raw?JSON.parse(raw) as T:null}catch{return null}}
async function saveJson(k:string,v:unknown){await SecureStore.setItemAsync(k,JSON.stringify(v))}
function clientId(u:string){return`hnk-mobile-d017-v1-${u}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`}
function clock(elapsed:number,max:number){const left=Math.max(0,max-elapsed);return`${String(Math.floor(left/60)).padStart(2,'0')}:${String(left%60).padStart(2,'0')}`}

export function Day017GoldenV1Mobile(){
 const auth=useHnkAuth();const live=Boolean(auth.configured&&auth.phase==='signed-in'&&auth.client&&auth.userId);const runtimeRef=useRef<QuestRuntime|null>(null);
 const[bundle,setBundle]=useState<RuntimeQuestBundle|null>(null);const[snapshot,setSnapshot]=useState<SessionSnapshot|null>(null);const[session,setSession]=useState<Session|null>(null);const[draft,setDraft]=useState<Draft>(emptyDraft);const[loaded,setLoaded]=useState(false);
 const[active,setActive]=useState<Block|null>(null);const[started,setStarted]=useState<number|null>(null);const[now,setNow]=useState(Date.now());const[jachinNote,setJachinNote]=useState('');const[boazNote,setBoazNote]=useState('');const[middleNote,setMiddleNote]=useState('');const[soulNote,setSoulNote]=useState('');const[voluntary,setVoluntary]=useState(false);const[busy,setBusy]=useState(false);const[error,setError]=useState<string|null>(null);const[sealed,setSealed]=useState<Seal|null>(null);
 const context=useMemo<PlayerContext>(()=>({mediationMode:'HNK_CANONICAL',accessibility:{reducedMotion:false,audioEnabled:false,microphoneAvailable:false},offline:!live}),[live]);
 const vault=useMemo(()=>auth.userId?createMobileVaultTextPort(auth.client??null):null,[auth.client,auth.userId]);
 useEffect(()=>{if(!auth.userId)return;let ok=true;const lib=createBundledQuestLibrary(),cat=createQuestCatalog(lib),k=keys(auth.userId);void Promise.all([cat.requireDay(17),lib.loadBundle(17),loadJson<SessionSnapshot>(k.snapshot),loadJson<Session>(k.session),loadJson<Draft>(k.draft)]).then(([def,b,saved,ss,dd])=>{if(!ok||!b)return;const r=new QuestRuntime(def);runtimeRef.current=r;setBundle(b);setSnapshot(saved?r.restore(saved):r.start());if(ss)setSession(ss);setDraft(dd??emptyDraft);setLoaded(true)}).catch(e=>ok&&setError(e instanceof Error?e.message:'day017_load_failed'));return()=>{ok=false}},[auth.userId]);
 useEffect(()=>{if(!auth.userId||!snapshot)return;const k=keys(auth.userId);if(snapshot.runState==='COMPLETE'){void SecureStore.deleteItemAsync(k.snapshot);void SecureStore.deleteItemAsync(k.session);void SecureStore.deleteItemAsync(k.draft)}else void saveJson(k.snapshot,snapshot)},[auth.userId,snapshot]);
 useEffect(()=>{if(auth.userId&&loaded&&snapshot?.runState!=='COMPLETE')void saveJson(keys(auth.userId).draft,draft)},[auth.userId,draft,loaded,snapshot?.runState]);
 useEffect(()=>{const id=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(id)},[]);
 useEffect(()=>{const sub=AppState.addEventListener('change',state=>{if(state!=='active'&&started!==null){setStarted(null);setActive(null);setError('bloco_interrompido_ao_sair_do_app__tempo_corrente_descartado')}});return()=>sub.remove()},[started]);
 const director=useMemo(()=>bundle?new ExperienceDirector(bundle.quest):null,[bundle]);const directive=useMemo(()=>director&&snapshot?.currentPhaseId?director.resolvePhase(snapshot.currentPhaseId,context,snapshot):null,[director,context,snapshot]);const max=active==='middle_vocal_integration'?180:600;const elapsed=started===null?0:Math.min(max,Math.max(0,Math.floor((now-started)/1000)));
 async function ensureSession(){if(session)return session;if(!live||!auth.client||!auth.userId)throw new Error('online_session_required_before_day017_practice');const s=await startDay017PracticeSessionV1(auth.client,{clientSessionId:clientId(auth.userId),appVersion:'0.1.0-mobile-day017-golden-v1'});setSession(s);await saveJson(keys(auth.userId).session,s);return s}
 async function complete(id:string){setError(null);try{if(id==='jachin_reading')await ensureSession();const r=runtimeRef.current;if(r)setSnapshot(r.completePhase(id))}catch(e){setError(e instanceof Error?e.message:'phase_failed')}}
 function startBlock(b:Block){if(started!==null)return;setError(null);setActive(b);setStarted(Date.now());setNow(Date.now())}
 function finishBlock(b:Block){if(active!==b||started===null)return;const e=Math.min(b==='middle_vocal_integration'?180:600,Math.max(0,Math.floor((Date.now()-started)/1000)));const min=b==='middle_vocal_integration'?120:1;if(e<min){setError(b==='middle_vocal_integration'?'middle_requires_at_least_120_seconds':'practice_requires_at_least_1_second');return}setDraft(d=>b==='jachin_vocal_flow'?{...d,jachinDuration:e}:b==='boaz_vocal_safety'?{...d,boazDuration:e}:{...d,middleDuration:e});setStarted(null);setActive(null)}
 function safetyStop(){setStarted(null);setActive(null);setDraft(d=>({...d,safetyStopped:true}));setError('safety_stop__respire_normalmente__hidrate_se__oriente_se_no_ambiente');if(runtimeRef.current)setSnapshot(runtimeRef.current.safetyStop())}
 function resume(){setError(null);if(runtimeRef.current)setSnapshot(runtimeRef.current.resume())}
 async function saveJachin(){if(!vault||!auth.userId||draft.jachinDuration<1||!draft.breathingComfort||!draft.voluntaryFlow||!draft.noExternalDivine||!jachinNote.trim())throw new Error('jachin_evidence_required');const e=await vault.saveText({userId:auth.userId,day:17,kind:'journal',plaintext:JSON.stringify({schema:'hnk-day017-jachin-v1',experience:jachinNote.trim()})});setDraft(d=>({...d,jachinRef:e.entryId}));setJachinNote('');await complete('jachin_vocal_flow')}
 async function saveBoaz(){if(!vault||!auth.userId||draft.boazDuration<1||!draft.lowModerate||!draft.breathingThroatChecks||!draft.agency||!boazNote.trim())throw new Error('boaz_safety_evidence_required');const e=await vault.saveText({userId:auth.userId,day:17,kind:'journal',plaintext:JSON.stringify({schema:'hnk-day017-boaz-v1',experience:boazNote.trim()})});setDraft(d=>({...d,boazRef:e.entryId}));setBoazNote('');await complete('boaz_vocal_safety')}
 async function saveMiddle(){if(!vault||!auth.userId||draft.middleDuration<120||!draft.slowedToSilence||!draft.normalBreathing||!draft.psalm64||!draft.noProphecy||!draft.grounding||!middleNote.trim())throw new Error('middle_integration_required');const e=await vault.saveText({userId:auth.userId,day:17,kind:'journal',plaintext:JSON.stringify({schema:'hnk-day017-middle-v1',integration:middleNote.trim()})});setDraft(d=>({...d,middleRef:e.entryId}));setMiddleNote('');await complete('middle_vocal_integration')}
 async function saveSoul(){if(!vault||!auth.userId||!soulNote.trim())throw new Error('soul_mirror_required');const e=await vault.saveText({userId:auth.userId,day:17,kind:'journal',plaintext:JSON.stringify({schema:'hnk-day017-soul-v1',soundEmotionInterpretationDiscernment:soulNote.trim()})});setDraft(d=>({...d,soulRef:e.entryId}));setSoulNote('');await complete('soul_mirror')}
 async function seal(){if(!runtimeRef.current||!live||!auth.client||!auth.userId||!session||!vault||!draft.jachinRef||!draft.boazRef||!draft.middleRef||!draft.soulRef||!voluntary)return;setBusy(true);setError(null);try{await vault.flushPending(auth.userId);const jr=await vault.resolveEntryId(auth.userId,draft.jachinRef),br=await vault.resolveEntryId(auth.userId,draft.boazRef),mr=await vault.resolveEntryId(auth.userId,draft.middleRef),sr=await vault.resolveEntryId(auth.userId,draft.soulRef);if(!jr||!br||!mr||!sr)throw new Error('vault_sync_required_before_completion');const result=await sealDay017V1(auth.client,{evidence:{sessionId:session.id,mode:'first_completion',jachinDurationSeconds:draft.jachinDuration,comfortScore:draft.comfort,spontaneityScore:draft.spontaneity,breathingComfortConfirmed:draft.breathingComfort,voluntaryNonsemanticFlowConfirmed:draft.voluntaryFlow,soundNotExternalOrDivineMessageConfirmed:draft.noExternalDivine,jachinSessionVaultEntryRef:jr,boazDurationSeconds:draft.boazDuration,lowOrModerateVolumeConfirmed:draft.lowModerate,breathingAndThroatChecksConfirmed:draft.breathingThroatChecks,agencyPreservedConfirmed:draft.agency,safetyResponse:draft.safetyResponse,boazExperienceVaultEntryRef:br,middleDurationSeconds:draft.middleDuration,slowedToSilenceConfirmed:draft.slowedToSilence,normalBreathingConfirmed:draft.normalBreathing,psalm64PrayerConfirmed:draft.psalm64,soundNotProphecyOrCommandConfirmed:draft.noProphecy,groundingConfirmed:draft.grounding,presenceScore:draft.presence,middleIntegrationVaultEntryRef:mr,soulMirrorCompleted:true,soundEmotionInterpretationDiscernmentVaultEntryRef:sr,safetyStopOccurred:draft.safetyStopped},totalDurationSeconds:draft.jachinDuration+draft.boazDuration+draft.middleDuration});if(!result.ok)throw new Error(result.code);assertElemiahProgress(result.response.crown,2);setSealed(result.response);setSnapshot(runtimeRef.current.confirmServerCompletion())}catch(e){setError(e instanceof Error?e.message:'day017_completion_failed')}finally{setBusy(false)}}
 if(!auth.userId)return <Center text="ENTRE NO ÁTRIO PARA INICIAR O DIA 017."/>;if(!bundle||!snapshot||!director)return <Center text={error??'CARREGANDO DAY 017…'}/>;if(snapshot.runState==='SAFETY_STOP')return <View style={s.center}><Text style={s.title}>PRÁTICA INTERROMPIDA</Text><Text style={s.text}>Respire normalmente, hidrate-se e reoriente-se no ambiente. Retome somente se desejar.</Text><Action label="RETOMAR" onPress={resume}/></View>;if(snapshot.runState==='COMPLETE')return <View style={s.center}><Text style={s.eyebrow}>DIA 017 · ELEMIAH 2/5</Text><Text style={s.title}>ATIVAÇÃO DA GLOSSOLÁLIA CONCLUÍDA</Text><Text style={s.text}>{sealed?.first_completion?`+${sealed.xp_awarded} XP canônicos.`:'Revisita sem novo XP.'}</Text><Text style={s.text}>Elemiah 2/5 confirmado pelo servidor · fragmento IV ainda apagado · Coroa {sealed?.crown.fragments_lit??3}/7.</Text></View>;if(!directive)return <Center text="FASE INDISPONÍVEL."/>;
 const p=directive.phase,texts=directive.requiresCanonicalContent?canon(bundle,directive):[],block=p.id as Block,isBlock=['jachin_vocal_flow','boaz_vocal_safety','middle_vocal_integration'].includes(p.id),done=block==='jachin_vocal_flow'?draft.jachinDuration>0:block==='boaz_vocal_safety'?draft.boazDuration>0:draft.middleDuration>=120,blockMax=block==='middle_vocal_integration'?180:600,blockMin=block==='middle_vocal_integration'?120:1;
 return <ScrollView contentContainerStyle={s.shell}><Text style={s.eyebrow}>DIA 017 · KETHER · ELEMIAH 2/5</Text><Text style={s.header}>ATIVAÇÃO DA GLOSSOLÁLIA</Text><Text style={s.status}>{live?'VAULT E2EE · ONLINE':'VAULT E2EE · FILA CIFRADA OFFLINE'} · ÁUDIO DESATIVADO V1</Text>{error?<Text style={s.error}>{error}</Text>:null}<View style={s.panel}><Text style={s.eyebrow}>{p.type} · {p.id}</Text>{p.type==='NARRATIVE'?<><Text style={s.title}>Fluxo vocal com agência.</Text><Text style={s.text}>Fluidez não é prova espiritual. Volume não é mérito. Você mantém o comando da prática.</Text></>:null}{p.type==='READ'?texts.map((t,i)=><Text key={i} style={s.canon}>{t}</Text>):null}{isBlock?<><Text style={s.timer}>{done?`${block==='middle_vocal_integration'?draft.middleDuration:block==='jachin_vocal_flow'?draft.jachinDuration:draft.boazDuration}s`:clock(active===block?elapsed:0,blockMax)}</Text>{active===block?<Action label={elapsed<blockMin?'CONTINUE CONFORTAVELMENTE':'ENCERRAR ESTE BLOCO'} onPress={()=>finishBlock(block)} disabled={elapsed<blockMin}/>:done?<Text style={s.stage}>BLOCO REGISTRADO ✓</Text>:<Action label="INICIAR BLOCO" onPress={()=>startBlock(block)}/>}<Action label="SAFETY STOP" onPress={safetyStop}/></>:null}
 {p.id==='jachin_vocal_flow'?<><Score label="Conforto vocal" value={draft.comfort} set={v=>setDraft(d=>({...d,comfort:v}))}/><Score label="Espontaneidade" value={draft.spontaneity} set={v=>setDraft(d=>({...d,spontaneity:v}))}/><Toggle label="Respiração permaneceu confortável" value={draft.breathingComfort} on={()=>setDraft(d=>({...d,breathingComfort:!d.breathingComfort}))}/><Toggle label="O fluxo foi voluntário" value={draft.voluntaryFlow} on={()=>setDraft(d=>({...d,voluntaryFlow:!d.voluntaryFlow}))}/><Toggle label="Não tratei os sons como mensagem externa ou divina automática" value={draft.noExternalDivine} on={()=>setDraft(d=>({...d,noExternalDivine:!d.noExternalDivine}))}/><Input value={jachinNote} set={setJachinNote} placeholder="Ritmo, respiração, atenção e experiência"/><Action label="CIFRAR E CONTINUAR" onPress={()=>void saveJachin()}/></>:null}
 {p.id==='boaz_vocal_safety'?<><Toggle label="Mantive volume baixo ou moderado" value={draft.lowModerate} on={()=>setDraft(d=>({...d,lowModerate:!d.lowModerate}))}/><Toggle label="Chequei respiração e garganta" value={draft.breathingThroatChecks} on={()=>setDraft(d=>({...d,breathingThroatChecks:!d.breathingThroatChecks}))}/><Toggle label="Mantive agência para pausar ou parar" value={draft.agency} on={()=>setDraft(d=>({...d,agency:!d.agency}))}/><View style={s.row}><Action label="SEM AJUSTE" onPress={()=>setDraft(d=>({...d,safetyResponse:'NONE'}))}/><Action label="AJUSTEI" onPress={()=>setDraft(d=>({...d,safetyResponse:'ADJUSTED'}))}/><Action label="PAREI" onPress={()=>setDraft(d=>({...d,safetyResponse:'STOPPED'}))}/></View><Text style={s.text}>Resposta: {draft.safetyResponse}</Text><Input value={boazNote} set={setBoazNote} placeholder="Tensão, emoção, expectativa e como preservou escolha"/><Action label="CIFRAR BOAZ" onPress={()=>void saveBoaz()}/></>:null}
 {p.id==='middle_vocal_integration'?<><Toggle label="Reduzi gradualmente até o silêncio" value={draft.slowedToSilence} on={()=>setDraft(d=>({...d,slowedToSilence:!d.slowedToSilence}))}/><Toggle label="Respiração voltou ao normal" value={draft.normalBreathing} on={()=>setDraft(d=>({...d,normalBreathing:!d.normalBreathing}))}/><Toggle label="Concluí oração orientada pelo Salmo 6:4" value={draft.psalm64} on={()=>setDraft(d=>({...d,psalm64:!d.psalm64}))}/><Toggle label="Som significativo não virou profecia/comando automático" value={draft.noProphecy} on={()=>setDraft(d=>({...d,noProphecy:!d.noProphecy}))}/><Toggle label="Reorientei-me no ambiente" value={draft.grounding} on={()=>setDraft(d=>({...d,grounding:!d.grounding}))}/><Score label="Presença" value={draft.presence} set={v=>setDraft(d=>({...d,presence:v}))}/><Input value={middleNote} set={setMiddleNote} placeholder="Som, emoção e interpretação — separados"/><Action label="CIFRAR INTEGRAÇÃO" onPress={()=>void saveMiddle()}/></>:null}
 {p.id==='soul_mirror'?<><Input value={soulNote} set={setSoulNote} placeholder="O que foi som, emoção e interpretação posterior"/><Action label="CIFRAR ESPELHO" onPress={()=>void saveSoul()}/></>:null}
 {p.id==='completion'?<><Toggle label="Concluo voluntariamente; intensidade, êxtase e gravação não são requisitos" value={voluntary} on={()=>setVoluntary(v=>!v)}/><Action label={busy?'SELANDO…':'SINCRONIZAR · SELAR DAY 017'} onPress={()=>void seal()} disabled={!live||busy||!voluntary}/></>:null}
 {!['jachin_vocal_flow','boaz_vocal_safety','middle_vocal_integration','soul_mirror','completion'].includes(p.id)&&p.type!=='READ'&&p.type!=='NARRATIVE'?<Action label="CONTINUAR" onPress={()=>void complete(p.id)}/>:null}</View></ScrollView>
}
function Action({label,onPress,disabled=false}:{label:string;onPress:()=>void;disabled?:boolean}){return <Pressable disabled={disabled} onPress={onPress} style={[s.button,disabled&&s.disabled]}><Text style={s.buttonText}>{label}</Text></Pressable>}
function Toggle({label,value,on}:{label:string;value:boolean;on:()=>void}){return <Pressable onPress={on} style={s.toggle}><Text style={s.text}>{value?'☑':'☐'} {label}</Text></Pressable>}
function Input({value,set,placeholder}:{value:string;set:(v:string)=>void;placeholder:string}){return <TextInput multiline value={value} onChangeText={set} placeholder={placeholder} placeholderTextColor="#817d86" style={s.input}/>}function Score({label,value,set}:{label:string;value:number;set:(v:number)=>void}){return <View><Text style={s.text}>{label}: {value}/10</Text><View style={s.row}>{[0,2,4,6,8,10].map(v=><Pressable key={v} onPress={()=>set(v)} style={s.small}><Text style={s.buttonText}>{v}</Text></Pressable>)}</View></View>}function Center({text}:{text:string}){return <View style={s.center}><Text style={s.text}>{text}</Text></View>}
const s=StyleSheet.create({shell:{padding:22,paddingBottom:80,backgroundColor:'#090910',minHeight:'100%'},center:{flex:1,justifyContent:'center',alignItems:'center',padding:24,backgroundColor:'#090910'},panel:{borderWidth:1,borderColor:'#7b638b',borderRadius:18,padding:18,gap:12,backgroundColor:'#111018'},header:{fontSize:28,fontWeight:'800',color:'#f1ead9'},title:{fontSize:22,fontWeight:'700',color:'#f1ead9'},eyebrow:{fontSize:12,fontWeight:'700',color:'#b9a3ca'},status:{color:'#d0c7d6',marginBottom:16},text:{color:'#eee7d7',lineHeight:22},canon:{color:'#eee7d7',lineHeight:25},error:{color:'#ffb4ab',marginBottom:10},timer:{fontSize:34,color:'#f1ead9'},stage:{color:'#cfc3d8',fontWeight:'700'},input:{minHeight:100,borderWidth:1,borderColor:'#4a4351',borderRadius:12,padding:12,color:'#f1ead9',textAlignVertical:'top'},button:{padding:12,borderRadius:10,borderWidth:1,borderColor:'#7b638b',backgroundColor:'#1a1520'},small:{padding:8,borderRadius:8,borderWidth:1,borderColor:'#7b638b'},disabled:{opacity:.45},buttonText:{color:'#f1ead9',fontWeight:'700'},toggle:{paddingVertical:5},row:{flexDirection:'row',flexWrap:'wrap',gap:8}});
