import { useEffect, useMemo, useRef, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { ExperienceDirector, QuestRuntime, createQuestCatalog, type ExperienceDirective, type PlayerContext, type SessionSnapshot } from '@hnk/quest-engine';
import { createBundledQuestLibrary, type RuntimeQuestBundle } from '@hnk/quest-library';
import { sealDay006V1, startDay006PracticeSessionV1 } from '@hnk/supabase-client';
import { useHnkAuth } from '../auth/AuthContext';
import { QuestVoicePhase, type VoicePracticeResult } from '../../runtime/QuestVoicePhase';

type Session=Awaited<ReturnType<typeof startDay006PracticeSessionV1>>; type Seal=Extract<Awaited<ReturnType<typeof sealDay006V1>>,{ok:true}>['response'];
function canon(bundle:RuntimeQuestBundle,d:ExperienceDirective){return(d.phase.source.block_ids??[]).map(id=>{const b=bundle.canon.blocks.find(x=>x.id===id);if(!b)throw new Error(`canonical_block_missing:${id}`);return b.text})}
function key(userId:string){return `hnk-mobile-d006-v1-${userId}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`}
export function Day006GoldenV1Mobile(){
  const auth=useHnkAuth(); const live=Boolean(auth.configured&&auth.phase==='signed-in'&&auth.client&&auth.userId); const runtimeRef=useRef<QuestRuntime|null>(null);
  const[bundle,setBundle]=useState<RuntimeQuestBundle|null>(null);const[snapshot,setSnapshot]=useState<SessionSnapshot|null>(null);const[session,setSession]=useState<Session|null>(null);const[listeningSeconds,setListeningSeconds]=useState(0);const[soundsNoted,setSoundsNoted]=useState(0);const[boazSeconds,setBoazSeconds]=useState(0);const[thoughtReturns,setThoughtReturns]=useState(0);const[difficultiesRecorded,setDifficultiesRecorded]=useState(false);const[voice,setVoice]=useState<VoicePracticeResult|null>(null);const[difficulty,setDifficulty]=useState<number|null>(null);const[voluntary,setVoluntary]=useState(false);const[safetyStopped,setSafetyStopped]=useState(false);const[sealed,setSealed]=useState<Seal|null>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState<string|null>(null);
  const context=useMemo<PlayerContext>(()=>({mediationMode:'HNK_CANONICAL',accessibility:{reducedMotion:false,audioEnabled:true,microphoneAvailable:false},offline:!live}),[live]);
  useEffect(()=>{let active=true;const library=createBundledQuestLibrary();const catalog=createQuestCatalog(library);void Promise.all([catalog.requireDay(6),library.loadBundle(6)]).then(([definition,loaded])=>{if(!active||!loaded)return;const runtime=new QuestRuntime(definition);runtimeRef.current=runtime;setBundle(loaded);setSnapshot(runtime.start())}).catch(c=>active&&setError(c instanceof Error?c.message:'day006_bundle_load_failed'));return()=>{active=false}},[]);
  const director=useMemo(()=>bundle?new ExperienceDirector(bundle.quest):null,[bundle]);const directive=useMemo(()=>director&&snapshot?.currentPhaseId?director.resolvePhase(snapshot.currentPhaseId,context,snapshot):null,[director,context,snapshot]);
  async function ensureSession(){if(session)return session;if(!live||!auth.client||!auth.userId)return null;const created=await startDay006PracticeSessionV1(auth.client,{clientSessionId:key(auth.userId),appVersion:'0.1.0-mobile-day006-golden-v1'});setSession(created);return created}
  async function completePhase(id:string){const r=runtimeRef.current;if(!r)return;if(id==='jachin_reading')await ensureSession();setSnapshot(r.completePhase(id))}
  async function safetyStop(reason?:string){setSafetyStopped(true);setError(reason??'safety_stop');if(runtimeRef.current)setSnapshot(runtimeRef.current.safetyStop())}
  function resume(){if(runtimeRef.current){setError(null);setSnapshot(runtimeRef.current.resume())}}
  async function seal(){if(!auth.client||!session||!runtimeRef.current||!voice||!difficultiesRecorded||!voluntary)return;if(listeningSeconds<=0||boazSeconds<=0){setError('day006_required_duration_missing');return}setBusy(true);setError(null);try{const result=await sealDay006V1(auth.client,{evidence:{sessionId:session.id,mode:'first_completion',jachin:{durationSeconds:listeningSeconds,soundsNotedCount:soundsNoted},boaz:{durationSeconds:boazSeconds,thoughtReturns,difficultiesRecordedCount:3},middle:{voiceRecorded:voice.voiceRecorded},soulMirror:{difficultyRating:difficulty},safetyStopOccurred:safetyStopped},totalDurationSeconds:listeningSeconds+boazSeconds,soundsNotedCount:soundsNoted,thoughtReturns});if(!result.ok)throw new Error(result.code);setSealed(result.response);setSnapshot(runtimeRef.current.confirmServerCompletion())}catch(c){setError(c instanceof Error?c.message:'day006_completion_failed')}finally{setBusy(false)}}
  if(!bundle||!snapshot||!director)return <View style={styles.center}><Text style={styles.text}>CARREGANDO DAY 006…</Text>{error?<Text style={styles.error}>{error}</Text>:null}</View>;
  if(snapshot.runState==='SAFETY_STOP')return <View style={styles.center}><Text style={styles.title}>Prática pausada com segurança.</Text><Action label="RETOMAR" onPress={resume}/></View>;
  if(snapshot.runState==='COMPLETE')return <View style={styles.center}><Text style={styles.eyebrow}>DIA 006 · JELIEL 1/5</Text><Text style={styles.title}>O Silêncio da Psuche registrado.</Text><Text style={styles.text}>{sealed?.first_completion?`+${sealed.xp_awarded} XP canônicos.`:'Revisita sem novo XP.'}</Text><Text style={styles.text}>+1 PER é servidor-side. A Coroa permanece 1/7.</Text></View>;
  if(!directive)return <View style={styles.center}><Text style={styles.text}>FASE INDISPONÍVEL.</Text></View>;
  const p=directive.phase;const texts=directive.requiresCanonicalContent?canon(bundle,directive):[];
  return <ScrollView contentContainerStyle={styles.shell}><Text style={styles.eyebrow}>DIA 006 · KETHER · JELIEL 1/5</Text><Text style={styles.headerTitle}>O SILÊNCIO DA PSUCHE</Text>{error?<Text style={styles.error}>{error}</Text>:null}<View style={styles.panel}><Text style={styles.eyebrow}>{p.type} · {p.id}</Text>
    {p.type==='NARRATIVE'?<><Text style={styles.title}>Do fazer ao escutar.</Text><Text style={styles.text}>Silêncio perfeito não é requisito. Perceba e retorne.</Text></>:null}
    {p.type==='TERM_REVEAL'?<Text style={styles.text}>{(p.terms??[]).join(' · ')}</Text>:null}
    {p.type==='READ'?texts.map((t,i)=><Text key={i} style={styles.canon}>{t}</Text>):null}
    {p.type==='INSTRUCTION'?(p.content_intent??[]).map(x=><Text key={x} style={styles.text}>{x}</Text>):null}
    {p.type==='FOCUS'&&p.id==='listening_practice'?<Timer target={600} label="SOM PERCEBIDO" counter={soundsNoted} onCount={()=>setSoundsNoted(v=>v+1)} onFinish={s=>{setListeningSeconds(s);void completePhase(p.id)}} onSafetyStop={()=>void safetyStop('listening_safety_stop')}/>:null}
    {p.type==='FOCUS'&&p.id==='boaz_silence'?<Timer target={600} label="PENSAMENTO PERCEBIDO · VOLTAR" counter={thoughtReturns} onCount={()=>setThoughtReturns(v=>v+1)} onFinish={s=>{setBoazSeconds(s);void completePhase(p.id)}} onSafetyStop={()=>void safetyStop('silence_safety_stop')}/>:null}
    {p.type==='JOURNAL'?<><Text style={styles.text}>Registre três dificuldades no Vault; o servidor recebe só a contagem.</Text><Action label={difficultiesRecorded?'3 DIFICULDADES REGISTRADAS ✓':'CONFIRMAR 3 DIFICULDADES'} onPress={()=>setDifficultiesRecorded(v=>!v)}/><Action disabled={!difficultiesRecorded} label="CONTINUAR" onPress={()=>void completePhase(p.id)}/></>:null}
    {p.type==='VOICE'?<QuestVoicePhase directive={directive} onResult={setVoice} onCompletePhase={completePhase} onSafetyStop={safetyStop}/>:null}
    {p.type==='RETURN'?<><Text style={styles.text}>Respire naturalmente, movimente-se e confirme orientação.</Text><Action label="ESTOU ORIENTADO · CONTINUAR" onPress={()=>void completePhase(p.id)}/></>:null}
    {p.type==='STRUCTURED_JOURNAL'?<><Text style={styles.text}>Espelho da Alma · dificuldade percebida.</Text><View style={styles.row}>{[0,2,4,6,8,10].map(v=><Action key={v} label={String(v)} onPress={()=>setDifficulty(v)}/>)}</View><Action label="CONCLUIR ESPELHO" onPress={()=>void completePhase(p.id)}/></>:null}
    {p.type==='COMPLETION'?<><Text style={styles.title}>Selo canônico</Text><Text style={styles.text}>Gravação não é requisito. XP e PER vêm do servidor.</Text><Action label={voluntary?'CONCLUSÃO VOLUNTÁRIA ✓':'CONFIRMAR CONCLUSÃO VOLUNTÁRIA'} onPress={()=>setVoluntary(v=>!v)}/><Action disabled={busy||!voluntary} label={busy?'SELANDO…':'SELAR DAY 006'} onPress={()=>void seal()}/></>:null}
    {['NARRATIVE','TERM_REVEAL','READ','INSTRUCTION','UNLOCK'].includes(p.type)?<Action label="CONTINUAR" onPress={()=>void completePhase(p.id)}/>:null}
  </View></ScrollView>;
}
function Timer({target,label,counter,onCount,onFinish,onSafetyStop}:{target:number;label:string;counter:number;onCount:()=>void;onFinish:(s:number)=>void;onSafetyStop:()=>void}){const[s,setS]=useState(0);const[running,setRunning]=useState(false);useEffect(()=>{if(!running)return;const id=setInterval(()=>setS(v=>v+1),1000);return()=>clearInterval(id)},[running]);return <View style={styles.practice}><Text style={styles.text}>{s}s / {target}s</Text><Action label={running?'PAUSAR':'INICIAR / RETOMAR'} onPress={()=>setRunning(v=>!v)}/><Action label={`${label} · ${counter}`} onPress={onCount}/><Action disabled={s<=0} label="CONCLUIR PRÁTICA" onPress={()=>onFinish(s)}/><Action label="SAFETY STOP" onPress={onSafetyStop}/></View>}
function Action({label,onPress,disabled=false}:{label:string;onPress:()=>void;disabled?:boolean}){return <Pressable disabled={disabled} onPress={onPress} style={[styles.button,disabled&&styles.disabled]}><Text style={styles.buttonText}>{label}</Text></Pressable>}
const styles=StyleSheet.create({shell:{padding:20,paddingBottom:80,backgroundColor:'#090910',minHeight:'100%'},center:{flex:1,padding:28,justifyContent:'center',backgroundColor:'#090910',gap:14},panel:{borderWidth:1,borderColor:'#6f5f29',borderRadius:18,padding:18,gap:14,backgroundColor:'#111018'},practice:{gap:10},row:{flexDirection:'row',flexWrap:'wrap',gap:6},eyebrow:{color:'#d9bd67',fontSize:12,letterSpacing:1.4},headerTitle:{color:'#f4e6b2',fontSize:25,fontWeight:'800'},title:{color:'#f4e6b2',fontSize:22,fontWeight:'700'},text:{color:'#eee7d7',lineHeight:21},canon:{color:'#eee7d7',lineHeight:24,fontSize:15},error:{color:'#ffb4ab'},button:{borderWidth:1,borderColor:'#9a8240',borderRadius:12,padding:12,alignItems:'center'},disabled:{opacity:.4},buttonText:{color:'#f4e6b2',fontWeight:'700'}});
