import {useEffect,useMemo,useRef,useState} from 'react';
import {Pressable,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';
import * as SecureStore from 'expo-secure-store';
import {ExperienceDirector,QuestRuntime,createQuestCatalog,type ExperienceDirective,type PlayerContext,type SessionSnapshot} from '@hnk/quest-engine';
import {createBundledQuestLibrary,type RuntimeQuestBundle} from '@hnk/quest-library';
import {assertSitaelProgress,loadDay015PracticeSessionV1,sealDay015V1,startDay015PracticeSessionV1,type Day015Method} from '@hnk/supabase-client';
import {useHnkAuth} from '../auth/AuthContext';
import {createMobileVaultTextPort} from '../../runtime/MobileVaultTextPort';

type Session=NonNullable<Awaited<ReturnType<typeof loadDay015PracticeSessionV1>>>;
type Seal=Extract<Awaited<ReturnType<typeof sealDay015V1>>,{ok:true}>['response'];
interface Draft{method:Day015Method|null;beforeScore:number;afterScore:number;disciplineScore:number;externalizationRef:string|null;closureRef:string|null;commitmentRef:string|null;soulRef:string|null;symbolicDestroyed:boolean;symbolNotGuarantee:boolean;responsibilityNotErased:boolean;prayer:boolean;responsibilityRemains:boolean;futureActionNotClaimedDone:boolean;burnStable:boolean;burnFlammablesClear:boolean;burnHeatContainer:boolean;burnWater:boolean;burnSupervised:boolean;burnSafeMaterial:boolean;burnExtinguished:boolean;burnAreaRechecked:boolean;safetyStopped:boolean}
const emptyDraft:Draft={method:null,beforeScore:5,afterScore:5,disciplineScore:5,externalizationRef:null,closureRef:null,commitmentRef:null,soulRef:null,symbolicDestroyed:false,symbolNotGuarantee:false,responsibilityNotErased:false,prayer:false,responsibilityRemains:false,futureActionNotClaimedDone:false,burnStable:false,burnFlammablesClear:false,burnHeatContainer:false,burnWater:false,burnSupervised:false,burnSafeMaterial:false,burnExtinguished:false,burnAreaRechecked:false,safetyStopped:false};
function canon(bundle:RuntimeQuestBundle,d:ExperienceDirective){return(d.phase.source.block_ids??[]).map(id=>{const b=bundle.canon.blocks.find(x=>x.id===id);if(!b)throw new Error(`canonical_block_missing:${id}`);return b.text})}
function keys(u:string){return{snapshot:`hnk.quest.d015.${u}.snapshot.v1`,session:`hnk.quest.d015.${u}.session.v1`,draft:`hnk.quest.d015.${u}.draft.v1`}}
async function loadJson<T>(k:string):Promise<T|null>{try{const raw=await SecureStore.getItemAsync(k);return raw?JSON.parse(raw) as T:null}catch{return null}}
async function saveJson(k:string,v:unknown){await SecureStore.setItemAsync(k,JSON.stringify(v))}
function clientId(u:string){return`hnk-mobile-d015-v1-${u}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`}
function clamp(v:string){const n=Number(v);return Number.isInteger(n)?Math.max(0,Math.min(10,n)):0}

export function Day015GoldenV1Mobile(){
 const auth=useHnkAuth();const live=Boolean(auth.configured&&auth.phase==='signed-in'&&auth.client&&auth.userId);const runtimeRef=useRef<QuestRuntime|null>(null);
 const[bundle,setBundle]=useState<RuntimeQuestBundle|null>(null);const[snapshot,setSnapshot]=useState<SessionSnapshot|null>(null);const[session,setSession]=useState<Session|null>(null);const[draft,setDraft]=useState<Draft>(emptyDraft);const[loaded,setLoaded]=useState(false);
 const[p1,setP1]=useState('');const[p2,setP2]=useState('');const[p3,setP3]=useState('');const[tomorrow,setTomorrow]=useState('');const[phrase,setPhrase]=useState('');const[closure,setClosure]=useState('');const[commitment,setCommitment]=useState('');const[soul,setSoul]=useState('');const[voluntary,setVoluntary]=useState(false);const[busy,setBusy]=useState(false);const[error,setError]=useState<string|null>(null);const[sealed,setSealed]=useState<Seal|null>(null);
 const context=useMemo<PlayerContext>(()=>({mediationMode:'HNK_CANONICAL',accessibility:{reducedMotion:false,audioEnabled:false,microphoneAvailable:false},offline:!live}),[live]);
 const vault=useMemo(()=>auth.userId?createMobileVaultTextPort(auth.client??null):null,[auth.client,auth.userId]);
 useEffect(()=>{if(!auth.userId)return;let ok=true;const lib=createBundledQuestLibrary(),cat=createQuestCatalog(lib),k=keys(auth.userId);void Promise.all([cat.requireDay(15),lib.loadBundle(15),loadJson<SessionSnapshot>(k.snapshot),loadJson<Session>(k.session),loadJson<Draft>(k.draft)]).then(([def,b,saved,ss,dd])=>{if(!ok||!b)return;const r=new QuestRuntime(def);runtimeRef.current=r;setBundle(b);setSnapshot(saved?r.restore(saved):r.start());if(ss)setSession(ss);setDraft(dd??emptyDraft);setLoaded(true)}).catch(e=>ok&&setError(e instanceof Error?e.message:'day015_load_failed'));return()=>{ok=false}},[auth.userId]);
 useEffect(()=>{if(!auth.userId||!snapshot)return;const k=keys(auth.userId);if(snapshot.runState==='COMPLETE'){void SecureStore.deleteItemAsync(k.snapshot);void SecureStore.deleteItemAsync(k.session);void SecureStore.deleteItemAsync(k.draft)}else void saveJson(k.snapshot,snapshot)},[auth.userId,snapshot]);
 useEffect(()=>{if(auth.userId&&loaded&&snapshot?.runState!=='COMPLETE')void saveJson(keys(auth.userId).draft,draft)},[auth.userId,draft,loaded,snapshot?.runState]);
 const director=useMemo(()=>bundle?new ExperienceDirector(bundle.quest):null,[bundle]);const directive=useMemo(()=>director&&snapshot?.currentPhaseId?director.resolvePhase(snapshot.currentPhaseId,context,snapshot):null,[director,context,snapshot]);
 async function ensureSession(){if(session)return session;if(!live||!auth.client||!auth.userId)throw new Error('online_session_required_before_day015_practice');const s=await startDay015PracticeSessionV1(auth.client,{clientSessionId:clientId(auth.userId),appVersion:'0.1.0-mobile-day015-golden-v1'});setSession(s);await saveJson(keys(auth.userId).session,s);return s}
 async function complete(id:string){setError(null);try{if(id==='jachin_reading')await ensureSession();const r=runtimeRef.current;if(r)setSnapshot(r.completePhase(id))}catch(e){setError(e instanceof Error?e.message:'phase_failed')}}
 function safetyStop(){setDraft(d=>({...d,safetyStopped:true}));setError('safety_stop__interrompa_o_gesto__apague_qualquer_chama__confira_o_ambiente');if(runtimeRef.current)setSnapshot(runtimeRef.current.safetyStop())}
 function resume(){setError(null);if(runtimeRef.current)setSnapshot(runtimeRef.current.resume())}
 async function saveExternalization(){if(!vault||!auth.userId||![p1,p2,p3,tomorrow,phrase].every(x=>x.trim()))throw new Error('three_patterns_discipline_and_phrase_required');const e=await vault.saveText({userId:auth.userId,day:15,kind:'journal',plaintext:JSON.stringify({schema:'hnk-day015-externalization-v1',patterns:[p1.trim(),p2.trim(),p3.trim()],tomorrowDiscipline:tomorrow.trim(),nextCyclePhrase:phrase.trim()})});setDraft(d=>({...d,externalizationRef:e.entryId}));setP1('');setP2('');setP3('');setTomorrow('');setPhrase('');await complete('jachin_externalization')}
 async function chooseMethod(m:Day015Method){setDraft(d=>({...d,method:m}));await complete('destruction_method')}
 async function saveClosure(){if(!vault||!auth.userId||!draft.method||!draft.symbolicDestroyed||!draft.symbolNotGuarantee||!draft.responsibilityNotErased||!closure.trim())throw new Error('closure_evidence_required');if(draft.method==='BURN_SAFE'&&!(draft.burnStable&&draft.burnFlammablesClear&&draft.burnHeatContainer&&draft.burnWater&&draft.burnSupervised&&draft.burnSafeMaterial&&draft.burnExtinguished&&draft.burnAreaRechecked))throw new Error('burn_safety_gate_required');const e=await vault.saveText({userId:auth.userId,day:15,kind:'journal',plaintext:JSON.stringify({schema:'hnk-day015-closure-v1',method:draft.method,closure:closure.trim()})});setDraft(d=>({...d,closureRef:e.entryId}));setClosure('');await complete('boaz_closure')}
 async function saveCommitment(){if(!vault||!auth.userId||!draft.prayer||!draft.responsibilityRemains||!draft.futureActionNotClaimedDone||!commitment.trim())throw new Error('middle_commitment_required');const e=await vault.saveText({userId:auth.userId,day:15,kind:'journal',plaintext:JSON.stringify({schema:'hnk-day015-middle-v1',nextCycleCommitment:commitment.trim(),disciplineScore:draft.disciplineScore})});setDraft(d=>({...d,commitmentRef:e.entryId}));setCommitment('');await complete('middle_integration')}
 async function saveSoul(){if(!vault||!auth.userId||!soul.trim())throw new Error('soul_mirror_required');const e=await vault.saveText({userId:auth.userId,day:15,kind:'journal',plaintext:JSON.stringify({schema:'hnk-day015-soul-v1',responsibilityAndTomorrowAction:soul.trim()})});setDraft(d=>({...d,soulRef:e.entryId}));setSoul('');await complete('soul_mirror')}
 async function seal(){if(!runtimeRef.current||!live||!auth.client||!auth.userId||!session||!vault||!draft.externalizationRef||!draft.closureRef||!draft.commitmentRef||!draft.soulRef||!draft.method||!voluntary)return;setBusy(true);setError(null);try{await vault.flushPending(auth.userId);const er=await vault.resolveEntryId(auth.userId,draft.externalizationRef),cr=await vault.resolveEntryId(auth.userId,draft.closureRef),mr=await vault.resolveEntryId(auth.userId,draft.commitmentRef),sr=await vault.resolveEntryId(auth.userId,draft.soulRef);if(!er||!cr||!mr||!sr)throw new Error('vault_sync_required_before_completion');const burnSafety=draft.method==='BURN_SAFE'?{stableSurfaceConfirmed:draft.burnStable,flammablesClearConfirmed:draft.burnFlammablesClear,heatResistantContainerConfirmed:draft.burnHeatContainer,waterAvailableConfirmed:draft.burnWater,continuousSupervisionConfirmed:draft.burnSupervised,safeMaterialOnlyConfirmed:draft.burnSafeMaterial,flameFullyExtinguishedConfirmed:draft.burnExtinguished,areaRecheckedConfirmed:draft.burnAreaRechecked}:undefined;const result=await sealDay015V1(auth.client,{evidence:{sessionId:session.id,mode:'first_completion',patternsCount:3,emotionalIntensityBefore:draft.beforeScore,externalizationVaultEntryRef:er,method:draft.method,symbolicDestructionCompleted:draft.symbolicDestroyed,emotionalIntensityAfter:draft.afterScore,symbolNotGuaranteeConfirmed:draft.symbolNotGuarantee,responsibilityNotErasedConfirmed:draft.responsibilityNotErased,closureVaultEntryRef:cr,burnSafety,psalm912PrayerConfirmed:draft.prayer,disciplineScore:draft.disciplineScore,responsibilityRemainsConfirmed:draft.responsibilityRemains,futureActionCommittedNotClaimedCompleted:draft.futureActionNotClaimedDone,nextCycleCommitmentVaultEntryRef:mr,soulMirrorCompleted:true,responsibilityAndTomorrowActionVaultEntryRef:sr,safetyStopOccurred:draft.safetyStopped},totalDurationSeconds:Math.max(0,Math.floor((Date.now()-new Date(session.started_at).getTime())/1000))});if(!result.ok)throw new Error(result.code);assertSitaelProgress(result.response.crown,5);setSealed(result.response);setSnapshot(runtimeRef.current.confirmServerCompletion())}catch(e){setError(e instanceof Error?e.message:'day015_completion_failed')}finally{setBusy(false)}}
 if(!auth.userId)return <Center text="ENTRE NO ÁTRIO PARA INICIAR O DIA 015."/>;if(!bundle||!snapshot||!director)return <Center text={error??'CARREGANDO DAY 015…'}/>;if(snapshot.runState==='SAFETY_STOP')return <View style={s.center}><Text style={s.title}>PRÁTICA INTERROMPIDA COM SEGURANÇA</Text><Text style={s.text}>Interrompa o gesto. Se houver chama, apague-a completamente e confira o ambiente.</Text><Action label="RETOMAR" onPress={resume}/></View>;if(snapshot.runState==='COMPLETE')return <View style={s.center}><Text style={s.eyebrow}>DIA 015 · SITAEL 5/5</Text><Text style={s.title}>FRAGMENTO III ACESO</Text><Text style={s.text}>{sealed?.first_completion?`+${sealed.xp_awarded} XP canônicos.`:'Revisita sem novo XP.'}</Text><Text style={s.text}>Sitael 5/5 confirmado pelo servidor · Coroa {sealed?.crown.fragments_lit??3}/7 · Day 16 liberado.</Text></View>;if(!directive)return <Center text="FASE INDISPONÍVEL."/>;
 const p=directive.phase,texts=directive.requiresCanonicalContent?canon(bundle,directive):[];
 return <ScrollView contentContainerStyle={s.shell}><Text style={s.eyebrow}>DIA 015 · KETHER · SITAEL 5/5</Text><Text style={s.header}>BANIMENTO PELO FOGO</Text><Text style={s.status}>{live?'VAULT E2EE · ONLINE':'VAULT E2EE · FILA CIFRADA OFFLINE'} · FOGO OPCIONAL</Text>{error?<Text style={s.error}>{error}</Text>:null}<View style={s.panel}><Text style={s.eyebrow}>{p.type} · {p.id}</Text>
 {p.type==='NARRATIVE'?<><Text style={s.title}>Externalizar. Encerrar. Retornar.</Text><Text style={s.text}>O sentido está na decisão e na ação seguinte. Combustão não é necessária.</Text></>:null}{p.type==='READ'?texts.map((t,i)=><Text key={i} style={s.canon}>{t}</Text>):null}
 {p.id==='jachin_externalization'?<><Input value={p1} set={setP1} placeholder="Padrão 1"/><Input value={p2} set={setP2} placeholder="Padrão 2"/><Input value={p3} set={setP3} placeholder="Padrão 3"/><Input value={tomorrow} set={setTomorrow} placeholder="Disciplina concreta para amanhã"/><Input value={phrase} set={setPhrase} placeholder="Frase para o próximo ciclo"/><Num label="Intensidade antes" value={draft.beforeScore} set={v=>setDraft(d=>({...d,beforeScore:v}))}/><Action label="CIFRAR NO VAULT" onPress={()=>void saveExternalization()}/></>:null}
 {p.id==='destruction_method'?<><Text style={s.text}>Se houver qualquer dúvida sobre segurança, escolha uma rota sem fogo.</Text><Action label="RASGAR" onPress={()=>void chooseMethod('TEAR')}/><Action label="PICOTAR / DESCARTAR" onPress={()=>void chooseMethod('SHRED_DISCARD')}/><Action label="FOGO — GATE COMPLETO" onPress={()=>void chooseMethod('BURN_SAFE')}/></>:null}
 {p.id==='boaz_closure'?<><Text style={s.title}>Método: {draft.method??'—'}</Text>{draft.method==='BURN_SAFE'?<><Toggle label="Superfície firme" value={draft.burnStable} on={()=>setDraft(d=>({...d,burnStable:!d.burnStable}))}/><Toggle label="Inflamáveis afastados" value={draft.burnFlammablesClear} on={()=>setDraft(d=>({...d,burnFlammablesClear:!d.burnFlammablesClear}))}/><Toggle label="Recipiente resistente ao calor" value={draft.burnHeatContainer} on={()=>setDraft(d=>({...d,burnHeatContainer:!d.burnHeatContainer}))}/><Toggle label="Água disponível" value={draft.burnWater} on={()=>setDraft(d=>({...d,burnWater:!d.burnWater}))}/><Toggle label="Supervisão contínua" value={draft.burnSupervised} on={()=>setDraft(d=>({...d,burnSupervised:!d.burnSupervised}))}/><Toggle label="Somente material seguro" value={draft.burnSafeMaterial} on={()=>setDraft(d=>({...d,burnSafeMaterial:!d.burnSafeMaterial}))}/><Toggle label="Chama totalmente apagada" value={draft.burnExtinguished} on={()=>setDraft(d=>({...d,burnExtinguished:!d.burnExtinguished}))}/><Toggle label="Ambiente conferido" value={draft.burnAreaRechecked} on={()=>setDraft(d=>({...d,burnAreaRechecked:!d.burnAreaRechecked}))}/></>:<Text style={s.text}>Rota sem fogo plenamente válida.</Text>}<Toggle label="Gesto simbólico concluído" value={draft.symbolicDestroyed} on={()=>setDraft(d=>({...d,symbolicDestroyed:!d.symbolicDestroyed}))}/><Toggle label="Símbolo não garante resultado" value={draft.symbolNotGuarantee} on={()=>setDraft(d=>({...d,symbolNotGuarantee:!d.symbolNotGuarantee}))}/><Toggle label="Responsabilidade não foi apagada" value={draft.responsibilityNotErased} on={()=>setDraft(d=>({...d,responsibilityNotErased:!d.responsibilityNotErased}))}/><Num label="Intensidade depois" value={draft.afterScore} set={v=>setDraft(d=>({...d,afterScore:v}))}/><Input value={closure} set={setClosure} placeholder="Segurança / alternativa / ação nas próximas horas" multiline/><Action label="CIFRAR FECHAMENTO" onPress={()=>void saveClosure()}/><Action label="SAFETY STOP" onPress={safetyStop}/></>:null}
 {p.id==='middle_integration'?<><Toggle label="Oração / Salmo 91:2" value={draft.prayer} on={()=>setDraft(d=>({...d,prayer:!d.prayer}))}/><Toggle label="Minha responsabilidade permanece" value={draft.responsibilityRemains} on={()=>setDraft(d=>({...d,responsibilityRemains:!d.responsibilityRemains}))}/><Toggle label="A ação futura não está falsamente marcada como concluída" value={draft.futureActionNotClaimedDone} on={()=>setDraft(d=>({...d,futureActionNotClaimedDone:!d.futureActionNotClaimedDone}))}/><Num label="Disciplina atual" value={draft.disciplineScore} set={v=>setDraft(d=>({...d,disciplineScore:v}))}/><Input value={commitment} set={setCommitment} placeholder="Compromisso do próximo ciclo" multiline/><Action label="CIFRAR COMPROMISSO" onPress={()=>void saveCommitment()}/></>:null}
 {p.id==='soul_mirror'?<><Input value={soul} set={setSoul} placeholder="Responsabilidade + ação de amanhã" multiline/><Action label="CIFRAR ESPELHO DA ALMA" onPress={()=>void saveSoul()}/></>:null}
 {p.id==='completion'?<><Toggle label="Confirmo voluntariamente o encerramento de Sitael" value={voluntary} on={()=>setVoluntary(v=>!v)}/><Action label={busy?'SELANDO…':'SELAR SITAEL — SERVIDOR AUTORITATIVO'} onPress={()=>void seal()} disabled={busy||!voluntary||!live}/></>:null}
 {!['jachin_externalization','destruction_method','boaz_closure','middle_integration','soul_mirror','completion'].includes(p.id)?<Action label="CONTINUAR" onPress={()=>void complete(p.id)}/>:null}</View></ScrollView>
}
function Center({text}:{text:string}){return <View style={s.center}><Text style={s.title}>{text}</Text></View>}
function Action({label,onPress,disabled=false}:{label:string;onPress:()=>void;disabled?:boolean}){return <Pressable disabled={disabled} onPress={onPress} style={[s.action,disabled&&s.disabled]}><Text style={s.actionText}>{label}</Text></Pressable>}
function Toggle({label,value,on}:{label:string;value:boolean;on:()=>void}){return <Pressable onPress={on} style={s.toggle}><Text style={s.text}>{value?'☑':'☐'} {label}</Text></Pressable>}
function Input({value,set,placeholder,multiline=false}:{value:string;set:(v:string)=>void;placeholder:string;multiline?:boolean}){return <TextInput style={[s.input,multiline&&s.multi]} value={value} onChangeText={set} placeholder={placeholder} placeholderTextColor="#82796e" multiline={multiline}/>} 
function Num({label,value,set}:{label:string;value:number;set:(v:number)=>void}){return <View><Text style={s.text}>{label}: {value}/10</Text><TextInput style={s.input} keyboardType="number-pad" value={String(value)} onChangeText={v=>set(clamp(v))}/></View>}
const s=StyleSheet.create({shell:{padding:22,paddingBottom:80,backgroundColor:'#090910',gap:14},center:{flex:1,minHeight:640,justifyContent:'center',padding:24,backgroundColor:'#090910'},panel:{borderWidth:1,borderColor:'#a06d37',borderRadius:18,padding:18,gap:12},eyebrow:{color:'#c9a66b',fontSize:12,letterSpacing:1.2},header:{color:'#f3eadb',fontSize:30,fontWeight:'800'},title:{color:'#f3eadb',fontSize:22,fontWeight:'700'},text:{color:'#ded5c5',fontSize:16,lineHeight:23},canon:{color:'#ded5c5',fontSize:16,lineHeight:26},status:{color:'#b7aa97'},error:{color:'#ffb4ab'},input:{borderWidth:1,borderColor:'#5e5549',borderRadius:10,padding:12,color:'#f3eadb'},multi:{minHeight:110,textAlignVertical:'top'},action:{padding:13,borderRadius:10,borderWidth:1,borderColor:'#a06d37'},actionText:{color:'#f3eadb',fontWeight:'700',textAlign:'center'},disabled:{opacity:.45},toggle:{paddingVertical:5}});
