import { assertBoardContract, type HnkBoard } from '../board';

export const ketherChapterOverview = assertBoardContract({
  schemaVersion: '1.0',
  id: 'kether-chapter-overview-v1',
  slug: 'kether-chapter-overview',
  family: 'chapter-overview',
  scope: 'chapter',
  scopeId: 'kether',
  version: 1,
  lifecycle: 'rendered',
  title: 'Kether — A Coroa',
  subtitle: 'O Portal da Emanação Primal de Atziluth',
  rangeLabel: 'Dias 1–36',
  summary:
    'Primeiro estágio do Codex Interativo 365: origem, silêncio, emanação, disciplina inicial e preparação do Portal de Transmutação para Chokmah.',
  facts: [
    { label: 'Sephira', value: 'Kether', emphasis: 'primary' },
    { label: 'Mundo', value: 'Atziluth', emphasis: 'ritual' },
    { label: 'Level', value: '1 — Neófito', emphasis: 'system' },
    { label: 'Atributo foco', value: 'SIN — Sintonia Espiritual Zoe', emphasis: 'system' },
    { label: 'Dias', value: '1–36', emphasis: 'secondary' },
  ],
  sections: [
    {
      id: 'thesis',
      eyebrow: 'Núcleo',
      title: 'Origem e Emanação',
      body:
        'Kether apresenta a Coroa como ponto de origem da jornada: silêncio, intenção, disciplina, foco e progressiva emanação da experiência sobre o vazio.',
    },
    {
      id: 'experience',
      eyebrow: 'Experiência',
      title: 'Da quase ausência de interface ao códice vivo',
      items: [
        'O Day 001 começa com baixa densidade e a interface emerge progressivamente.',
        'Luz comunica estado, desbloqueio e transformação.',
        'Ouro funciona como material e autoridade, nunca apenas como borda decorativa.',
        'A geometria deve organizar a leitura e permanecer legível em 390px.',
      ],
    },
    {
      id: 'rpg',
      eyebrow: 'RPG',
      title: 'Progressão de Neófito',
      facts: [
        { label: 'Level', value: '1 — Neófito', emphasis: 'primary' },
        { label: 'Foco', value: 'SIN', emphasis: 'system' },
        { label: 'Portal', value: 'Dia 036 → Chokmah', emphasis: 'ritual' },
      ],
    },
  ],
  cycles: [
    {
      id: 'vehuiah',
      index: 1,
      label: 'Ciclo I',
      days: [1, 5],
      title: 'Vehuiah',
      focus: 'Faísca inicial, intenção e entrada disciplinada no Codex.',
      attributes: ['SIN', 'DIS'],
    },
    {
      id: 'jeliel',
      index: 2,
      label: 'Ciclo II',
      days: [6, 10],
      title: 'Jeliel',
      focus: 'Silêncio, relaxamento e aprofundamento do estado de prática.',
      attributes: ['HIP', 'SIN'],
    },
    {
      id: 'sitael',
      index: 3,
      label: 'Ciclo III',
      days: [11, 15],
      title: 'Sitael',
      focus: 'Disciplina de foco, observação e concentração unidirecional.',
      attributes: ['VNT', 'PER'],
    },
    {
      id: 'elemiah',
      index: 4,
      label: 'Ciclo IV',
      days: [16, 20],
      title: 'Elemiah',
      focus: 'Expressão extática e passagem do controle verbal para experiência direta.',
      attributes: ['SIN', 'HIP'],
    },
    {
      id: 'mahasiah',
      index: 5,
      label: 'Ciclo V',
      days: [21, 25],
      title: 'Mahasiah',
      focus: 'Luz, integração somática e linguagem bioenergética dentro do modelo HNK.',
      attributes: ['BIO', 'SIN'],
    },
    {
      id: 'lelahel',
      index: 6,
      label: 'Ciclo VI',
      days: [26, 30],
      title: 'Lelahel',
      focus: 'Consolidação da luz, percepção e continuidade da prática.',
      attributes: ['PER', 'SIN'],
    },
    {
      id: 'achaiah',
      index: 7,
      label: 'Ciclo VII',
      days: [31, 35],
      title: 'Achaiah',
      focus: 'Maturação do ciclo e preparação direta para a transmutação.',
      attributes: ['DIS', 'SIN'],
    },
  ],
  portal: {
    days: [36],
    title: 'Portal de Transmutação de Kether para Chokmah',
    destination: 'Chokmah',
    summary: 'Fechamento de Kether e passagem para o estágio de receptividade e sabedoria.',
  },
  sources: [
    {
      kind: 'canonical',
      label: 'Codex canônico — Capítulo 1 Kether',
      repository: 'Tehkne-Solutions/hnk-codex-365',
      path: 'canon/capitulo-01-kether',
      note: 'Canonical chapter/day content remains the source of truth.',
    },
    {
      kind: 'design',
      label: 'HNK Visual Bible',
      repository: 'Tehkne-Solutions/codex-hnk-app',
      path: 'docs/HNK_VISUAL_BIBLE.md',
    },
    {
      kind: 'spec',
      label: 'Kether Freeze V1',
      repository: 'Tehkne-Solutions/codex-hnk-app',
      path: 'docs/experience/kether/HNK_KETHER_FREEZE_V1.md',
    },
    {
      kind: 'spec',
      label: 'Board Artifact System V1',
      repository: 'Tehkne-Solutions/codex-hnk-app',
      path: 'docs/design/HNK_BOARD_ARTIFACT_SYSTEM_V1.md',
    },
  ],
  outputs: [
    {
      kind: 'board-img',
      path: 'assets/boards/chapter/kether/v1/kether-chapter-overview.png',
      mimeType: 'image/png',
    },
    {
      kind: 'board-doc',
      path: 'assets/boards/chapter/kether/v1/README.md',
      mimeType: 'text/markdown',
    },
    {
      kind: 'board-code',
      path: 'packages/assets/src/boards/kether-chapter-overview.ts',
      mimeType: 'text/typescript',
    },
  ],
  renderTargets: ['print-landscape', 'desktop', 'tablet', 'mobile-390', 'thumbnail'],
  visual: {
    direction: 'HNK SACRED EDITORIAL FANTASY',
    density: 'dense-editorial',
    paletteIntent: ['deep black', 'intense origin white', 'restrained material gold'],
    materialIntent: ['obsidian', 'dark glass', 'engraved metal', 'luminous linework'],
    allowedGeometry: ['crown/origin axis', 'circles', 'rings', 'Tree node', 'portal geometry'],
    forbiddenAdditions: [
      'invented sacred names',
      'invented Hebrew',
      'invented sigils presented as canon',
      'generic fantasy angel figures',
      'decorative galaxy wallpaper',
      'generic SaaS card grid',
    ],
  },
  accessibility: {
    alt: 'Editorial overview board for Kether, Chapter 1 of the HNK Codex, showing the 36-day progression, seven cycles and the Day 36 portal to Chokmah.',
    mobileSummary: 'Kether, Days 1–36: seven cycles culminating in the Day 36 portal to Chokmah.',
  },
} satisfies HnkBoard);
