import { useState } from 'react';
import { Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import type { ExperienceDirective } from '@hnk/quest-engine';
import type { VaultTextPort } from '@hnk/vault-contract';

export type DreamRecallStatus='REMEMBERED'|'NO_RECALL';
export type DreamJournalResult=
 |{mode:'CAPTURE';recallStatus:DreamRecallStatus;dreamVaultEntryRef?:string;emotionRecorded:boolean;scenarioRecorded:boolean;firstDetailRecorded:boolean}
 |{mode:'SEPARATE';separationCompleted:true;interpretationIsHypothesisConfirmed:true;sleepProtectionConfirmed:true}
 |{mode:'REFLECT';associationsCount:number;reflectionVaultEntryRef?:string;analysisStoppedConfirmed:true};
export interface Props{directive:ExperienceDirective;port:VaultTextPort;userId:string;recallStatus?:DreamRecallStatus;onResult:(result:DreamJournalResult)=>void;onCompletePhase:(phaseId:string)=>void|Promise<void>;onSafetyStop:(reason?:string)=>void|Promise<void>}
export function QuestDreamJournalPhase({directive,port,userId,recallStatus:externalRecall,onResult,onCompletePhase,onSafetyStop}:Props){
 const mode=String(directive.phase.interaction?.mode??'CAPTURE') as 'CAPTURE'|'SEPARATE'|'REFLECT';const[recall,setRecall]=useState<DreamRecallStatus>(externalRecall??'REMEMBERED');const[a,setA]=useState('');const[b,setB]=useState('');const[c,setC]=useState('');const[d,setD]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState<string|null>(null);const cap=port.capability();
 async function finish(){setBusy(true);setError(null);try{if(mode==='CAPTURE'){if(recall==='NO_RECALL'){onResult({mode:'CAPTURE',recallStatus:'NO_RECALL',emotionRecorded:false,scenarioRecorded:false,firstDetailRecorded:false});await onCompletePhase(directive.phase.id);return}if(!a.trim()||!b.trim()||!c.trim()||!d.trim())throw new Error('dream_capture_fields_required');const saved=await port.saveText({userId,day:9,kind:'dream',plaintext:JSON.stringify({schema:'hnk-dream-capture-v1',description:a,emotion:b,scenario:c,firstDetail:d})});onResult({mode:'CAPTURE',recallStatus:'REMEMBERED',dreamVaultEntryRef:saved.entryId,emotionRecorded:true,scenarioRecorded:true,firstDetailRecorded:true});await onCompletePhase(directive.phase.id);return}if(mode==='SEPARATE'){if(externalRecall==='REMEMBERED'){if(!a.trim()||!b.trim()||!c.trim())throw new Error('dream_separation_fields_required');await port.saveText({userId,day:9,kind:'journal',plaintext:JSON.stringify({schema:'hnk-dream-separation-v1',whatIDreamed:a,whatIFelt:b,whatIThink:c,interpretationStatus:'PERSONAL_HYPOTHESIS'})})}onResult({mode:'SEPARATE',separationCompleted:true,interpretationIsHypothesisConfirmed:true,sleepProtectionConfirmed:true});await onCompletePhase(directive.phase.id);return}if(externalRecall==='REMEMBERED'){if(!a.trim()||!b.trim()||!c.trim())throw new Error('three_associations_required');const saved=await port.saveText({userId,day:9,kind:'journal',plaintext:JSON.stringify({schema:'hnk-dream-reflection-v1',associations:[a,b,c],universalMeaningClaimed:false})});onResult({mode:'REFLECT',associationsCount:3,reflectionVaultEntryRef:saved.entryId,analysisStoppedConfirmed:true});await onCompletePhase(directive.phase.id);return}onResult({mode:'REFLECT',associationsCount:0,analysisStoppedConfirmed:true});await onCompletePhase(directive.phase.id)}catch(e){setError(e instanceof Error?e.message:'dream_journal_failed')}finally{setBusy(false)}}
 return <View style={styles.panel}><Text style={styles.eyebrow}>DIÁRIO ONÍRICO · {mode}</Text><Text style={styles.text}>O conteúdo é cifrado neste dispositivo antes do envio. O servidor recebe apenas ciphertext e referência opaca.</Text>{cap.deviceBound&&!cap.recoveryConfigured?<Text style={styles.warn}>Vault V1 é ligado a este dispositivo. Sem recovery configurado, perder a chave local pode tornar registros antigos irrecuperáveis.</Text>:null}<Text style={styles.text}>Áudio E2EE ainda não está disponível nesta V1; texto criptografado ou “sem lembrança” são caminhos completos.</Text>
 {mode==='CAPTURE'?<><Action label={recall==='REMEMBERED'?'LEMBREI DE ALGO ✓':'LEMBREI DE ALGO'} onPress={()=>setRecall('REMEMBERED')}/><Action label={recall==='NO_RECALL'?'SEM LEMBRANÇA HOJE ✓':'SEM LEMBRANÇA HOJE'} onPress={()=>setRecall('NO_RECALL')}/>{recall==='REMEMBERED'?<><Field value={a} set={setA} placeholder="O que aconteceu no sonho?" multiline/><Field value={b} set={setB} placeholder="Emoção predominante"/><Field value={c} set={setC} placeholder="Cenário principal"/><Field value={d} set={setD} placeholder="Primeiro detalhe lembrado"/></>:null}</>:null}
 {mode==='SEPARATE'&&externalRecall==='REMEMBERED'?<><Field value={a} set={setA} placeholder="O que sonhei — descrição" multiline/><Field value={b} set={setB} placeholder="O que senti" multiline/><Field value={c} set={setC} placeholder="O que penso — hipótese pessoal" multiline/></>:null}{mode==='SEPARATE'&&externalRecall==='NO_RECALL'?<Text style={styles.text}>“Sem lembrança hoje” é dado válido. Não invente conteúdo.</Text>:null}
 {mode==='REFLECT'&&externalRecall==='REMEMBERED'?<><Field value={a} set={setA} placeholder="Associação pessoal 1"/><Field value={b} set={setB} placeholder="Associação pessoal 2"/><Field value={c} set={setC} placeholder="Associação pessoal 3"/><Text style={styles.text}>Associações pessoais não são significado universal nem previsão.</Text></>:null}{mode==='REFLECT'&&externalRecall==='NO_RECALL'?<Text style={styles.text}>Sem imagem lembrada, não há associações a fabricar.</Text>:null}
 {error?<Text style={styles.error}>{error}</Text>:null}<Action disabled={busy} label={busy?'CIFRANDO…':'SALVAR COM SEGURANÇA · CONTINUAR'} onPress={()=>void finish()}/><Action label="ENCERRAR POR AGORA" onPress={()=>void onSafetyStop('dream_journal_stop')}/></View>
}
function Field({value,set,placeholder,multiline=false}:{value:string;set:(v:string)=>void;placeholder:string;multiline?:boolean}){return <TextInput value={value} onChangeText={set} placeholder={placeholder} placeholderTextColor="#817967" multiline={multiline} style={[styles.input,multiline&&styles.multiline]}/>}
function Action({label,onPress,disabled=false}:{label:string;onPress:()=>void;disabled?:boolean}){return <Pressable disabled={disabled} onPress={onPress} style={[styles.button,disabled&&styles.disabled]}><Text style={styles.buttonText}>{label}</Text></Pressable>}
const styles=StyleSheet.create({panel:{gap:12,padding:18,borderWidth:1,borderColor:'#6f5f29',borderRadius:18,backgroundColor:'#111018'},eyebrow:{color:'#d9bd67',fontSize:12,letterSpacing:1.4},text:{color:'#eee7d7',lineHeight:21},warn:{color:'#d9bd67',lineHeight:20},input:{borderWidth:1,borderColor:'#6f5f29',borderRadius:10,padding:12,color:'#eee7d7'},multiline:{minHeight:96,textAlignVertical:'top'},button:{borderWidth:1,borderColor:'#9a8240',borderRadius:12,padding:12,alignItems:'center'},disabled:{opacity:.4},buttonText:{color:'#f4e6b2',fontWeight:'700'},error:{color:'#ffb4ab'}});
