import { useEffect, useMemo, useRef, useState } from 'react';
import { AppState, Pressable, StyleSheet, Text, View } from 'react-native';
import {
  createQuestAudioController,
  type AudioRuntimeSnapshot,
  type ExperienceDirective,
} from '@hnk/quest-engine';
import { createMobileQuestAudioRuntimeRegistry } from './quest-audio-runtime';

export interface TimedAudioCompletion {
  effectiveSeconds: number;
  averageVolumePermille: number;
  headphonesConfirmed: boolean;
}
export interface QuestTimedAudioPhaseProps {
  directive: ExperienceDirective;
  volume: number;
  onVolumeChange: (volume: number) => void;
  onCompletePhase: (phaseId: string, result: TimedAudioCompletion) => void | Promise<void>;
  onSafetyStop: (reason?: string) => void | Promise<void>;
  onInvalidated?: (reason: string) => void;
}
const VOLUME_STEPS=[0.15,0.2,0.25,0.3,0.35,0.4,0.45,0.5,0.55,0.6,0.65,0.7] as const;
function clampVolume(value:number){if(!Number.isFinite(value))return .2;return Math.max(.05,Math.min(1,value))}
function clock(seconds:number){const safe=Math.max(0,Math.floor(seconds));return`${String(Math.floor(safe/60)).padStart(2,'0')}:${String(safe%60).padStart(2,'0')}`}

export function QuestTimedAudioPhase({directive,volume,onVolumeChange,onCompletePhase,onSafetyStop,onInvalidated}:QuestTimedAudioPhaseProps){
 const registry=useMemo(()=>createMobileQuestAudioRuntimeRegistry(),[]);const controller=useMemo(()=>createQuestAudioController(directive,registry),[directive,registry]);const raw=directive.phase.audio?.required_effective_seconds;const requiredSeconds=typeof raw==='number'&&Number.isInteger(raw)&&raw>0?raw:0;if(!requiredSeconds)throw new Error(`timed_audio_required_seconds_invalid:${directive.phase.id}`);const targetMs=requiredSeconds*1000;const headphonesNeeded=directive.phase.audio?.headphones_required_for_binaural_difference===true||directive.phase.audio?.headphones_match_active===true;
 const[snapshot,setSnapshot]=useState<AudioRuntimeSnapshot>(()=>controller.snapshot());const[elapsedMs,setElapsedMs]=useState(0);const[ready,setReady]=useState(false);const[headphonesConfirmed,setHeadphonesConfirmed]=useState(false);const[busy,setBusy]=useState(false);const[error,setError]=useState<string|null>(null);const effective=useRef(0),weighted=useRef(0),segmentStart=useRef<number|null>(null),segmentVolume=useRef(clampVolume(volume)),finishing=useRef(false),volumeRef=useRef(clampVolume(volume));volumeRef.current=clampVolume(volume);
 function refresh(){setSnapshot(controller.snapshot())}function reset(){effective.current=0;weighted.current=0;segmentStart.current=null;segmentVolume.current=volumeRef.current;finishing.current=false;setElapsedMs(0);setReady(false)}function commit(now:number){if(segmentStart.current===null)return effective.current;const delta=Math.min(Math.max(0,targetMs-effective.current),Math.max(0,now-segmentStart.current));effective.current+=delta;weighted.current+=delta*segmentVolume.current;segmentStart.current=null;setElapsedMs(effective.current);return effective.current}
 async function finish(){if(finishing.current||effective.current<targetMs)return;finishing.current=true;effective.current=targetMs;setElapsedMs(targetMs);await controller.stop();refresh();setReady(true)}
 async function start(){if(headphonesNeeded&&!headphonesConfirmed){setError('Confirme os fones antes de iniciar.');return}setBusy(true);setError(null);try{if(ready||snapshot.status==='STOPPED')reset();const next=volumeRef.current;await controller.start(next);segmentVolume.current=next;segmentStart.current=Date.now();refresh()}catch(e){setError(e instanceof Error?e.message:'timed_audio_start_failed');refresh()}finally{setBusy(false)}}
 async function pause(){setBusy(true);setError(null);try{commit(Date.now());await controller.pause();refresh()}catch(e){setError(e instanceof Error?e.message:'timed_audio_pause_failed');refresh()}finally{setBusy(false)}}
 async function resume(){setBusy(true);setError(null);try{await controller.resume();segmentVolume.current=volumeRef.current;segmentStart.current=Date.now();refresh()}catch(e){setError(e instanceof Error?e.message:'timed_audio_resume_failed');refresh()}finally{setBusy(false)}}
 async function changeVolume(nextRaw:number){const next=clampVolume(nextRaw);setError(null);try{const playing=snapshot.status==='PLAYING';if(playing)commit(Date.now());await controller.setVolume(next);onVolumeChange(next);volumeRef.current=next;segmentVolume.current=next;if(playing&&effective.current<targetMs)segmentStart.current=Date.now();refresh()}catch(e){setError(e instanceof Error?e.message:'timed_audio_volume_failed');refresh()}}
 async function discard(reason='audio_block_discarded'){try{commit(Date.now());await controller.stop()}catch{}reset();refresh();setError('Bloco corrente descartado. Reinicie os 10 minutos quando estiver pronto.');onInvalidated?.(reason)}async function safety(){try{await controller.stop()}catch{}reset();refresh();await onSafetyStop('audio_safety_stop')}async function complete(){if(!ready||effective.current!==targetMs)return;const avg=Math.round(weighted.current/targetMs*1000);await onCompletePhase(directive.phase.id,{effectiveSeconds:requiredSeconds,averageVolumePermille:Math.max(1,Math.min(1000,avg)),headphonesConfirmed:!headphonesNeeded||headphonesConfirmed})}
 useEffect(()=>{if(snapshot.status!=='PLAYING'||ready)return;const id=setInterval(()=>{const now=Date.now(),total=commit(now);if(total>=targetMs){void finish();return}segmentVolume.current=volumeRef.current;segmentStart.current=now},250);return()=>clearInterval(id)},[snapshot.status,ready,targetMs]);
 useEffect(()=>{const sub=AppState.addEventListener('change',state=>{if(state==='active'||ready)return;if(segmentStart.current!==null||effective.current>0)void discard('audio_background_invalidation')});return()=>sub.remove()},[ready]);useEffect(()=>()=>{void controller.stop()},[controller]);
 const remaining=Math.max(0,Math.ceil((targetMs-elapsedMs)/1000)),playing=snapshot.status==='PLAYING',paused=snapshot.status==='PAUSED',started=snapshot.started&&snapshot.status!=='STOPPED';
 return <View style={s.panel}><Text style={s.eyebrow}>ÁUDIO CRONOMETRADO · TEMPO EFETIVO</Text><Text style={s.profile}>{controller.profileId}</Text><Text style={s.timer}>{clock(remaining)}</Text><Text style={s.notice}>Só conta enquanto o áudio toca com o app ativo. Pausa não conta; sair do app descarta o bloco corrente. Volume maior não vale mais.</Text>{headphonesNeeded?<Pressable disabled={started||ready} onPress={()=>setHeadphonesConfirmed(v=>!v)} style={[s.check,headphonesConfirmed&&s.active]}><Text style={s.text}>{headphonesConfirmed?'✓ ':''}{directive.phase.audio?.headphones_match_active===true?'Estou usando os mesmos fones da condição ativa':'Estou usando fones de ouvido'}</Text></Pressable>:null}<Text style={s.label}>VOLUME · {Math.round(volumeRef.current*100)}%</Text><View style={s.row}>{VOLUME_STEPS.map(step=><Pressable key={step} disabled={ready} onPress={()=>void changeVolume(step)} style={[s.chip,Math.abs(volume-step)<.001&&s.active]}><Text style={s.text}>{Math.round(step*100)}%</Text></Pressable>)}</View><View style={s.row}>{!started&&!ready?<Pressable disabled={busy||Boolean(headphonesNeeded&&!headphonesConfirmed)} onPress={()=>void start()} style={[s.button,(busy||Boolean(headphonesNeeded&&!headphonesConfirmed))&&s.disabled]}><Text style={s.buttonText}>INICIAR BLOCO</Text></Pressable>:null}{playing?<Pressable disabled={busy} onPress={()=>void pause()} style={s.button}><Text style={s.buttonText}>PAUSAR</Text></Pressable>:null}{paused?<Pressable disabled={busy} onPress={()=>void resume()} style={s.button}><Text style={s.buttonText}>RETOMAR</Text></Pressable>:null}{started?<Pressable disabled={busy} onPress={()=>void discard()} style={s.button}><Text style={s.buttonText}>PARAR · DESCARTAR</Text></Pressable>:null}</View><Text style={s.status}>STATUS · {ready?'TEMPO COMPLETO':snapshot.status} · EFETIVO {Math.floor(elapsedMs/1000)} / {requiredSeconds}s</Text>{error?<Text style={s.error}>{error}</Text>:null}<Pressable onPress={()=>void safety()} style={s.button}><Text style={s.buttonText}>ENCERRAR COM SEGURANÇA</Text></Pressable><Pressable disabled={!ready||busy} onPress={()=>void complete()} style={[s.button,!ready&&s.disabled]}><Text style={s.buttonText}>CONCLUIR BLOCO DE ÁUDIO</Text></Pressable></View>
}
const s=StyleSheet.create({panel:{gap:12,padding:18,borderWidth:1,borderColor:'rgba(255,255,255,.18)',borderRadius:18},eyebrow:{fontSize:11,letterSpacing:1.8,opacity:.7},profile:{fontSize:12,opacity:.7},timer:{fontSize:54,fontWeight:'800',fontVariant:['tabular-nums']},notice:{lineHeight:20,padding:12,borderRadius:12,backgroundColor:'rgba(255,255,255,.06)'},label:{fontSize:11,letterSpacing:1.4,opacity:.7},row:{flexDirection:'row',flexWrap:'wrap',gap:8},chip:{paddingVertical:8,paddingHorizontal:12,borderWidth:1,borderColor:'rgba(255,255,255,.28)',borderRadius:999},check:{padding:12,borderWidth:1,borderColor:'rgba(255,255,255,.28)',borderRadius:12},active:{backgroundColor:'rgba(255,255,255,.12)'},text:{color:'white'},button:{minHeight:44,justifyContent:'center',alignItems:'center',paddingHorizontal:16,borderWidth:1,borderColor:'rgba(255,255,255,.4)',borderRadius:999},buttonText:{color:'white',fontWeight:'700',fontSize:12,letterSpacing:.8},status:{fontSize:11,letterSpacing:1.2,opacity:.7},error:{color:'#ffb4b4'},disabled:{opacity:.4}})
