'use client';
import {useEffect,useMemo,useRef,useState,type CSSProperties} from 'react';
import {ExperienceDirector,QuestRuntime,createQuestCatalog,type ExperienceDirective,type PlayerContext,type SessionSnapshot} from '@hnk/quest-engine';
import {createBundledQuestLibrary,type RuntimeQuestBundle} from '@hnk/quest-library';
import {assertSitaelProgress,loadDay012PracticeSessionV1,sealDay012V1,startDay012PracticeSessionV1,type Day012DiscomfortResponse} from '@hnk/supabase-client';
import {createWebQuestSnapshotStore} from '../_runtime/quest-snapshot-store';
import {createWebVaultTextPort} from '../_runtime/WebVaultTextPort';
import {useWebHnkRuntime} from '../_runtime/WebHnkRuntime';

type Session=NonNullable<Awaited<ReturnType<typeof loadDay012PracticeSessionV1>>>;
type Seal=Extract<Awaited<ReturnType<typeof sealDay012V1>>,{ok:true}>['response'];
type BlockKey='jachin_trataka'|'boaz_trataka'|'middle_trataka';
interface Draft{
 stableSurface:boolean;flammablesClear:boolean;childrenAnimalsClear:boolean;supervised:boolean;alertNotSleepy:boolean;naturalBlinking:boolean;
 jachinDuration:number;jachinDistractions:number;jachinReturned:boolean;jachinRef:string|null;
 boazDuration:number;boazDistractions:number;competitionAvoided:boolean;discomfort:Day012DiscomfortResponse;noForcedEyeStrain:boolean;boazRef:string|null;
 middleDuration:number;thoughtReturnNoRestart:boolean;simultaneousAwareness:boolean;prayer:boolean;attentionScore:number;flameExtinguished:boolean;middleRef:string|null;
 soulRef:string|null;safetyStopped:boolean;
}
const emptyDraft:Draft={stableSurface:false,flammablesClear:false,childrenAnimalsClear:false,supervised:false,alertNotSleepy:false,naturalBlinking:false,jachinDuration:0,jachinDistractions:0,jachinReturned:false,jachinRef:null,boazDuration:0,boazDistractions:0,competitionAvoided:false,discomfort:'NONE',noForcedEyeStrain:false,boazRef:null,middleDuration:0,thoughtReturnNoRestart:false,simultaneousAwareness:false,prayer:false,attentionScore:5,flameExtinguished:false,middleRef:null,soulRef:null,safetyStopped:false};
function canon(bundle:RuntimeQuestBundle,d:ExperienceDirective){return(d.phase.source.block_ids??[]).map(id=>{const b=bundle.canon.blocks.find(x=>x.id===id);if(!b)throw new Error(`canonical_block_missing:${id}`);return b.text})}
function clientId(userId:string){return`hnk-web-d012-v1-${userId}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`}
function keys(userId:string){return{snapshot:`hnk:quest:d012:${userId}:snapshot:v1`,session:`hnk:quest:d012:${userId}:practice-session:v1`,sessionCache:`hnk:quest:d012:${userId}:practice-session-cache:v1`,draft:`hnk:quest:d012:${userId}:draft:v1`}}
function parseLocal<T>(key:string):T|null{try{const raw=window.localStorage.getItem(key);return raw?JSON.parse(raw) as T:null}catch{return null}}
function time(total:number){const s=Math.max(0,Math.min(600,total));return`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}

export function Day012GoldenV1Web(){
 const auth=useWebHnkRuntime();const live=Boolean(auth.configured&&auth.phase==='signed-in'&&auth.client&&auth.userId);const runtimeRef=useRef<QuestRuntime|null>(null);
 const[bundle,setBundle]=useState<RuntimeQuestBundle|null>(null);const[snapshot,setSnapshot]=useState<SessionSnapshot|null>(null);const[session,setSession]=useState<Session|null>(null);const[draft,setDraft]=useState<Draft>(emptyDraft);const[draftLoaded,setDraftLoaded]=useState(false);
 const[activeBlock,setActiveBlock]=useState<BlockKey|null>(null);const[activeStartedAt,setActiveStartedAt]=useState<number|null>(null);const[now,setNow]=useState(Date.now());
 const[jachinNote,setJachinNote]=useState('');const[boazNote,setBoazNote]=useState('');const[middleNote,setMiddleNote]=useState('');const[soulNote,setSoulNote]=useState('');const[voluntary,setVoluntary]=useState(false);const[sealed,setSealed]=useState<Seal|null>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState<string|null>(null);
 const context=useMemo<PlayerContext>(()=>({mediationMode:'HNK_CANONICAL',accessibility:{reducedMotion:typeof window!=='undefined'&&window.matchMedia?.('(prefers-reduced-motion: reduce)').matches===true,audioEnabled:false,microphoneAvailable:false},offline:!live}),[live]);
 const vault=useMemo(()=>auth.userId?createWebVaultTextPort(auth.client??null):null,[auth.client,auth.userId]);

 useEffect(()=>{if(!auth.userId)return;let active=true;const library=createBundledQuestLibrary();const catalog=createQuestCatalog(library);const store=createWebQuestSnapshotStore();const k=keys(auth.userId);void Promise.all([catalog.requireDay(12),library.loadBundle(12),store.load(k.snapshot)]).then(([definition,b,saved])=>{if(!active||!b)return;const r=new QuestRuntime(definition);runtimeRef.current=r;setBundle(b);setSnapshot(saved?r.restore(saved):r.start());const cached=parseLocal<Session>(k.sessionCache);if(cached)setSession(cached);setDraft(parseLocal<Draft>(k.draft)??emptyDraft);setDraftLoaded(true)}).catch(e=>active&&setError(e instanceof Error?e.message:'day012_bundle_load_failed'));return()=>{active=false}},[auth.userId]);
 useEffect(()=>{if(!auth.userId||!snapshot)return;const store=createWebQuestSnapshotStore();const k=keys(auth.userId);if(snapshot.runState==='COMPLETE'){void store.remove(k.snapshot);window.localStorage.removeItem(k.draft);window.localStorage.removeItem(k.sessionCache);window.localStorage.removeItem(k.session)}else void store.save(k.snapshot,snapshot)},[auth.userId,snapshot]);
 useEffect(()=>{if(!auth.userId||!draftLoaded||snapshot?.runState==='COMPLETE')return;window.localStorage.setItem(keys(auth.userId).draft,JSON.stringify(draft))},[auth.userId,draft,draftLoaded,snapshot?.runState]);
 useEffect(()=>{if(!live||!auth.client||!auth.userId)return;const k=keys(auth.userId);const id=window.localStorage.getItem(k.session);if(!id)return;void loadDay012PracticeSessionV1(auth.client,id).then(s=>{if(s){setSession(s);window.localStorage.setItem(k.sessionCache,JSON.stringify(s))}else{window.localStorage.removeItem(k.session);window.localStorage.removeItem(k.sessionCache)}}).catch(()=>undefined)},[auth.client,auth.userId,live]);
 useEffect(()=>{const id=window.setInterval(()=>setNow(Date.now()),1000);return()=>window.clearInterval(id)},[]);
 useEffect(()=>{const onVisibility=()=>{if(document.visibilityState!=='visible'&&activeStartedAt){setActiveStartedAt(null);setActiveBlock(null);setError('bloco_interrompido_ao_sair_da_tela__apague_a_chama_e_reinicie') }};document.addEventListener('visibilitychange',onVisibility);return()=>document.removeEventListener('visibilitychange',onVisibility)},[activeStartedAt]);

 const director=useMemo(()=>bundle?new ExperienceDirector(bundle.quest):null,[bundle]);const directive=useMemo(()=>director&&snapshot?.currentPhaseId?director.resolvePhase(snapshot.currentPhaseId,context,snapshot):null,[director,context,snapshot]);
 const elapsed=activeStartedAt?Math.min(600,Math.max(0,Math.floor((now-activeStartedAt)/1000))):0;
 async function ensureSession(){if(session)return session;if(!live||!auth.client||!auth.userId)throw new Error('online_session_required_before_day012_practice');const s=await startDay012PracticeSessionV1(auth.client,{clientSessionId:clientId(auth.userId),appVersion:'0.1.0-web-day012-golden-v1'});setSession(s);const k=keys(auth.userId);window.localStorage.setItem(k.session,s.id);window.localStorage.setItem(k.sessionCache,JSON.stringify(s));return s}
 async function complete(id:string){setError(null);try{if(id==='jachin_reading')await ensureSession();const r=runtimeRef.current;if(r)setSnapshot(r.completePhase(id));window.scrollTo({top:0,behavior:'smooth'})}catch(e){setError(e instanceof Error?e.message:'phase_completion_failed')}}
 function startBlock(id:BlockKey){if(activeStartedAt)return;setError(null);setActiveBlock(id);setActiveStartedAt(Date.now());setNow(Date.now())}
 function endBlock(id:BlockKey){if(activeBlock!==id||!activeStartedAt)throw new Error('practice_timer_not_started');const seconds=Math.min(600,Math.floor((Date.now()-activeStartedAt)/1000));if(seconds<1)throw new Error('practice_duration_too_short');setDraft(d=>id==='jachin_trataka'?{...d,jachinDuration:seconds}:id==='boaz_trataka'?{...d,boazDuration:seconds}:{...d,middleDuration:seconds});setActiveStartedAt(null);setActiveBlock(null)}
 function safetyStop(){setActiveStartedAt(null);setActiveBlock(null);setDraft(d=>({...d,safetyStopped:true}));setError('safety_stop__apague_a_chama_e_afaste_o_olhar');if(runtimeRef.current)setSnapshot(runtimeRef.current.safetyStop())}
 function resume(){setError(null);if(runtimeRef.current)setSnapshot(runtimeRef.current.resume())}
 async function saveJachin(){if(!vault||!auth.userId||draft.jachinDuration<1)throw new Error('jachin_practice_required');if(!draft.jachinReturned||!jachinNote.trim())throw new Error('jachin_return_note_required');const e=await vault.saveText({userId:auth.userId,day:12,kind:'journal',plaintext:JSON.stringify({schema:'hnk-day012-jachin-v1',returnAfterDistraction:jachinNote.trim()})});setDraft(d=>({...d,jachinRef:e.entryId}));setJachinNote('');await complete('jachin_trataka')}
 async function saveBoaz(){if(!vault||!auth.userId||draft.boazDuration<1)throw new Error('boaz_practice_required');if(!draft.competitionAvoided||!draft.noForcedEyeStrain||!boazNote.trim())throw new Error('boaz_safety_note_required');const e=await vault.saveText({userId:auth.userId,day:12,kind:'journal',plaintext:JSON.stringify({schema:'hnk-day012-boaz-v1',distractionAndDiscomfort:boazNote.trim()})});setDraft(d=>({...d,boazRef:e.entryId}));setBoazNote('');await complete('boaz_trataka')}
 async function saveMiddle(){if(!vault||!auth.userId||draft.middleDuration<1)throw new Error('middle_practice_required');if(!draft.thoughtReturnNoRestart||!draft.simultaneousAwareness||!draft.prayer||!draft.flameExtinguished||!middleNote.trim())throw new Error('middle_safety_and_integration_required');const e=await vault.saveText({userId:auth.userId,day:12,kind:'journal',plaintext:JSON.stringify({schema:'hnk-day012-middle-v1',finalNote:middleNote.trim(),attentionStabilityScore:draft.attentionScore})});setDraft(d=>({...d,middleRef:e.entryId}));setMiddleNote('');await complete('middle_trataka')}
 async function saveSoul(){if(!vault||!auth.userId||!soulNote.trim())throw new Error('soul_mirror_note_required');const e=await vault.saveText({userId:auth.userId,day:12,kind:'journal',plaintext:JSON.stringify({schema:'hnk-day012-soul-v1',attentionDistractionReturn:soulNote.trim()})});setDraft(d=>({...d,soulRef:e.entryId}));setSoulNote('');await complete('soul_mirror')}
 async function seal(){if(!runtimeRef.current||!live||!auth.client||!auth.userId||!session||!vault||!draft.jachinRef||!draft.boazRef||!draft.middleRef||!draft.soulRef||!draft.flameExtinguished||!voluntary)return;setBusy(true);setError(null);try{await vault.flushPending(auth.userId);const jr=await vault.resolveEntryId(auth.userId,draft.jachinRef);const br=await vault.resolveEntryId(auth.userId,draft.boazRef);const mr=await vault.resolveEntryId(auth.userId,draft.middleRef);const sr=await vault.resolveEntryId(auth.userId,draft.soulRef);if(!jr||!br||!mr||!sr)throw new Error('vault_sync_required_before_completion');const total=Math.max(0,Math.floor((Date.now()-new Date(session.started_at).getTime())/1000));const result=await sealDay012V1(auth.client,{evidence:{sessionId:session.id,mode:'first_completion',stableSurfaceConfirmed:draft.stableSurface,flammablesClearConfirmed:draft.flammablesClear,childrenAnimalsClearConfirmed:draft.childrenAnimalsClear,continuousSupervisionConfirmed:draft.supervised,alertNotSleepyConfirmed:draft.alertNotSleepy,naturalBlinkingConfirmed:draft.naturalBlinking,jachinDurationSeconds:draft.jachinDuration,jachinDistractionCount:draft.jachinDistractions,jachinReturnedWithoutJudgmentConfirmed:draft.jachinReturned,jachinReturnVaultEntryRef:jr,boazDurationSeconds:draft.boazDuration,boazDistractionCount:draft.boazDistractions,boazCompetitionAvoidanceConfirmed:draft.competitionAvoided,boazDiscomfortResponse:draft.discomfort,boazNoForcedEyeStrainConfirmed:draft.noForcedEyeStrain,boazDistractionDiscomfortVaultEntryRef:br,middleDurationSeconds:draft.middleDuration,middleThoughtReturnWithoutRestartConfirmed:draft.thoughtReturnNoRestart,middleSimultaneousAwarenessConfirmed:draft.simultaneousAwareness,psalm912PrayerConfirmed:draft.prayer,attentionStabilityScore:draft.attentionScore,middleFinalVaultEntryRef:mr,flameExtinguishedConfirmed:draft.flameExtinguished,soulMirrorCompleted:true,attentionDistractionReturnVaultEntryRef:sr,safetyStopOccurred:draft.safetyStopped},totalDurationSeconds:total});if(!result.ok)throw new Error(result.code);assertSitaelProgress(result.response.crown,2);setSealed(result.response);setSnapshot(runtimeRef.current.confirmServerCompletion())}catch(e){setError(e instanceof Error?e.message:'day012_completion_failed')}finally{setBusy(false)}}
 const safetyReady=draft.stableSurface&&draft.flammablesClear&&draft.childrenAnimalsClear&&draft.supervised&&draft.alertNotSleepy&&draft.naturalBlinking;
 const shell:CSSProperties={maxWidth:860,margin:'0 auto',padding:'28px 20px 80px',color:'#eee7d7',background:'#090910',minHeight:'100vh',fontFamily:'system-ui'};const panel:CSSProperties={border:'1px solid #80622f',borderRadius:18,padding:22,display:'grid',gap:14,background:'#111018'};const danger:CSSProperties={border:'1px solid #8e4d4d',background:'transparent',color:'#ffb4ab',padding:10,borderRadius:10};
 if(!auth.userId)return <main style={shell}>ENTRE NO ÁTRIO PARA INICIAR O DIA 012.</main>;if(!bundle||!snapshot||!director)return <main style={shell}>CARREGANDO DAY 012…{error?<p>{error}</p>:null}</main>;if(snapshot.runState==='SAFETY_STOP')return <main style={shell}><h1>Prática interrompida com segurança.</h1><p>Apague a vela, afaste o olhar e cuide do conforto ocular. Ao retomar, o bloco interrompido começa novamente.</p><button onClick={resume}>RETOMAR SOMENTE SEM CHAMA ACESA</button></main>;if(snapshot.runState==='COMPLETE')return <main style={shell}><small>DIA 012 · SITAEL 2/5</small><h1>TRATAKA PRIMAL CONCLUÍDO</h1><p>{sealed?.first_completion?`+${sealed.xp_awarded} XP canônicos.`:'Revisita sem novo XP.'}</p><p>Sitael 2/5 confirmado pelo servidor · fragmento III ainda apagado · Coroa {sealed?.crown.fragments_lit??2}/7.</p><p>Matriz: +1 PER solicitado ao servidor, sujeito ao cap 20; DIS é atributo secundário, sem ponto automático.</p></main>;if(!directive)return <main style={shell}>FASE INDISPONÍVEL.</main>;
 const p=directive.phase;const texts=directive.requiresCanonicalContent?canon(bundle,directive):[];const current=p.id as BlockKey;
 return <main style={shell}><header><small>DIA 012 · KETHER · SITAEL 2/5</small><h1>TRATAKA PRIMAL</h1><p>{live?'VAULT E2EE · ONLINE':'VAULT E2EE · FILA CIFRADA OFFLINE'}</p></header>{error?<p style={{color:'#ffb4ab'}}>{error}</p>:null}<section style={panel}><small>{p.type} · {p.id}</small>
 {p.type==='NARRATIVE'?<><h2>Foco sem violência.</h2><p>Pensamentos não invalidam a prática. Piscar é permitido. Dez minutos são teto, não obrigação.</p></>:null}
 {p.type==='READ'?texts.map((t,i)=><p key={i} style={{lineHeight:1.75}}>{t}</p>):null}
 {p.id==='fire_safety_gate'?<><h2>Gate de segurança da chama</h2><Toggle label="Vela em superfície firme" value={draft.stableSurface} on={()=>setDraft(d=>({...d,stableSurface:!d.stableSurface}))}/><Toggle label="Cortinas, papéis e inflamáveis afastados" value={draft.flammablesClear} on={()=>setDraft(d=>({...d,flammablesClear:!d.flammablesClear}))}/><Toggle label="Fora do alcance de crianças e animais" value={draft.childrenAnimalsClear} on={()=>setDraft(d=>({...d,childrenAnimalsClear:!d.childrenAnimalsClear}))}/><Toggle label="Vou supervisionar a chama continuamente" value={draft.supervised} on={()=>setDraft(d=>({...d,supervised:!d.supervised}))}/><Toggle label="Estou desperto, sem sono intenso" value={draft.alertNotSleepy} on={()=>setDraft(d=>({...d,alertNotSleepy:!d.alertNotSleepy}))}/><Toggle label="Vou piscar naturalmente quando precisar" value={draft.naturalBlinking} on={()=>setDraft(d=>({...d,naturalBlinking:!d.naturalBlinking}))}/><button disabled={!safetyReady} onClick={()=>void complete(p.id)}>SEGURANÇA CONFIRMADA · CONTINUAR</button></>:null}
 {['jachin_trataka','boaz_trataka','middle_trataka'].includes(p.id)?<><div style={{fontSize:36,fontVariantNumeric:'tabular-nums'}}>{time(activeBlock===current?elapsed:current==='jachin_trataka'?draft.jachinDuration:current==='boaz_trataka'?draft.boazDuration:draft.middleDuration)}</div>{activeBlock===current?<><p>Chama supervisionada · permaneça nesta tela. Máximo 10:00.</p><button onClick={()=>{try{endBlock(current)}catch(e){setError(e instanceof Error?e.message:'timer_end_failed')}}}>ENCERRAR COM SEGURANÇA · REGISTRAR TEMPO</button></>:<button disabled={Boolean(activeBlock)} onClick={()=>startBlock(current)}>INICIAR BLOCO · ATÉ 10 MIN</button>}<button style={danger} onClick={safetyStop}>INTERROMPER · APAGAR CHAMA</button></>:null}
 {p.id==='jachin_trataka'?<><Counter label="DISTRAÇÕES PERCEBIDAS" value={draft.jachinDistractions} set={v=>setDraft(d=>({...d,jachinDistractions:v}))}/><Toggle label="Retornei à chama sem irritação ou julgamento" value={draft.jachinReturned} on={()=>setDraft(d=>({...d,jachinReturned:!d.jachinReturned}))}/><textarea value={jachinNote} onChange={e=>setJachinNote(e.target.value)} placeholder="Como foi retornar à chama? (será cifrado)"/><button disabled={draft.jachinDuration<1||!draft.jachinReturned} onClick={()=>void saveJachin().catch(e=>setError(e instanceof Error?e.message:'vault_save_failed'))}>{draft.jachinRef?'REGISTRO CIFRADO ✓':'CIFRAR · CONTINUAR'}</button></>:null}
 {p.id==='boaz_trataka'?<><Counter label="DISTRAÇÕES PERCEBIDAS" value={draft.boazDistractions} set={v=>setDraft(d=>({...d,boazDistractions:v}))}/><Toggle label="Não competi com o temporizador" value={draft.competitionAvoided} on={()=>setDraft(d=>({...d,competitionAvoided:!d.competitionAvoided}))}/><Toggle label="Não forcei os olhos nem evitei piscar" value={draft.noForcedEyeStrain} on={()=>setDraft(d=>({...d,noForcedEyeStrain:!d.noForcedEyeStrain}))}/><label>Resposta a desconforto <select value={draft.discomfort} onChange={e=>setDraft(d=>({...d,discomfort:e.target.value as Day012DiscomfortResponse}))}><option value="NONE">Nenhum desconforto relevante</option><option value="ADJUSTED">Ajustei/reduzi</option><option value="STOPPED">Encerrei</option></select></label><textarea value={boazNote} onChange={e=>setBoazNote(e.target.value)} placeholder="Distrações e ajustes de conforto (será cifrado)"/><button disabled={draft.boazDuration<1||!draft.competitionAvoided||!draft.noForcedEyeStrain} onClick={()=>void saveBoaz().catch(e=>setError(e instanceof Error?e.message:'vault_save_failed'))}>{draft.boazRef?'REGISTRO CIFRADO ✓':'CIFRAR · CONTINUAR'}</button></>:null}
 {p.id==='middle_trataka'?<><Toggle label="Retornei aos pensamentos sem reiniciar toda a prática" value={draft.thoughtReturnNoRestart} on={()=>setDraft(d=>({...d,thoughtReturnNoRestart:!d.thoughtReturnNoRestart}))}/><Toggle label="Percebi chama, respiração e corpo sem rigidez" value={draft.simultaneousAwareness} on={()=>setDraft(d=>({...d,simultaneousAwareness:!d.simultaneousAwareness}))}/><Toggle label="Concluí a oração devocional com Salmo 91:2" value={draft.prayer} on={()=>setDraft(d=>({...d,prayer:!d.prayer}))}/><Score value={draft.attentionScore} set={v=>setDraft(d=>({...d,attentionScore:v}))}/><textarea value={middleNote} onChange={e=>setMiddleNote(e.target.value)} placeholder="Distração, retorno e segurança (será cifrado)"/><Toggle label="A vela está APAGADA" value={draft.flameExtinguished} on={()=>setDraft(d=>({...d,flameExtinguished:!d.flameExtinguished}))}/><button disabled={draft.middleDuration<1||!draft.thoughtReturnNoRestart||!draft.simultaneousAwareness||!draft.prayer||!draft.flameExtinguished} onClick={()=>void saveMiddle().catch(e=>setError(e instanceof Error?e.message:'vault_save_failed'))}>{draft.middleRef?'REGISTRO CIFRADO ✓':'CIFRAR · CONTINUAR'}</button></>:null}
 {p.id==='soul_mirror'?<><textarea value={soulNote} onChange={e=>setSoulNote(e.target.value)} placeholder="Como atenção, distração e retorno mudaram quando você abandonou a exigência de controlar pensamentos? (cifrado)"/><button onClick={()=>void saveSoul().catch(e=>setError(e instanceof Error?e.message:'vault_save_failed'))}>{draft.soulRef?'ESPELHO CIFRADO ✓':'CIFRAR ESPELHO · CONTINUAR'}</button></>:null}
 {p.type==='COMPLETION'?<><h2>Selo de Sitael 2/5</h2><p>Somente o servidor concede XP e aplica a matriz de atributos. O cliente não incrementa PER.</p><Toggle label="Confirmo que a vela está apagada e a conclusão é voluntária" value={voluntary} on={()=>setVoluntary(v=>!v)}/><button disabled={busy||!voluntary||!draft.flameExtinguished||!draft.soulRef} onClick={()=>void seal()}>{busy?'SINCRONIZANDO E SELANDO…':'SINCRONIZAR · SELAR DAY 012'}</button></>:null}
 {['NARRATIVE','READ','UNLOCK'].includes(p.type)?<button onClick={()=>void complete(p.id)}>CONTINUAR</button>:null}
 </section></main>
}
function Toggle({label,value,on}:{label:string;value:boolean;on:()=>void}){return <label><input type="checkbox" checked={value} onChange={on}/> {label}</label>}
function Counter({label,value,set}:{label:string;value:number;set:(v:number)=>void}){return <div><span>{label} · {value}</span> <button onClick={()=>set(Math.max(0,value-1))}>−</button> <button onClick={()=>set(value+1)}>+</button></div>}
function Score({value,set}:{value:number;set:(v:number)=>void}){return <label>ESTABILIDADE DA ATENÇÃO · {value}/10 <input type="range" min="0" max="10" step="1" value={value} onChange={e=>set(Number(e.target.value))}/></label>}
