export const DAY025_QUEST_ID='HNK-KETHER-D025-V1' as const;
export const DAY025_SOURCE_SHA='88336e31521c64b3b43aae06d6d5e221fc77a490' as const;
export const DAY025_REFERENCE_ID='reiki-usui-dai-ko-myo-v1' as const;
export const DAY025_MASTER_SHA256='25d7853168b209665a66c01a83b3ebd4681b620e1ae2a98e65d74fbab6f7b4d0' as const;
export type Day025ArTrackingMode='WEBXR_IMMERSIVE_AR'|'NATIVE_ARCORE_ARKIT';
export type Day025PointId='P1'|'P2'|'P3'|'P4';
export interface Day025PointScores{focus:number;comfort:number;silence:number;presence:number;meditation_readiness:number}
export type Day025PointMap=Record<Day025PointId,Day025PointScores>;
export interface Day025EvidenceV1{
 protocol_version:'HNK-KETHER-D025-V1';source_sha:typeof DAY025_SOURCE_SHA;session_id:string;mode:'first_completion'|'revisit';
 reference:{canonical_reference_id:typeof DAY025_REFERENCE_ID;master_sha256:typeof DAY025_MASTER_SHA256;family:'USUI_KANJI';semantic_master:'大光明'};
 ar_runtime:{tracking_mode:Day025ArTrackingMode;camera_permission_granted:boolean;real_world_tracking_confirmed:boolean;flat_overlay_used:false;camera_frames_server_side:false;camera_frames_persisted:false};
 environment_baseline:{recorded:true;vault_entry_ref:string};
 jachin:{duration_seconds:420;tracked_seconds:420;world_anchor_established_confirmed:true;dai_koo_myo_world_space_confirmed:true;natural_breathing_confirmed:true;four_points_ordered:['P1','P2','P3','P4'];point_scores:Day025PointMap;active_environment_map_vault_entry_ref:string};
 boaz:{duration_seconds:420;camera_active_seconds:420;same_environment_confirmed:true;same_route_confirmed:true;same_point_order_confirmed:true;approximate_time_and_lighting_preserved_confirmed:true;ar_symbol_absent_confirmed:true;formula_absent_confirmed:true;expectation_acknowledged_confirmed:true;four_points_ordered:['P1','P2','P3','P4'];point_scores:Day025PointMap;competing_environmental_variable_identified_confirmed:true;single_episode_not_definitive_confirmed:true;control_environment_map_vault_entry_ref:string};
 middle:{duration_seconds:420;tracked_seconds:420;silent_observation_seconds:60;world_anchor_reestablished_confirmed:true;same_four_points_order_confirmed:true;mem_he_shin_once_per_point_confirmed:true;psalm_34_4_orientation_confirmed:true;five_domains_recorded_confirmed:true;environmental_signature_not_objective_energy_proof_confirmed:true;hypothesis_refined_confirmed:true;objective_repeatability_criterion_defined_confirmed:true;integration_environment_map_vault_entry_ref:string};
 soul_mirror:{completed:true;physical_configuration_operator_expectation_interaction_constant_parameter_vault_entry_ref:string};
 voluntary_completion_confirmed:true;safety_stop_occurred:boolean;
}
export interface Day025EvidenceInput{
 sessionId:string;mode?:'first_completion'|'revisit';trackingMode:Day025ArTrackingMode;cameraPermissionGranted:boolean;realWorldTrackingConfirmed:boolean;flatOverlayUsed?:boolean;cameraFramesServerSide?:boolean;cameraFramesPersisted?:boolean;environmentBaselineVaultEntryRef:string;
 activeDurationSeconds:number;activeTrackedSeconds:number;worldAnchorEstablishedConfirmed:boolean;daiKooMyoWorldSpaceConfirmed:boolean;naturalBreathingConfirmed:boolean;activePointScores:Day025PointMap;activeEnvironmentMapVaultEntryRef:string;
 controlDurationSeconds:number;controlCameraActiveSeconds:number;sameEnvironmentConfirmed:boolean;sameRouteConfirmed:boolean;samePointOrderConfirmed:boolean;approximateTimeAndLightingPreservedConfirmed:boolean;arSymbolAbsentConfirmed:boolean;formulaAbsentConfirmed:boolean;expectationAcknowledgedConfirmed:boolean;controlPointScores:Day025PointMap;competingEnvironmentalVariableIdentifiedConfirmed:boolean;singleEpisodeNotDefinitiveConfirmed:boolean;controlEnvironmentMapVaultEntryRef:string;
 middleDurationSeconds:number;middleTrackedSeconds:number;silentObservationSeconds:number;worldAnchorReestablishedConfirmed:boolean;sameFourPointsOrderConfirmed:boolean;memHeShinOncePerPointConfirmed:boolean;psalm344OrientationConfirmed:boolean;fiveDomainsRecordedConfirmed:boolean;environmentalSignatureNotObjectiveEnergyProofConfirmed:boolean;hypothesisRefinedConfirmed:boolean;objectiveRepeatabilityCriterionDefinedConfirmed:boolean;integrationEnvironmentMapVaultEntryRef:string;
 soulMirrorCompleted:boolean;physicalConfigurationOperatorExpectationInteractionConstantParameterVaultEntryRef:string;safetyStopOccurred?:boolean;
}
const POINTS:Day025PointId[]=['P1','P2','P3','P4'];
function bool(v:boolean,name:string){if(v!==true)throw new Error(name)}function zero(v:boolean|undefined,name:string){if(v===true)throw new Error(name)}function ref(v:string,name:string){if(!v.trim()||v.length>256||/\s/.test(v))throw new Error(name);return v}function seconds(v:number,expected:number,name:string){if(!Number.isInteger(v)||v!==expected)throw new Error(name)}function score(v:number,name:string){if(!Number.isInteger(v)||v<0||v>10)throw new Error(name)}function map(v:Day025PointMap,name:string){for(const p of POINTS){const s=v[p];if(!s)throw new Error(name);for(const [k,n] of Object.entries(s))score(n,`${name}_${p}_${k}`)}return v}
export function buildDay025EvidenceV1(i:Day025EvidenceInput):Day025EvidenceV1{
 if(!i.sessionId.trim())throw new Error('day025_session_required');if(!['WEBXR_IMMERSIVE_AR','NATIVE_ARCORE_ARKIT'].includes(i.trackingMode))throw new Error('day025_tracking_mode_invalid');bool(i.cameraPermissionGranted,'day025_camera_permission_required');bool(i.realWorldTrackingConfirmed,'day025_real_world_tracking_required');zero(i.flatOverlayUsed,'day025_flat_overlay_forbidden');zero(i.cameraFramesServerSide,'day025_camera_frames_server_forbidden');zero(i.cameraFramesPersisted,'day025_camera_frames_persistence_forbidden');
 seconds(i.activeDurationSeconds,420,'day025_active_requires_420_seconds');seconds(i.activeTrackedSeconds,420,'day025_active_tracking_requires_420_seconds');bool(i.worldAnchorEstablishedConfirmed,'day025_world_anchor_required');bool(i.daiKooMyoWorldSpaceConfirmed,'day025_world_space_symbol_required');bool(i.naturalBreathingConfirmed,'day025_natural_breathing_required');
 seconds(i.controlDurationSeconds,420,'day025_control_requires_420_seconds');seconds(i.controlCameraActiveSeconds,420,'day025_control_camera_requires_420_seconds');for(const [v,n] of [[i.sameEnvironmentConfirmed,'day025_same_environment_required'],[i.sameRouteConfirmed,'day025_same_route_required'],[i.samePointOrderConfirmed,'day025_same_point_order_required'],[i.approximateTimeAndLightingPreservedConfirmed,'day025_environment_comparability_required'],[i.arSymbolAbsentConfirmed,'day025_control_symbol_absent_required'],[i.formulaAbsentConfirmed,'day025_control_formula_absent_required'],[i.expectationAcknowledgedConfirmed,'day025_expectation_acknowledgement_required'],[i.competingEnvironmentalVariableIdentifiedConfirmed,'day025_competing_variable_required'],[i.singleEpisodeNotDefinitiveConfirmed,'day025_single_episode_boundary_required']] as const)bool(v,n);
 seconds(i.middleDurationSeconds,420,'day025_middle_requires_420_seconds');seconds(i.middleTrackedSeconds,420,'day025_middle_tracking_requires_420_seconds');seconds(i.silentObservationSeconds,60,'day025_middle_silence_requires_60_seconds');for(const [v,n] of [[i.worldAnchorReestablishedConfirmed,'day025_middle_anchor_required'],[i.sameFourPointsOrderConfirmed,'day025_middle_point_order_required'],[i.memHeShinOncePerPointConfirmed,'day025_middle_formula_required'],[i.psalm344OrientationConfirmed,'day025_psalm_orientation_required'],[i.fiveDomainsRecordedConfirmed,'day025_five_domains_required'],[i.environmentalSignatureNotObjectiveEnergyProofConfirmed,'day025_epistemic_boundary_required'],[i.hypothesisRefinedConfirmed,'day025_hypothesis_refinement_required'],[i.objectiveRepeatabilityCriterionDefinedConfirmed,'day025_repeatability_criterion_required'],[i.soulMirrorCompleted,'day025_soul_mirror_required']] as const)bool(v,n);
 return{protocol_version:'HNK-KETHER-D025-V1',source_sha:DAY025_SOURCE_SHA,session_id:i.sessionId,mode:i.mode??'first_completion',reference:{canonical_reference_id:DAY025_REFERENCE_ID,master_sha256:DAY025_MASTER_SHA256,family:'USUI_KANJI',semantic_master:'大光明'},ar_runtime:{tracking_mode:i.trackingMode,camera_permission_granted:true,real_world_tracking_confirmed:true,flat_overlay_used:false,camera_frames_server_side:false,camera_frames_persisted:false},environment_baseline:{recorded:true,vault_entry_ref:ref(i.environmentBaselineVaultEntryRef,'day025_baseline_vault_ref_required')},jachin:{duration_seconds:420,tracked_seconds:420,world_anchor_established_confirmed:true,dai_koo_myo_world_space_confirmed:true,natural_breathing_confirmed:true,four_points_ordered:['P1','P2','P3','P4'],point_scores:map(i.activePointScores,'day025_active_scores_invalid'),active_environment_map_vault_entry_ref:ref(i.activeEnvironmentMapVaultEntryRef,'day025_active_vault_ref_required')},boaz:{duration_seconds:420,camera_active_seconds:420,same_environment_confirmed:true,same_route_confirmed:true,same_point_order_confirmed:true,approximate_time_and_lighting_preserved_confirmed:true,ar_symbol_absent_confirmed:true,formula_absent_confirmed:true,expectation_acknowledged_confirmed:true,four_points_ordered:['P1','P2','P3','P4'],point_scores:map(i.controlPointScores,'day025_control_scores_invalid'),competing_environmental_variable_identified_confirmed:true,single_episode_not_definitive_confirmed:true,control_environment_map_vault_entry_ref:ref(i.controlEnvironmentMapVaultEntryRef,'day025_control_vault_ref_required')},middle:{duration_seconds:420,tracked_seconds:420,silent_observation_seconds:60,world_anchor_reestablished_confirmed:true,same_four_points_order_confirmed:true,mem_he_shin_once_per_point_confirmed:true,psalm_34_4_orientation_confirmed:true,five_domains_recorded_confirmed:true,environmental_signature_not_objective_energy_proof_confirmed:true,hypothesis_refined_confirmed:true,objective_repeatability_criterion_defined_confirmed:true,integration_environment_map_vault_entry_ref:ref(i.integrationEnvironmentMapVaultEntryRef,'day025_integration_vault_ref_required')},soul_mirror:{completed:true,physical_configuration_operator_expectation_interaction_constant_parameter_vault_entry_ref:ref(i.physicalConfigurationOperatorExpectationInteractionConstantParameterVaultEntryRef,'day025_soul_vault_ref_required')},voluntary_completion_confirmed:true,safety_stop_occurred:i.safetyStopOccurred===true};
}
export function day025TotalDurationSeconds(e:Day025EvidenceV1){return e.jachin.duration_seconds+e.boaz.duration_seconds+e.middle.duration_seconds+e.middle.silent_observation_seconds}
export function buildDay025SafeMetrics(input:{totalDurationSeconds:number}){if(!Number.isInteger(input.totalDurationSeconds)||input.totalDurationSeconds<1)throw new Error('day025_total_duration_invalid');return{protocol_version:'HNK-KETHER-D025-V1',total_duration_seconds:input.totalDurationSeconds,camera_frames_uploaded:false,private_text_uploaded:false}}
