import type {SafeMetricRecord} from './types.js';

export const DAY056_QUEST_ID='HNK-CHOKMAH-D056-V2' as const;
export const DAY056_SOURCE_SHA='9eb847d460768615d2e6fb9173c2557a21c705c7' as const;
export type Day056SafetyReason='NONE'|'DIZZINESS'|'PAIN'|'SHORTNESS_OF_BREATH'|'MALAISE'|'OTHER_DISCOMFORT';
export interface Day056ConditionInput{effectPresent:boolean;mood:number;tension:number;closure:number;comfort:number;expectation:number}
export interface Day056EvidenceV2{
 protocol_version:typeof DAY056_QUEST_ID;source_sha:typeof DAY056_SOURCE_SHA;session_id:string;mode:'first_completion'|'revisit';
 active:{measured_seconds:number;comfortable_inhalation_confirmed:true;symbolic_discharge_imagery_confirmed:true;brief_laughter_on_exhalation_confirmed:true;no_hyperventilation_confirmed:true;no_prolonged_retention_confirmed:true;effect_present:boolean;mood:number;tension:number;closure:number;comfort:number;expectation:number;returned_to_common_focus_confirmed:true;emotional_vault_entry_ref?:string};
 control:{measured_seconds:number;comfortable_exhalation_without_laughter_confirmed:true;similar_context_confirmed:true;same_metrics_confirmed:true;preselected_winner_absent_confirmed:true;no_duration_intensity_or_effort_compensation_confirmed:true;effect_present:boolean;mood:number;tension:number;closure:number;comfort:number;expectation:number;returned_to_common_focus_confirmed:true;emotional_vault_entry_ref?:string};
 comparison:{completed_confirmed:true;interpretation_separated_confirmed:true;null_results_preserved_confirmed:true;contradictory_results_preserved_confirmed:true;alternative_explanations_recorded_confirmed:true;clinical_substitute_not_claimed_confirmed:true;entity_contamination_not_reinforced_confirmed:true;external_mechanism_not_claimed_confirmed:true;spiritual_superiority_not_claimed_confirmed:true;prudence_rule_defined_confirmed:true;vault_entry_ref?:string};
 middle:{psalm_18_46_confirmed:true;lamed_aleph_vav_confirmed:true;brief_central_gesture_without_intensity_seeking_confirmed:true;three_observable_facts_named_confirmed:true;one_subjective_experience_named_confirmed:true;one_open_hypothesis_named_confirmed:true;body_moved_confirmed:true;environment_oriented_confirmed:true;natural_breathing_confirmed:true;thanks_to_god_confirmed:true;subjective_traditional_objective_separated_confirmed:true;functional_return_confirmed:true;vault_entry_ref?:string};
 voluntary_completion_confirmed:true;final_safety_clear_confirmed:true;safety_stop_occurred:boolean;safety_stop_reason:Day056SafetyReason
}
export interface Day056EvidenceInput{
 sessionId:string;mode?:'first_completion'|'revisit';active:Day056ConditionInput;activeMeasuredSeconds?:number;activeComfortableInhalationConfirmed:boolean;activeSymbolicDischargeImageryConfirmed:boolean;activeBriefLaughterOnExhalationConfirmed:boolean;activeNoHyperventilationConfirmed:boolean;activeNoProlongedRetentionConfirmed:boolean;activeReturnedToCommonFocusConfirmed:boolean;activeEmotionalVaultEntryRef?:string|null;
 control:Day056ConditionInput;controlMeasuredSeconds?:number;controlComfortableExhalationWithoutLaughterConfirmed:boolean;controlSimilarContextConfirmed:boolean;controlSameMetricsConfirmed:boolean;preselectedWinnerAbsentConfirmed:boolean;noDurationIntensityOrEffortCompensationConfirmed:boolean;controlReturnedToCommonFocusConfirmed:boolean;controlEmotionalVaultEntryRef?:string|null;
 comparisonCompletedConfirmed:boolean;interpretationSeparatedConfirmed:boolean;nullResultsPreservedConfirmed:boolean;contradictoryResultsPreservedConfirmed:boolean;alternativeExplanationsRecordedConfirmed:boolean;clinicalSubstituteNotClaimedConfirmed:boolean;entityContaminationNotReinforcedConfirmed:boolean;externalMechanismNotClaimedConfirmed:boolean;spiritualSuperiorityNotClaimedConfirmed:boolean;prudenceRuleDefinedConfirmed:boolean;comparisonVaultEntryRef?:string|null;
 psalm1846Confirmed:boolean;lamedAlephVavConfirmed:boolean;briefCentralGestureWithoutIntensitySeekingConfirmed:boolean;threeObservableFactsNamedConfirmed:boolean;oneSubjectiveExperienceNamedConfirmed:boolean;oneOpenHypothesisNamedConfirmed:boolean;bodyMovedConfirmed:boolean;environmentOrientedConfirmed:boolean;middleNaturalBreathingConfirmed:boolean;thanksToGodConfirmed:boolean;subjectiveTraditionalObjectiveSeparatedConfirmed:boolean;functionalReturnConfirmed:boolean;middleVaultEntryRef?:string|null;
 voluntaryCompletionConfirmed:boolean;finalSafetyClearConfirmed:boolean;safetyStopOccurred?:boolean;safetyStopReason?:Day056SafetyReason
}
function yes(v:boolean,n:string){if(v!==true)throw new Error(n)}
function integer(v:number,min:number,max:number,n:string){if(!Number.isInteger(v)||v<min||v>max)throw new Error(n);return v}
function scale(v:number,n:string){return integer(v,0,10,n)}
function optionalRef(v:string|null|undefined,n:string){if(v==null||v.trim()==='')return undefined;const x=v.trim();if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(x))throw new Error(n);return x}
function condition(x:Day056ConditionInput,prefix:string){return{effect_present:Boolean(x.effectPresent),mood:scale(x.mood,`${prefix}_mood_invalid`),tension:scale(x.tension,`${prefix}_tension_invalid`),closure:scale(x.closure,`${prefix}_closure_invalid`),comfort:scale(x.comfort,`${prefix}_comfort_invalid`),expectation:scale(x.expectation,`${prefix}_expectation_invalid`)}}
export function buildDay056EvidenceV2(i:Day056EvidenceInput):Day056EvidenceV2{
 if(!i.sessionId.trim())throw new Error('day056_session_required');
 for(const[v,n]of[[i.activeComfortableInhalationConfirmed,'day056_active_comfortable_inhalation_required'],[i.activeSymbolicDischargeImageryConfirmed,'day056_active_symbolic_imagery_required'],[i.activeBriefLaughterOnExhalationConfirmed,'day056_active_brief_laughter_required'],[i.activeNoHyperventilationConfirmed,'day056_no_hyperventilation_required'],[i.activeNoProlongedRetentionConfirmed,'day056_no_prolonged_retention_required'],[i.activeReturnedToCommonFocusConfirmed,'day056_active_return_required'],[i.controlComfortableExhalationWithoutLaughterConfirmed,'day056_control_exhalation_required'],[i.controlSimilarContextConfirmed,'day056_control_context_required'],[i.controlSameMetricsConfirmed,'day056_control_same_metrics_required'],[i.preselectedWinnerAbsentConfirmed,'day056_no_winner_required'],[i.noDurationIntensityOrEffortCompensationConfirmed,'day056_no_compensation_required'],[i.controlReturnedToCommonFocusConfirmed,'day056_control_return_required'],[i.comparisonCompletedConfirmed,'day056_comparison_required'],[i.interpretationSeparatedConfirmed,'day056_interpretation_separated_required'],[i.nullResultsPreservedConfirmed,'day056_null_results_required'],[i.contradictoryResultsPreservedConfirmed,'day056_contradictory_results_required'],[i.alternativeExplanationsRecordedConfirmed,'day056_alternatives_required'],[i.clinicalSubstituteNotClaimedConfirmed,'day056_clinical_boundary_required'],[i.entityContaminationNotReinforcedConfirmed,'day056_entity_boundary_required'],[i.externalMechanismNotClaimedConfirmed,'day056_external_mechanism_boundary_required'],[i.spiritualSuperiorityNotClaimedConfirmed,'day056_superiority_boundary_required'],[i.prudenceRuleDefinedConfirmed,'day056_prudence_required'],[i.psalm1846Confirmed,'day056_psalm_required'],[i.lamedAlephVavConfirmed,'day056_formula_required'],[i.briefCentralGestureWithoutIntensitySeekingConfirmed,'day056_middle_gesture_required'],[i.threeObservableFactsNamedConfirmed,'day056_three_facts_required'],[i.oneSubjectiveExperienceNamedConfirmed,'day056_subjective_required'],[i.oneOpenHypothesisNamedConfirmed,'day056_hypothesis_required'],[i.bodyMovedConfirmed,'day056_body_move_required'],[i.environmentOrientedConfirmed,'day056_environment_required'],[i.middleNaturalBreathingConfirmed,'day056_middle_breath_required'],[i.thanksToGodConfirmed,'day056_thanks_required'],[i.subjectiveTraditionalObjectiveSeparatedConfirmed,'day056_layers_required'],[i.functionalReturnConfirmed,'day056_functional_return_required'],[i.voluntaryCompletionConfirmed,'day056_voluntary_required'],[i.finalSafetyClearConfirmed,'day056_final_safety_required']]as const)yes(v,n);
 const stopped=i.safetyStopOccurred===true,reason=i.safetyStopReason??'NONE';if(!['NONE','DIZZINESS','PAIN','SHORTNESS_OF_BREATH','MALAISE','OTHER_DISCOMFORT'].includes(reason))throw new Error('day056_safety_reason_invalid');if(stopped&&reason==='NONE')throw new Error('day056_safety_reason_required');if(!stopped&&reason!=='NONE')throw new Error('day056_safety_reason_without_stop');
 const a=condition(i.active,'day056_active'),c=condition(i.control,'day056_control'),av=optionalRef(i.activeEmotionalVaultEntryRef,'day056_active_vault_invalid'),cv=optionalRef(i.controlEmotionalVaultEntryRef,'day056_control_vault_invalid'),cmp=optionalRef(i.comparisonVaultEntryRef,'day056_comparison_vault_invalid'),mv=optionalRef(i.middleVaultEntryRef,'day056_middle_vault_invalid');
 return{protocol_version:DAY056_QUEST_ID,source_sha:DAY056_SOURCE_SHA,session_id:i.sessionId,mode:i.mode??'first_completion',active:{measured_seconds:integer(i.activeMeasuredSeconds??0,0,7200,'day056_active_measured_seconds_invalid'),comfortable_inhalation_confirmed:true,symbolic_discharge_imagery_confirmed:true,brief_laughter_on_exhalation_confirmed:true,no_hyperventilation_confirmed:true,no_prolonged_retention_confirmed:true,...a,returned_to_common_focus_confirmed:true,...(av?{emotional_vault_entry_ref:av}:{})},control:{measured_seconds:integer(i.controlMeasuredSeconds??0,0,7200,'day056_control_measured_seconds_invalid'),comfortable_exhalation_without_laughter_confirmed:true,similar_context_confirmed:true,same_metrics_confirmed:true,preselected_winner_absent_confirmed:true,no_duration_intensity_or_effort_compensation_confirmed:true,...c,returned_to_common_focus_confirmed:true,...(cv?{emotional_vault_entry_ref:cv}:{})},comparison:{completed_confirmed:true,interpretation_separated_confirmed:true,null_results_preserved_confirmed:true,contradictory_results_preserved_confirmed:true,alternative_explanations_recorded_confirmed:true,clinical_substitute_not_claimed_confirmed:true,entity_contamination_not_reinforced_confirmed:true,external_mechanism_not_claimed_confirmed:true,spiritual_superiority_not_claimed_confirmed:true,prudence_rule_defined_confirmed:true,...(cmp?{vault_entry_ref:cmp}:{})},middle:{psalm_18_46_confirmed:true,lamed_aleph_vav_confirmed:true,brief_central_gesture_without_intensity_seeking_confirmed:true,three_observable_facts_named_confirmed:true,one_subjective_experience_named_confirmed:true,one_open_hypothesis_named_confirmed:true,body_moved_confirmed:true,environment_oriented_confirmed:true,natural_breathing_confirmed:true,thanks_to_god_confirmed:true,subjective_traditional_objective_separated_confirmed:true,functional_return_confirmed:true,...(mv?{vault_entry_ref:mv}:{})},voluntary_completion_confirmed:true,final_safety_clear_confirmed:true,safety_stop_occurred:stopped,safety_stop_reason:reason as Day056SafetyReason};
}
export function buildDay056LegacyScalarEvidence(e:Day056EvidenceV2){return{protocol_completed:true,return_confirmed:e.middle.functional_return_confirmed,active_completed:true,control_completed:true,comparison_completed:e.comparison.completed_confirmed,interpretation_separated:e.comparison.interpretation_separated_confirmed,no_hyperventilation:e.active.no_hyperventilation_confirmed,no_prolonged_retention:e.active.no_prolonged_retention_confirmed,clinical_substitute_not_claimed:e.comparison.clinical_substitute_not_claimed_confirmed,entity_contamination_not_reinforced:e.comparison.entity_contamination_not_reinforced_confirmed,null_results_preserved:e.comparison.null_results_preserved_confirmed,safety_clear:e.final_safety_clear_confirmed,active_effect_present:e.active.effect_present,control_effect_present:e.control.effect_present}}
export function buildDay056SafeMetrics(e:Day056EvidenceV2):SafeMetricRecord{return{active_measured_seconds:e.active.measured_seconds,control_measured_seconds:e.control.measured_seconds,active_effect_present:e.active.effect_present?1:0,control_effect_present:e.control.effect_present?1:0,active_mood:e.active.mood,control_mood:e.control.mood,active_tension:e.active.tension,control_tension:e.control.tension,active_closure:e.active.closure,control_closure:e.control.closure,active_comfort:e.active.comfort,control_comfort:e.control.comfort,safety_stop_occurred:e.safety_stop_occurred?1:0}}
