import type {SafeMetricRecord} from './types.js';

export const DAY060_QUEST_ID='HNK-CHOKMAH-D060-V2' as const;
export const DAY060_SOURCE_SHA='e98e8925c8e03555c39b033813999d6a488149a9' as const;
export type Day060Feature='POSTURE'|'APPARENT_BREATHING'|'GAZE_DIRECTION'|'PUPIL_VISIBILITY'|'OTHER_VISIBLE_CHANGE';
export type Day060Distance='LT_2M'|'M2_TO_5M'|'GT_5M'|'UNKNOWN';
export type Day060Lighting='BRIGHT'|'DIM'|'MIXED'|'UNKNOWN';
export type Day060SafetyReason='NONE'|'PRIVACY_CONCERN'|'CONSENT_WITHDRAWN'|'FIXATION_CONCERN'|'DISCOMFORT'|'OTHER';
export interface Day060PublicObservationInput{index:number;feature:Day060Feature;distanceBucket:Day060Distance;lighting:Day060Lighting;interpretationDiscarded:boolean}
export interface Day060EvidenceInput{
  sessionId:string;mode?:'first_completion'|'revisit';publicDurationSeconds:number;partnerDurationSeconds:number;
  publicObservations:[Day060PublicObservationInput,Day060PublicObservationInput,Day060PublicObservationInput,Day060PublicObservationInput,Day060PublicObservationInput];
  publicContextSafeConfirmed:boolean;cameraNotUsedConfirmed:boolean;zoomNotUsedConfirmed:boolean;recognitionNotUsedConfirmed:boolean;identityNotStoredConfirmed:boolean;noProlongedFixationConfirmed:boolean;descriptionsBeforeInterpretationConfirmed:boolean;pupilLightingPrimaryVariableConfirmed:boolean;noIntentInferenceConfirmed:boolean;noLieInferenceConfirmed:boolean;noAttractionInferenceConfirmed:boolean;noTraumaInferenceConfirmed:boolean;noClinicalInferenceConfirmed:boolean;
  partnerConsentConfirmed:boolean;neutralTopicsCount:number;partnerIdentityNotStoredConfirmed:boolean;partnerCameraNotUsedConfirmed:boolean;descriptionsBeforeFeedbackConfirmed:boolean;onlyVoluntaryDisclosureComparedConfirmed:boolean;divergenceNotLieConfirmed:boolean;vulnerablePeopleNotTargetedConfirmed:boolean;intimateSituationNotUsedConfirmed:boolean;partnerComparisonCompletedConfirmed:boolean;partnerExerciseExplicitlyEndedConfirmed:boolean;
  correctInferenceCount:number;incorrectInferenceCount:number;unverifiableInferenceCount:number;publicPartnerComparedConfirmed:boolean;errorsPreservedConfirmed:boolean;competingVariablesPreservedConfirmed:boolean;mindReadingNotClaimedConfirmed:boolean;diagnosisNotClaimedConfirmed:boolean;highImpactNotUsedConfirmed:boolean;
  psalm101Confirmed:boolean;heHeAlephConfirmed:boolean;observationsReviewedCount:number;environmentalVariablesNamedCount:number;unsupportedInterpretationsRemovedConfirmed:boolean;partnerThankedConfirmed:boolean;visionRestedConfirmed:boolean;noContinuedMonitoringConfirmed:boolean;noIdentifiableDataInPracticeRecordConfirmed:boolean;consciousReturnConfirmed:boolean;
  vaultEntryRef:string;vaultPayloadNoIdentifyingDataConfirmed:boolean;voluntaryCompletionConfirmed:boolean;finalSafetyClearConfirmed:boolean;safetyStopOccurred?:boolean;safetyStopReason?:Day060SafetyReason;
}
export interface Day060EvidenceV2{
  protocol_version:typeof DAY060_QUEST_ID;source_sha:typeof DAY060_SOURCE_SHA;session_id:string;mode:'first_completion'|'revisit';public_duration_seconds:number;partner_duration_seconds:number;
  public_observations:Array<{index:number;feature:Day060Feature;distance_bucket:Day060Distance;lighting:Day060Lighting;interpretation_discarded:boolean}>;
  public_boundaries:{public_context_safe_confirmed:true;camera_not_used_confirmed:true;zoom_not_used_confirmed:true;recognition_not_used_confirmed:true;identity_not_stored_confirmed:true;no_prolonged_fixation_confirmed:true;descriptions_before_interpretation_confirmed:true;pupil_lighting_primary_variable_confirmed:true;no_intent_inference_confirmed:true;no_lie_inference_confirmed:true;no_attraction_inference_confirmed:true;no_trauma_inference_confirmed:true;no_clinical_inference_confirmed:true};
  partner_control:{consent_confirmed:true;neutral_topics_count:2;identity_not_stored_confirmed:true;camera_not_used_confirmed:true;descriptions_before_feedback_confirmed:true;only_voluntary_disclosure_compared_confirmed:true;divergence_not_lie_confirmed:true;vulnerable_people_not_targeted_confirmed:true;intimate_situation_not_used_confirmed:true;comparison_completed_confirmed:true;exercise_explicitly_ended_confirmed:true};
  comparison:{correct_inference_count:number;incorrect_inference_count:number;unverifiable_inference_count:number;public_partner_compared_confirmed:true;errors_preserved_confirmed:true;competing_variables_preserved_confirmed:true;mind_reading_not_claimed_confirmed:true;diagnosis_not_claimed_confirmed:true;high_impact_not_used_confirmed:true};
  middle:{psalm_10_1_confirmed:true;he_he_aleph_confirmed:true;observations_reviewed_count:3;environmental_variables_named_count:3;unsupported_interpretations_removed_confirmed:true;partner_thanked_confirmed:true;vision_rested_confirmed:true;no_continued_monitoring_confirmed:true;no_identifiable_data_in_practice_record_confirmed:true;conscious_return_confirmed:true};
  vault_entry_ref:string;vault_payload_no_identifying_data_confirmed:true;voluntary_completion_confirmed:true;final_safety_clear_confirmed:true;safety_stop_occurred:boolean;safety_stop_reason:Day060SafetyReason;
}
function yes(v:boolean,n:string){if(v!==true)throw new Error(n)}function nn(v:number,n:string){if(!Number.isInteger(v)||v<0)throw new Error(n);return v}function uuid(v:string){const x=v.trim();if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(x))throw new Error('day060_vault_ref_invalid');return x}
export function buildDay060EvidenceV2(i:Day060EvidenceInput):Day060EvidenceV2{
 const sessionId=i.sessionId.trim();if(!sessionId)throw new Error('day060_session_required');if(i.mode!==undefined&&!['first_completion','revisit'].includes(i.mode))throw new Error('day060_mode_invalid');if(i.publicObservations.length!==5)throw new Error('day060_exactly_five_public_observations_required');
 const features=['POSTURE','APPARENT_BREATHING','GAZE_DIRECTION','PUPIL_VISIBILITY','OTHER_VISIBLE_CHANGE'],dist=['LT_2M','M2_TO_5M','GT_5M','UNKNOWN'],light=['BRIGHT','DIM','MIXED','UNKNOWN'];
 const observations=i.publicObservations.map((o,p)=>{if(!Number.isInteger(o.index)||o.index!==p+1)throw new Error('day060_observation_index_invalid');if(!features.includes(o.feature))throw new Error('day060_feature_invalid');if(!dist.includes(o.distanceBucket))throw new Error('day060_distance_invalid');if(!light.includes(o.lighting))throw new Error('day060_lighting_invalid');if(typeof o.interpretationDiscarded!=='boolean')throw new Error('day060_interpretation_discarded_invalid');return{index:o.index,feature:o.feature,distance_bucket:o.distanceBucket,lighting:o.lighting,interpretation_discarded:o.interpretationDiscarded}});
 for(const[v,k]of[[i.publicContextSafeConfirmed,'public_context_safe'],[i.cameraNotUsedConfirmed,'camera_not_used'],[i.zoomNotUsedConfirmed,'zoom_not_used'],[i.recognitionNotUsedConfirmed,'recognition_not_used'],[i.identityNotStoredConfirmed,'identity_not_stored'],[i.noProlongedFixationConfirmed,'no_prolonged_fixation'],[i.descriptionsBeforeInterpretationConfirmed,'descriptions_before_interpretation'],[i.pupilLightingPrimaryVariableConfirmed,'pupil_lighting_primary_variable'],[i.noIntentInferenceConfirmed,'no_intent_inference'],[i.noLieInferenceConfirmed,'no_lie_inference'],[i.noAttractionInferenceConfirmed,'no_attraction_inference'],[i.noTraumaInferenceConfirmed,'no_trauma_inference'],[i.noClinicalInferenceConfirmed,'no_clinical_inference'],[i.partnerConsentConfirmed,'partner_consent'],[i.partnerIdentityNotStoredConfirmed,'partner_identity_not_stored'],[i.partnerCameraNotUsedConfirmed,'partner_camera_not_used'],[i.descriptionsBeforeFeedbackConfirmed,'descriptions_before_feedback'],[i.onlyVoluntaryDisclosureComparedConfirmed,'only_voluntary_disclosure'],[i.divergenceNotLieConfirmed,'divergence_not_lie'],[i.vulnerablePeopleNotTargetedConfirmed,'vulnerable_people_not_targeted'],[i.intimateSituationNotUsedConfirmed,'intimate_situation_not_used'],[i.partnerComparisonCompletedConfirmed,'partner_comparison'],[i.partnerExerciseExplicitlyEndedConfirmed,'partner_explicit_end'],[i.publicPartnerComparedConfirmed,'public_partner_compared'],[i.errorsPreservedConfirmed,'errors_preserved'],[i.competingVariablesPreservedConfirmed,'competing_variables_preserved'],[i.mindReadingNotClaimedConfirmed,'mind_reading_not_claimed'],[i.diagnosisNotClaimedConfirmed,'diagnosis_not_claimed'],[i.highImpactNotUsedConfirmed,'high_impact_not_used'],[i.psalm101Confirmed,'psalm'],[i.heHeAlephConfirmed,'formula'],[i.unsupportedInterpretationsRemovedConfirmed,'unsupported_interpretations_removed'],[i.partnerThankedConfirmed,'partner_thanked'],[i.visionRestedConfirmed,'vision_rested'],[i.noContinuedMonitoringConfirmed,'no_continued_monitoring'],[i.noIdentifiableDataInPracticeRecordConfirmed,'no_identifiable_data'],[i.consciousReturnConfirmed,'return'],[i.vaultPayloadNoIdentifyingDataConfirmed,'vault_no_identifying_data'],[i.voluntaryCompletionConfirmed,'voluntary'],[i.finalSafetyClearConfirmed,'final_safety']]as const)yes(v,`day060_${k}_required`);
 if(i.neutralTopicsCount!==2)throw new Error('day060_two_neutral_topics_required');if(i.observationsReviewedCount!==3)throw new Error('day060_three_observations_reviewed_required');if(i.environmentalVariablesNamedCount!==3)throw new Error('day060_three_environmental_variables_required');const stopped=i.safetyStopOccurred===true,reason=i.safetyStopReason??'NONE';if(!['NONE','PRIVACY_CONCERN','CONSENT_WITHDRAWN','FIXATION_CONCERN','DISCOMFORT','OTHER'].includes(reason))throw new Error('day060_safety_reason_invalid');if(stopped&&reason==='NONE')throw new Error('day060_safety_reason_required');if(!stopped&&reason!=='NONE')throw new Error('day060_safety_reason_without_stop');
 return{protocol_version:DAY060_QUEST_ID,source_sha:DAY060_SOURCE_SHA,session_id:sessionId,mode:i.mode??'first_completion',public_duration_seconds:nn(i.publicDurationSeconds,'day060_public_duration_invalid'),partner_duration_seconds:nn(i.partnerDurationSeconds,'day060_partner_duration_invalid'),public_observations:observations,public_boundaries:{public_context_safe_confirmed:true,camera_not_used_confirmed:true,zoom_not_used_confirmed:true,recognition_not_used_confirmed:true,identity_not_stored_confirmed:true,no_prolonged_fixation_confirmed:true,descriptions_before_interpretation_confirmed:true,pupil_lighting_primary_variable_confirmed:true,no_intent_inference_confirmed:true,no_lie_inference_confirmed:true,no_attraction_inference_confirmed:true,no_trauma_inference_confirmed:true,no_clinical_inference_confirmed:true},partner_control:{consent_confirmed:true,neutral_topics_count:2,identity_not_stored_confirmed:true,camera_not_used_confirmed:true,descriptions_before_feedback_confirmed:true,only_voluntary_disclosure_compared_confirmed:true,divergence_not_lie_confirmed:true,vulnerable_people_not_targeted_confirmed:true,intimate_situation_not_used_confirmed:true,comparison_completed_confirmed:true,exercise_explicitly_ended_confirmed:true},comparison:{correct_inference_count:nn(i.correctInferenceCount,'day060_correct_count_invalid'),incorrect_inference_count:nn(i.incorrectInferenceCount,'day060_incorrect_count_invalid'),unverifiable_inference_count:nn(i.unverifiableInferenceCount,'day060_unverifiable_count_invalid'),public_partner_compared_confirmed:true,errors_preserved_confirmed:true,competing_variables_preserved_confirmed:true,mind_reading_not_claimed_confirmed:true,diagnosis_not_claimed_confirmed:true,high_impact_not_used_confirmed:true},middle:{psalm_10_1_confirmed:true,he_he_aleph_confirmed:true,observations_reviewed_count:3,environmental_variables_named_count:3,unsupported_interpretations_removed_confirmed:true,partner_thanked_confirmed:true,vision_rested_confirmed:true,no_continued_monitoring_confirmed:true,no_identifiable_data_in_practice_record_confirmed:true,conscious_return_confirmed:true},vault_entry_ref:uuid(i.vaultEntryRef),vault_payload_no_identifying_data_confirmed:true,voluntary_completion_confirmed:true,final_safety_clear_confirmed:true,safety_stop_occurred:stopped,safety_stop_reason:reason as Day060SafetyReason};
}
export function buildDay060LegacyScalarEvidence(e:Day060EvidenceV2){return{protocol_completed:true,return_confirmed:e.middle.conscious_return_confirmed,five_public_observations_completed:e.public_observations.length===5,camera_not_used:e.public_boundaries.camera_not_used_confirmed,identity_not_stored:e.public_boundaries.identity_not_stored_confirmed,partner_consent:e.partner_control.consent_confirmed,partner_comparison_completed:e.partner_control.comparison_completed_confirmed,diagnosis_not_claimed:e.comparison.diagnosis_not_claimed_confirmed,mind_reading_not_claimed:e.comparison.mind_reading_not_claimed_confirmed,vulnerable_people_not_targeted:e.partner_control.vulnerable_people_not_targeted_confirmed,vault_saved:true,safety_clear:e.final_safety_clear_confirmed,public_observations_count:e.public_observations.length}}
export function buildDay060SafeMetrics(e:Day060EvidenceV2):SafeMetricRecord{return{public_observations_count:e.public_observations.length,public_duration_seconds:e.public_duration_seconds,partner_duration_seconds:e.partner_duration_seconds,correct_inference_count:e.comparison.correct_inference_count,incorrect_inference_count:e.comparison.incorrect_inference_count,unverifiable_inference_count:e.comparison.unverifiable_inference_count,interpretations_discarded_count:e.public_observations.filter(x=>x.interpretation_discarded).length,safety_stop_occurred:e.safety_stop_occurred?1:0}}
