import type {SafeMetricRecord} from './types.js';

export const DAY059_QUEST_ID='HNK-CHOKMAH-D059-V2' as const;
export const DAY059_SOURCE_SHA='e0b9b51cac81012e4511e6394c6f3dff7f50aaf8' as const;
export const DAY059_CANONICAL_SECONDS=900 as const;

export type Day059SafetyReason='NONE'|'OCULAR_DISCOMFORT'|'HEADACHE'|'VERTIGO'|'ANXIETY_INCREASED'|'DISORIENTATION'|'OTHER';
export interface Day059BlueInput{
  measuredSeconds:number;imagePresent:boolean;returnCount:number;sharpness:number;brightness:number;ocularEffort:number;silence:number;
  bluePearlFocusConfirmed:boolean;thoughtsReleasedWithoutForceConfirmed:boolean;noEyePressureConfirmed:boolean;noForcedBrightnessOrSilenceConfirmed:boolean;
}
export interface Day059GrayInput{
  measuredSeconds:number;imagePresent:boolean;returnCount:number;sharpness:number;brightness:number;ocularEffort:number;expectation:number;
  neutralGrayPointConfirmed:boolean;samePostureConfirmed:boolean;sameEnvironmentConfirmed:boolean;controlNotSabotagedConfirmed:boolean;
}
export interface Day059EvidenceInput{
  sessionId:string;mode?:'first_completion'|'revisit';blue:Day059BlueInput;gray:Day059GrayInput;privateVaultEntryRef?:string|null;
  comparisonCompletedConfirmed:boolean;comparedOnlyAfterBothConfirmed:boolean;interpretationSeparatedConfirmed:boolean;clairvoyanceNotClaimedConfirmed:boolean;reasonPreservedConfirmed:boolean;differenceNotExternalMechanismProofConfirmed:boolean;absenceValidConfirmed:boolean;highImpactNotUsedConfirmed:boolean;
  psalm101Confirmed:boolean;heHeAlephConfirmed:boolean;instrumentalObservationNamedConfirmed:boolean;sensationNamedConfirmed:boolean;traditionalSymbolNamedConfirmed:boolean;openHypothesisNamedConfirmed:boolean;thanksToGodConfirmed:boolean;consciousReturnConfirmed:boolean;groundingThreeObjectsConfirmed:boolean;
  voluntaryCompletionConfirmed:boolean;finalSafetyClearConfirmed:boolean;safetyStopOccurred?:boolean;safetyStopReason?:Day059SafetyReason;
}
export interface Day059EvidenceV2{
  protocol_version:typeof DAY059_QUEST_ID;source_sha:typeof DAY059_SOURCE_SHA;session_id:string;mode:'first_completion'|'revisit';
  blue:{measured_seconds:number;image_present:boolean;return_count:number;sharpness:number;brightness:number;ocular_effort:number;silence:number;blue_pearl_focus_confirmed:true;thoughts_released_without_force_confirmed:true;no_eye_pressure_confirmed:true;no_forced_brightness_or_silence_confirmed:true};
  gray:{measured_seconds:number;image_present:boolean;return_count:number;sharpness:number;brightness:number;ocular_effort:number;expectation:number;neutral_gray_point_confirmed:true;same_posture_confirmed:true;same_environment_confirmed:true;control_not_sabotaged_confirmed:true};
  comparison:{completed_confirmed:true;compared_only_after_both_confirmed:true;interpretation_separated_confirmed:true;clairvoyance_not_claimed_confirmed:true;reason_preserved_confirmed:true;difference_not_external_mechanism_proof_confirmed:true;absence_valid_confirmed:true;high_impact_not_used_confirmed:true};
  middle:{psalm_10_1_confirmed:true;he_he_aleph_confirmed:true;instrumental_observation_named_confirmed:true;sensation_named_confirmed:true;traditional_symbol_named_confirmed:true;open_hypothesis_named_confirmed:true;thanks_to_god_confirmed:true;conscious_return_confirmed:true;grounding_three_objects_confirmed:true};
  private_vault_entry_ref?:string;voluntary_completion_confirmed:true;final_safety_clear_confirmed:true;safety_stop_occurred:boolean;safety_stop_reason:Day059SafetyReason;
}
function yes(v:boolean,n:string){if(v!==true)throw new Error(n)}
function seconds(v:number,n:string){if(!Number.isInteger(v)||v<DAY059_CANONICAL_SECONDS)throw new Error(n);return v}
function count(v:number,n:string){if(!Number.isInteger(v)||v<0)throw new Error(n);return v}
function scale(v:number,n:string){if(!Number.isInteger(v)||v<0||v>10)throw new Error(n);return v}
function optRef(v:string|null|undefined){if(v==null||v.trim()==='')return undefined;const x=v.trim();if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(x))throw new Error('day059_private_vault_ref_invalid');return x}
export function buildDay059EvidenceV2(i:Day059EvidenceInput):Day059EvidenceV2{
  const sessionId=i.sessionId.trim();if(!sessionId)throw new Error('day059_session_required');if(i.mode!==undefined&&!['first_completion','revisit'].includes(i.mode))throw new Error('day059_mode_invalid');
  for(const[v,k]of[[i.blue.bluePearlFocusConfirmed,'blue_focus'],[i.blue.thoughtsReleasedWithoutForceConfirmed,'blue_no_force'],[i.blue.noEyePressureConfirmed,'blue_no_eye_pressure'],[i.blue.noForcedBrightnessOrSilenceConfirmed,'blue_no_forced_effect'],[i.gray.neutralGrayPointConfirmed,'gray_neutral'],[i.gray.samePostureConfirmed,'gray_same_posture'],[i.gray.sameEnvironmentConfirmed,'gray_same_environment'],[i.gray.controlNotSabotagedConfirmed,'gray_control_not_sabotaged'],[i.comparisonCompletedConfirmed,'comparison'],[i.comparedOnlyAfterBothConfirmed,'comparison_order'],[i.interpretationSeparatedConfirmed,'interpretation_separated'],[i.clairvoyanceNotClaimedConfirmed,'clairvoyance_boundary'],[i.reasonPreservedConfirmed,'reason_preserved'],[i.differenceNotExternalMechanismProofConfirmed,'external_mechanism_boundary'],[i.absenceValidConfirmed,'absence_valid'],[i.highImpactNotUsedConfirmed,'high_impact_boundary'],[i.psalm101Confirmed,'psalm'],[i.heHeAlephConfirmed,'formula'],[i.instrumentalObservationNamedConfirmed,'instrumental_observation'],[i.sensationNamedConfirmed,'sensation'],[i.traditionalSymbolNamedConfirmed,'traditional_symbol'],[i.openHypothesisNamedConfirmed,'open_hypothesis'],[i.thanksToGodConfirmed,'thanks_to_god'],[i.consciousReturnConfirmed,'return'],[i.groundingThreeObjectsConfirmed,'grounding'],[i.voluntaryCompletionConfirmed,'voluntary'],[i.finalSafetyClearConfirmed,'final_safety']]as const)yes(v,`day059_${k}_required`);
  if(typeof i.blue.imagePresent!=='boolean'||typeof i.gray.imagePresent!=='boolean')throw new Error('day059_image_presence_boolean_required');
  const stopped=i.safetyStopOccurred===true,reason=i.safetyStopReason??'NONE';if(!['NONE','OCULAR_DISCOMFORT','HEADACHE','VERTIGO','ANXIETY_INCREASED','DISORIENTATION','OTHER'].includes(reason))throw new Error('day059_safety_reason_invalid');if(stopped&&reason==='NONE')throw new Error('day059_safety_reason_required');if(!stopped&&reason!=='NONE')throw new Error('day059_safety_reason_without_stop');
  const privateRef=optRef(i.privateVaultEntryRef);
  return{protocol_version:DAY059_QUEST_ID,source_sha:DAY059_SOURCE_SHA,session_id:sessionId,mode:i.mode??'first_completion',blue:{measured_seconds:seconds(i.blue.measuredSeconds,'day059_blue_900_seconds_required'),image_present:i.blue.imagePresent,return_count:count(i.blue.returnCount,'day059_blue_return_count_invalid'),sharpness:scale(i.blue.sharpness,'day059_blue_sharpness_invalid'),brightness:scale(i.blue.brightness,'day059_blue_brightness_invalid'),ocular_effort:scale(i.blue.ocularEffort,'day059_blue_ocular_effort_invalid'),silence:scale(i.blue.silence,'day059_blue_silence_invalid'),blue_pearl_focus_confirmed:true,thoughts_released_without_force_confirmed:true,no_eye_pressure_confirmed:true,no_forced_brightness_or_silence_confirmed:true},gray:{measured_seconds:seconds(i.gray.measuredSeconds,'day059_gray_900_seconds_required'),image_present:i.gray.imagePresent,return_count:count(i.gray.returnCount,'day059_gray_return_count_invalid'),sharpness:scale(i.gray.sharpness,'day059_gray_sharpness_invalid'),brightness:scale(i.gray.brightness,'day059_gray_brightness_invalid'),ocular_effort:scale(i.gray.ocularEffort,'day059_gray_ocular_effort_invalid'),expectation:scale(i.gray.expectation,'day059_gray_expectation_invalid'),neutral_gray_point_confirmed:true,same_posture_confirmed:true,same_environment_confirmed:true,control_not_sabotaged_confirmed:true},comparison:{completed_confirmed:true,compared_only_after_both_confirmed:true,interpretation_separated_confirmed:true,clairvoyance_not_claimed_confirmed:true,reason_preserved_confirmed:true,difference_not_external_mechanism_proof_confirmed:true,absence_valid_confirmed:true,high_impact_not_used_confirmed:true},middle:{psalm_10_1_confirmed:true,he_he_aleph_confirmed:true,instrumental_observation_named_confirmed:true,sensation_named_confirmed:true,traditional_symbol_named_confirmed:true,open_hypothesis_named_confirmed:true,thanks_to_god_confirmed:true,conscious_return_confirmed:true,grounding_three_objects_confirmed:true},...(privateRef?{private_vault_entry_ref:privateRef}:{}),voluntary_completion_confirmed:true,final_safety_clear_confirmed:true,safety_stop_occurred:stopped,safety_stop_reason:reason as Day059SafetyReason};
}
export function buildDay059LegacyScalarEvidence(e:Day059EvidenceV2){return{protocol_completed:true,return_confirmed:e.middle.conscious_return_confirmed,blue_completed:e.blue.measured_seconds>=DAY059_CANONICAL_SECONDS,gray_completed:e.gray.measured_seconds>=DAY059_CANONICAL_SECONDS,comparison_completed:e.comparison.completed_confirmed,interpretation_separated:e.comparison.interpretation_separated_confirmed,clarivoyance_not_claimed:e.comparison.clairvoyance_not_claimed_confirmed,reason_preserved:e.comparison.reason_preserved_confirmed,safety_clear:e.final_safety_clear_confirmed,blue_image_present:e.blue.image_present,gray_image_present:e.gray.image_present,blue_seconds:e.blue.measured_seconds,gray_seconds:e.gray.measured_seconds}}
export function buildDay059SafeMetrics(e:Day059EvidenceV2):SafeMetricRecord{return{blue_seconds:e.blue.measured_seconds,gray_seconds:e.gray.measured_seconds,blue_image_present:e.blue.image_present?1:0,gray_image_present:e.gray.image_present?1:0,blue_return_count:e.blue.return_count,gray_return_count:e.gray.return_count,blue_sharpness:e.blue.sharpness,blue_brightness:e.blue.brightness,blue_ocular_effort:e.blue.ocular_effort,blue_silence:e.blue.silence,gray_sharpness:e.gray.sharpness,gray_brightness:e.gray.brightness,gray_ocular_effort:e.gray.ocular_effort,gray_expectation:e.gray.expectation,safety_stop_occurred:e.safety_stop_occurred?1:0}}
