import type {SafeMetricRecord} from './types.js';

export const DAY038_QUEST_ID='HNK-CHOKMAH-D038-V1' as const;
export const DAY038_SOURCE_SHA='db42ffb5a78fb9f3d816c2921b02b227bb7c7652' as const;
export const DAY038_JACHIN_SECONDS=360 as const;
export const DAY038_BOAZ_SECONDS=300 as const;

export type Day038LeadingEffect='INCREASED_RESISTANCE'|'REDUCED_CONFLICT'|'NO_PERCEPTIBLE_CHANGE'|'MIXED';
export type Day038LeadingTarget='CALM'|'FOCUS'|'PRAYER'|'MIXED';

export interface Day038EvidenceV1{
  protocol_version:typeof DAY038_QUEST_ID;source_sha:typeof DAY038_SOURCE_SHA;session_id:string;mode:'first_completion'|'revisit';
  jachin:{observation_seconds:360;thoughts_accompanied_count:10;pacing_statement_count:number;leading_count:number;accepted_leading_count:number;rejected_leading_count:number;three_acknowledgements_before_leading_confirmed:true;leading_permissive_confirmed:true;suggestion_rejectable_confirmed:true;thought_not_fact_confirmed:true;pacing_not_agreement_confirmed:true;tension_initial:number;tension_final:number;mental_rhythm_initial:number;mental_rhythm_final:number;breathing_change_recorded_confirmed:true;distraction_count:number;attention_return_count:number;subjective_depth:number;vault_entry_ref:string};
  boaz:{duration_seconds:300;original_thought_to_description_completed:true;pacing_statement_count:number;leading_count:number;discomfort_stops_leading_confirmed:true;observation_only_return_supported_confirmed:true;resistance_recorded_confirmed:true;tension_recorded_confirmed:true;body_response_recorded_confirmed:true;leading_effect:Day038LeadingEffect;voluntary_interruption_count:number;change_or_no_change_valid_confirmed:true;personal_limit_declared_confirmed:true;vault_entry_ref:string};
  middle:{thoughts_observed_count:3;pacing_statement_count:number;leading_count:number;leading_target:Day038LeadingTarget;psalm_11_7_confirmed:true;kaph_he_tav_confirmed:true;truthful_pacing_confirmed:true;two_breath_wordless_pause_confirmed:true;thanks_to_god_confirmed:true;conscious_trance_exit_confirmed:true;given_interpreted_chosen_triplet_completed:true;voluntary_choice_preserved_confirmed:true;functional_return_confirmed:true;vault_entry_ref:string};
  soul_mirror:{completed:true;vault_entry_ref:string};voluntary_completion_confirmed:true;safety_stop_occurred:boolean
}
export interface Day038EvidenceInput{sessionId:string;mode?:'first_completion'|'revisit';thoughtsAccompaniedCount:number;pacingStatementCount:number;leadingCount:number;acceptedLeadingCount:number;rejectedLeadingCount:number;threeAcknowledgementsBeforeLeadingConfirmed:boolean;leadingPermissiveConfirmed:boolean;suggestionRejectableConfirmed:boolean;thoughtNotFactConfirmed:boolean;pacingNotAgreementConfirmed:boolean;tensionInitial:number;tensionFinal:number;mentalRhythmInitial:number;mentalRhythmFinal:number;breathingChangeRecordedConfirmed:boolean;distractionCount:number;attentionReturnCount:number;subjectiveDepth:number;jachinVaultEntryRef:string;boazPacingStatementCount:number;boazLeadingCount:number;originalThoughtToDescriptionCompleted:boolean;discomfortStopsLeadingConfirmed:boolean;observationOnlyReturnSupportedConfirmed:boolean;resistanceRecordedConfirmed:boolean;tensionRecordedConfirmed:boolean;bodyResponseRecordedConfirmed:boolean;leadingEffect:Day038LeadingEffect;voluntaryInterruptionCount:number;changeOrNoChangeValidConfirmed:boolean;personalLimitDeclaredConfirmed:boolean;boazVaultEntryRef:string;middleThoughtsObservedCount:number;middlePacingStatementCount:number;middleLeadingCount:number;middleLeadingTarget:Day038LeadingTarget;psalm117Confirmed:boolean;kaphHeTavConfirmed:boolean;truthfulPacingConfirmed:boolean;twoBreathWordlessPauseConfirmed:boolean;thanksToGodConfirmed:boolean;consciousTranceExitConfirmed:boolean;givenInterpretedChosenTripletCompleted:boolean;voluntaryChoicePreservedConfirmed:boolean;functionalReturnConfirmed:boolean;middleVaultEntryRef:string;soulMirrorCompleted:boolean;soulMirrorVaultEntryRef:string;voluntaryCompletionConfirmed:boolean;safetyStopOccurred?:boolean}
function yes(v:boolean,n:string){if(v!==true)throw new Error(n)}function integer(v:number,min:number,max:number,n:string){if(!Number.isInteger(v)||v<min||v>max)throw new Error(n);return v}function scale(v:number,n:string){return integer(v,0,10,n)}function ref(v:string,n:string){const x=v.trim();if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(x))throw new Error(n);return x}
export function buildDay038EvidenceV1(i:Day038EvidenceInput):Day038EvidenceV1{
 if(!i.sessionId.trim())throw new Error('day038_session_required');
 for(const[v,n]of[[i.threeAcknowledgementsBeforeLeadingConfirmed,'day038_three_acknowledgements_required'],[i.leadingPermissiveConfirmed,'day038_permissive_leading_required'],[i.suggestionRejectableConfirmed,'day038_rejectable_suggestion_required'],[i.thoughtNotFactConfirmed,'day038_thought_not_fact_required'],[i.pacingNotAgreementConfirmed,'day038_pacing_not_agreement_required'],[i.breathingChangeRecordedConfirmed,'day038_breathing_record_required'],[i.originalThoughtToDescriptionCompleted,'day038_description_reframe_required'],[i.discomfortStopsLeadingConfirmed,'day038_discomfort_stop_required'],[i.observationOnlyReturnSupportedConfirmed,'day038_observation_return_required'],[i.resistanceRecordedConfirmed,'day038_resistance_record_required'],[i.tensionRecordedConfirmed,'day038_tension_record_required'],[i.bodyResponseRecordedConfirmed,'day038_body_response_required'],[i.changeOrNoChangeValidConfirmed,'day038_no_change_valid_required'],[i.personalLimitDeclaredConfirmed,'day038_personal_limit_required'],[i.psalm117Confirmed,'day038_psalm_required'],[i.kaphHeTavConfirmed,'day038_kaph_he_tav_required'],[i.truthfulPacingConfirmed,'day038_truthful_pacing_required'],[i.twoBreathWordlessPauseConfirmed,'day038_two_breath_pause_required'],[i.thanksToGodConfirmed,'day038_thanks_required'],[i.consciousTranceExitConfirmed,'day038_conscious_exit_required'],[i.givenInterpretedChosenTripletCompleted,'day038_triplet_required'],[i.voluntaryChoicePreservedConfirmed,'day038_voluntary_choice_required'],[i.functionalReturnConfirmed,'day038_functional_return_required'],[i.soulMirrorCompleted,'day038_soul_mirror_required'],[i.voluntaryCompletionConfirmed,'day038_voluntary_completion_required']]as const)yes(v,n);
 const thoughts=integer(i.thoughtsAccompaniedCount,10,10,'day038_ten_thoughts_required'),pacing=integer(i.pacingStatementCount,10,9999,'day038_pacing_count_invalid'),leading=integer(i.leadingCount,1,9999,'day038_leading_count_invalid'),accepted=integer(i.acceptedLeadingCount,0,leading,'day038_accept_count_invalid'),rejected=integer(i.rejectedLeadingCount,0,leading,'day038_reject_count_invalid');if(accepted+rejected!==leading)throw new Error('day038_every_leading_must_be_classified');
 return{protocol_version:DAY038_QUEST_ID,source_sha:DAY038_SOURCE_SHA,session_id:i.sessionId,mode:i.mode??'first_completion',jachin:{observation_seconds:360,thoughts_accompanied_count:thoughts,pacing_statement_count:pacing,leading_count:leading,accepted_leading_count:accepted,rejected_leading_count:rejected,three_acknowledgements_before_leading_confirmed:true,leading_permissive_confirmed:true,suggestion_rejectable_confirmed:true,thought_not_fact_confirmed:true,pacing_not_agreement_confirmed:true,tension_initial:scale(i.tensionInitial,'day038_tension_initial_invalid'),tension_final:scale(i.tensionFinal,'day038_tension_final_invalid'),mental_rhythm_initial:scale(i.mentalRhythmInitial,'day038_mental_rhythm_initial_invalid'),mental_rhythm_final:scale(i.mentalRhythmFinal,'day038_mental_rhythm_final_invalid'),breathing_change_recorded_confirmed:true,distraction_count:integer(i.distractionCount,0,9999,'day038_distraction_count_invalid'),attention_return_count:integer(i.attentionReturnCount,0,9999,'day038_attention_return_invalid'),subjective_depth:scale(i.subjectiveDepth,'day038_subjective_depth_invalid'),vault_entry_ref:ref(i.jachinVaultEntryRef,'day038_jachin_vault_ref_invalid')},boaz:{duration_seconds:300,original_thought_to_description_completed:true,pacing_statement_count:integer(i.boazPacingStatementCount,3,9999,'day038_boaz_pacing_invalid'),leading_count:integer(i.boazLeadingCount,1,9999,'day038_boaz_leading_invalid'),discomfort_stops_leading_confirmed:true,observation_only_return_supported_confirmed:true,resistance_recorded_confirmed:true,tension_recorded_confirmed:true,body_response_recorded_confirmed:true,leading_effect:i.leadingEffect,voluntary_interruption_count:integer(i.voluntaryInterruptionCount,0,9999,'day038_voluntary_interruptions_invalid'),change_or_no_change_valid_confirmed:true,personal_limit_declared_confirmed:true,vault_entry_ref:ref(i.boazVaultEntryRef,'day038_boaz_vault_ref_invalid')},middle:{thoughts_observed_count:integer(i.middleThoughtsObservedCount,3,3,'day038_middle_three_thoughts_required'),pacing_statement_count:integer(i.middlePacingStatementCount,3,9999,'day038_middle_pacing_invalid'),leading_count:integer(i.middleLeadingCount,1,9999,'day038_middle_leading_invalid'),leading_target:i.middleLeadingTarget,psalm_11_7_confirmed:true,kaph_he_tav_confirmed:true,truthful_pacing_confirmed:true,two_breath_wordless_pause_confirmed:true,thanks_to_god_confirmed:true,conscious_trance_exit_confirmed:true,given_interpreted_chosen_triplet_completed:true,voluntary_choice_preserved_confirmed:true,functional_return_confirmed:true,vault_entry_ref:ref(i.middleVaultEntryRef,'day038_middle_vault_ref_invalid')},soul_mirror:{completed:true,vault_entry_ref:ref(i.soulMirrorVaultEntryRef,'day038_soul_vault_ref_invalid')},voluntary_completion_confirmed:true,safety_stop_occurred:i.safetyStopOccurred===true};
}
export function buildDay038SafeMetrics(e:Day038EvidenceV1):SafeMetricRecord{return{fixed_protocol_seconds:660,jachin_seconds:360,boaz_seconds:300,thoughts_accompanied_count:e.jachin.thoughts_accompanied_count,pacing_statement_count:e.jachin.pacing_statement_count,leading_count:e.jachin.leading_count,accepted_leading_count:e.jachin.accepted_leading_count,rejected_leading_count:e.jachin.rejected_leading_count,distraction_count:e.jachin.distraction_count,attention_return_count:e.jachin.attention_return_count,subjective_depth:e.jachin.subjective_depth,voluntary_interruption_count:e.boaz.voluntary_interruption_count,middle_thoughts_observed_count:e.middle.thoughts_observed_count}}
