import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from 'react-native';
import { useHnkAuth } from '../auth/AuthContext';
import { MebahelDay067SpatialAnchorExperience } from './MebahelDay067SpatialAnchorExperience';
import { MebahelDay068DigitalFastExperience } from './MebahelDay068DigitalFastExperience';
import { MebahelDay069EyeMovementExperience } from './MebahelDay069EyeMovementExperience';
import { MebahelDay070TetragrammatonExperience } from './MebahelDay070TetragrammatonExperience';
import { MebahelDay071BanishmentExperience } from './MebahelDay071BanishmentExperience';

const DAYS=[67,68,69,70,71] as const; type Day=(typeof DAYS)[number];
export function ChokmahCycle07Mebahel(){
 const auth=useHnkAuth(); const [currentDay,setCurrentDay]=useState(67); const [xp,setXp]=useState(0); const [title,setTitle]=useState('Iniciado'); const [display,setDisplay]=useState<Day>(67); const [loading,setLoading]=useState(true);
 const refresh=useCallback(async()=>{if(!auth.client||auth.phase!=='signed-in'){setLoading(false);return;}const {data,error}=await auth.client.from('user_progress').select('current_day,xp_total,initiatory_title').maybeSingle();if(!error&&data){setCurrentDay(data.current_day);setXp(data.xp_total);setTitle(data.initiatory_title);if(data.current_day>=67&&data.current_day<=71)setDisplay(data.current_day as Day);if(data.current_day>71)setDisplay(71);}setLoading(false);},[auth.client,auth.phase]);
 useEffect(()=>{void refresh();},[refresh]); useEffect(()=>{if(!auth.client||auth.phase!=='signed-in')return;const id=setInterval(()=>void refresh(),4000);return()=>clearInterval(id);},[auth.client,auth.phase,refresh]);
 if(loading&&auth.phase==='signed-in')return <View style={s.loading}><ActivityIndicator color="#9fc6ff"/><Text style={s.loadingText}>ABRINDO O CICLO DE MEBAHEL</Text></View>;
 const completed=Math.max(0,Math.min(5,currentDay-67));
 return <View style={s.screen}><View style={s.rail}><View style={s.railLine}/>{DAYS.map((day,index)=>{const done=index<completed,available=day<=currentDay,active=display===day;return <Pressable key={day} disabled={!available} onPress={()=>setDisplay(day)} style={s.nodeWrap}><View style={[s.node,done&&s.nodeDone,active&&s.nodeActive,!available&&s.nodeLocked]}><Text style={[s.nodeText,(done||active)&&s.nodeTextActive]}>{done?'✓':day}</Text></View><Text style={[s.nodeLabel,active&&s.nodeLabelActive]}>{day===67?'ÂNCORA':day===68?'JEJUM':day===69?'OLHAR':day===70?'PANTÁCULO':'BANIMENTO'}</Text></Pressable>;})}</View>
 <View style={s.header}><View><Text style={s.eyebrow}>CHOKMAH · CICLO VII · LIMITE E PRUDÊNCIA DE MEBAHEL</Text><Text style={s.heading}>DIA {String(display).padStart(3,'0')}</Text></View><View style={s.stats}><Text style={s.stat}>{title.toUpperCase()}</Text><Text style={s.stat}>{xp} XP</Text><Text style={s.stat}>LEVEL 2</Text></View></View>
 {display===67?<MebahelDay067SpatialAnchorExperience/>:null}{display===68?<MebahelDay068DigitalFastExperience/>:null}{display===69?<MebahelDay069EyeMovementExperience/>:null}{display===70?<MebahelDay070TetragrammatonExperience/>:null}{display===71?<MebahelDay071BanishmentExperience/>:null}</View>;
}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:'#02050a'},loading:{flex:1,alignItems:'center',justifyContent:'center',gap:16,backgroundColor:'#02050a'},loadingText:{color:'#6585a5',fontSize:9,letterSpacing:1.5},rail:{flexDirection:'row',justifyContent:'space-between',paddingHorizontal:18,paddingTop:18,paddingBottom:10,backgroundColor:'#030810',position:'relative'},railLine:{position:'absolute',left:44,right:44,top:33,height:1,backgroundColor:'#1d3046'},nodeWrap:{flex:1,alignItems:'center',gap:7},node:{width:30,height:30,borderRadius:15,borderWidth:1,borderColor:'#334861',backgroundColor:'#07101a',alignItems:'center',justifyContent:'center'},nodeDone:{borderColor:'#5f87b7',backgroundColor:'#0b2034'},nodeActive:{borderColor:'#9fcfff',backgroundColor:'#17334d'},nodeLocked:{opacity:.3},nodeText:{color:'#71879b',fontSize:8,fontWeight:'700'},nodeTextActive:{color:'#e2f2ff'},nodeLabel:{color:'#526b80',fontSize:6,letterSpacing:.7},nodeLabelActive:{color:'#8fb5d7'},header:{flexDirection:'row',justifyContent:'space-between',gap:16,paddingHorizontal:24,paddingVertical:14,borderBottomWidth:1,borderBottomColor:'#12263a'},eyebrow:{color:'#6f96ba',fontSize:8,letterSpacing:1.5},heading:{color:'#e8f4ff',fontSize:14,letterSpacing:2.1,marginTop:5},stats:{alignItems:'flex-end',gap:3},stat:{color:'#72899c',fontSize:8,letterSpacing:1}});
