import {useEffect,useState,type ReactNode} from 'react';
import {AppState,Pressable,ScrollView,StyleSheet,Switch,Text,View} from 'react-native';
import * as SecureStore from 'expo-secure-store';
import {loadDay056PracticeSessionV2,sealDay056V2,startDay056PracticeSessionV2} from '@hnk/supabase-client';
import {useHnkAuth} from '../auth/AuthContext';

type Session=NonNullable<Awaited<ReturnType<typeof loadDay056PracticeSessionV2>>>;
type Safety='NONE'|'DIZZINESS'|'PAIN'|'SHORTNESS_OF_BREATH'|'MALAISE'|'OTHER_DISCOMFORT';
type Timer='ACTIVE'|'CONTROL'|null;type Cond={effectPresent:boolean;mood:number;tension:number;closure:number;comfort:number;expectation:number};
type Draft={activeDone:boolean;activeReturn:boolean;activeSeconds:number;active:Cond;controlDone:boolean;controlReturn:boolean;controlSeconds:number;control:Cond;similarContext:boolean;sameMetrics:boolean;noWinner:boolean;noComp:boolean;comparisonDone:boolean;interpretationSeparated:boolean;nullPreserved:boolean;contradictoryPreserved:boolean;alternatives:boolean;clinicalBoundary:boolean;entityBoundary:boolean;externalMechanismBoundary:boolean;superiorityBoundary:boolean;prudence:boolean;psalm:boolean;formula:boolean;middleGesture:boolean;threeFacts:boolean;subjective:boolean;openHypothesis:boolean;bodyMoved:boolean;oriented:boolean;naturalBreathing:boolean;thanks:boolean;layers:boolean;functionalReturn:boolean;voluntary:boolean;finalSafety:boolean;safetyStop:boolean;safetyReason:Safety};
const C=():Cond=>({effectPresent:false,mood:5,tension:5,closure:5,comfort:5,expectation:5});const empty:Draft={activeDone:false,activeReturn:false,activeSeconds:0,active:C(),controlDone:false,controlReturn:false,controlSeconds:0,control:C(),similarContext:false,sameMetrics:false,noWinner:false,noComp:false,comparisonDone:false,interpretationSeparated:false,nullPreserved:false,contradictoryPreserved:false,alternatives:false,clinicalBoundary:false,entityBoundary:false,externalMechanismBoundary:false,superiorityBoundary:false,prudence:false,psalm:false,formula:false,middleGesture:false,threeFacts:false,subjective:false,openHypothesis:false,bodyMoved:false,oriented:false,naturalBreathing:false,thanks:false,layers:false,functionalReturn:false,voluntary:false,finalSafety:false,safetyStop:false,safetyReason:'NONE'};
function keys(u:string){return{draft:`hnk.day056.${u}.draft.v2`,session:`hnk.day056.${u}.session.v2`}}async function load<T>(k:string):Promise<T|null>{try{const v=await SecureStore.getItemAsync(k);return v?JSON.parse(v)as T:null}catch{return null}}function cid(u:string){return`hnk-mobile-d056-v2-${u}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`}
export function Day056GoldenV2Mobile(){
 const auth=useHnkAuth(),live=Boolean(auth.configured&&auth.phase==='signed-in'&&auth.client&&auth.userId);const[session,setSession]=useState<Session|null>(null),[d,setD]=useState<Draft>(empty),[loaded,setLoaded]=useState(false),[timer,setTimer]=useState<Timer>(null),[started,setStarted]=useState<number|null>(null),[error,setError]=useState<string|null>(null),[busy,setBusy]=useState(false),[complete,setComplete]=useState(false);
 useEffect(()=>{if(!auth.userId)return;const k=keys(auth.userId);void Promise.all([load<Draft>(k.draft),SecureStore.getItemAsync(k.session)]).then(async([draft,id])=>{setD(draft??empty);if(id&&auth.client){const s=await loadDay056PracticeSessionV2(auth.client,id).catch(()=>null);if(s)setSession(s);else await SecureStore.deleteItemAsync(k.session)}setLoaded(true)})},[auth.client,auth.userId]);
 useEffect(()=>{if(auth.userId&&loaded&&!complete)void SecureStore.setItemAsync(keys(auth.userId).draft,JSON.stringify(d))},[auth.userId,d,loaded,complete]);
 useEffect(()=>{const sub=AppState.addEventListener('change',state=>{if(state==='active')return;if(timer){setTimer(null);setStarted(null);setError('segmento_de_medicao_corrente_descartado')}});return()=>sub.remove()},[timer]);
 function patch(p:Partial<Draft>){setD(x=>({...x,...p}))}function patchCond(k:'active'|'control',p:Partial<Cond>){setD(x=>({...x,[k]:{...x[k],...p}}))}
 async function ensureSession(){if(session)return session;if(!live||!auth.client||!auth.userId)throw new Error('online_session_required_before_day056_practice');const s=await startDay056PracticeSessionV2(auth.client,{clientSessionId:cid(auth.userId),appVersion:'0.1.0-mobile-day056-v2'});setSession(s);await SecureStore.setItemAsync(keys(auth.userId).session,s.id);return s}
 function startMeasure(k:Timer){if(timer)throw new Error('measurement_already_running');setTimer(k);setStarted(Date.now());setError(null)}function stopMeasure(){if(!timer||started===null)return;const s=Math.min(7200,Math.max(0,Math.floor((Date.now()-started)/1000)));patch(timer==='ACTIVE'?{activeSeconds:Math.min(7200,d.activeSeconds+s)}:{controlSeconds:Math.min(7200,d.controlSeconds+s)});setTimer(null);setStarted(null)}
 function safetyStop(){if(d.safetyReason==='NONE'){setError('selecione_motivo_de_seguranca');return}setTimer(null);setStarted(null);patch({safetyStop:true,finalSafety:false});setError('safety_stop_registrado')}
 async function seal(){if(!auth.client||!auth.userId)return;setBusy(true);setError(null);try{const s=await ensureSession();const r=await sealDay056V2(auth.client,{evidence:{sessionId:s.id,active:d.active,activeMeasuredSeconds:d.activeSeconds,activeComfortableInhalationConfirmed:d.activeDone,activeSymbolicDischargeImageryConfirmed:d.activeDone,activeBriefLaughterOnExhalationConfirmed:d.activeDone,activeNoHyperventilationConfirmed:d.activeDone,activeNoProlongedRetentionConfirmed:d.activeDone,activeReturnedToCommonFocusConfirmed:d.activeReturn,control:d.control,controlMeasuredSeconds:d.controlSeconds,controlComfortableExhalationWithoutLaughterConfirmed:d.controlDone,controlSimilarContextConfirmed:d.similarContext,controlSameMetricsConfirmed:d.sameMetrics,preselectedWinnerAbsentConfirmed:d.noWinner,noDurationIntensityOrEffortCompensationConfirmed:d.noComp,controlReturnedToCommonFocusConfirmed:d.controlReturn,comparisonCompletedConfirmed:d.comparisonDone,interpretationSeparatedConfirmed:d.interpretationSeparated,nullResultsPreservedConfirmed:d.nullPreserved,contradictoryResultsPreservedConfirmed:d.contradictoryPreserved,alternativeExplanationsRecordedConfirmed:d.alternatives,clinicalSubstituteNotClaimedConfirmed:d.clinicalBoundary,entityContaminationNotReinforcedConfirmed:d.entityBoundary,externalMechanismNotClaimedConfirmed:d.externalMechanismBoundary,spiritualSuperiorityNotClaimedConfirmed:d.superiorityBoundary,prudenceRuleDefinedConfirmed:d.prudence,psalm1846Confirmed:d.psalm,lamedAlephVavConfirmed:d.formula,briefCentralGestureWithoutIntensitySeekingConfirmed:d.middleGesture,threeObservableFactsNamedConfirmed:d.threeFacts,oneSubjectiveExperienceNamedConfirmed:d.subjective,oneOpenHypothesisNamedConfirmed:d.openHypothesis,bodyMovedConfirmed:d.bodyMoved,environmentOrientedConfirmed:d.oriented,middleNaturalBreathingConfirmed:d.naturalBreathing,thanksToGodConfirmed:d.thanks,subjectiveTraditionalObjectiveSeparatedConfirmed:d.layers,functionalReturnConfirmed:d.functionalReturn,voluntaryCompletionConfirmed:d.voluntary,finalSafetyClearConfirmed:d.finalSafety,safetyStopOccurred:d.safetyStop,safetyStopReason:d.safetyReason}});if(!r.ok)throw new Error(r.code);setComplete(true);await SecureStore.deleteItemAsync(keys(auth.userId).draft);await SecureStore.deleteItemAsync(keys(auth.userId).session)}catch(e){setError(e instanceof Error?e.message:'day056_completion_failed')}finally{setBusy(false)}}
 if(!auth.userId)return <View style={s.center}><Text style={s.text}>ENTRE NO ÁTRIO PARA INICIAR O DAY 056.</Text></View>;if(complete)return <View style={s.center}><Text style={s.title}>Day 056 concluído</Text><Text style={s.text}>Lauviah V registrado. Próximo: Day 057.</Text></View>;
 const ready=[d.activeDone,d.activeReturn,d.controlDone,d.controlReturn,d.similarContext,d.sameMetrics,d.noWinner,d.noComp,d.comparisonDone,d.interpretationSeparated,d.nullPreserved,d.contradictoryPreserved,d.alternatives,d.clinicalBoundary,d.entityBoundary,d.externalMechanismBoundary,d.superiorityBoundary,d.prudence,d.psalm,d.formula,d.middleGesture,d.threeFacts,d.subjective,d.openHypothesis,d.bodyMoved,d.oriented,d.naturalBreathing,d.thanks,d.layers,d.functionalReturn,d.voluntary,d.finalSafety].every(Boolean);
 return <ScrollView contentContainerStyle={s.shell}><Text style={s.kicker}>CHOKMAH · LAUVIAH · DAY 056</Text><Text style={s.title}>Expiração simbólica com comparação segura</Text><Text style={s.text}>Sem duração mínima canônica. Não hiperventile nem faça retenções prolongadas. “Expulsar confusão” é linguagem ritual; não prova entidade e não substitui cuidado clínico.</Text>{error&&<Text style={s.error}>{error}</Text>}
 <Card title="Ativo"><Check l="Inspiração confortável + descarga imaginada + expiração com gargalhada breve, sem hiperventilação/retenção prolongada" v={d.activeDone} set={v=>patch({activeDone:v})}/><Measure seconds={d.activeSeconds} active={timer==='ACTIVE'} start={()=>startMeasure('ACTIVE')} stop={stopMeasure}/><CondEdit c={d.active} patch={p=>patchCond('active',p)}/><Check l="Retorno ao foco comum" v={d.activeReturn} set={v=>patch({activeReturn:v})}/></Card>
 <Card title="Controle"><Check l="Expiração confortável sem gargalhada" v={d.controlDone} set={v=>patch({controlDone:v})}/><Check l="Contexto semelhante" v={d.similarContext} set={v=>patch({similarContext:v})}/><Check l="Mesmas métricas" v={d.sameMetrics} set={v=>patch({sameMetrics:v})}/><Check l="Sem vencedor pré-selecionado" v={d.noWinner} set={v=>patch({noWinner:v})}/><Check l="Sem compensar com duração/intensidade/esforço" v={d.noComp} set={v=>patch({noComp:v})}/><Measure seconds={d.controlSeconds} active={timer==='CONTROL'} start={()=>startMeasure('CONTROL')} stop={stopMeasure}/><CondEdit c={d.control} patch={p=>patchCond('control',p)}/><Check l="Retorno ao foco comum" v={d.controlReturn} set={v=>patch({controlReturn:v})}/></Card>
 <Card title="Comparação">{[['Comparação concluída','comparisonDone'],['Interpretação separada','interpretationSeparated'],['Resultados nulos preservados','nullPreserved'],['Contradições preservadas','contradictoryPreserved'],['Alternativas registradas','alternatives'],['Não substitui cuidado clínico','clinicalBoundary'],['Não reforça contaminação por entidades','entityBoundary'],['Sem mecanismo externo alegado','externalMechanismBoundary'],['Sem superioridade espiritual alegada','superiorityBoundary'],['Regra de prudência definida','prudence']].map(([l,k])=><Check key={k} l={l} v={Boolean(d[k as keyof Draft])} set={v=>patch({[k]:v} as Partial<Draft>)}/>)}</Card>
 <Card title="Pilar do Meio">{[['Salmo 18:46','psalm'],['LAMED-ALEPH-VAV','formula'],['Gesto breve sem buscar intensidade','middleGesture'],['3 fatos observáveis','threeFacts'],['1 experiência subjetiva','subjective'],['1 hipótese aberta','openHypothesis'],['Movi o corpo','bodyMoved'],['Reconheci o ambiente','oriented'],['Respiração natural','naturalBreathing'],['Agradeci a Deus','thanks'],['Separei subjetivo/tradicional/objetivo','layers'],['Retorno funcional','functionalReturn']].map(([l,k])=><Check key={k} l={l} v={Boolean(d[k as keyof Draft])} set={v=>patch({[k]:v} as Partial<Draft>)}/>)}</Card>
 <Card title="Safety / Return"><Text style={s.text}>Motivo de parada:</Text>{(['NONE','DIZZINESS','PAIN','SHORTNESS_OF_BREATH','MALAISE','OTHER_DISCOMFORT']as Safety[]).map(x=><Button key={x} label={x} onPress={()=>patch({safetyReason:x})}/>)}<Button label="Registrar Safety Stop" onPress={safetyStop}/><Check l="Conclusão voluntária" v={d.voluntary} set={v=>patch({voluntary:v})}/><Check l="Segurança final e orientação normal" v={d.finalSafety} set={v=>patch({finalSafety:v})}/><Button label={busy?'Selando…':'Concluir Day 056'} disabled={!ready||busy||Boolean(timer)} onPress={()=>void seal()}/></Card></ScrollView>
}
function Card({title,children}:{title:string;children:ReactNode}){return <View style={s.card}><Text style={s.cardTitle}>{title}</Text>{children}</View>}function Button({label,onPress,disabled=false}:{label:string;onPress:()=>void;disabled?:boolean}){return <Pressable disabled={disabled} onPress={onPress} style={[s.button,disabled&&s.disabled]}><Text style={s.buttonText}>{label}</Text></Pressable>}function Check({l,v,set}:{l:string;v:boolean;set:(v:boolean)=>void}){return <View style={s.check}><Switch value={v} onValueChange={set}/><Text style={s.checkText}>{l}</Text></View>}function CondEdit({c,patch}:{c:Cond;patch:(p:Partial<Cond>)=>void}){return <View><Check l="Houve efeito subjetivo" v={c.effectPresent} set={v=>patch({effectPresent:v})}/>{(['mood','tension','closure','comfort','expectation']as const).map(k=><Scale key={k} l={k} v={c[k]} set={v=>patch({[k]:v})}/>)}</View>}function Scale({l,v,set}:{l:string;v:number;set:(v:number)=>void}){return <View style={s.metric}><Text style={s.text}>{l}: {v}</Text><View style={s.row}>{[0,2,4,6,8,10].map(n=><Button key={n} label={String(n)} onPress={()=>set(n)}/>)}</View></View>}function Measure({seconds,active,start,stop}:{seconds:number;active:boolean;start:()=>void;stop:()=>void}){return <View><Text style={s.text}>Medição opcional: {seconds}s — sem mínimo canônico.</Text><View style={s.row}><Button label="Iniciar" disabled={active} onPress={start}/><Button label="Parar" disabled={!active} onPress={stop}/></View></View>}
const s=StyleSheet.create({shell:{padding:20,paddingBottom:72,backgroundColor:'#0b0b0f'},center:{flex:1,justifyContent:'center',padding:24,backgroundColor:'#0b0b0f'},kicker:{color:'#b9a67d',letterSpacing:2,marginBottom:8},title:{fontSize:28,fontWeight:'800',color:'#f5f2ea',marginBottom:10},text:{color:'#e7e2d8',lineHeight:22},error:{color:'#ff9da8',marginVertical:10},card:{backgroundColor:'#121217',borderWidth:1,borderColor:'#34313f',borderRadius:18,padding:16,marginTop:14,gap:9},cardTitle:{fontSize:20,fontWeight:'800',color:'#f5f2ea'},button:{backgroundColor:'#d9b86c',borderRadius:10,paddingVertical:9,paddingHorizontal:11,marginVertical:3,alignSelf:'flex-start'},disabled:{opacity:.38},buttonText:{color:'#17120a',fontWeight:'800'},check:{flexDirection:'row',alignItems:'center',gap:9,marginVertical:2},checkText:{color:'#e7e2d8',flex:1},row:{flexDirection:'row',flexWrap:'wrap',gap:6},metric:{marginVertical:5}});
