import {useEffect,useMemo,useState,type ReactNode} from 'react';
import {AppState,Pressable,ScrollView,StyleSheet,Switch,Text,TextInput,View} from 'react-native';
import * as SecureStore from 'expo-secure-store';
import {loadDay058PracticeSessionV2,sealDay058V2,startDay058PracticeSessionV2} from '@hnk/supabase-client';
import {useHnkAuth} from '../auth/AuthContext';
import {createMobileVaultTextPort} from '../../runtime/MobileVaultTextPort';

type Session=NonNullable<Awaited<ReturnType<typeof loadDay058PracticeSessionV2>>>;
type Safety='NONE'|'PRESSURE_INCREASED'|'DISCOMFORT'|'AUTONOMY_CONCERN'|'OTHER';
type Metrics={relaxation:number;clarity:number;pressure:number;autonomy:number};
type ScriptDraft=Metrics&{ref:string|null;twoBenign:boolean;realRefusal:boolean;selfUseOnly:boolean;noClinicalPromise:boolean;noCovertCommand:boolean;choicePreserved:boolean};
type ControlDraft=Metrics&{ref:string|null;selectedScriptIndex:1|2|3;sameGoal:boolean;separateMoment:boolean;textLocked:boolean;directFormulation:boolean;discomfortAllowsAbandonment:boolean};
type Draft={scripts:[ScriptDraft,ScriptDraft,ScriptDraft];control:ControlDraft;comparisonDone:boolean;autonomyPreserved:boolean;pressureIsData:boolean;obedienceNotSuccess:boolean;noConsentBypass:boolean;noAffectiveCommercialSexualAdvantage:boolean;noHighImpact:boolean;noClinicalPromise:boolean;noCovertCommand:boolean;prudenceRule:boolean;psalm:boolean;formula:boolean;transparentRewrite:boolean;refusalPreserved:boolean;layersSeparated:boolean;consciousReturn:boolean;personalNoConsentBypassRule:boolean;voluntary:boolean;finalSafety:boolean;safetyStop:boolean;safetyReason:Safety};

const M=():Metrics=>({relaxation:0,clarity:0,pressure:0,autonomy:0});
const S=():ScriptDraft=>({...M(),ref:null,twoBenign:false,realRefusal:false,selfUseOnly:false,noClinicalPromise:false,noCovertCommand:false,choicePreserved:false});
const empty:Draft={scripts:[S(),S(),S()],control:{...M(),ref:null,selectedScriptIndex:1,sameGoal:false,separateMoment:false,textLocked:false,directFormulation:false,discomfortAllowsAbandonment:false},comparisonDone:false,autonomyPreserved:false,pressureIsData:false,obedienceNotSuccess:false,noConsentBypass:false,noAffectiveCommercialSexualAdvantage:false,noHighImpact:false,noClinicalPromise:false,noCovertCommand:false,prudenceRule:false,psalm:false,formula:false,transparentRewrite:false,refusalPreserved:false,layersSeparated:false,consciousReturn:false,personalNoConsentBypassRule:false,voluntary:false,finalSafety:false,safetyStop:false,safetyReason:'NONE'};
function keys(u:string){return{draft:`hnk.day058.${u}.draft.v2`,session:`hnk.day058.${u}.session.v2`}}
async function load<T>(k:string):Promise<T|null>{try{const v=await SecureStore.getItemAsync(k);return v?JSON.parse(v)as T:null}catch{return null}}
function cid(u:string){return`hnk-mobile-d058-v2-${u}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`}

export function Day058GoldenV2Mobile(){
  const auth=useHnkAuth();
  const live=Boolean(auth.configured&&auth.phase==='signed-in'&&auth.client&&auth.userId);
  const vault=useMemo(()=>auth.userId?createMobileVaultTextPort(auth.client??null):null,[auth.client,auth.userId]);
  const[session,setSession]=useState<Session|null>(null);
  const[d,setD]=useState<Draft>(empty);
  const[loaded,setLoaded]=useState(false);
  const[scriptText,setScriptText]=useState<[string,string,string]>(['','','']);
  const[controlText,setControlText]=useState('');
  const[error,setError]=useState<string|null>(null);
  const[busy,setBusy]=useState(false);
  const[complete,setComplete]=useState(false);

  useEffect(()=>{if(!auth.userId)return;const k=keys(auth.userId);void Promise.all([load<Draft>(k.draft),SecureStore.getItemAsync(k.session)]).then(async([draft,id])=>{setD(draft??empty);if(id&&auth.client){const s=await loadDay058PracticeSessionV2(auth.client,id).catch(()=>null);if(s)setSession(s);else await SecureStore.deleteItemAsync(k.session)}setLoaded(true)})},[auth.client,auth.userId]);
  useEffect(()=>{if(auth.userId&&loaded&&!complete)void SecureStore.setItemAsync(keys(auth.userId).draft,JSON.stringify(d))},[auth.userId,d,loaded,complete]);
  useEffect(()=>{const sub=AppState.addEventListener('change',state=>{if(state==='active')return;setScriptText(['','','']);setControlText('');setError('conteudo_privado_nao_cifrado_descartado')});return()=>sub.remove()},[]);

  function patch(p:Partial<Draft>){setD(x=>({...x,...p}))}
  function patchScript(index:number,p:Partial<ScriptDraft>){setD(x=>{const scripts=[...x.scripts] as [ScriptDraft,ScriptDraft,ScriptDraft];scripts[index]={...scripts[index],...p};return{...x,scripts}})}
  function patchControl(p:Partial<ControlDraft>){setD(x=>({...x,control:{...x.control,...p}}))}
  async function ensureSession(){if(session)return session;if(!live||!auth.client||!auth.userId)throw new Error('online_session_required_before_day058_practice');const s=await startDay058PracticeSessionV2(auth.client,{clientSessionId:cid(auth.userId),appVersion:'0.1.0-mobile-day058-v2'});setSession(s);await SecureStore.setItemAsync(keys(auth.userId).session,s.id);return s}
  async function saveScript(index:number){const text=scriptText[index];if(!text.trim())throw new Error(`script_${index+1}_text_required`);if(!vault||!auth.userId)throw new Error('vault_unavailable');await ensureSession();const e=await vault.saveText({userId:auth.userId,day:58,kind:'journal',plaintext:JSON.stringify({schema:'hnk-day058-self-script-v2',script_index:index+1,text:text.trim()})});patchScript(index,{ref:e.entryId});setScriptText(x=>{const y=[...x] as [string,string,string];y[index]='';return y})}
  async function saveControl(){if(!controlText.trim())throw new Error('direct_control_text_required');if(!vault||!auth.userId)throw new Error('vault_unavailable');await ensureSession();const e=await vault.saveText({userId:auth.userId,day:58,kind:'journal',plaintext:JSON.stringify({schema:'hnk-day058-direct-control-v2',selected_script_index:d.control.selectedScriptIndex,text:controlText.trim()})});patchControl({ref:e.entryId});setControlText('')}
  async function req(ref:string|null,n:string){if(!ref||!vault||!auth.userId)throw new Error(n);await vault.flushPending(auth.userId);const x=await vault.resolveEntryId(auth.userId,ref);if(!x)throw new Error(n);return x}
  function safetyStop(){if(d.safetyReason==='NONE'){setError('selecione_motivo_de_seguranca');return}patch({safetyStop:true,finalSafety:false});setScriptText(['','','']);setControlText('');setError('safety_stop_registrado')}

  async function seal(){if(!auth.client||!auth.userId)return;setBusy(true);setError(null);try{
    const s=await ensureSession();
    const refs=await Promise.all(d.scripts.map((x,n)=>req(x.ref,`script_${n+1}_vault_required`)));
    const controlRef=await req(d.control.ref,'direct_control_vault_required');
    if(new Set([...refs,controlRef].map(x=>x.toLowerCase())).size!==4)throw new Error('day058_four_distinct_vault_refs_required');
    const scriptInput=(n:0|1|2)=>{const x=d.scripts[n];return{vaultEntryRef:refs[n],relaxation:x.relaxation,clarity:x.clarity,pressure:x.pressure,autonomy:x.autonomy,twoBenignOptionsConfirmed:x.twoBenign,realRefusalOptionConfirmed:x.realRefusal,selfUseOnlyConfirmed:x.selfUseOnly,noClinicalPromiseConfirmed:x.noClinicalPromise,noCovertCommandConfirmed:x.noCovertCommand,choicePreservedConfirmed:x.choicePreserved}};
    const r=await sealDay058V2(auth.client,{evidence:{sessionId:s.id,scripts:[scriptInput(0),scriptInput(1),scriptInput(2)],directControl:{selectedScriptIndex:d.control.selectedScriptIndex,vaultEntryRef:controlRef,relaxation:d.control.relaxation,clarity:d.control.clarity,pressure:d.control.pressure,autonomy:d.control.autonomy,sameGoalConfirmed:d.control.sameGoal,separateMomentConfirmed:d.control.separateMoment,textLockedBeforeResultConfirmed:d.control.textLocked,directFormulationConfirmed:d.control.directFormulation,discomfortAllowsAbandonmentConfirmed:d.control.discomfortAllowsAbandonment},comparisonCompletedConfirmed:d.comparisonDone,autonomyPreservedConfirmed:d.autonomyPreserved,pressureAcceptedAsDataConfirmed:d.pressureIsData,obedienceNotSuccessMetricConfirmed:d.obedienceNotSuccess,consentBypassNotUsedConfirmed:d.noConsentBypass,affectiveCommercialSexualAdvantageNotUsedConfirmed:d.noAffectiveCommercialSexualAdvantage,highImpactNotUsedConfirmed:d.noHighImpact,clinicalPromiseNotUsedConfirmed:d.noClinicalPromise,covertCommandNotUsedConfirmed:d.noCovertCommand,prudenceRuleDefinedConfirmed:d.prudenceRule,psalm101Confirmed:d.psalm,heHeAlephConfirmed:d.formula,transparentRewriteCompletedConfirmed:d.transparentRewrite,refusalPreservedConfirmed:d.refusalPreserved,languageSensationInterpretationSeparatedConfirmed:d.layersSeparated,consciousReturnConfirmed:d.consciousReturn,personalNoConsentBypassRuleDefinedConfirmed:d.personalNoConsentBypassRule,voluntaryCompletionConfirmed:d.voluntary,finalSafetyClearConfirmed:d.finalSafety,safetyStopOccurred:d.safetyStop,safetyStopReason:d.safetyReason}});
    if(!r.ok)throw new Error(r.code);
    setComplete(true);const k=keys(auth.userId);await SecureStore.deleteItemAsync(k.draft);await SecureStore.deleteItemAsync(k.session);
  }catch(e){setError(e instanceof Error?e.message:'day058_completion_failed')}finally{setBusy(false)}}

  if(!auth.userId)return <View style={s.center}><Text style={s.text}>ENTRE NO ÁTRIO PARA INICIAR O DAY 058.</Text></View>;
  if(complete)return <View style={s.center}><Text style={s.title}>Day 058 concluído</Text><Text style={s.text}>Hahaiah II registrado. Próximo: Day 059.</Text></View>;
  const scriptReady=d.scripts.every(x=>Boolean(x.ref)&&x.twoBenign&&x.realRefusal&&x.selfUseOnly&&x.noClinicalPromise&&x.noCovertCommand&&x.choicePreserved);
  const controlReady=Boolean(d.control.ref)&&d.control.sameGoal&&d.control.separateMoment&&d.control.textLocked&&d.control.directFormulation&&d.control.discomfortAllowsAbandonment;
  const ready=scriptReady&&controlReady&&[d.comparisonDone,d.autonomyPreserved,d.pressureIsData,d.obedienceNotSuccess,d.noConsentBypass,d.noAffectiveCommercialSexualAdvantage,d.noHighImpact,d.noClinicalPromise,d.noCovertCommand,d.prudenceRule,d.psalm,d.formula,d.transparentRewrite,d.refusalPreserved,d.layersSeparated,d.consciousReturn,d.personalNoConsentBypassRule,d.voluntary,d.finalSafety].every(Boolean);

  return <ScrollView contentContainerStyle={s.shell}>
    <Text style={s.kicker}>CHOKMAH · HAHAIAH II · DAY 058</Text><Text style={s.title}>Linguagem de escolha — auto-uso</Text><Text style={s.text}>Os três roteiros e o controle direto existem em claro apenas na memória da tela até serem selados no Vault E2EE. Obediência não conta como sucesso.</Text>{error&&<Text style={s.error}>{error}</Text>}
    {d.scripts.map((x,n)=><ScriptCard key={n} index={n} data={x} text={scriptText[n]} setText={v=>setScriptText(a=>{const b=[...a] as [string,string,string];b[n]=v;return b})} patch={p=>patchScript(n,p)} save={()=>void saveScript(n).catch(e=>setError(e instanceof Error?e.message:String(e)))}/>) }
    <Card title="Controle direto"><Text style={s.text}>Roteiro selecionado: {d.control.selectedScriptIndex}</Text><View style={s.row}>{([1,2,3] as const).map(n=><Button key={n} label={String(n)} onPress={()=>patchControl({selectedScriptIndex:n})}/>)}</View><TextInput style={s.note} multiline value={controlText} onChangeText={setControlText} placeholder="Frase direta equivalente — memória volátil" placeholderTextColor="#777"/><Button label="Selar controle e limpar" disabled={Boolean(d.control.ref)} onPress={()=>void saveControl().catch(e=>setError(e instanceof Error?e.message:String(e)))}/><Check l="Mesmo objetivo" v={d.control.sameGoal} set={v=>patchControl({sameGoal:v})}/><Check l="Momento separado" v={d.control.separateMoment} set={v=>patchControl({separateMoment:v})}/><Check l="Texto travado antes do resultado" v={d.control.textLocked} set={v=>patchControl({textLocked:v})}/><Check l="Formulação direta" v={d.control.directFormulation} set={v=>patchControl({directFormulation:v})}/><Check l="Desconforto permite abandonar" v={d.control.discomfortAllowsAbandonment} set={v=>patchControl({discomfortAllowsAbandonment:v})}/><MetricEditor value={d.control} set={patchControl}/></Card>
    <Card title="Comparação e limites"><Check l="Comparação concluída" v={d.comparisonDone} set={v=>patch({comparisonDone:v})}/><Check l="Autonomia preservada" v={d.autonomyPreserved} set={v=>patch({autonomyPreserved:v})}/><Check l="Pressão é dado" v={d.pressureIsData} set={v=>patch({pressureIsData:v})}/><Check l="Obediência não é sucesso" v={d.obedienceNotSuccess} set={v=>patch({obedienceNotSuccess:v})}/><Check l="Sem bypass de consentimento" v={d.noConsentBypass} set={v=>patch({noConsentBypass:v})}/><Check l="Sem vantagem afetiva/comercial/sexual" v={d.noAffectiveCommercialSexualAdvantage} set={v=>patch({noAffectiveCommercialSexualAdvantage:v})}/><Check l="Sem uso de alto impacto" v={d.noHighImpact} set={v=>patch({noHighImpact:v})}/><Check l="Sem promessa clínica" v={d.noClinicalPromise} set={v=>patch({noClinicalPromise:v})}/><Check l="Sem comando encoberto" v={d.noCovertCommand} set={v=>patch({noCovertCommand:v})}/><Check l="Regra de prudência definida" v={d.prudenceRule} set={v=>patch({prudenceRule:v})}/></Card>
    <Card title="Coluna do Meio"><Check l="Salmo 10:1 confirmado" v={d.psalm} set={v=>patch({psalm:v})}/><Check l="HE–HE–ALEPH confirmado" v={d.formula} set={v=>patch({formula:v})}/><Check l="Reescrita transparente concluída" v={d.transparentRewrite} set={v=>patch({transparentRewrite:v})}/><Check l="Recusa preservada" v={d.refusalPreserved} set={v=>patch({refusalPreserved:v})}/><Check l="Linguagem/sensação/interpretação separadas" v={d.layersSeparated} set={v=>patch({layersSeparated:v})}/><Check l="Retorno consciente" v={d.consciousReturn} set={v=>patch({consciousReturn:v})}/><Check l="Regra pessoal de não contornar consentimento" v={d.personalNoConsentBypassRule} set={v=>patch({personalNoConsentBypassRule:v})}/></Card>
    <Card title="Fechamento"><Check l="Conclusão voluntária" v={d.voluntary} set={v=>patch({voluntary:v})}/><Check l="Estado final seguro e claro" v={d.finalSafety} set={v=>patch({finalSafety:v})}/><Text style={s.text}>Safety stop: {d.safetyReason}</Text><View style={s.row}>{(['NONE','PRESSURE_INCREASED','DISCOMFORT','AUTONOMY_CONCERN','OTHER'] as const).map(v=><Button key={v} label={v} onPress={()=>patch({safetyReason:v})}/>)}</View><Button label="Safety stop" onPress={safetyStop}/></Card>
    <Button label={busy?'Selando…':'Concluir Day 058'} disabled={!ready||busy} onPress={()=>void seal()}/>{!ready&&<Text style={s.muted}>Exige 3 roteiros + 1 controle no Vault, limites confirmados e retorno consciente.</Text>}
  </ScrollView>;
}

function Card({title,children}:{title:string;children:ReactNode}){return <View style={s.card}><Text style={s.cardTitle}>{title}</Text>{children}</View>}
function Button({label,onPress,disabled=false}:{label:string;onPress:()=>void;disabled?:boolean}){return <Pressable disabled={disabled} onPress={onPress} style={[s.button,disabled&&s.disabled]}><Text style={s.buttonText}>{label}</Text></Pressable>}
function Check({l,v,set}:{l:string;v:boolean;set:(v:boolean)=>void}){return <View style={s.check}><Switch value={v} onValueChange={set}/><Text style={s.checkText}>{l}</Text></View>}
function MetricEditor({value,set}:{value:Metrics;set:(p:Partial<Metrics>)=>void}){return <View>{(['relaxation','clarity','pressure','autonomy'] as const).map(k=><View key={k} style={s.metric}><Text style={s.text}>{k}: {value[k]}</Text><View style={s.row}><Button label="−" onPress={()=>set({[k]:Math.max(0,value[k]-1)})}/><Button label="+" onPress={()=>set({[k]:Math.min(10,value[k]+1)})}/></View></View>)}</View>}
function ScriptCard({index,data,text,setText,patch,save}:{index:number;data:ScriptDraft;text:string;setText:(v:string)=>void;patch:(p:Partial<ScriptDraft>)=>void;save:()=>void}){return <Card title={`Roteiro ${index+1} — auto-uso`}><TextInput style={s.note} multiline value={text} onChangeText={setText} placeholder="Texto privado — não persistido no draft" placeholderTextColor="#777"/><Button label="Selar roteiro e limpar" disabled={Boolean(data.ref)} onPress={save}/>{data.ref&&<Text style={s.muted}>Artefato privado selado.</Text>}<Check l="Duas opções benignas" v={data.twoBenign} set={v=>patch({twoBenign:v})}/><Check l="Recusa real" v={data.realRefusal} set={v=>patch({realRefusal:v})}/><Check l="Somente auto-uso" v={data.selfUseOnly} set={v=>patch({selfUseOnly:v})}/><Check l="Sem promessa clínica" v={data.noClinicalPromise} set={v=>patch({noClinicalPromise:v})}/><Check l="Sem comando encoberto" v={data.noCovertCommand} set={v=>patch({noCovertCommand:v})}/><Check l="Escolha preservada" v={data.choicePreserved} set={v=>patch({choicePreserved:v})}/><MetricEditor value={data} set={patch}/></Card>}
const s=StyleSheet.create({shell:{padding:20,paddingBottom:72,backgroundColor:'#0b0b0f'},center:{flex:1,justifyContent:'center',padding:24,backgroundColor:'#0b0b0f'},kicker:{color:'#b9a67d',letterSpacing:2,marginBottom:8},title:{fontSize:28,fontWeight:'800',color:'#f5f2ea',marginBottom:10},text:{color:'#e7e2d8',lineHeight:22},muted:{color:'#aaa',marginVertical:6},error:{color:'#ff9da8',marginVertical:10},card:{backgroundColor:'#121217',borderWidth:1,borderColor:'#34313f',borderRadius:18,padding:16,marginTop:14,gap:9},cardTitle:{fontSize:20,fontWeight:'800',color:'#f5f2ea'},button:{backgroundColor:'#d9b86c',borderRadius:10,paddingVertical:9,paddingHorizontal:11,marginVertical:3,alignSelf:'flex-start'},disabled:{opacity:.38},buttonText:{color:'#17120a',fontWeight:'800'},check:{flexDirection:'row',alignItems:'center',gap:9,marginVertical:2},checkText:{color:'#e7e2d8',flex:1},row:{flexDirection:'row',flexWrap:'wrap',gap:6},note:{borderWidth:1,borderColor:'#423d49',borderRadius:10,padding:10,color:'#f5f2ea',minHeight:82,textAlignVertical:'top'},metric:{borderTopWidth:1,borderTopColor:'#292630',paddingTop:7,marginTop:7}});
