import { useEffect, useState } from 'react';
import { ScrollView, StyleSheet, Text, View } from 'react-native';
import { loadCanonicalDay, type CanonicalDaySnapshot } from '../kether/canonical-day';
import { CanonicalText, RuntimeCard, RuntimeChoice, RuntimeCompletion, RuntimeCounter, RuntimeNotice, RuntimeOpenTimer, RuntimePrimary, RuntimeScale, runtimeTextStyles } from '../kether/KetherRuntimePrimitives';
import { useHnkDayRuntime } from '../kether/useHnkDayRuntime';
import { TetragrammatonMasterV1, TETRAGRAMMATON_MASTER_ID, TETRAGRAMMATON_MASTER_SHA256 } from './TetragrammatonMasterV1';
import { MEBAHEL_DAY_070 } from './runtime-definitions/mebahel';

export function MebahelDay070TetragrammatonExperience(){
 const controller=useHnkDayRuntime(MEBAHEL_DAY_070); const [canon,setCanon]=useState<CanonicalDaySnapshot|null>(null); const [error,setError]=useState<string|null>(null); const [a,setA]=useState(0),[b,setB]=useState(0);
 const [master,setMaster]=useState(false),[upright,setUpright]=useState(false),[back,setBack]=useState(false),[chest,setChest]=useState(false),[crown,setCrown]=useState(false),[control,setControl]=useState(false),[comparison,setComparison]=useState(false),[invul,setInvul]=useState(false),[realSafety,setRealSafety]=useState(false),[riskNamed,setRiskNamed]=useState(false),[orientation,setOrientation]=useState(false),[safe,setSafe]=useState(false),[limitA,setLimitA]=useState(5),[limitB,setLimitB]=useState(5),[objects,setObjects]=useState(0);
 useEffect(()=>{let x=true;if(!controller.auth.client||controller.auth.phase!=='signed-in')return()=>{x=false;};void loadCanonicalDay(controller.auth.client,70).then(v=>{if(x)setCanon(v);}).catch(e=>{if(x)setError(e instanceof Error?e.message:'canonical_day_load_failed');});return()=>{x=false;};},[controller.auth.client,controller.auth.phase]);
 if(controller.loading)return <View style={s.loading}><Text style={s.meta}>ABRINDO MEBAHEL · DIA 070</Text></View>; const phase=controller.phase?.id; const stop=()=>controller.interrupt({durationSeconds:a+b,evidence:{safety_stop:true},metrics:{limit_active:limitA,limit_control:limitB}});
 return <ScrollView style={s.screen} contentContainerStyle={s.content}><View style={s.header}><Text style={s.eyebrow}>CHOKMAH · MEBAHEL 4/5 · DIA 070</Text><Text style={s.title}>{canon?.title??'CÂNONE SINCRONIZANDO'}</Text><Text style={s.meta}>{canon?`${canon.sourcePath} · ${canon.sourceSha.slice(0,10)}`:'SEM FALLBACK EDITORIAL'}</Text></View>
 {controller.error||error?<RuntimeNotice title="RUNTIME">{error??controller.error}</RuntimeNotice>:null}{controller.runtime?.status==='locked'?<RuntimeCard label="GATE" title="Dia 070 bloqueado pela sequência"><Text style={runtimeTextStyles.body}>A primeira conclusão exige o Dia 069 confirmado no servidor.</Text></RuntimeCard>:null}
 {phase==='threshold'?<RuntimeCard label="MEBAHEL 4/5" title="Pantáculo HNK V1 · ereto · não espelhado"><CanonicalText>{canon?.blocks['jachin-kavanah']??''}</CanonicalText><TetragrammatonMasterV1/><RuntimeNotice title="MASTER">{TETRAGRAMMATON_MASTER_ID} · SHA-256 {TETRAGRAMMATON_MASTER_SHA256.slice(0,16)}…</RuntimeNotice><RuntimeChoice selected={master} label="CONFIRMEI O MASTER CANÔNICO" onPress={()=>setMaster(v=>!v)}/><RuntimeChoice selected={upright} label="ORIENTAÇÃO ERETA · SEM ESPELHAMENTO" onPress={()=>setUpright(v=>!v)}/><RuntimePrimary label="INICIAR" disabled={!canon||!master||!upright||controller.busy} onPress={()=>void controller.begin().then(controller.nextPhase)}/></RuntimeCard>:null}
 {phase==='active'?<RuntimeCard label="CONDIÇÃO A" title="Costas → peito → acima da Coroa"><TetragrammatonMasterV1/><RuntimeOpenTimer value={a} onChange={setA}/><RuntimeChoice selected={back} label="VISUALIZEI ATRÁS DAS COSTAS" onPress={()=>setBack(v=>!v)}/><RuntimeChoice selected={chest} label="VISUALIZEI NO PEITO" onPress={()=>setChest(v=>!v)}/><RuntimeChoice selected={crown} label="VISUALIZEI ACIMA DA COROA" onPress={()=>setCrown(v=>!v)}/><RuntimeScale label="SENSAÇÃO DE LIMITE" value={limitA} onChange={setLimitA}/><RuntimePrimary label="SAFETY STOP" onPress={stop}/><RuntimePrimary label="CONTROLE" disabled={a<1||!back||!chest||!crown} onPress={controller.nextPhase}/></RuntimeCard>:null}
 {phase==='control'?<RuntimeCard label="CONTROLE" title="Três formas azuis neutras nas mesmas posições"><CanonicalText>{canon?.blocks['boaz-kavanah']??''}</CanonicalText><RuntimeOpenTimer value={b} onChange={setB}/><RuntimeScale label="SENSAÇÃO DE LIMITE" value={limitB} onChange={setLimitB}/><RuntimeChoice selected={control} label="CONCLUÍ AS TRÊS POSIÇÕES SEM PANTÁCULO/FÓRMULA" onPress={()=>setControl(v=>!v)}/><RuntimePrimary label="COMPARAR" disabled={b<1||!control} onPress={controller.nextPhase}/></RuntimeCard>:null}
 {phase==='compare'?<RuntimeCard label="REVISÃO" title="Proteção ritual não substitui prudência concreta"><RuntimeChoice selected={comparison} label="COMPAREI LIMITE, CALMA, FOCO, EXPECTATIVA E RETORNO" onPress={()=>setComparison(v=>!v)}/><RuntimeChoice selected={invul} label="NÃO TRATEI O RITO COMO INVULNERABILIDADE OU BARREIRA FÍSICA" onPress={()=>setInvul(v=>!v)}/><RuntimeChoice selected={realSafety} label="MEDIDAS REAIS DE SEGURANÇA, CUIDADO E RESPONSABILIDADE CONTINUAM VÁLIDAS" onPress={()=>setRealSafety(v=>!v)}/><RuntimeChoice selected={riskNamed} label="NOMEEI AO MENOS UM RISCO CONCRETO QUE AINDA EXIGE PRUDÊNCIA" onPress={()=>setRiskNamed(v=>!v)}/><RuntimeChoice selected={safe} label="SEM GRANDIOSIDADE, INVULNERABILIDADE OU COMPULSÃO AO FINAL" onPress={()=>setSafe(v=>!v)}/><RuntimePrimary label="GROUNDING" disabled={!comparison||!invul||!realSafety||!riskNamed||!safe} onPress={controller.nextPhase}/></RuntimeCard>:null}
 {phase==='grounding'?<RuntimeCard label="GROUNDING" title="Fechar as imagens e retornar"><RuntimeCounter label="OBJETOS REAIS NOMEADOS" value={objects} onPress={()=>setObjects(v=>Math.min(5,v+1))}/><RuntimeChoice selected={orientation} label="LOCALIZAÇÃO E ORIENTAÇÃO RESTAURADAS" onPress={()=>setOrientation(v=>!v)}/><RuntimePrimary label="RETORNO CONFIRMADO" disabled={objects<5||!orientation} onPress={()=>{controller.setReturnConfirmed();controller.nextPhase();}}/></RuntimeCard>:null}
 {phase==='seal'?<RuntimeCard label="SELO SERVER-SIDE" title="Mebahel 4/5"><RuntimePrimary label={controller.busy?'SELANDO…':'SELAR DIA 070'} disabled={controller.busy} onPress={()=>void controller.seal({durationSeconds:a+b,evidence:{protocol_completed:true,return_confirmed:true,master_verified:master,upright_not_mirrored:upright,three_positions_completed:back&&chest&&crown,control_completed:control,comparison_completed:comparison,invulnerability_not_claimed:invul,real_safety_preserved:realSafety,risk_measure_named:riskNamed,orientation_restored:orientation,safety_clear:safe,tetragrammaton_master_id:TETRAGRAMMATON_MASTER_ID,active_seconds:a,control_seconds:b},metrics:{limit_active:limitA,limit_control:limitB}}).then(controller.nextPhase).catch(e=>setError(e instanceof Error?e.message:'day070_seal_failed'))}/></RuntimeCard>:null}
 {phase==='complete'?<RuntimeCompletion completion={controller.runtime?.serverCompletion} label="MEBAHEL 4/5"/>:null}</ScrollView>;
}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:'#02050a'},content:{padding:24,gap:18,paddingBottom:52},loading:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:'#02050a'},header:{gap:6},eyebrow:{color:'#6f96ba',fontSize:8,letterSpacing:1.5},title:{color:'#e8f4ff',fontSize:25,lineHeight:31,fontWeight:'300'},meta:{color:'#637e94',fontSize:8,letterSpacing:0.8}});
