import { useEffect, useState } from 'react';
import { ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { saveEncryptedVaultEntry } from '@hnk/supabase-client';
import { encryptVaultText } from '../vault/vault-crypto';
import { loadCanonicalDay, type CanonicalDaySnapshot } from '../kether/canonical-day';
import { CanonicalText, RuntimeCard, RuntimeChoice, RuntimeCompletion, RuntimeCounter, RuntimeNotice, RuntimePrimary, RuntimeScale, runtimeTextStyles } from '../kether/KetherRuntimePrimitives';
import { useHnkDayRuntime } from '../kether/useHnkDayRuntime';
import { usePersistentWallClock } from './usePersistentWallClock';
import { MEBAHEL_DAY_068 } from './runtime-definitions/mebahel';

const CAP_SECONDS = 12 * 60 * 60;
const format = (s:number) => `${String(Math.floor(s/3600)).padStart(2,'0')}:${String(Math.floor((s%3600)/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;

export function MebahelDay068DigitalFastExperience() {
  const controller=useHnkDayRuntime(MEBAHEL_DAY_068); const [canon,setCanon]=useState<CanonicalDaySnapshot|null>(null); const [error,setError]=useState<string|null>(null);
  const fast=usePersistentWallClock('hnk-mebahel-day068-fast-v1',CAP_SECONDS); const control=usePersistentWallClock('hnk-mebahel-day068-control-v1',CAP_SECONDS);
  const [sources,setSources]=useState(['','','']); const [critical,setCritical]=useState(false); const [family,setFamily]=useState(false); const [work,setWork]=useState(false); const [auth,setAuth]=useState(false); const [earlyExit,setEarlyExit]=useState(false);
  const [fastDone,setFastDone]=useState(false); const [controlDone,setControlDone]=useState(false); const [fastChecks,setFastChecks]=useState(0); const [controlChecks,setControlChecks]=useState(0); const [focusFast,setFocusFast]=useState(5); const [focusControl,setFocusControl]=useState(5); const [anxietyFast,setAnxietyFast]=useState(5); const [anxietyControl,setAnxietyControl]=useState(5);
  const [comparison,setComparison]=useState(false); const [responsibilities,setResponsibilities]=useState(false); const [egregoreNotLiteral,setEgregoreNotLiteral]=useState(false); const [safetyClear,setSafetyClear]=useState(false); const [rule,setRule]=useState(''); const [vaultSaved,setVaultSaved]=useState(false); const [checksum,setChecksum]=useState<string|null>(null); const [objects,setObjects]=useState(0);
  useEffect(()=>{let a=true;if(!controller.auth.client||controller.auth.phase!=='signed-in')return()=>{a=false;};void loadCanonicalDay(controller.auth.client,68).then(v=>{if(a)setCanon(v);}).catch(e=>{if(a)setError(e instanceof Error?e.message:'canonical_day_load_failed');});return()=>{a=false;};},[controller.auth.client,controller.auth.phase]);
  if(controller.loading)return <View style={styles.loading}><Text style={styles.meta}>ABRINDO MEBAHEL · DIA 068</Text></View>;
  const phase=controller.phase?.id; const sourcesReady=sources.every(v=>v.trim().length>=2); const exceptionsReady=critical&&family&&work&&auth;
  const saveVault=async()=>{if(!controller.auth.client||!controller.auth.userId||!sourcesReady||rule.trim().length<4)return;try{const enc=await encryptVaultText({userId:controller.auth.userId,day:68,kind:'digital-fast-policy',plaintext:JSON.stringify({schema:'hnk-day068-policy-v1',sources:sources.map(v=>v.trim()),sustainable_rule:rule.trim()})});await saveEncryptedVaultEntry(controller.auth.client,{day:68,payload:enc});setChecksum(enc.checksumSha256);setVaultSaved(true);controller.nextPhase();}catch(e){setError(e instanceof Error?e.message:'day068_vault_failed');}};
  const stop=()=>controller.interrupt({durationSeconds:fast.elapsedSeconds+control.elapsedSeconds,evidence:{safety_stop:true},metrics:{focus_fast:focusFast,focus_control:focusControl}});
  return <ScrollView style={styles.screen} contentContainerStyle={styles.content}>
    <View style={styles.header}><Text style={styles.eyebrow}>CHOKMAH · MEBAHEL 2/5 · DIA 068</Text><Text style={styles.title}>{canon?.title??'CÂNONE SINCRONIZANDO'}</Text><Text style={styles.meta}>{canon?`${canon.sourcePath} · ${canon.sourceSha.slice(0,10)}`:'SEM FALLBACK EDITORIAL'}</Text></View>
    {controller.error||error?<RuntimeNotice title="RUNTIME">{error??controller.error}</RuntimeNotice>:null}
    {controller.runtime?.status==='locked'?<RuntimeCard label="GATE" title="Dia 068 bloqueado pela sequência"><Text style={runtimeTextStyles.body}>A primeira conclusão exige o Dia 067 confirmado no servidor.</Text></RuntimeCard>:null}
    {phase==='threshold'?<RuntimeCard label="MEBAHEL 2/5" title="Jejum digital como experimento temporário"><CanonicalText>{canon?.blocks['jachin-kavanah']??''}</CanonicalText><RuntimeNotice title="ATÉ 12 HORAS">Doze horas é teto, não meta. Encerre antes quando trabalho, família, segurança, autenticação ou emergência exigirem conectividade.</RuntimeNotice><RuntimePrimary label="PLANEJAR" disabled={!canon||controller.busy} onPress={()=>void controller.begin().then(controller.nextPhase)}/></RuntimeCard>:null}
    {phase==='plan'?<RuntimeCard label="PLANO" title="Três fontes de ruído + exceções essenciais">{sources.map((v,i)=><TextInput key={i} value={v} onChangeText={x=>setSources(s=>s.map((q,j)=>j===i?x:q))} placeholder={`Fonte ${i+1} · ficará no Vault`} placeholderTextColor="#666971" style={runtimeTextStyles.input}/>)}<RuntimeChoice selected={critical} label="PRESERVAREI ALERTAS CRÍTICOS/EMERGÊNCIA" onPress={()=>setCritical(v=>!v)}/><RuntimeChoice selected={auth} label="PRESERVAREI AUTENTICAÇÃO/SEGURANÇA" onPress={()=>setAuth(v=>!v)}/><RuntimeChoice selected={family} label="PRESERVAREI CONTATOS E CUIDADO FAMILIAR" onPress={()=>setFamily(v=>!v)}/><RuntimeChoice selected={work} label="PRESERVAREI TRABALHO INDISPENSÁVEL" onPress={()=>setWork(v=>!v)}/><RuntimeChoice selected={earlyExit} label="ACEITO ENCERRAR A JANELA ANTES DA META QUANDO RESPONSABILIDADES REAIS EXIGIREM" onPress={()=>setEarlyExit(v=>!v)}/><RuntimePrimary label="INICIAR JANELA PROTEGIDA" disabled={!sourcesReady||!exceptionsReady||!earlyExit||fast.loading||fast.startedAt!==null} onPress={()=>void fast.start().then(controller.nextPhase)}/></RuntimeCard>:null}
    {phase==='fast'?<RuntimeCard label="JANELA PROTEGIDA" title="Sem as três fontes escolhidas"><Text style={styles.clock}>{format(fast.elapsedSeconds)}</Text><Text style={styles.clockSub}>TETO · 12:00:00 · pode encerrar antes</Text><RuntimeCounter label="IMPULSOS/CHECAGENS REGISTRADOS" value={fastChecks} onPress={()=>setFastChecks(v=>v+1)}/><RuntimeScale label="FOCO" value={focusFast} onChange={setFocusFast}/><RuntimeScale label="ANSIEDADE" value={anxietyFast} onChange={setAnxietyFast}/><RuntimePrimary label="ENCERRAR JANELA AGORA" disabled={fast.elapsedSeconds<1||fastDone} onPress={()=>void fast.finish().then(()=>{setFastDone(true);controller.nextPhase();})}/><RuntimePrimary label="SAFETY STOP" onPress={stop}/></RuntimeCard>:null}
    {phase==='control'?<RuntimeCard label="CONTROLE" title="Janela habitual comparável"><CanonicalText>{canon?.blocks['boaz-kavanah']??''}</CanonicalText>{control.startedAt===null&&!controlDone?<RuntimePrimary label="INICIAR JANELA HABITUAL" disabled={control.loading} onPress={()=>void control.start()}/>:null}<Text style={styles.clock}>{format(control.elapsedSeconds)}</Text><RuntimeCounter label="CHECAGENS/IMPULSOS" value={controlChecks} onPress={()=>setControlChecks(v=>v+1)}/><RuntimeScale label="FOCO" value={focusControl} onChange={setFocusControl}/><RuntimeScale label="ANSIEDADE" value={anxietyControl} onChange={setAnxietyControl}/><RuntimePrimary label="ENCERRAR CONTROLE E COMPARAR" disabled={control.elapsedSeconds<1||controlDone} onPress={()=>void control.finish().then(()=>{setControlDone(true);controller.nextPhase();})}/></RuntimeCard>:null}
    {phase==='compare'?<RuntimeCard label="REVISÃO" title="Ruído digital não é entidade medida"><RuntimeChoice selected={comparison} label="COMPAREI JEJUM E JANELA HABITUAL SEM EXIGIR MELHORA" onPress={()=>setComparison(v=>!v)}/><RuntimeChoice selected={responsibilities} label="RESPONSABILIDADES, INFORMAÇÃO ÚTIL E CONTATOS REAIS FORAM PRESERVADOS" onPress={()=>setResponsibilities(v=>!v)}/><RuntimeChoice selected={egregoreNotLiteral} label="NÃO TRATEI TODO DESCONFORTO COMO EGREGOR EXTERNO" onPress={()=>setEgregoreNotLiteral(v=>!v)}/><RuntimeChoice selected={safetyClear} label="A JANELA NÃO PREJUDICOU SEGURANÇA OU CUIDADO" onPress={()=>setSafetyClear(v=>!v)}/><TextInput value={rule} onChangeText={setRule} placeholder="Regra digital sustentável por sete dias · Vault" placeholderTextColor="#666971" style={runtimeTextStyles.textArea}/><RuntimePrimary label="GROUNDING" disabled={!comparison||!responsibilities||!egregoreNotLiteral||!safetyClear||rule.trim().length<4} onPress={controller.nextPhase}/></RuntimeCard>:null}
    {phase==='grounding'?<RuntimeCard label="GROUNDING" title="Retornar deliberadamente à conectividade"><RuntimeCounter label="OBJETOS REAIS NOMEADOS" value={objects} onPress={()=>setObjects(v=>Math.min(3,v+1))}/><RuntimePrimary label="RETORNO CONFIRMADO" disabled={objects<3} onPress={()=>{controller.setReturnConfirmed();controller.nextPhase();}}/></RuntimeCard>:null}
    {phase==='vault'?<RuntimeCard label="VAULT" title="Fontes e política ficam privadas"><RuntimePrimary label={vaultSaved?'VAULT SALVO':'CIFRAR E SALVAR POLÍTICA'} disabled={vaultSaved||rule.trim().length<4} onPress={()=>void saveVault()}/></RuntimeCard>:null}
    {phase==='seal'?<RuntimeCard label="SELO SERVER-SIDE" title="Mebahel 2/5"><RuntimePrimary label={controller.busy?'SELANDO…':'SELAR DIA 068'} disabled={controller.busy||!vaultSaved||!checksum||!fastDone||!controlDone} onPress={()=>void controller.seal({localRecordHash:checksum??undefined,durationSeconds:fast.elapsedSeconds+control.elapsedSeconds,evidence:{protocol_completed:true,return_confirmed:true,three_sources_identified:true,essential_exceptions_defined:exceptionsReady,fast_completed:fastDone,control_completed:controlDone,comparison_completed:comparison,early_exit_allowed:earlyExit,critical_alerts_preserved:critical,responsibilities_preserved:responsibilities,egregore_not_literalized:egregoreNotLiteral,sustainable_rule_defined:rule.trim().length>=4,vault_saved:vaultSaved,safety_clear:safetyClear,sources_count:3,fast_seconds:fast.elapsedSeconds,control_seconds:control.elapsedSeconds},metrics:{fast_checks:fastChecks,control_checks:controlChecks,focus_fast:focusFast,focus_control:focusControl,anxiety_fast:anxietyFast,anxiety_control:anxietyControl}}).then(controller.nextPhase).catch(e=>setError(e instanceof Error?e.message:'day068_seal_failed'))}/></RuntimeCard>:null}
    {phase==='complete'?<RuntimeCompletion completion={controller.runtime?.serverCompletion} label="MEBAHEL 2/5"/>:null}
  </ScrollView>;
}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:'#02050a'},content:{padding:24,gap:18,paddingBottom:52},loading:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:'#02050a'},header:{gap:6},eyebrow:{color:'#6f96ba',fontSize:8,letterSpacing:1.5},title:{color:'#e8f4ff',fontSize:25,lineHeight:31,fontWeight:'300'},meta:{color:'#637e94',fontSize:8,letterSpacing:0.8},clock:{color:'#f3df98',fontSize:34,fontVariant:['tabular-nums']},clockSub:{color:'#6f684f',fontSize:9,letterSpacing:1}});
