import { useEffect, useState } from 'react';
import { ScrollView, StyleSheet, Text, View } from 'react-native';
import { loadCanonicalDay, type CanonicalDaySnapshot } from '../kether/canonical-day';
import { CanonicalText, RuntimeCard, RuntimeChoice, RuntimeCompletion, RuntimeCounter, RuntimeNotice, RuntimeOpenTimer, RuntimePrimary, RuntimeScale, runtimeTextStyles } from '../kether/KetherRuntimePrimitives';
import { useHnkDayRuntime } from '../kether/useHnkDayRuntime';
import { MEBAHEL_DAY_069 } from './runtime-definitions/mebahel';

export function MebahelDay069EyeMovementExperience(){
 const controller=useHnkDayRuntime(MEBAHEL_DAY_069); const [canon,setCanon]=useState<CanonicalDaySnapshot|null>(null); const [error,setError]=useState<string|null>(null);
 const [activeSeconds,setActiveSeconds]=useState(0),[controlSeconds,setControlSeconds]=useState(0),[reps,setReps]=useState(0); const [focusA,setFocusA]=useState(5),[focusB,setFocusB]=useState(5),[comfort,setComfort]=useState(5);
 const [activeDone,setActiveDone]=useState(false),[controlDone,setControlDone]=useState(false),[comparison,setComparison]=useState(false),[noForce,setNoForce]=useState(false),[noSpeed,setNoSpeed]=useState(false),[brainClaim,setBrainClaim]=useState(false),[therapyClaim,setTherapyClaim]=useState(false),[guidance,setGuidance]=useState(false),[orientation,setOrientation]=useState(false),[safety,setSafety]=useState(false),[objects,setObjects]=useState(0);
 useEffect(()=>{let a=true;if(!controller.auth.client||controller.auth.phase!=='signed-in')return()=>{a=false;};void loadCanonicalDay(controller.auth.client,69).then(v=>{if(a)setCanon(v);}).catch(e=>{if(a)setError(e instanceof Error?e.message:'canonical_day_load_failed');});return()=>{a=false;};},[controller.auth.client,controller.auth.phase]);
 if(controller.loading)return <View style={s.loading}><Text style={s.meta}>ABRINDO MEBAHEL · DIA 069</Text></View>; const phase=controller.phase?.id; const stop=()=>controller.interrupt({durationSeconds:activeSeconds+controlSeconds,evidence:{safety_stop:true},metrics:{focus_active:focusA,focus_control:focusB,comfort}});
 return <ScrollView style={s.screen} contentContainerStyle={s.content}><View style={s.header}><Text style={s.eyebrow}>CHOKMAH · MEBAHEL 3/5 · DIA 069</Text><Text style={s.title}>{canon?.title??'CÂNONE SINCRONIZANDO'}</Text><Text style={s.meta}>{canon?`${canon.sourcePath} · ${canon.sourceSha.slice(0,10)}`:'SEM FALLBACK EDITORIAL'}</Text></View>
 {controller.error||error?<RuntimeNotice title="RUNTIME">{error??controller.error}</RuntimeNotice>:null}
 {controller.runtime?.status==='locked'?<RuntimeCard label="GATE" title="Dia 069 bloqueado pela sequência"><Text style={runtimeTextStyles.body}>A primeira conclusão exige o Dia 068 confirmado no servidor.</Text></RuntimeCard>:null}
 {phase==='threshold'?<RuntimeCard label="MEBAHEL 3/5" title="Movimento ocular como prática atencional, não neurodiagnóstico"><CanonicalText>{canon?.blocks['jachin-kavanah']??''}</CanonicalText><RuntimeNotice title="STOP GATE">Dor, visão turva, náusea, vertigem, nistagmo desconfortável ou cefaleia encerram imediatamente. Condição ocular, vestibular ou neurológica relevante exige orientação apropriada antes do experimento.</RuntimeNotice><RuntimeChoice selected={guidance} label="RESPEITEI A NECESSIDADE DE ORIENTAÇÃO APROPRIADA SE HOUVER CONDIÇÃO RELEVANTE" onPress={()=>setGuidance(v=>!v)}/><RuntimePrimary label="INICIAR" disabled={!canon||!guidance||controller.busy} onPress={()=>void controller.begin().then(controller.nextPhase)}/></RuntimeCard>:null}
 {phase==='active'?<RuntimeCard label="CONDIÇÃO A" title="Movimentos laterais lentos em amplitude confortável"><RuntimeOpenTimer value={activeSeconds} onChange={setActiveSeconds}/><RuntimeCounter label="REPETIÇÕES CONFORTÁVEIS" value={reps} onPress={()=>setReps(v=>v+1)}/><RuntimeScale label="FOCO" value={focusA} onChange={setFocusA}/><RuntimeScale label="CONFORTO OCULAR" value={comfort} onChange={setComfort}/><RuntimeChoice selected={noForce} label="NÃO FORCEI EXTREMOS NEM BUSQUEI COMPLETAR 30 REPETIÇÕES" onPress={()=>setNoForce(v=>!v)}/><RuntimeChoice selected={noSpeed} label="NÃO USEI VELOCIDADE EXTREMA" onPress={()=>setNoSpeed(v=>!v)}/><RuntimeChoice selected={activeDone} label="ENCERREI ABAIXO DO LIMITE DE FADIGA" onPress={()=>setActiveDone(v=>!v)}/><RuntimePrimary label="SAFETY STOP" onPress={stop}/><RuntimePrimary label="CONTROLE" disabled={activeSeconds<1||reps<1||!noForce||!noSpeed||!activeDone} onPress={controller.nextPhase}/></RuntimeCard>:null}
 {phase==='control'?<RuntimeCard label="CONTROLE" title="Olhar em ponto central estável"><CanonicalText>{canon?.blocks['boaz-kavanah']??''}</CanonicalText><RuntimeOpenTimer value={controlSeconds} onChange={setControlSeconds}/><RuntimeScale label="FOCO" value={focusB} onChange={setFocusB}/><RuntimeChoice selected={controlDone} label="CONCLUÍ O CONTROLE SEM FORÇAR A VISÃO" onPress={()=>setControlDone(v=>!v)}/><RuntimePrimary label="COMPARAR" disabled={controlSeconds<1||!controlDone} onPress={controller.nextPhase}/></RuntimeCard>:null}
 {phase==='compare'?<RuntimeCard label="REVISÃO" title="Sensação não mede hemisférios ou ondas cerebrais"><RuntimeChoice selected={comparison} label="COMPAREI FOCO, CONFORTO E SINTOMAS" onPress={()=>setComparison(v=>!v)}/><RuntimeChoice selected={brainClaim} label="NÃO AFIRMEI INTEGRAÇÃO HEMISFÉRICA OU ONDAS CEREBRAIS COMO FATO MEDIDO" onPress={()=>setBrainClaim(v=>!v)}/><RuntimeChoice selected={therapyClaim} label="NÃO TRATEI O EXERCÍCIO COMO SUBSTITUTO DE TERAPIA BASEADA EM MOVIMENTO OCULAR" onPress={()=>setTherapyClaim(v=>!v)}/><RuntimeChoice selected={safety} label="SEM SINTOMA DE STOP GATE AO FINAL" onPress={()=>setSafety(v=>!v)}/><RuntimePrimary label="GROUNDING" disabled={!comparison||!brainClaim||!therapyClaim||!safety} onPress={controller.nextPhase}/></RuntimeCard>:null}
 {phase==='grounding'?<RuntimeCard label="GROUNDING" title="Descansar a visão e confirmar orientação"><RuntimeCounter label="OBJETOS EM DISTÂNCIAS DIFERENTES" value={objects} onPress={()=>setObjects(v=>Math.min(3,v+1))}/><RuntimeChoice selected={orientation} label="SEM TONTURA E COM ORIENTAÇÃO RESTAURADA" onPress={()=>setOrientation(v=>!v)}/><RuntimePrimary label="RETORNO CONFIRMADO" disabled={objects<3||!orientation} onPress={()=>{controller.setReturnConfirmed();controller.nextPhase();}}/></RuntimeCard>:null}
 {phase==='seal'?<RuntimeCard label="SELO SERVER-SIDE" title="Mebahel 3/5"><RuntimePrimary label={controller.busy?'SELANDO…':'SELAR DIA 069'} disabled={controller.busy} onPress={()=>void controller.seal({durationSeconds:activeSeconds+controlSeconds,evidence:{protocol_completed:true,return_confirmed:true,active_completed:activeDone,control_completed:controlDone,comparison_completed:comparison,no_forced_repetition:noForce,no_extreme_speed:noSpeed,brainwave_claim_not_made:brainClaim,therapy_substitute_not_claimed:therapyClaim,relevant_condition_guidance_respected:guidance,orientation_restored:orientation,safety_clear:safety,repetitions_completed:reps,active_seconds:activeSeconds,control_seconds:controlSeconds},metrics:{focus_active:focusA,focus_control:focusB,comfort}}).then(controller.nextPhase).catch(e=>setError(e instanceof Error?e.message:'day069_seal_failed'))}/></RuntimeCard>:null}
 {phase==='complete'?<RuntimeCompletion completion={controller.runtime?.serverCompletion} label="MEBAHEL 3/5"/>:null}</ScrollView>;
}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:'#02050a'},content:{padding:24,gap:18,paddingBottom:52},loading:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:'#02050a'},header:{gap:6},eyebrow:{color:'#6f96ba',fontSize:8,letterSpacing:1.5},title:{color:'#e8f4ff',fontSize:25,lineHeight:31,fontWeight:'300'},meta:{color:'#637e94',fontSize:8,letterSpacing:0.8}});
