import { useEffect, useState } from 'react';
import { ScrollView, StyleSheet, Text, View } from 'react-native';
import { loadCanonicalDay, type CanonicalDaySnapshot } from '../kether/canonical-day';
import { CanonicalText, RuntimeCard, RuntimeChoice, RuntimeCompletion, RuntimeCounter, RuntimeNotice, RuntimeOpenTimer, RuntimePrimary, RuntimeScale, runtimeTextStyles } from '../kether/KetherRuntimePrimitives';
import { useHnkDayRuntime } from '../kether/useHnkDayRuntime';
import { MEBAHEL_DAY_067 } from './runtime-definitions/mebahel';

export function MebahelDay067SpatialAnchorExperience() {
  const controller = useHnkDayRuntime(MEBAHEL_DAY_067);
  const [canon,setCanon]=useState<CanonicalDaySnapshot|null>(null); const [error,setError]=useState<string|null>(null);
  const [firstSeconds,setFirstSeconds]=useState(0); const [returnSeconds,setReturnSeconds]=useState(0); const [controlSeconds,setControlSeconds]=useState(0);
  const [firstDone,setFirstDone]=useState(false); const [returnDone,setReturnDone]=useState(false); const [controlDone,setControlDone]=useState(false); const [cancelDone,setCancelDone]=useState(false);
  const [activeEffect,setActiveEffect]=useState(false); const [activeRecorded,setActiveRecorded]=useState(false); const [controlEffect,setControlEffect]=useState(false); const [controlRecorded,setControlRecorded]=useState(false);
  const [focusActive,setFocusActive]=useState(5); const [focusControl,setFocusControl]=useState(5); const [comparison,setComparison]=useState(false);
  const [objectivePowerNotClaimed,setObjectivePowerNotClaimed]=useState(false); const [riskMovementAvoided,setRiskMovementAvoided]=useState(false); const [orientationPreserved,setOrientationPreserved]=useState(false); const [safetyClear,setSafetyClear]=useState(false); const [objectsNamed,setObjectsNamed]=useState(0);
  useEffect(()=>{let active=true;if(!controller.auth.client||controller.auth.phase!=='signed-in')return()=>{active=false;};void loadCanonicalDay(controller.auth.client,67).then(v=>{if(active)setCanon(v);}).catch(e=>{if(active)setError(e instanceof Error?e.message:'canonical_day_load_failed');});return()=>{active=false;};},[controller.auth.client,controller.auth.phase]);
  if(controller.loading)return <View style={styles.loading}><Text style={styles.meta}>ABRINDO MEBAHEL · DIA 067</Text></View>;
  const phase=controller.phase?.id; const activeSeconds=firstSeconds+returnSeconds; const stop=()=>controller.interrupt({durationSeconds:activeSeconds+controlSeconds,evidence:{safety_stop:true},metrics:{focus_active:focusActive,focus_control:focusControl}});
  return <ScrollView style={styles.screen} contentContainerStyle={styles.content}>
    <View style={styles.header}><Text style={styles.eyebrow}>CHOKMAH · MEBAHEL 1/5 · DIA 067</Text><Text style={styles.title}>{canon?.title??'CÂNONE SINCRONIZANDO'}</Text><Text style={styles.meta}>{canon?`${canon.sourcePath} · ${canon.sourceSha.slice(0,10)}`:'SEM FALLBACK EDITORIAL'}</Text></View>
    {controller.error||error?<RuntimeNotice title="RUNTIME">{error??controller.error}</RuntimeNotice>:null}
    {controller.runtime?.status==='locked'?<RuntimeCard label="GATE" title="Dia 067 bloqueado pela sequência"><Text style={runtimeTextStyles.body}>A primeira conclusão exige Iezalel 5/5, Dia 066, confirmado no servidor.</Text></RuntimeCard>:null}
    {phase==='threshold'?<RuntimeCard label="MEBAHEL 1/5" title="Âncora espacial como pista contextual, não campo físico"><CanonicalText>{canon?.blocks['jachin-kavanah']??''}</CanonicalText><RuntimeNotice title="SEGURANÇA">Use um ponto sem obstáculos. Nada de olhos fechados ao se deslocar, escadas, bordas, direção ou tarefa de risco.</RuntimeNotice><RuntimePrimary label="INICIAR" disabled={!canon||controller.busy} onPress={()=>void controller.begin().then(controller.nextPhase)}/></RuntimeCard>:null}
    {phase==='anchor-a'?<RuntimeCard label="ÂNCORA A · PRIMEIRA ENTRADA" title="Círculo azul · entrar, observar e sair"><RuntimeOpenTimer value={firstSeconds} onChange={setFirstSeconds}/><RuntimeScale label="FOCO" value={focusActive} onChange={setFocusActive}/><RuntimeChoice selected={firstDone} label="ENTREI E SAÍ VOLUNTARIAMENTE, TOTALMENTE ORIENTADO" onPress={()=>setFirstDone(v=>!v)}/><RuntimePrimary label="SAFETY STOP" onPress={stop}/><RuntimePrimary label="RETORNAR À ÂNCORA" disabled={firstSeconds<1||!firstDone} onPress={controller.nextPhase}/></RuntimeCard>:null}
    {phase==='anchor-b'?<RuntimeCard label="ÂNCORA A · RETORNO" title="Repetir sem buscar profundidade"><RuntimeOpenTimer value={returnSeconds} onChange={setReturnSeconds}/><View style={runtimeTextStyles.row}><RuntimeChoice selected={activeRecorded&&activeEffect} label="HOUVE MUDANÇA SUBJETIVA" onPress={()=>{setActiveEffect(true);setActiveRecorded(true);}}/><RuntimeChoice selected={activeRecorded&&!activeEffect} label="NENHUMA MUDANÇA MARCANTE" onPress={()=>{setActiveEffect(false);setActiveRecorded(true);}}/></View><RuntimeChoice selected={returnDone} label="RETORNEI E SAÍ DA ÂNCORA POR DECISÃO PRÓPRIA" onPress={()=>setReturnDone(v=>!v)}/><RuntimePrimary label="CONTROLE" disabled={returnSeconds<1||!activeRecorded||!returnDone} onPress={controller.nextPhase}/></RuntimeCard>:null}
    {phase==='control'?<RuntimeCard label="CONTROLE" title="Outro ponto seguro · sem círculo azul nem fórmula"><CanonicalText>{canon?.blocks['boaz-kavanah']??''}</CanonicalText><RuntimeOpenTimer value={controlSeconds} onChange={setControlSeconds}/><RuntimeScale label="FOCO" value={focusControl} onChange={setFocusControl}/><View style={runtimeTextStyles.row}><RuntimeChoice selected={controlRecorded&&controlEffect} label="HOUVE MUDANÇA SUBJETIVA" onPress={()=>{setControlEffect(true);setControlRecorded(true);}}/><RuntimeChoice selected={controlRecorded&&!controlEffect} label="NENHUMA MUDANÇA MARCANTE" onPress={()=>{setControlEffect(false);setControlRecorded(true);}}/></View><RuntimeChoice selected={controlDone} label="CONCLUÍ O PONTO NEUTRO" onPress={()=>setControlDone(v=>!v)}/><RuntimePrimary label="TESTAR CANCELAMENTO" disabled={controlSeconds<1||!controlRecorded||!controlDone} onPress={controller.nextPhase}/></RuntimeCard>:null}
    {phase==='cancel'?<RuntimeCard label="CANCELAMENTO" title="Abrir as mãos · respirar · declarar encerrado · sair"><RuntimeChoice selected={cancelDone} label="TESTEI E CONFIRMEI QUE A ÂNCORA É CANCELÁVEL" onPress={()=>setCancelDone(v=>!v)}/><RuntimeChoice selected={riskMovementAvoided} label="NÃO USEI A ÂNCORA EM MOVIMENTO OU CONTEXTO DE RISCO" onPress={()=>setRiskMovementAvoided(v=>!v)}/><RuntimePrimary label="COMPARAR" disabled={!cancelDone||!riskMovementAvoided} onPress={controller.nextPhase}/></RuntimeCard>:null}
    {phase==='compare'?<RuntimeCard label="REVISÃO" title="Pista espacial não possui poder objetivo demonstrado"><RuntimeChoice selected={comparison} label="COMPAREI ÂNCORA E PONTO NEUTRO SEM ESCOLHER UM VENCEDOR" onPress={()=>setComparison(v=>!v)}/><RuntimeChoice selected={objectivePowerNotClaimed} label="NÃO ATRIBUÍ PROPRIEDADE FÍSICA OU PODER SOBERANO AO LOCAL" onPress={()=>setObjectivePowerNotClaimed(v=>!v)}/><RuntimeChoice selected={orientationPreserved} label="ORIENTAÇÃO AMBIENTAL PERMANECEU PRESERVADA" onPress={()=>setOrientationPreserved(v=>!v)}/><RuntimeChoice selected={safetyClear} label="SEM DESORIENTAÇÃO OU NECESSIDADE COMPULSIVA DE REPETIR" onPress={()=>setSafetyClear(v=>!v)}/><RuntimePrimary label="GROUNDING" disabled={!comparison||!objectivePowerNotClaimed||!orientationPreserved||!safetyClear} onPress={controller.nextPhase}/></RuntimeCard>:null}
    {phase==='grounding'?<RuntimeCard label="GROUNDING" title="Voltar ao quarto e à tarefa comum"><RuntimeCounter label="OBJETOS REAIS NOMEADOS" value={objectsNamed} onPress={()=>setObjectsNamed(v=>Math.min(3,v+1))}/><RuntimePrimary label="RETORNO CONFIRMADO" disabled={objectsNamed<3} onPress={()=>{controller.setReturnConfirmed();controller.nextPhase();}}/></RuntimeCard>:null}
    {phase==='seal'?<RuntimeCard label="SELO SERVER-SIDE" title="Mebahel 1/5"><RuntimePrimary label={controller.busy?'SELANDO…':'SELAR DIA 067'} disabled={controller.busy} onPress={()=>void controller.seal({durationSeconds:activeSeconds+controlSeconds,evidence:{protocol_completed:true,return_confirmed:true,anchor_first_completed:firstDone,anchor_return_completed:returnDone,control_completed:controlDone,cancellation_completed:cancelDone,comparison_completed:comparison,objective_space_power_not_claimed:objectivePowerNotClaimed,risk_movement_avoided:riskMovementAvoided,orientation_preserved:orientationPreserved,safety_clear:safetyClear,active_effect_present:activeEffect,control_effect_present:controlEffect,active_seconds:activeSeconds,control_seconds:controlSeconds},metrics:{focus_active:focusActive,focus_control:focusControl}}).then(controller.nextPhase).catch(e=>setError(e instanceof Error?e.message:'day067_seal_failed'))}/></RuntimeCard>:null}
    {phase==='complete'?<RuntimeCompletion completion={controller.runtime?.serverCompletion} label="MEBAHEL 1/5"/>:null}
  </ScrollView>;
}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:'#02050a'},content:{padding:24,gap:18,paddingBottom:52},loading:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:'#02050a'},header:{gap:6},eyebrow:{color:'#6f96ba',fontSize:8,letterSpacing:1.5},title:{color:'#e8f4ff',fontSize:25,lineHeight:31,fontWeight:'300'},meta:{color:'#637e94',fontSize:8,letterSpacing:0.8}});
