import type { Database as BaseDatabase } from './database.types';

/**
 * Table shape copied from the migrated-schema proof generated by
 * `supabase gen types typescript --local`.
 *
 * Proof run: 33772590525
 * Artifact: 9900307150
 * Generated file SHA-256:
 * 5bcb7aee221ae75ba4d20050ce781681d42ba19997bae558568dca837e83fc7d
 *
 * This narrow augmentation keeps the existing generated/manual database type
 * surface stable while making the newly migrated table available without any
 * runtime cast. A future full database-type refresh can replace this bridge.
 */
export type VaultKeyEnvelopesTable = {
  Row: {
    created_at: string;
    envelope_kind: string;
    id: string;
    kdf_alg: string;
    kdf_info_version: number;
    kdf_salt: string;
    key_version: number;
    revoked_at: string | null;
    rotated_at: string | null;
    updated_at: string;
    user_id: string;
    wrap_alg: string;
    wrapped_key: string;
  };
  Insert: {
    created_at?: string;
    envelope_kind?: string;
    id?: string;
    kdf_alg: string;
    kdf_info_version?: number;
    kdf_salt: string;
    key_version: number;
    revoked_at?: string | null;
    rotated_at?: string | null;
    updated_at?: string;
    user_id: string;
    wrap_alg: string;
    wrapped_key: string;
  };
  Update: {
    created_at?: string;
    envelope_kind?: string;
    id?: string;
    kdf_alg?: string;
    kdf_info_version?: number;
    kdf_salt?: string;
    key_version?: number;
    revoked_at?: string | null;
    rotated_at?: string | null;
    updated_at?: string;
    user_id?: string;
    wrap_alg?: string;
    wrapped_key?: string;
  };
  Relationships: [];
};

type PublicSchema = BaseDatabase['public'];

export type Database = Omit<BaseDatabase, 'public'> & {
  public: Omit<PublicSchema, 'Tables'> & {
    Tables: PublicSchema['Tables'] & {
      vault_key_envelopes: VaultKeyEnvelopesTable;
    };
  };
};

export type PublicTables = Database['public']['Tables'];
export type TableName = keyof PublicTables;
export type Row<T extends TableName> = PublicTables[T]['Row'];
export type Insert<T extends TableName> = PublicTables[T]['Insert'];
export type Update<T extends TableName> = PublicTables[T]['Update'];
