create or replace function hnk_private.validate_day066_completion_v2(p_evidence jsonb,p_expected_source_sha text)
returns void language plpgsql set search_path=''
as $function$
declare m jsonb;a jsonb;c jsonb;p jsonb;i jsonb;s jsonb;k text;r text;reason text;score_key text;
begin
 if jsonb_typeof(p_evidence) is distinct from 'object' then raise exception 'day066_v2_evidence_object_required'; end if;
 if exists(select 1 from jsonb_object_keys(p_evidence) x where x not in ('protocol_version','source_sha','session_id','mode','master','active','control','comparison','middle','private_vault_entry_ref','private_vault_e2ee_confirmed','practice_record_no_private_prose_confirmed','voluntary_completion_confirmed','final_safety_clear_confirmed','safety_stop_occurred','safety_stop_reason')) then raise exception 'day066_v2_unknown_top_field'; end if;
 if p_evidence->>'protocol_version' is distinct from 'HNK-CHOKMAH-D066-V2' then raise exception 'day066_v2_protocol_invalid'; end if;
 if p_evidence->>'source_sha' is distinct from p_expected_source_sha or p_expected_source_sha is distinct from 'a6d48785ee355f734cadda61b0bb3810b125bf5e' then raise exception 'day066_v2_source_sha_invalid'; end if;
 if nullif(btrim(p_evidence->>'session_id'),'') is null then raise exception 'day066_v2_session_required'; end if;
 if coalesce(p_evidence->>'mode','first_completion') not in ('first_completion','revisit') then raise exception 'day066_v2_mode_invalid'; end if;
 if not exists(select 1 from public.asset_registry where asset_key='hnk.gneo_geo.v1.master' and approval_state='approved' and checksum_sha256='2547d18241651980ed1668408b189ecfd1eb28acb400cdf6c1d96e7514d90436') then raise exception 'day066_parent_gneo_reference_not_approved'; end if;
 if not exists(select 1 from public.asset_registry where asset_key='hnk.gneo_geo.day066.v1.master' and day=66 and approval_state='approved' and checksum_sha256='c8ac82fc3ccb2155a6c9f289c438a01894f0fd6666322720b95dde434c208ed6' and metadata->>'repo_asset_materialized'='true' and metadata->>'canonical_reference_status'='REFERENCE_APPROVED') then raise exception 'day066_gneo_master_not_materialized'; end if;
 r:=p_evidence->>'private_vault_entry_ref';
 if r is not null and r!~*'^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' then raise exception 'day066_v2_vault_ref_invalid'; end if;
 if r is not null and p_evidence->'private_vault_e2ee_confirmed' is distinct from 'true'::jsonb then raise exception 'day066_v2_vault_requires_e2ee'; end if;
 if r is null and p_evidence ? 'private_vault_e2ee_confirmed' and p_evidence->'private_vault_e2ee_confirmed' is not null and p_evidence->'private_vault_e2ee_confirmed' is distinct from 'false'::jsonb then raise exception 'day066_v2_e2ee_without_vault_ref'; end if;
 if p_evidence->'practice_record_no_private_prose_confirmed' is distinct from 'true'::jsonb or p_evidence->'voluntary_completion_confirmed' is distinct from 'true'::jsonb or p_evidence->'final_safety_clear_confirmed' is distinct from 'true'::jsonb then raise exception 'day066_v2_completion_boundary_missing'; end if;
 reason:=coalesce(p_evidence->>'safety_stop_reason','NONE');if reason not in ('NONE','DISORIENTATION','INTENSE_FEAR','PERSISTENT_DEREALIZATION','DIFFICULTY_RETURNING','OTHER') then raise exception 'day066_v2_safety_reason_invalid';end if;
 if p_evidence->'safety_stop_occurred' is distinct from 'false'::jsonb or reason<>'NONE' then raise exception 'day066_v2_unresolved_safety_stop'; end if;
 m:=p_evidence->'master';if jsonb_typeof(m) is distinct from 'object' then raise exception 'day066_v2_master_required';end if;
 if exists(select 1 from jsonb_object_keys(m) x where x not in ('master_id','asset_key','checksum_sha256','reference_freeze_path','reference_approved_confirmed','repo_materialized_confirmed','blue_pearl_centered_confirmed','eight_nodes_preserved_confirmed','cardinal_axes_preserved_confirmed','fixed_north_confirmed','nodes_circuits_kept_distinct_confirmed','no_route_invented_confirmed','all_nodes_simultaneous_confirmed')) then raise exception 'day066_v2_master_unknown_field';end if;
 if m->>'master_id' is distinct from 'cockpit-gneo-geo-hnk-master-v1.svg' or m->>'asset_key' is distinct from 'hnk.gneo_geo.day066.v1.master' or m->>'checksum_sha256' is distinct from 'c8ac82fc3ccb2155a6c9f289c438a01894f0fd6666322720b95dde434c208ed6' or m->>'reference_freeze_path' is distinct from 'docs/design/canonical-references/HNK_GNEO_GEO_REFERENCE_FREEZE_V1.md' then raise exception 'day066_v2_master_identity_invalid';end if;
 foreach k in array array['reference_approved_confirmed','repo_materialized_confirmed','blue_pearl_centered_confirmed','eight_nodes_preserved_confirmed','cardinal_axes_preserved_confirmed','fixed_north_confirmed','nodes_circuits_kept_distinct_confirmed','no_route_invented_confirmed','all_nodes_simultaneous_confirmed'] loop if m->k is distinct from 'true'::jsonb then raise exception 'day066_v2_master_boundary_required:%',k;end if;end loop;
 a:=p_evidence->'active';if jsonb_typeof(a) is distinct from 'object' then raise exception 'day066_v2_active_required';end if;
 if exists(select 1 from jsonb_object_keys(a) x where x not in ('active_seconds','scores','completed_confirmed','known_safe_induction_confirmed','posture_safe_confirmed','master_used_confirmed','no_hidden_functions_added_confirmed','no_forced_node_route_confirmed','external_travel_not_claimed_confirmed','remote_perception_not_claimed_confirmed','objective_external_access_not_claimed_confirmed','no_risky_task_while_immersed_confirmed','subjective_flight_or_displacement_occurred','scene_dissolved_confirmed','counted_up_confirmed','eyes_opened_confirmed','environment_elements_named_count')) then raise exception 'day066_v2_active_unknown_field';end if;
 if not coalesce(hnk_private.jsonb_is_nonnegative_integer(a->'active_seconds'),false) or (a->>'active_seconds')::integer<1 then raise exception 'day066_v2_active_duration_incomplete';end if;
 foreach k in array array['completed_confirmed','known_safe_induction_confirmed','posture_safe_confirmed','master_used_confirmed','no_hidden_functions_added_confirmed','no_forced_node_route_confirmed','external_travel_not_claimed_confirmed','remote_perception_not_claimed_confirmed','objective_external_access_not_claimed_confirmed','no_risky_task_while_immersed_confirmed','scene_dissolved_confirmed','counted_up_confirmed','eyes_opened_confirmed'] loop if a->k is distinct from 'true'::jsonb then raise exception 'day066_v2_active_boundary_required:%',k;end if;end loop;
 if jsonb_typeof(a->'subjective_flight_or_displacement_occurred') is distinct from 'boolean' then raise exception 'day066_v2_subjective_effect_flag_invalid';end if;
 if not coalesce(hnk_private.jsonb_is_nonnegative_integer(a->'environment_elements_named_count'),false) or (a->>'environment_elements_named_count')::integer<>5 then raise exception 'day066_v2_five_environment_elements_required';end if;
 s:=a->'scores';if jsonb_typeof(s) is distinct from 'object' or exists(select 1 from jsonb_object_keys(s) x where x not in ('depth','stability','orientation','presence')) then raise exception 'day066_v2_active_scores_invalid';end if;
 foreach score_key in array array['depth','stability','orientation','presence'] loop if not coalesce(hnk_private.jsonb_is_nonnegative_integer(s->score_key),false) or (s->>score_key)::integer>10 then raise exception 'day066_v2_active_score_invalid:%',score_key;end if;end loop;
 c:=p_evidence->'control';if jsonb_typeof(c) is distinct from 'object' then raise exception 'day066_v2_control_required';end if;
 if exists(select 1 from jsonb_object_keys(c) x where x not in ('control_seconds','scores','completed_confirmed','same_known_safe_induction_confirmed','neutral_space_confirmed','approximate_same_period_confirmed','no_cockpit_confirmed','return_completed_confirmed')) then raise exception 'day066_v2_control_unknown_field';end if;
 if not coalesce(hnk_private.jsonb_is_nonnegative_integer(c->'control_seconds'),false) or (c->>'control_seconds')::integer<1 then raise exception 'day066_v2_control_duration_incomplete';end if;
 foreach k in array array['completed_confirmed','same_known_safe_induction_confirmed','neutral_space_confirmed','approximate_same_period_confirmed','no_cockpit_confirmed','return_completed_confirmed'] loop if c->k is distinct from 'true'::jsonb then raise exception 'day066_v2_control_boundary_required:%',k;end if;end loop;
 s:=c->'scores';if jsonb_typeof(s) is distinct from 'object' or exists(select 1 from jsonb_object_keys(s) x where x not in ('depth','stability','presence','return_ease')) then raise exception 'day066_v2_control_scores_invalid';end if;
 foreach score_key in array array['depth','stability','presence','return_ease'] loop if not coalesce(hnk_private.jsonb_is_nonnegative_integer(s->score_key),false) or (s->>score_key)::integer>10 then raise exception 'day066_v2_control_score_invalid:%',score_key;end if;end loop;
 p:=p_evidence->'comparison';if jsonb_typeof(p) is distinct from 'object' then raise exception 'day066_v2_comparison_required';end if;
 if exists(select 1 from jsonb_object_keys(p) x where x not in ('completed_confirmed','after_both_conditions_confirmed','no_winner_declared_confirmed','internal_states_only_confirmed','travel_not_measured_confirmed','distance_not_measured_confirmed','external_influence_not_measured_confirmed','intensity_not_external_travel_proof_confirmed','intensity_not_entity_proof_confirmed','intensity_not_circuit_activation_proof_confirmed','intensity_not_initiatory_superiority_confirmed','nodes_circuits_distinct_confirmed','no_route_invented_confirmed','null_or_control_better_result_valid_confirmed')) then raise exception 'day066_v2_comparison_unknown_field';end if;
 foreach k in array array['completed_confirmed','after_both_conditions_confirmed','no_winner_declared_confirmed','internal_states_only_confirmed','travel_not_measured_confirmed','distance_not_measured_confirmed','external_influence_not_measured_confirmed','intensity_not_external_travel_proof_confirmed','intensity_not_entity_proof_confirmed','intensity_not_circuit_activation_proof_confirmed','intensity_not_initiatory_superiority_confirmed','nodes_circuits_distinct_confirmed','no_route_invented_confirmed','null_or_control_better_result_valid_confirmed'] loop if p->k is distinct from 'true'::jsonb then raise exception 'day066_v2_comparison_boundary_required:%',k;end if;end loop;
 i:=p_evidence->'middle';if jsonb_typeof(i) is distinct from 'object' then raise exception 'day066_v2_middle_required';end if;
 if exists(select 1 from jsonb_object_keys(i) x where x not in ('psalm_98_4_confirmed','yod_zayin_lamed_confirmed','master_visualized_confirmed','blue_pearl_recognized_confirmed','eight_nodes_without_mapping_confirmed','observable_data_named_count','sensation_named_count','hypothesis_named_count','field_dissolved_confirmed','eyes_opened_confirmed','body_moved_confirmed','location_confirmed','time_confirmed','orientation_restored_confirmed','thanks_to_god_confirmed','return_confirmed')) then raise exception 'day066_v2_middle_unknown_field';end if;
 foreach k in array array['psalm_98_4_confirmed','yod_zayin_lamed_confirmed','master_visualized_confirmed','blue_pearl_recognized_confirmed','eight_nodes_without_mapping_confirmed','field_dissolved_confirmed','eyes_opened_confirmed','body_moved_confirmed','location_confirmed','time_confirmed','orientation_restored_confirmed','thanks_to_god_confirmed','return_confirmed'] loop if i->k is distinct from 'true'::jsonb then raise exception 'day066_v2_middle_boundary_required:%',k;end if;end loop;
 foreach k in array array['observable_data_named_count','sensation_named_count','hypothesis_named_count'] loop if not coalesce(hnk_private.jsonb_is_nonnegative_integer(i->k),false) or (i->>k)::integer<>1 then raise exception 'day066_v2_middle_exactly_one_required:%',k;end if;end loop;
 perform hnk_private.validate_day066_scalar_evidence_v1(jsonb_build_object('protocol_completed',true,'return_confirmed',i->'return_confirmed','active_completed',a->'completed_confirmed','control_completed',c->'completed_confirmed','comparison_completed',p->'completed_confirmed','master_verified',m->'reference_approved_confirmed','pearl_centered',m->'blue_pearl_centered_confirmed','eight_nodes_preserved',m->'eight_nodes_preserved_confirmed','nodes_circuits_kept_distinct',m->'nodes_circuits_kept_distinct_confirmed','no_route_invented',m->'no_route_invented_confirmed','external_travel_not_claimed',a->'external_travel_not_claimed_confirmed','orientation_restored',i->'orientation_restored_confirmed','safety_clear',p_evidence->'final_safety_clear_confirmed','gneo_master_id',m->>'master_id','active_seconds',a->'active_seconds','control_seconds',c->'control_seconds'));
end$function$;

create or replace function hnk_private.enforce_iezalel_062_066_scalar_evidence()
returns trigger language plpgsql security definer set search_path=''
as $function$
declare v_existing boolean;v_source_sha text;v_status text;
begin
 if new.day not in (62,63,64,65,66) or new.state not in ('evidence_pending','complete') then return new;end if;
 select exists(select 1 from public.day_completions where user_id=new.user_id and day=new.day) into v_existing;if v_existing then return new;end if;
 select source_sha,status into v_source_sha,v_status from public.codex_days where day=new.day;if v_status is distinct from 'canon' then raise exception 'iezalel_canonical_day_not_available';end if;
 if new.day=62 then if v_source_sha is distinct from '56a8aaafbd2d602324ecfb9c06da39563fefaaf6' then raise exception 'day062_canonical_source_sha_mismatch';end if;if new.evidence->>'protocol_version'='HNK-CHOKMAH-D062-V2' then perform hnk_private.validate_day062_completion_v2(new.evidence,v_source_sha);else perform hnk_private.validate_day062_scalar_evidence_v1(new.evidence);end if;
 elsif new.day=63 then if v_source_sha is distinct from 'b9c9872ddf618aff3f515f601b3abfd611dace46' then raise exception 'day063_canonical_source_sha_mismatch';end if;if new.evidence->>'protocol_version'='HNK-CHOKMAH-D063-V2' then perform hnk_private.validate_day063_completion_v2(new.evidence,v_source_sha);else perform hnk_private.validate_day063_scalar_evidence_v1(new.evidence);end if;
 elsif new.day=64 then if v_source_sha is distinct from 'fb05d22be494099a5a1d3e1e0f5480ecc6c072cb' then raise exception 'day064_canonical_source_sha_mismatch';end if;if new.evidence->>'protocol_version'='HNK-CHOKMAH-D064-V2' then perform hnk_private.validate_day064_completion_v2(new.evidence,v_source_sha);else perform hnk_private.validate_day064_scalar_evidence_v1(new.evidence);end if;
 elsif new.day=65 then if v_source_sha is distinct from '8d8cd2a39fb05be283b8326fa258ed547b40f442' then raise exception 'day065_canonical_source_sha_mismatch';end if;if new.evidence->>'protocol_version'='HNK-CHOKMAH-D065-V2' then perform hnk_private.validate_day065_completion_v2(new.evidence,v_source_sha);else perform hnk_private.validate_day065_scalar_evidence_v1(new.evidence);end if;
 else if v_source_sha is distinct from 'a6d48785ee355f734cadda61b0bb3810b125bf5e' then raise exception 'day066_canonical_source_sha_mismatch';end if;if new.evidence->>'protocol_version'='HNK-CHOKMAH-D066-V2' then perform hnk_private.validate_day066_completion_v2(new.evidence,v_source_sha);else perform hnk_private.validate_day066_scalar_evidence_v1(new.evidence);end if;end if;
 return new;
end$function$;

do $patch$
declare d text;
begin
 select pg_get_functiondef('hnk_private.validate_completion_contract_v2(text,jsonb,text)'::regprocedure) into d;
 if position('when ''day066_v2''' in d)=0 then
  d:=replace(d,'  when ''day065_v2'' then perform hnk_private.validate_day065_completion_v2(p_evidence,p_expected_source_sha);','  when ''day065_v2'' then perform hnk_private.validate_day065_completion_v2(p_evidence,p_expected_source_sha);'||E'\n'||'  when ''day066_v2'' then perform hnk_private.validate_day066_completion_v2(p_evidence,p_expected_source_sha);');
  execute d;
 end if;
end$patch$;

insert into hnk_private.completion_contract_registry(completion_contract_id,quest_definition_id,day,canonical_source_sha,contract_version,validator_key,status)
values('HNK-CHOKMAH-D066-COMP-V2','HNK-CHOKMAH-D066-V2',66,'a6d48785ee355f734cadda61b0bb3810b125bf5e','2.0.0','day066_v2','draft')
on conflict(completion_contract_id) do update set quest_definition_id=excluded.quest_definition_id,day=excluded.day,canonical_source_sha=excluded.canonical_source_sha,contract_version=excluded.contract_version,validator_key=excluded.validator_key,status='draft',updated_at=now();
