create or replace function hnk_private.validate_day069_completion_v2(p_evidence jsonb,p_expected_source_sha text)
returns void language plpgsql set search_path='' as $$
declare a jsonb;c jsonb;p jsonb;m jsonb;s jsonb;sym jsonb;k text;score_key text;r text;reason text;
begin
 if jsonb_typeof(p_evidence) is distinct from 'object' then raise exception 'day069_v2_evidence_object_required'; end if;
 if exists(select 1 from jsonb_object_keys(p_evidence) q where q not in ('protocol_version','source_sha','session_id','mode','active','control','comparison','middle','private_vault_entry_ref','private_vault_e2ee_confirmed','practice_record_no_private_prose_confirmed','voluntary_completion_confirmed','final_safety_clear_confirmed','safety_stop_occurred','safety_stop_reason')) then raise exception 'day069_v2_unknown_top_field'; end if;
 if p_evidence->>'protocol_version' is distinct from 'HNK-CHOKMAH-D069-V2' then raise exception 'day069_v2_protocol_invalid'; end if;
 if p_evidence->>'source_sha' is distinct from p_expected_source_sha or p_expected_source_sha is distinct from '5ec5e7ade94e1a20c348028d75517475a6920e5a' then raise exception 'day069_v2_source_sha_invalid'; end if;
 if nullif(btrim(p_evidence->>'session_id'),'') is null then raise exception 'day069_v2_session_required'; end if;
 if coalesce(p_evidence->>'mode','first_completion') not in ('first_completion','revisit') then raise exception 'day069_v2_mode_invalid'; end if;
 r:=p_evidence->>'private_vault_entry_ref';
 if r is not null and r!~*'^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' then raise exception 'day069_v2_vault_ref_invalid'; end if;
 if r is not null and p_evidence->'private_vault_e2ee_confirmed' is distinct from 'true'::jsonb then raise exception 'day069_v2_vault_requires_e2ee'; end if;
 if r is null and p_evidence ? 'private_vault_e2ee_confirmed' and p_evidence->'private_vault_e2ee_confirmed' is not null and p_evidence->'private_vault_e2ee_confirmed' is distinct from 'false'::jsonb then raise exception 'day069_v2_e2ee_without_vault_ref'; end if;
 if p_evidence->'practice_record_no_private_prose_confirmed' is distinct from 'true'::jsonb or p_evidence->'voluntary_completion_confirmed' is distinct from 'true'::jsonb or p_evidence->'final_safety_clear_confirmed' is distinct from 'true'::jsonb then raise exception 'day069_v2_completion_boundary_missing'; end if;
 reason:=coalesce(p_evidence->>'safety_stop_reason','NONE');
 if reason not in ('NONE','PAIN','BLURRED_VISION','NAUSEA','VERTIGO','HEADACHE','GROWING_DISCOMFORT','OTHER') then raise exception 'day069_v2_safety_reason_invalid'; end if;
 if p_evidence->'safety_stop_occurred' is distinct from 'false'::jsonb or reason<>'NONE' then raise exception 'day069_v2_unresolved_safety_stop'; end if;
 a:=p_evidence->'active'; if jsonb_typeof(a) is distinct from 'object' then raise exception 'day069_v2_active_required'; end if;
 if not coalesce(hnk_private.jsonb_is_nonnegative_integer(a->'active_seconds'),false) or (a->>'active_seconds')::int<1 then raise exception 'day069_v2_active_duration_incomplete'; end if;
 if not coalesce(hnk_private.jsonb_is_nonnegative_integer(a->'repetitions_completed'),false) or (a->>'repetitions_completed')::int<1 then raise exception 'day069_v2_repetitions_incomplete'; end if;
 foreach k in array array['completed_confirmed','seated_supported_confirmed','head_stable_only_while_natural_confirmed','moderate_amplitude_confirmed','slow_pace_confirmed','pause_and_comfort_check_confirmed','personal_limit_below_fatigue_confirmed','no_forced_repetition_confirmed','no_extreme_speed_confirmed','thirty_repetitions_not_required_confirmed','relevant_condition_guidance_respected_confirmed'] loop if a->k is distinct from 'true'::jsonb then raise exception 'day069_v2_active_boundary_required:%',k; end if; end loop;
 s:=a->'pre_scores'; if jsonb_typeof(s) is distinct from 'object' then raise exception 'day069_v2_pre_scores_invalid'; end if; foreach score_key in array array['ocular_comfort','dizziness','headache','focus'] loop if not coalesce(hnk_private.jsonb_is_nonnegative_integer(s->score_key),false) or (s->>score_key)::int>10 then raise exception 'day069_v2_pre_score_invalid:%',score_key; end if; end loop;
 s:=a->'post_scores'; if jsonb_typeof(s) is distinct from 'object' then raise exception 'day069_v2_post_scores_invalid'; end if; foreach score_key in array array['focus','ocular_tension','calm','dizziness'] loop if not coalesce(hnk_private.jsonb_is_nonnegative_integer(s->score_key),false) or (s->>score_key)::int>10 then raise exception 'day069_v2_post_score_invalid:%',score_key; end if; end loop;
 sym:=a->'symptoms'; if jsonb_typeof(sym) is distinct from 'object' then raise exception 'day069_v2_symptoms_invalid'; end if; foreach k in array array['pain','blurred_vision','nausea','vertigo','uncomfortable_nystagmus','headache','growing_discomfort'] loop if jsonb_typeof(sym->k) is distinct from 'boolean' then raise exception 'day069_v2_symptom_flag_invalid:%',k; end if; if sym->k='true'::jsonb then raise exception 'day069_v2_stop_symptom_present:%',k; end if; end loop;
 c:=p_evidence->'control'; if jsonb_typeof(c) is distinct from 'object' then raise exception 'day069_v2_control_required'; end if; if not coalesce(hnk_private.jsonb_is_nonnegative_integer(c->'control_seconds'),false) or (c->>'control_seconds')::int<1 then raise exception 'day069_v2_control_duration_incomplete'; end if; foreach k in array array['completed_confirmed','separate_session_confirmed','central_stable_gaze_confirmed','approximately_same_duration_confirmed'] loop if c->k is distinct from 'true'::jsonb then raise exception 'day069_v2_control_boundary_required:%',k; end if; end loop;
 s:=c->'scores'; if jsonb_typeof(s) is distinct from 'object' then raise exception 'day069_v2_control_scores_invalid'; end if; foreach score_key in array array['focus','calm','ocular_tension','dizziness'] loop if not coalesce(hnk_private.jsonb_is_nonnegative_integer(s->score_key),false) or (s->>score_key)::int>10 then raise exception 'day069_v2_control_score_invalid:%',score_key; end if; end loop;
 p:=p_evidence->'comparison'; if jsonb_typeof(p) is distinct from 'object' then raise exception 'day069_v2_comparison_required'; end if; foreach k in array array['completed_confirmed','after_both_conditions_confirmed','self_report_and_observable_execution_only_confirmed','brainwave_claim_not_made_confirmed','hemispheric_integration_claim_not_made_confirmed','therapy_substitute_not_claimed_confirmed','null_or_control_better_result_valid_confirmed','lateral_discomfort_triggers_reduce_or_discard_confirmed','no_competition_or_extreme_speed_confirmed'] loop if p->k is distinct from 'true'::jsonb then raise exception 'day069_v2_comparison_boundary_required:%',k; end if; end loop;
 m:=p_evidence->'middle'; if jsonb_typeof(m) is distinct from 'object' then raise exception 'day069_v2_middle_required'; end if; foreach k in array array['psalm_9_9_confirmed','mem_bet_he_confirmed','eyes_rested_confirmed','traditional_hypothesis_separated_confirmed','thanks_to_god_confirmed','head_moved_normally_confirmed','no_dizziness_before_end_confirmed','limitation_registered_confirmed','accept_abandon_if_needed_confirmed','return_confirmed'] loop if m->k is distinct from 'true'::jsonb then raise exception 'day069_v2_middle_boundary_required:%',k; end if; end loop; foreach k in array array['movements_named_count','comfort_named_count','focus_named_count','symptoms_named_count'] loop if not coalesce(hnk_private.jsonb_is_nonnegative_integer(m->k),false) or (m->>k)::int<>1 then raise exception 'day069_v2_middle_exactly_one_required:%',k; end if; end loop; if not coalesce(hnk_private.jsonb_is_nonnegative_integer(m->'objects_at_different_distances_count'),false) or (m->>'objects_at_different_distances_count')::int<>3 then raise exception 'day069_v2_three_objects_required'; end if;
 perform hnk_private.validate_day069_scalar_evidence_v1(jsonb_build_object('protocol_completed',true,'return_confirmed',m->'return_confirmed','active_completed',a->'completed_confirmed','control_completed',c->'completed_confirmed','comparison_completed',p->'completed_confirmed','no_forced_repetition',a->'no_forced_repetition_confirmed','no_extreme_speed',a->'no_extreme_speed_confirmed','brainwave_claim_not_made',p->'brainwave_claim_not_made_confirmed','therapy_substitute_not_claimed',p->'therapy_substitute_not_claimed_confirmed','relevant_condition_guidance_respected',a->'relevant_condition_guidance_respected_confirmed','orientation_restored',m->'return_confirmed','safety_clear',p_evidence->'final_safety_clear_confirmed','repetitions_completed',a->'repetitions_completed','active_seconds',a->'active_seconds','control_seconds',c->'control_seconds'));
end $$;

create or replace function hnk_private.enforce_mebahel_067_071_scalar_evidence()
returns trigger language plpgsql security definer set search_path='' as $$
declare existing boolean; sha text; st text; begin
 if new.day not in (67,68,69,70,71) or new.state not in ('evidence_pending','complete') then return new; end if;
 select exists(select 1 from public.day_completions where user_id=new.user_id and day=new.day) into existing; if existing then return new; end if;
 select source_sha,status into sha,st from public.codex_days where day=new.day; if st is distinct from 'canon' then raise exception 'mebahel_canonical_day_not_available'; end if;
 if new.day=67 then if sha is distinct from '1fe06968c724f74311e4fd567075fabc181f1125' then raise exception 'day067_canonical_source_sha_mismatch'; end if; if new.evidence->>'protocol_version'='HNK-CHOKMAH-D067-V2' then perform hnk_private.validate_day067_completion_v2(new.evidence,sha); else perform hnk_private.validate_day067_scalar_evidence_v1(new.evidence); end if;
 elsif new.day=68 then if sha is distinct from '176ebffccc845a909f5d1d2bdb88181b94809afb' then raise exception 'day068_canonical_source_sha_mismatch'; end if; if new.evidence->>'protocol_version'='HNK-CHOKMAH-D068-V2' then perform hnk_private.validate_day068_completion_v2(new.evidence,sha); else perform hnk_private.validate_day068_scalar_evidence_v1(new.evidence); end if;
 elsif new.day=69 then if sha is distinct from '5ec5e7ade94e1a20c348028d75517475a6920e5a' then raise exception 'day069_canonical_source_sha_mismatch'; end if; if new.evidence->>'protocol_version'='HNK-CHOKMAH-D069-V2' then perform hnk_private.validate_day069_completion_v2(new.evidence,sha); else perform hnk_private.validate_day069_scalar_evidence_v1(new.evidence); end if;
 elsif new.day=70 then if sha is distinct from 'bb1e47aee510fe9df58a46f697ebafb9005e223e' then raise exception 'day070_canonical_source_sha_mismatch'; end if; perform hnk_private.validate_day070_scalar_evidence_v1(new.evidence);
 else if sha is distinct from '6dfa6b5768bd7cdc2812d5dbfc68a8bc66ad90c3' then raise exception 'day071_canonical_source_sha_mismatch'; end if; perform hnk_private.validate_day071_scalar_evidence_v1(new.evidence); end if; return new; end $$;

do $$ declare d text; begin d:=pg_get_functiondef('hnk_private.validate_completion_contract_v2(text,jsonb,text)'::regprocedure); if position('when ''day069_v2''' in d)=0 then d:=replace(d,'else raise exception ''unsupported_completion_validator:%'',p_validator_key;','when ''day069_v2'' then perform hnk_private.validate_day069_completion_v2(p_evidence,p_expected_source_sha);'||chr(10)||'  else raise exception ''unsupported_completion_validator:%'',p_validator_key;'); if position('when ''day069_v2''' in d)=0 then raise exception 'day069_dispatcher_patch_failed'; end if; execute d; end if; end $$;
insert into hnk_private.completion_contract_registry(completion_contract_id,quest_definition_id,day,canonical_source_sha,contract_version,validator_key,status) values('HNK-CHOKMAH-D069-COMP-V2','HNK-CHOKMAH-D069-V2',69,'5ec5e7ade94e1a20c348028d75517475a6920e5a','2.0.0','day069_v2','draft') on conflict(completion_contract_id) do update set quest_definition_id=excluded.quest_definition_id,day=excluded.day,canonical_source_sha=excluded.canonical_source_sha,contract_version=excluded.contract_version,validator_key=excluded.validator_key,status='draft',updated_at=now();
