create or replace function hnk_private.validate_day070_completion_v2(p_evidence jsonb,p_expected_source_sha text)
returns void language plpgsql set search_path='' as $$
declare ref jsonb;a jsonb;c jsonb;p jsonb;m jsonb;s jsonb;k text;score_key text;r text;reason text;asset_ok boolean;
begin
 select exists(select 1 from public.asset_registry ar where ar.asset_key='hnk.tetragrammaton.day070.v1.master' and ar.day=70 and ar.approval_state='approved' and ar.checksum_sha256='16cd1d9ff1cc256f570d526bc6c6bfd249d06957d972f87f51168011cb78451b' and coalesce(ar.metadata->>'repo_path','')='assets/canonical/chokmah/pantaculo-tetragrammaton-hnk-master-v1.svg' and coalesce((ar.metadata->>'upright')::boolean,false)=true and coalesce((ar.metadata->>'mirrored')::boolean,true)=false) into asset_ok;
 if not asset_ok then raise exception 'day070_v2_reference_not_ready'; end if;
 if jsonb_typeof(p_evidence) is distinct from 'object' then raise exception 'day070_v2_evidence_object_required'; end if;
 if exists(select 1 from jsonb_object_keys(p_evidence) q where q not in ('protocol_version','source_sha','session_id','mode','reference','active','control','comparison','middle','private_vault_entry_ref','private_vault_e2ee_confirmed','practice_record_no_private_prose_confirmed','voluntary_completion_confirmed','final_safety_clear_confirmed','safety_stop_occurred','safety_stop_reason')) then raise exception 'day070_v2_unknown_top_field'; end if;
 if p_evidence->>'protocol_version' is distinct from 'HNK-CHOKMAH-D070-V2' then raise exception 'day070_v2_protocol_invalid'; end if;
 if p_evidence->>'source_sha' is distinct from p_expected_source_sha or p_expected_source_sha is distinct from 'bb1e47aee510fe9df58a46f697ebafb9005e223e' then raise exception 'day070_v2_source_sha_invalid'; end if;
 if nullif(btrim(p_evidence->>'session_id'),'') is null then raise exception 'day070_v2_session_required'; end if;
 if coalesce(p_evidence->>'mode','first_completion') not in ('first_completion','revisit') then raise exception 'day070_v2_mode_invalid'; end if;
 r:=p_evidence->>'private_vault_entry_ref'; if r is not null and r!~*'^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' then raise exception 'day070_v2_vault_ref_invalid'; end if;
 if r is not null and p_evidence->'private_vault_e2ee_confirmed' is distinct from 'true'::jsonb then raise exception 'day070_v2_vault_requires_e2ee'; end if;
 if r is null and p_evidence ? 'private_vault_e2ee_confirmed' and p_evidence->'private_vault_e2ee_confirmed' is not null and p_evidence->'private_vault_e2ee_confirmed' is distinct from 'false'::jsonb then raise exception 'day070_v2_e2ee_without_vault_ref'; end if;
 if p_evidence->'practice_record_no_private_prose_confirmed' is distinct from 'true'::jsonb or p_evidence->'voluntary_completion_confirmed' is distinct from 'true'::jsonb or p_evidence->'final_safety_clear_confirmed' is distinct from 'true'::jsonb then raise exception 'day070_v2_completion_boundary_missing'; end if;
 reason:=coalesce(p_evidence->>'safety_stop_reason','NONE'); if reason not in ('NONE','INVULNERABILITY','GRANDIOSITY','COMPULSIVE_REPETITION','DISTRESS','DISORIENTATION','OTHER') then raise exception 'day070_v2_safety_reason_invalid'; end if; if p_evidence->'safety_stop_occurred' is distinct from 'false'::jsonb or reason<>'NONE' then raise exception 'day070_v2_unresolved_safety_stop'; end if;
 ref:=p_evidence->'reference'; if jsonb_typeof(ref) is distinct from 'object' then raise exception 'day070_v2_reference_required'; end if;
 if ref->>'master_id' is distinct from 'pantaculo-tetragrammaton-hnk-master-v1.svg' or ref->>'checksum_sha256' is distinct from '16cd1d9ff1cc256f570d526bc6c6bfd249d06957d972f87f51168011cb78451b' then raise exception 'day070_v2_master_mismatch'; end if;
 foreach k in array array['master_verified_confirmed','upright_not_mirrored_confirmed','geometry_unaltered_confirmed'] loop if ref->k is distinct from 'true'::jsonb then raise exception 'day070_v2_reference_boundary_required:%',k; end if; end loop;
 a:=p_evidence->'active'; if jsonb_typeof(a) is distinct from 'object' then raise exception 'day070_v2_active_required'; end if; if not coalesce(hnk_private.jsonb_is_nonnegative_integer(a->'active_seconds'),false) or (a->>'active_seconds')::int<1 then raise exception 'day070_v2_active_duration_incomplete'; end if; if not coalesce(hnk_private.jsonb_is_nonnegative_integer(a->'positions_completed'),false) or (a->>'positions_completed')::int<>3 then raise exception 'day070_v2_three_positions_required'; end if;
 foreach k in array array['completed_confirmed','blue_light_imagery_only_confirmed','natural_breathing_confirmed','no_invulnerability_goal_confirmed','images_deliberately_closed_confirmed','orientation_before_confirmed','orientation_after_confirmed'] loop if a->k is distinct from 'true'::jsonb then raise exception 'day070_v2_active_boundary_required:%',k; end if; end loop;
 s:=a->'scores'; if jsonb_typeof(s) is distinct from 'object' then raise exception 'day070_v2_active_scores_invalid'; end if; foreach score_key in array array['limit','calm','focus','expectation','return_ease'] loop if not coalesce(hnk_private.jsonb_is_nonnegative_integer(s->score_key),false) or (s->>score_key)::int>10 then raise exception 'day070_v2_active_score_invalid:%',score_key; end if; end loop;
 c:=p_evidence->'control'; if jsonb_typeof(c) is distinct from 'object' then raise exception 'day070_v2_control_required'; end if; if not coalesce(hnk_private.jsonb_is_nonnegative_integer(c->'control_seconds'),false) or (c->>'control_seconds')::int<1 then raise exception 'day070_v2_control_duration_incomplete'; end if; if not coalesce(hnk_private.jsonb_is_nonnegative_integer(c->'positions_completed'),false) or (c->>'positions_completed')::int<>3 then raise exception 'day070_v2_control_three_positions_required'; end if;
 foreach k in array array['completed_confirmed','same_space_confirmed','neutral_blue_markers_confirmed','no_pantacle_formula_or_sacred_names_confirmed','similar_duration_confirmed','natural_breathing_confirmed','dignified_control_visual_confirmed'] loop if c->k is distinct from 'true'::jsonb then raise exception 'day070_v2_control_boundary_required:%',k; end if; end loop;
 s:=c->'scores'; if jsonb_typeof(s) is distinct from 'object' then raise exception 'day070_v2_control_scores_invalid'; end if; foreach score_key in array array['limit','calm','focus','expectation','return_ease'] loop if not coalesce(hnk_private.jsonb_is_nonnegative_integer(s->score_key),false) or (s->>score_key)::int>10 then raise exception 'day070_v2_control_score_invalid:%',score_key; end if; end loop;
 p:=p_evidence->'comparison'; if jsonb_typeof(p) is distinct from 'object' then raise exception 'day070_v2_comparison_required'; end if; foreach k in array array['completed_confirmed','after_both_conditions_confirmed','no_winner_declared_confirmed','null_or_control_better_result_valid_confirmed','objective_physical_shield_not_claimed_confirmed','measurable_aura_not_claimed_confirmed','invulnerability_not_claimed_confirmed','real_safety_preserved_confirmed','medical_care_preserved_confirmed','legal_prudence_preserved_confirmed','everyday_risk_attention_preserved_confirmed','no_condition_declared_spiritually_superior_confirmed'] loop if p->k is distinct from 'true'::jsonb then raise exception 'day070_v2_comparison_boundary_required:%',k; end if; end loop;
 m:=p_evidence->'middle'; if jsonb_typeof(m) is distinct from 'object' then raise exception 'day070_v2_middle_required'; end if; foreach k in array array['psalm_9_9_confirmed','mem_bet_he_confirmed','images_closed_by_choice_confirmed','body_moved_confirmed','location_confirmed','time_confirmed','thanks_to_god_confirmed','return_confirmed'] loop if m->k is distinct from 'true'::jsonb then raise exception 'day070_v2_middle_boundary_required:%',k; end if; end loop; if not coalesce(hnk_private.jsonb_is_nonnegative_integer(m->'risk_measure_named_count'),false) or (m->>'risk_measure_named_count')::int<>1 then raise exception 'day070_v2_one_risk_measure_required'; end if; if not coalesce(hnk_private.jsonb_is_nonnegative_integer(m->'responsibility_named_count'),false) or (m->>'responsibility_named_count')::int<>1 then raise exception 'day070_v2_one_responsibility_required'; end if;
 perform hnk_private.validate_day070_scalar_evidence_v1(jsonb_build_object('protocol_completed',true,'return_confirmed',m->'return_confirmed','master_verified',ref->'master_verified_confirmed','upright_not_mirrored',ref->'upright_not_mirrored_confirmed','three_positions_completed',a->'completed_confirmed','control_completed',c->'completed_confirmed','comparison_completed',p->'completed_confirmed','invulnerability_not_claimed',p->'invulnerability_not_claimed_confirmed','real_safety_preserved',p->'real_safety_preserved_confirmed','risk_measure_named',true,'orientation_restored',m->'return_confirmed','safety_clear',p_evidence->'final_safety_clear_confirmed','tetragrammaton_master_id',ref->>'master_id','active_seconds',a->'active_seconds','control_seconds',c->'control_seconds'));
end $$;

create or replace function hnk_private.enforce_mebahel_067_071_scalar_evidence()
returns trigger language plpgsql security definer set search_path='' as $$
declare existing boolean; sha text; st text; begin
 if new.day not in (67,68,69,70,71) or new.state not in ('evidence_pending','complete') then return new; end if;
 select exists(select 1 from public.day_completions where user_id=new.user_id and day=new.day) into existing; if existing then return new; end if;
 select source_sha,status into sha,st from public.codex_days where day=new.day; if st is distinct from 'canon' then raise exception 'mebahel_canonical_day_not_available'; end if;
 if new.day=67 then if sha is distinct from '1fe06968c724f74311e4fd567075fabc181f1125' then raise exception 'day067_canonical_source_sha_mismatch'; end if; if new.evidence->>'protocol_version'='HNK-CHOKMAH-D067-V2' then perform hnk_private.validate_day067_completion_v2(new.evidence,sha); else perform hnk_private.validate_day067_scalar_evidence_v1(new.evidence); end if;
 elsif new.day=68 then if sha is distinct from '176ebffccc845a909f5d1d2bdb88181b94809afb' then raise exception 'day068_canonical_source_sha_mismatch'; end if; if new.evidence->>'protocol_version'='HNK-CHOKMAH-D068-V2' then perform hnk_private.validate_day068_completion_v2(new.evidence,sha); else perform hnk_private.validate_day068_scalar_evidence_v1(new.evidence); end if;
 elsif new.day=69 then if sha is distinct from '5ec5e7ade94e1a20c348028d75517475a6920e5a' then raise exception 'day069_canonical_source_sha_mismatch'; end if; if new.evidence->>'protocol_version'='HNK-CHOKMAH-D069-V2' then perform hnk_private.validate_day069_completion_v2(new.evidence,sha); else perform hnk_private.validate_day069_scalar_evidence_v1(new.evidence); end if;
 elsif new.day=70 then if sha is distinct from 'bb1e47aee510fe9df58a46f697ebafb9005e223e' then raise exception 'day070_canonical_source_sha_mismatch'; end if; if new.evidence->>'protocol_version'='HNK-CHOKMAH-D070-V2' then perform hnk_private.validate_day070_completion_v2(new.evidence,sha); else perform hnk_private.validate_day070_scalar_evidence_v1(new.evidence); end if;
 else if sha is distinct from '6dfa6b5768bd7cdc2812d5dbfc68a8bc66ad90c3' then raise exception 'day071_canonical_source_sha_mismatch'; end if; perform hnk_private.validate_day071_scalar_evidence_v1(new.evidence); end if; return new; end $$;

do $$ declare d text; begin d:=pg_get_functiondef('hnk_private.validate_completion_contract_v2(text,jsonb,text)'::regprocedure); if position('when ''day070_v2''' in d)=0 then d:=replace(d,'else raise exception ''unsupported_completion_validator:%'',p_validator_key;','when ''day070_v2'' then perform hnk_private.validate_day070_completion_v2(p_evidence,p_expected_source_sha);'||chr(10)||'  else raise exception ''unsupported_completion_validator:%'',p_validator_key;'); if position('when ''day070_v2''' in d)=0 then raise exception 'day070_dispatcher_patch_failed'; end if; execute d; end if; end $$;
insert into hnk_private.completion_contract_registry(completion_contract_id,quest_definition_id,day,canonical_source_sha,contract_version,validator_key,status) values('HNK-CHOKMAH-D070-COMP-V2','HNK-CHOKMAH-D070-V2',70,'bb1e47aee510fe9df58a46f697ebafb9005e223e','2.0.0','day070_v2','draft') on conflict(completion_contract_id) do update set quest_definition_id=excluded.quest_definition_id,day=excluded.day,canonical_source_sha=excluded.canonical_source_sha,contract_version=excluded.contract_version,validator_key=excluded.validator_key,status='draft',updated_at=now();