create or replace function hnk_private.validate_day071_completion_v2(p_evidence jsonb,p_expected_source_sha text)
returns void language plpgsql set search_path='' as $function$
declare a jsonb;c jsonb;p jsonb;m jsonb;s jsonb;k text;score_key text;ref text;reason text;
begin
 if jsonb_typeof(p_evidence) is distinct from 'object' then raise exception 'day071_v2_evidence_object_required'; end if;
 if exists(select 1 from jsonb_object_keys(p_evidence) q where q not in ('protocol_version','source_sha','session_id','mode','active','control','comparison','middle','private_vault_entry_ref','private_vault_e2ee_confirmed','practice_record_no_private_prose_confirmed','voluntary_completion_confirmed','final_safety_clear_confirmed','safety_stop_occurred','safety_stop_reason')) then raise exception 'day071_v2_unknown_top_field'; end if;
 if p_evidence->>'protocol_version' is distinct from 'HNK-CHOKMAH-D071-V2' then raise exception 'day071_v2_protocol_invalid'; end if;
 if p_evidence->>'source_sha' is distinct from p_expected_source_sha or p_expected_source_sha is distinct from '6dfa6b5768bd7cdc2812d5dbfc68a8bc66ad90c3' then raise exception 'day071_v2_source_sha_invalid'; end if;
 if nullif(btrim(p_evidence->>'session_id'),'') is null then raise exception 'day071_v2_session_required'; end if;
 if coalesce(p_evidence->>'mode','first_completion') not in ('first_completion','revisit') then raise exception 'day071_v2_mode_invalid'; end if;
 ref:=p_evidence->>'private_vault_entry_ref'; if ref is null or ref!~*'^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' then raise exception 'day071_v2_vault_ref_required'; end if;
 if p_evidence->'private_vault_e2ee_confirmed' is distinct from 'true'::jsonb then raise exception 'day071_v2_vault_e2ee_required'; end if;
 if p_evidence->'practice_record_no_private_prose_confirmed' is distinct from 'true'::jsonb or p_evidence->'voluntary_completion_confirmed' is distinct from 'true'::jsonb or p_evidence->'final_safety_clear_confirmed' is distinct from 'true'::jsonb then raise exception 'day071_v2_completion_boundary_missing'; end if;
 reason:=coalesce(p_evidence->>'safety_stop_reason','NONE'); if reason not in ('NONE','COMPULSIVE_REPEAT_URGE','PERSISTENT_FEAR','PERSECUTION_DISTRESS','DISORIENTATION','FUNCTIONAL_IMPAIRMENT','OTHER') then raise exception 'day071_v2_safety_reason_invalid'; end if; if p_evidence->'safety_stop_occurred' is distinct from 'false'::jsonb or reason<>'NONE' then raise exception 'day071_v2_unresolved_safety_stop'; end if;
 a:=p_evidence->'active'; if jsonb_typeof(a) is distinct from 'object' then raise exception 'day071_v2_active_required'; end if;
 if exists(select 1 from jsonb_object_keys(a) q where q not in ('active_seconds','completed_confirmed','safe_space_confirmed','real_flame_not_used_confirmed','imaginary_flame_only_confirmed','circle_symbolic_confirmed','pattern_named_without_entity_claim_confirmed','environment_awareness_preserved_confirmed','freedom_to_stop_confirmed','visualization_closed_confirmed','active_effect_present','scores')) then raise exception 'day071_v2_unknown_active_field'; end if;
 if not coalesce(hnk_private.jsonb_is_nonnegative_integer(a->'active_seconds'),false) or (a->>'active_seconds')::int<1 then raise exception 'day071_v2_active_duration_incomplete'; end if; if jsonb_typeof(a->'active_effect_present') is distinct from 'boolean' then raise exception 'day071_v2_active_effect_invalid'; end if;
 foreach k in array array['completed_confirmed','safe_space_confirmed','real_flame_not_used_confirmed','imaginary_flame_only_confirmed','circle_symbolic_confirmed','pattern_named_without_entity_claim_confirmed','environment_awareness_preserved_confirmed','freedom_to_stop_confirmed','visualization_closed_confirmed'] loop if a->k is distinct from 'true'::jsonb then raise exception 'day071_v2_active_boundary_required:%',k; end if; end loop;
 s:=a->'scores'; if jsonb_typeof(s) is distinct from 'object' then raise exception 'day071_v2_active_scores_required'; end if; foreach score_key in array array['tension_before','tension_after','clarity_before','clarity_after','rumination_before','rumination_after','expectation'] loop if not coalesce(hnk_private.jsonb_is_nonnegative_integer(s->score_key),false) or (s->>score_key)::int>10 then raise exception 'day071_v2_active_score_invalid:%',score_key; end if; end loop;
 c:=p_evidence->'control'; if jsonb_typeof(c) is distinct from 'object' then raise exception 'day071_v2_control_required'; end if;
 if exists(select 1 from jsonb_object_keys(c) q where q not in ('control_seconds','completed_confirmed','separate_moment_confirmed','same_gesture_and_breathing_confirmed','no_formula_confirmed','no_imaginary_flame_confirmed','no_expulsion_language_confirmed','similar_duration_confirmed','control_effect_present','scores')) then raise exception 'day071_v2_unknown_control_field'; end if;
 if not coalesce(hnk_private.jsonb_is_nonnegative_integer(c->'control_seconds'),false) or (c->>'control_seconds')::int<1 then raise exception 'day071_v2_control_duration_incomplete'; end if; if jsonb_typeof(c->'control_effect_present') is distinct from 'boolean' then raise exception 'day071_v2_control_effect_invalid'; end if;
 foreach k in array array['completed_confirmed','separate_moment_confirmed','same_gesture_and_breathing_confirmed','no_formula_confirmed','no_imaginary_flame_confirmed','no_expulsion_language_confirmed','similar_duration_confirmed'] loop if c->k is distinct from 'true'::jsonb then raise exception 'day071_v2_control_boundary_required:%',k; end if; end loop;
 s:=c->'scores'; if jsonb_typeof(s) is distinct from 'object' then raise exception 'day071_v2_control_scores_required'; end if; foreach score_key in array array['tension','clarity','rumination','expectation'] loop if not coalesce(hnk_private.jsonb_is_nonnegative_integer(s->score_key),false) or (s->>score_key)::int>10 then raise exception 'day071_v2_control_score_invalid:%',score_key; end if; end loop;
 p:=p_evidence->'comparison'; if jsonb_typeof(p) is distinct from 'object' then raise exception 'day071_v2_comparison_required'; end if;
 if exists(select 1 from jsonb_object_keys(p) q where q not in ('completed_confirmed','after_both_conditions_confirmed','no_winner_declared_confirmed','null_or_control_better_result_valid_confirmed','entity_diagnosis_not_claimed_confirmed','third_party_entity_accusation_forbidden_confirmed','anti_compulsion_rule_confirmed','no_repeat_to_neutralize_fear_confirmed','persistent_fear_support_priority_confirmed','real_safety_preserved_confirmed','appropriate_care_preserved_confirmed','invulnerability_not_claimed_confirmed','external_enemy_not_confirmed')) then raise exception 'day071_v2_unknown_comparison_field'; end if;
 foreach k in array array['completed_confirmed','after_both_conditions_confirmed','no_winner_declared_confirmed','null_or_control_better_result_valid_confirmed','entity_diagnosis_not_claimed_confirmed','third_party_entity_accusation_forbidden_confirmed','anti_compulsion_rule_confirmed','no_repeat_to_neutralize_fear_confirmed','persistent_fear_support_priority_confirmed','real_safety_preserved_confirmed','appropriate_care_preserved_confirmed','invulnerability_not_claimed_confirmed','external_enemy_not_confirmed'] loop if p->k is distinct from 'true'::jsonb then raise exception 'day071_v2_comparison_boundary_required:%',k; end if; end loop;
 m:=p_evidence->'middle'; if jsonb_typeof(m) is distinct from 'object' then raise exception 'day071_v2_middle_required'; end if;
 if exists(select 1 from jsonb_object_keys(m) q where q not in ('psalm_9_9_confirmed','mem_bet_he_confirmed','final_gesture_once_confirmed','thanks_to_god_confirmed','exercise_declared_closed_confirmed','imaginary_flames_released_confirmed','hands_opened_confirmed','environment_observed_confirmed','practical_boundary_named_count','open_hypothesis_named_count','no_contamination_monitoring_confirmed','no_ritual_reconfirmation_confirmed','daily_action_named_count','return_confirmed')) then raise exception 'day071_v2_unknown_middle_field'; end if;
 foreach k in array array['psalm_9_9_confirmed','mem_bet_he_confirmed','final_gesture_once_confirmed','thanks_to_god_confirmed','exercise_declared_closed_confirmed','imaginary_flames_released_confirmed','hands_opened_confirmed','environment_observed_confirmed','no_contamination_monitoring_confirmed','no_ritual_reconfirmation_confirmed','return_confirmed'] loop if m->k is distinct from 'true'::jsonb then raise exception 'day071_v2_middle_boundary_required:%',k; end if; end loop;
 if not coalesce(hnk_private.jsonb_is_nonnegative_integer(m->'practical_boundary_named_count'),false) or (m->>'practical_boundary_named_count')::int<>1 then raise exception 'day071_v2_one_practical_boundary_required'; end if; if not coalesce(hnk_private.jsonb_is_nonnegative_integer(m->'open_hypothesis_named_count'),false) or (m->>'open_hypothesis_named_count')::int<>1 then raise exception 'day071_v2_one_open_hypothesis_required'; end if; if not coalesce(hnk_private.jsonb_is_nonnegative_integer(m->'daily_action_named_count'),false) or (m->>'daily_action_named_count')::int<>1 then raise exception 'day071_v2_one_daily_action_required'; end if;
 perform hnk_private.validate_day071_scalar_evidence_v1(jsonb_build_object('protocol_completed',true,'return_confirmed',m->'return_confirmed','active_completed',a->'completed_confirmed','control_completed',c->'completed_confirmed','comparison_completed',p->'completed_confirmed','imaginary_flame_only',a->'imaginary_flame_only_confirmed','entity_diagnosis_not_claimed',p->'entity_diagnosis_not_claimed_confirmed','anti_compulsion_rule_confirmed',p->'anti_compulsion_rule_confirmed','no_repeat_to_neutralize_fear',p->'no_repeat_to_neutralize_fear_confirmed','practical_boundary_considered',true,'vault_saved',true,'orientation_restored',m->'return_confirmed','safety_clear',p_evidence->'final_safety_clear_confirmed','active_effect_present',a->'active_effect_present','control_effect_present',c->'control_effect_present','active_seconds',a->'active_seconds','control_seconds',c->'control_seconds'));
end $function$;

create or replace function hnk_private.enforce_mebahel_067_071_scalar_evidence()
returns trigger language plpgsql security definer set search_path='' as $function$
declare existing boolean; sha text; st text;
begin
 if new.day not in (67,68,69,70,71) or new.state not in ('evidence_pending','complete') then return new; end if;
 select exists(select 1 from public.day_completions where user_id=new.user_id and day=new.day) into existing; if existing then return new; end if;
 select source_sha,status into sha,st from public.codex_days where day=new.day; if st is distinct from 'canon' then raise exception 'mebahel_canonical_day_not_available'; end if;
 if new.day=67 then if sha is distinct from '1fe06968c724f74311e4fd567075fabc181f1125' then raise exception 'day067_canonical_source_sha_mismatch'; end if; if new.evidence->>'protocol_version'='HNK-CHOKMAH-D067-V2' then perform hnk_private.validate_day067_completion_v2(new.evidence,sha); else perform hnk_private.validate_day067_scalar_evidence_v1(new.evidence); end if;
 elsif new.day=68 then if sha is distinct from '176ebffccc845a909f5d1d2bdb88181b94809afb' then raise exception 'day068_canonical_source_sha_mismatch'; end if; if new.evidence->>'protocol_version'='HNK-CHOKMAH-D068-V2' then perform hnk_private.validate_day068_completion_v2(new.evidence,sha); else perform hnk_private.validate_day068_scalar_evidence_v1(new.evidence); end if;
 elsif new.day=69 then if sha is distinct from '5ec5e7ade94e1a20c348028d75517475a6920e5a' then raise exception 'day069_canonical_source_sha_mismatch'; end if; if new.evidence->>'protocol_version'='HNK-CHOKMAH-D069-V2' then perform hnk_private.validate_day069_completion_v2(new.evidence,sha); else perform hnk_private.validate_day069_scalar_evidence_v1(new.evidence); end if;
 elsif new.day=70 then if sha is distinct from 'bb1e47aee510fe9df58a46f697ebafb9005e223e' then raise exception 'day070_canonical_source_sha_mismatch'; end if; if new.evidence->>'protocol_version'='HNK-CHOKMAH-D070-V2' then perform hnk_private.validate_day070_completion_v2(new.evidence,sha); else perform hnk_private.validate_day070_scalar_evidence_v1(new.evidence); end if;
 else if sha is distinct from '6dfa6b5768bd7cdc2812d5dbfc68a8bc66ad90c3' then raise exception 'day071_canonical_source_sha_mismatch'; end if; if new.evidence->>'protocol_version'='HNK-CHOKMAH-D071-V2' then perform hnk_private.validate_day071_completion_v2(new.evidence,sha); else perform hnk_private.validate_day071_scalar_evidence_v1(new.evidence); end if; end if;
 return new;
end $function$;

do $do$ declare d text; begin select pg_get_functiondef('hnk_private.validate_completion_contract_v2(text,jsonb,text)'::regprocedure) into d; if position('when ''day071_v2''' in d)=0 then d:=replace(d,'when ''day070_v2'' then perform hnk_private.validate_day070_completion_v2(p_evidence,p_expected_source_sha);','when ''day070_v2'' then perform hnk_private.validate_day070_completion_v2(p_evidence,p_expected_source_sha);'||chr(10)||'  when ''day071_v2'' then perform hnk_private.validate_day071_completion_v2(p_evidence,p_expected_source_sha);'); execute d; end if; end $do$;
insert into hnk_private.completion_contract_registry(completion_contract_id,quest_definition_id,day,canonical_source_sha,contract_version,validator_key,status) values('HNK-CHOKMAH-D071-COMP-V2','HNK-CHOKMAH-D071-V2',71,'6dfa6b5768bd7cdc2812d5dbfc68a8bc66ad90c3','2.0.0','day071_v2','draft') on conflict(completion_contract_id) do update set quest_definition_id=excluded.quest_definition_id,day=excluded.day,canonical_source_sha=excluded.canonical_source_sha,contract_version=excluded.contract_version,validator_key=excluded.validator_key,status='draft',updated_at=now();
