-- Strict first-completion evidence for canonical Binah / Leuviah Days 094-098.
create or replace function hnk_private.validate_day094_scalar_evidence_v1(p jsonb) returns void language plpgsql set search_path='' as $$ declare k text; begin
 if p is null or p='{}'::jsonb or jsonb_typeof(p)<>'object' then raise exception 'day094_evidence_required'; end if;
 for k in select jsonb_object_keys(p) loop if k<>all(array['protocol_completed','return_confirmed','focus_object_prepared','observation_completed','fact_interpretation_separated','water_hidden_properties_not_claimed','energy_transfer_not_claimed','intensity_not_scored','orientation_restored','safety_clear','effect_present','practice_seconds']) then raise exception 'day094_evidence_unknown_field'; end if; end loop;
 if p->'protocol_completed' is distinct from 'true'::jsonb or p->'return_confirmed' is distinct from 'true'::jsonb or p->'focus_object_prepared' is distinct from 'true'::jsonb or p->'observation_completed' is distinct from 'true'::jsonb or p->'fact_interpretation_separated' is distinct from 'true'::jsonb or p->'water_hidden_properties_not_claimed' is distinct from 'true'::jsonb or p->'energy_transfer_not_claimed' is distinct from 'true'::jsonb or p->'intensity_not_scored' is distinct from 'true'::jsonb or p->'orientation_restored' is distinct from 'true'::jsonb or p->'safety_clear' is distinct from 'true'::jsonb then raise exception 'day094_required_flag_missing'; end if;
 if jsonb_typeof(p->'effect_present')<>'boolean' then raise exception 'day094_effect_boolean_required'; end if;
 if not coalesce(hnk_private.jsonb_is_nonnegative_integer(p->'practice_seconds'),false) or (p->>'practice_seconds')::int<1 then raise exception 'day094_practice_required'; end if;
end $$;
create or replace function hnk_private.validate_day095_scalar_evidence_v1(p jsonb) returns void language plpgsql set search_path='' as $$ declare k text; begin
 if p is null or p='{}'::jsonb or jsonb_typeof(p)<>'object' then raise exception 'day095_evidence_required'; end if;
 for k in select jsonb_object_keys(p) loop if k<>all(array['protocol_completed','return_confirmed','melancholy_reviewed','self_pity_reviewed','jealousy_reviewed','resentment_reviewed','mood_instability_reviewed','memory_not_forced','diagnosis_not_claimed','moral_sentence_not_claimed','safe_repair_not_forced','vault_saved','orientation_restored','safety_clear','categories_reviewed','total_examples_count']) then raise exception 'day095_evidence_unknown_field'; end if; end loop;
 if p->'protocol_completed' is distinct from 'true'::jsonb or p->'return_confirmed' is distinct from 'true'::jsonb or p->'melancholy_reviewed' is distinct from 'true'::jsonb or p->'self_pity_reviewed' is distinct from 'true'::jsonb or p->'jealousy_reviewed' is distinct from 'true'::jsonb or p->'resentment_reviewed' is distinct from 'true'::jsonb or p->'mood_instability_reviewed' is distinct from 'true'::jsonb or p->'memory_not_forced' is distinct from 'true'::jsonb or p->'diagnosis_not_claimed' is distinct from 'true'::jsonb or p->'moral_sentence_not_claimed' is distinct from 'true'::jsonb or p->'safe_repair_not_forced' is distinct from 'true'::jsonb or p->'vault_saved' is distinct from 'true'::jsonb or p->'orientation_restored' is distinct from 'true'::jsonb or p->'safety_clear' is distinct from 'true'::jsonb then raise exception 'day095_required_flag_missing'; end if;
 if not coalesce(hnk_private.jsonb_is_nonnegative_integer(p->'categories_reviewed'),false) or (p->>'categories_reviewed')::int<>5 or not coalesce(hnk_private.jsonb_is_nonnegative_integer(p->'total_examples_count'),false) then raise exception 'day095_counts_invalid'; end if;
end $$;
create or replace function hnk_private.validate_day096_scalar_evidence_v1(p jsonb) returns void language plpgsql set search_path='' as $$ declare k text; begin
 if p is null or p='{}'::jsonb or jsonb_typeof(p)<>'object' then raise exception 'day096_evidence_required'; end if;
 for k in select jsonb_object_keys(p) loop if k<>all(array['protocol_completed','return_confirmed','compassion_reviewed','devotion_reviewed','emotional_empathy_reviewed','astral_sensitivity_reviewed','evidence_or_gap_recorded','limits_recorded','spiritual_ranking_avoided','astral_sensitivity_not_objective_field','service_application_defined','vault_saved','orientation_restored','safety_clear','categories_reviewed','total_examples_count']) then raise exception 'day096_evidence_unknown_field'; end if; end loop;
 if p->'protocol_completed' is distinct from 'true'::jsonb or p->'return_confirmed' is distinct from 'true'::jsonb or p->'compassion_reviewed' is distinct from 'true'::jsonb or p->'devotion_reviewed' is distinct from 'true'::jsonb or p->'emotional_empathy_reviewed' is distinct from 'true'::jsonb or p->'astral_sensitivity_reviewed' is distinct from 'true'::jsonb or p->'evidence_or_gap_recorded' is distinct from 'true'::jsonb or p->'limits_recorded' is distinct from 'true'::jsonb or p->'spiritual_ranking_avoided' is distinct from 'true'::jsonb or p->'astral_sensitivity_not_objective_field' is distinct from 'true'::jsonb or p->'service_application_defined' is distinct from 'true'::jsonb or p->'vault_saved' is distinct from 'true'::jsonb or p->'orientation_restored' is distinct from 'true'::jsonb or p->'safety_clear' is distinct from 'true'::jsonb then raise exception 'day096_required_flag_missing'; end if;
 if not coalesce(hnk_private.jsonb_is_nonnegative_integer(p->'categories_reviewed'),false) or (p->>'categories_reviewed')::int<>4 or not coalesce(hnk_private.jsonb_is_nonnegative_integer(p->'total_examples_count'),false) then raise exception 'day096_counts_invalid'; end if;
end $$;
create or replace function hnk_private.validate_day097_scalar_evidence_v1(p jsonb) returns void language plpgsql set search_path='' as $$ declare k text; begin
 if p is null or p='{}'::jsonb or jsonb_typeof(p)<>'object' then raise exception 'day097_evidence_required'; end if;
 for k in select jsonb_object_keys(p) loop if k<>all(array['protocol_completed','return_confirmed','equivalence_recorded','alternatives_generated','context_considered','crying_grief_not_invalidated','serenity_not_required','fixed_identity_not_claimed','diagnosis_not_claimed','vault_saved','orientation_restored','safety_clear']) then raise exception 'day097_evidence_unknown_field'; end if; end loop;
 if p->'protocol_completed' is distinct from 'true'::jsonb or p->'return_confirmed' is distinct from 'true'::jsonb or p->'equivalence_recorded' is distinct from 'true'::jsonb or p->'alternatives_generated' is distinct from 'true'::jsonb or p->'context_considered' is distinct from 'true'::jsonb or p->'crying_grief_not_invalidated' is distinct from 'true'::jsonb or p->'serenity_not_required' is distinct from 'true'::jsonb or p->'fixed_identity_not_claimed' is distinct from 'true'::jsonb or p->'diagnosis_not_claimed' is distinct from 'true'::jsonb or p->'vault_saved' is distinct from 'true'::jsonb or p->'orientation_restored' is distinct from 'true'::jsonb or p->'safety_clear' is distinct from 'true'::jsonb then raise exception 'day097_required_flag_missing'; end if;
end $$;
create or replace function hnk_private.validate_day098_scalar_evidence_v1(p jsonb) returns void language plpgsql set search_path='' as $$ declare k text; begin
 if p is null or p='{}'::jsonb or jsonb_typeof(p)<>'object' then raise exception 'day098_evidence_required'; end if;
 for k in select jsonb_object_keys(p) loop if k<>all(array['protocol_completed','return_confirmed','ritual_completed','cold_water_optional_confirmed','physical_safety_checked','larvae_symbolic_not_entity_diagnosis','energy_cleansing_not_claimed_as_measured','anti_compulsion_rule_confirmed','orientation_restored','safety_clear','cold_water_used','effect_present','practice_seconds']) then raise exception 'day098_evidence_unknown_field'; end if; end loop;
 if p->'protocol_completed' is distinct from 'true'::jsonb or p->'return_confirmed' is distinct from 'true'::jsonb or p->'ritual_completed' is distinct from 'true'::jsonb or p->'cold_water_optional_confirmed' is distinct from 'true'::jsonb or p->'physical_safety_checked' is distinct from 'true'::jsonb or p->'larvae_symbolic_not_entity_diagnosis' is distinct from 'true'::jsonb or p->'energy_cleansing_not_claimed_as_measured' is distinct from 'true'::jsonb or p->'anti_compulsion_rule_confirmed' is distinct from 'true'::jsonb or p->'orientation_restored' is distinct from 'true'::jsonb or p->'safety_clear' is distinct from 'true'::jsonb then raise exception 'day098_required_flag_missing'; end if;
 if jsonb_typeof(p->'cold_water_used')<>'boolean' or jsonb_typeof(p->'effect_present')<>'boolean' then raise exception 'day098_boolean_observation_required'; end if;
 if not coalesce(hnk_private.jsonb_is_nonnegative_integer(p->'practice_seconds'),false) or (p->>'practice_seconds')::int<1 then raise exception 'day098_practice_required'; end if;
end $$;
revoke all on function hnk_private.validate_day094_scalar_evidence_v1(jsonb) from public,anon,authenticated;
revoke all on function hnk_private.validate_day095_scalar_evidence_v1(jsonb) from public,anon,authenticated;
revoke all on function hnk_private.validate_day096_scalar_evidence_v1(jsonb) from public,anon,authenticated;
revoke all on function hnk_private.validate_day097_scalar_evidence_v1(jsonb) from public,anon,authenticated;
revoke all on function hnk_private.validate_day098_scalar_evidence_v1(jsonb) from public,anon,authenticated;
create or replace function hnk_private.enforce_leuviah_094_098_scalar_evidence() returns trigger language plpgsql security definer set search_path='' as $$ declare existing boolean; sha text; st text; begin
 if new.day not in (94,95,96,97,98) or new.state not in ('evidence_pending','complete') then return new; end if;
 select exists(select 1 from public.day_completions where user_id=new.user_id and day=new.day) into existing; if existing then return new; end if;
 select source_sha,status into sha,st from public.codex_days where day=new.day; if st is distinct from 'canon' then raise exception 'leuviah_canonical_day_not_available'; end if;
 if new.day=94 then if sha is distinct from '21953e229705418d91d410234a3ad151ed1c3e6e' then raise exception 'day094_canonical_source_sha_mismatch'; end if; perform hnk_private.validate_day094_scalar_evidence_v1(new.evidence);
 elsif new.day=95 then if sha is distinct from '45b09623cdcf750c4f7d60ce2d361a5b77e4d039' then raise exception 'day095_canonical_source_sha_mismatch'; end if; perform hnk_private.validate_day095_scalar_evidence_v1(new.evidence);
 elsif new.day=96 then if sha is distinct from '610279b722317d3cd6f8896292f34c555d787647' then raise exception 'day096_canonical_source_sha_mismatch'; end if; perform hnk_private.validate_day096_scalar_evidence_v1(new.evidence);
 elsif new.day=97 then if sha is distinct from '7a59eed915909c60dd05f078a4a6f4b4e06d8365' then raise exception 'day097_canonical_source_sha_mismatch'; end if; perform hnk_private.validate_day097_scalar_evidence_v1(new.evidence);
 else if sha is distinct from '4fa277aa58c8f5c9eb9dd4fb6a84e7a2c10e942b' then raise exception 'day098_canonical_source_sha_mismatch'; end if; perform hnk_private.validate_day098_scalar_evidence_v1(new.evidence); end if;
 return new;
end $$;
revoke all on function hnk_private.enforce_leuviah_094_098_scalar_evidence() from public,anon,authenticated;
drop trigger if exists practice_sessions_enforce_leuviah_094_098_evidence on public.practice_sessions;
create trigger practice_sessions_enforce_leuviah_094_098_evidence before insert or update of state,evidence,day,user_id on public.practice_sessions for each row execute function hnk_private.enforce_leuviah_094_098_scalar_evidence();
