'use client';
import {useEffect,useRef,useState} from 'react';
import type {PublishedDay036PortalAudioAsset} from '@hnk/audio-contract/day036';
export interface KetherPortalTunerV1Props{asset:PublishedDay036PortalAudioAsset|null;reducedSensory?:boolean;onSafetyStop?:(reason:string)=>void}
function clock(v:number){const s=Math.max(0,Math.floor(v));return`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
export function KetherPortalTunerV1({asset,reducedSensory=false,onSafetyStop}:KetherPortalTunerV1Props){const audioRef=useRef<HTMLAudioElement|null>(null);const[volume,setVolume]=useState(reducedSensory?0.2:0.35);const[headphones,setHeadphones]=useState(false);const[playing,setPlaying]=useState(false);const[current,setCurrent]=useState(0);const[duration,setDuration]=useState(0);const[error,setError]=useState<string|null>(null);
useEffect(()=>{const old=audioRef.current;if(old){old.pause();old.src='';audioRef.current=null}setPlaying(false);setCurrent(0);setDuration(0);if(!asset)return;const a=new Audio(asset.uri);a.preload='auto';a.volume=volume;a.ontimeupdate=()=>setCurrent(a.currentTime);a.onloadedmetadata=()=>setDuration(a.duration);a.onplay=()=>setPlaying(true);a.onpause=()=>setPlaying(false);a.onended=()=>setPlaying(false);a.onerror=()=>setError('day036_published_audio_load_failed');audioRef.current=a;return()=>{a.pause();a.src='';if(audioRef.current===a)audioRef.current=null}},[asset?.uri]);
useEffect(()=>{const a=audioRef.current;if(a)a.volume=Math.max(.05,Math.min(1,volume))},[volume]);
async function play(){if(!asset){setError('day036_audio_not_published');return}if(!headphones){setError('Confirme os fones antes de iniciar o preset stereo do Portal.');return}setError(null);try{await audioRef.current?.play()}catch(e){setError(e instanceof Error?e.message:'day036_audio_play_failed')}}
function pause(){audioRef.current?.pause()}function stop(){const a=audioRef.current;if(!a)return;a.pause();a.currentTime=0;setCurrent(0);setPlaying(false)}function restart(){const a=audioRef.current;if(!a)return;a.pause();a.currentTime=0;setCurrent(0);void play()}function safety(){stop();onSafetyStop?.('day036_tuner_safety_stop')}
const locked=!asset;const shownDuration=asset?.durationSeconds??(duration||720);return <section data-hnk-operator="hnk.tuner.kether.v1" style={{background:'#101116',border:'1px solid #363845',borderRadius:16,padding:16,marginTop:16}}><h3>Sintonizador Angelical HNK — Kether V1</h3><p>{locked?'LOCKED — aguarda asset publicado e listening QA.':'Published-asset mode. Nenhuma frequência é sintetizada em runtime.'}</p><p>{clock(current)} / {clock(shownDuration)}</p><label style={{display:'block',margin:'10px 0'}}><input type="checkbox" checked={headphones} onChange={e=>setHeadphones(e.target.checked)} disabled={locked}/> Confirmo fones em volume confortável.</label><label style={{display:'block',margin:'10px 0'}}>Volume <input aria-label="Volume" type="range" min="0.05" max="1" step="0.05" value={volume} onChange={e=>setVolume(Number(e.target.value))} disabled={locked}/><span> {Math.round(volume*100)}%</span></label><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button onClick={()=>void play()} disabled={locked||playing}>Play</button><button onClick={pause} disabled={locked||!playing}>Pause</button><button onClick={stop} disabled={locked}>Stop</button><button onClick={restart} disabled={locked}>Reiniciar fase</button><button onClick={safety} disabled={locked}>Retorno / Safety Stop</button></div>{reducedSensory&&<p>Modo sensorial reduzido: volume inicial limitado a 20%; sem flashes ou strobe.</p>}{error&&<p role="alert">{error}</p>}</section>}
